DimensionDev/firefly.mask.social

next.config.js, src/assets/follow-user.svg, src/assets/unfollow-user.svg, src/components/Actions/Like.tsx, src/components/Actions/Mirrors.tsx, src/components/Actions/More.tsx, src/components/Posts/PostHeader.tsx, src/modals/FarcasterStatusModal.tsx, src/providers/lens/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> feat: more action

.vscode/settings.json, src/app/(settings)/components/SettingList/index.tsx, src/app/(settings)/settings/connected/page.tsx, src/app/(settings)/settings/display/page.tsx, src/components/LoginFarcaster.tsx, src/components/LoginLens/index.tsx, src/hooks/useSetTheme.ts, src/modals/LogoutModal.tsx, src/store/useFarcasterStore.ts, src/store/useLensStore.ts, src/types/index.ts
https://mask.atlassian.net/browse/MF-5656
https://mask.atlassian.net/browse/MF-5658
https://mask.atlassian.net/browse/MF-5661
https://mask.atlassian.net/browse/MF-5664
https://mask.atlassian.net/browse/MF-5665
https://mask.atlassian.net/browse/MF-5666
https://mask.atlassian.net/browse/MF-5655
https://mask.atlassian.net/browse/MF-5672
=> feat: update settings 

.editorconfig, .github/workflows/conventional-commits.yml
Learn more CC here: https://www.conventionalcommits.org/en/v1.0.0/
=> ci: validate pr title with conventional commits

src/app/(normal)/search/page.tsx, src/helpers/formatWarpcastUser.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/Warpcast.ts, src/providers/warpcast/SocialMedia.ts
=> fix: search on farcaster

src/app/globals.css, src/components/Actions/More.tsx, src/components/Markup/MarkupLink/MentionLink.tsx, src/components/Notification/NotificationItem.tsx, src/components/Posts/Attachment.tsx, src/components/Posts/ImageAsset.tsx, src/components/Posts/PostBody.tsx, src/components/Posts/Quote.tsx, src/modals/PreviewImagesModal.tsx
https://mask.atlassian.net/browse/MF-5725
https://mask.atlassian.net/browse/MF-5726
https://mask.atlassian.net/browse/MF-5730
https://mask.atlassian.net/browse/MF-5737
https://mask.atlassian.net/browse/MF-5744
https://mask.atlassian.net/browse/MF-5739
https://mask.atlassian.net/browse/MF-5745
=> fix: post ui issues

src/app/(normal)/layout.tsx, src/components/CustomElements.tsx
=> refactor: lazy load CustomElements

.ignore, src/app/(normal)/layout.tsx, src/app/globals.css, src/components/Actions/Collect.tsx, src/components/Actions/Comment.tsx, src/components/Actions/Like.tsx, src/components/Actions/Mirrors.tsx, src/components/Actions/More.tsx, src/components/Actions/Share.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/PostBy.tsx, src/components/Image.tsx, src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginLens.tsx, src/components/Notification/NotificationItem.tsx, src/components/Notification/ProfileLink.tsx, src/components/Providers.tsx, src/components/Search/SearchBar.tsx, src/hooks/useCustomSnackbar.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/mask/widgets/CalendarWidget.tsx, tailwind.config.cjs
https://mask.atlassian.net/browse/MF-5687
https://mask.atlassian.net/browse/MF-5740
https://mask.atlassian.net/browse/MF-5742
https://mask.atlassian.net/browse/MF-5746
https://mask.atlassian.net/browse/MF-5755
=> fix: some ui issues

src/app/(normal)/page.tsx, src/components/Search/ProfileInList.tsx, src/components/Search/SearchBar.tsx, src/components/Search/useSearchHistories.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po
https://mask.atlassian.net/browse/MF-5713
https://mask.atlassian.net/browse/MF-5749
https://mask.atlassian.net/browse/MF-5751
https://mask.atlassian.net/browse/MF-5753
=> feat: mf-5751 add search history

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeContent.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/Discard.tsx, src/components/Compose/Editor.tsx, src/components/Compose/PostBy.tsx, src/components/Compose/ReplyRestriction.tsx, src/components/Posts/PostHeader.tsx, src/components/Profile/ContentCollected.tsx, src/components/Profile/ContentFeed.tsx, src/components/Profile/ContentTabs.tsx, src/components/Profile/FarcasterProfile.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/Info.tsx, src/components/Profile/LensProfile.tsx, src/components/Profile/Title.tsx, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/MF-5758
https://mask.atlassian.net/browse/MF-5757
https://mask.atlassian.net/browse/MF-5724
https://mask.atlassian.net/browse/MF-5723
https://mask.atlassian.net/browse/MF-5711
https://mask.atlassian.net/browse/MF-5710
https://mask.atlassian.net/browse/MF-5709
https://mask.atlassian.net/browse/MF-5669
=> fix: fix style and bug

src/app/globals.css, src/components/Actions/Mirrors.tsx, src/components/Markup/index.tsx, src/components/Posts/Attachment.tsx, src/components/Posts/PostBody.tsx, src/components/Search/ProfileInList.tsx, src/hooks/useCustomSnackbar.tsx
https://mask.atlassian.net/browse/MF-5687
https://mask.atlassian.net/browse/MF-5726
https://mask.atlassian.net/browse/MF-5756
=> fix: quoted post

src/components/Search/SearchBar.tsx
MF-0000
https://mask.atlassian.net/browse/MF-5762
=> fix: adjust search bar behavior

src/components/Login/LoginLens.tsx, src/components/SideBar/ConnectWalletNav.tsx, src/hooks/useRainbowModal.ts, src/hooks/useRainbowModalRef.ts, src/modals/AccountModal.tsx, src/modals/ChainModal.tsx, src/modals/ConnectWalletModal.tsx, src/modals/LoginModal.tsx, src/modals/index.tsx, src/providers/lens/SocialMedia.ts
=> fix: change wallet

src/helpers/formatWarpcastPost.ts, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/MF-5694
=> fix: discover cast

src/app/(normal)/layout.tsx, src/components/Actions/More.tsx, src/components/Profile/FollowButton.tsx, src/components/Search/SearchBar.tsx, src/components/WagmiProvider.tsx, src/hooks/useToggleFollow.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po
https://mask.atlassian.net/browse/MF-5729
https://mask.atlassian.net/browse/MF-5747
https://mask.atlassian.net/browse/MF-5749
https://mask.atlassian.net/browse/MF-5751
https://mask.atlassian.net/browse/MF-5753
=> fix: follow in profile search result

src/app/(normal)/profile/page.tsx, src/components/Posts/PostHeader.tsx, src/components/Profile/FarcasterProfile.tsx, src/components/SideBar/index.tsx, src/components/SocialPlatformTabs.tsx, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/MF-5767
=> fix: farcaster profile

src/components/Avatar.tsx, src/components/Image.tsx, src/components/Notification/NotificationItem.tsx, src/components/Oembed/Mirror.tsx, src/components/Posts/PostHeader.tsx, src/components/Profile/Info.tsx, src/components/Search/ProfileInList.tsx, src/components/Search/SearchBar.tsx, src/helpers/formatWarpcastUser.ts, src/providers/types/Warpcast.ts
https://mask.atlassian.net/browse/MF-5769
https://mask.atlassian.net/browse/MF-5775
https://mask.atlassian.net/browse/MF-5776
=> refactor: mf-5769 add <Avatar /> component

src/components/Login/LoginFarcaster.tsx, src/helpers/waitForSignedKeyRequestComplete.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/providers/warpcast/createSessionByGrantPermission.ts
=> feat: login with warpcast

src/helpers/formatWarpcastPost.ts, src/providers/types/Warpcast.ts, src/providers/warpcast/SocialMedia.ts
=> fix: warpcast api types

src/components/Search/SearchBar.tsx, src/helpers/formatLensProfile.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po
https://mask.atlassian.net/browse/MF-5751
=> fix: mf-5751 align publications

lingui.config.js, src/locales/en/messages.po, src/locales/pseudo/messages.po
=> fix: modals i18n

src/components/Login/LoginLens.tsx
=> fix: login modal change wallet

src/components/Compose/ComposeAction.tsx, src/mask/modals/index.tsx, src/mask/widgets/PageInspector.tsx
=> refactor: reduce modals

src/app/(normal)/profile/[source]/[id]/page.tsx, src/components/Actions/More.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/Info.tsx, src/components/Profile/Title.tsx, src/hooks/useIsFollowing.ts, src/hooks/useToggleFollow.tsx
https://mask.atlassian.net/browse/MF-5729
=> fix: mf-5729 refresh state after follow/unfollow

env.d.ts, scripts/setup-vercel.sh, src/components/Compose/ComposeAction.tsx, src/components/CustomElements.tsx, src/components/Posts/Attachment.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/mask/background-worker/register.ts, src/mask/message-host/index.ts, src/mask/plugin-host/enable.ts, src/mask/plugin-host/register.ts, src/mask/setup/message.ts, src/mask/setup/storage.ts, tsconfig.json
=> chore: inject debug dialog

.eslintrc.json
=> chore: eslint - react/self-closing-comp

src/components/Compose/ComposeSend.tsx, src/components/Compose/Discard.tsx, src/components/Compose/Media.tsx, src/modals/ComposeModal.tsx
=> refactor: code style

src/components/Compose/ComposeSend.tsx, src/components/Compose/CountdownCircle.tsx, src/store/useComposeStore.ts
=> fix: hide indicator when content is empty

src/helpers/waitForSignedKeyRequest.ts, src/helpers/waitForSignedKeyRequestComplete.ts, src/providers/base/Session.ts, src/providers/base/SessionFactory.ts, src/providers/warpcast/Session.ts, src/providers/warpcast/createSessionByGrantPermission.ts
=> refactor: add signerRequestToken

src/app/(normal)/following/loading.tsx, src/components/AccountSetting.tsx, src/components/Login/AccountCard.tsx, src/components/Oembed/index.tsx, src/components/ProfileAvatar.tsx, src/components/ProfileName.tsx, src/components/WarpcastSignerRequestIndicator.tsx, src/components/WarpcastSignerRequsetIndicator.tsx, src/hooks/useProfiles.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/modals/LogoutModal.tsx, src/modals/ProfileStatusModal.tsx, src/providers/base/Session.ts, src/providers/base/SessionFactory.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/Session.ts, src/providers/lens/SocialMedia.ts, src/providers/types/Session.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/Session.ts, src/providers/warpcast/SocialMedia.ts
=> feat: add <WarpcastSignerRequsetIndicator />

src/app/(settings)/settings/connected/page.tsx, src/components/AccountSetting.tsx, src/components/Compose/PostByItem.tsx, src/components/Login/LoginLens.tsx, src/components/Posts/PostHeader.tsx, src/helpers/isSameProfile.ts
=> refactor: isSameProfile

src/app/(normal)/page.tsx, src/app/api/warpcast/signin/route.ts, src/components/AccountSetting.tsx, src/components/Avatar.tsx, src/components/OnlineStatusIndicator.tsx, src/components/WarpcastSignerRequestIndicator.tsx, src/helpers/createSessionStorage.ts, src/helpers/resolveAvatarFallbackUrl.ts, src/helpers/resolveImgurUrl.ts, src/helpers/waitForSignedKeyRequest.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/providers/base/SessionFactory.ts, src/providers/types/Warpcast.ts, src/providers/warpcast/Session.ts, src/providers/warpcast/createSessionByGrantPermission.ts
=> feat: add OnlineStatusIndicator

src/providers/base/Session.ts, src/providers/base/SessionFactory.ts, src/providers/lens/Session.ts
=> fix: lens session

src/components/Actions/More.tsx, src/components/Profile/FollowButton.tsx, src/hooks/useToggleFollow.tsx, src/hooks/useUnmountRef.ts
https://mask.atlassian.net/browse/MF-5729
=> fixup! fix: mf-5729 refresh state after follow/unfollow

src/components/CustomElements.tsx, src/components/MaskProviders.tsx, src/configs/wagmiClient.ts, src/mask/modals/index.tsx, src/mask/setup/custom-event-provider.ts, src/mask/widgets/PageInspector.tsx, src/modals/index.tsx
=> feat: use CustomEventProvider

cspell.json, src/app/(normal)/profile/[source]/[id]/page.tsx, src/components/Profile/ContentCollected.tsx, src/components/Profile/ContentFeed.tsx, src/components/Profile/ContentTabs.tsx
=> fix: invalid source request

src/components/Avatar.tsx, src/components/ProfileAvatar.tsx, src/components/SourceIcon.tsx
=> fix: dynamic class might not be generated at build time

src/app/(normal)/layout.tsx, src/app/(settings)/components/SettingList/index.tsx, src/components/IfPathname.tsx, src/components/Posts/ActionType.tsx, src/components/Posts/SinglePost.tsx, src/components/Posts/ThreadBody.tsx, src/components/Search/SearchBar.tsx, src/components/SideBar/index.tsx, src/components/SocialPlatformTabs.tsx, src/helpers/isRoutePathname.ts, tests/helpers/isRoutePathname.ts
=> refactor: isRoutePathname

src/components/Compose/ComposeImage.tsx, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/components/Compose/ComposeSend/useSendLens.ts, src/components/Compose/ComposeVideo.tsx, src/configs/wagmiClient.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/services/uploadToIPFS.ts
=> fix: compose dialog error handling

src/components/MaskProviders.tsx, src/mask/custom-elements.ts, src/mask/setup/custom-event-provider.ts
=> fix: connect custom event provider

src/modals/ComposeModal.tsx
=> fix: payload author

src/mask/setup/wallet.ts
=> fix: await setup wallet

src/app/(settings)/components/SettingList/index.tsx
=> fix: settings i18n

src/app/(normal)/profile/[source]/[id]/page.tsx, src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeContent.tsx, src/components/Compose/ComposeVideo.tsx, src/components/Compose/Discard.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostByItem.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/Info.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po
https://mask.atlassian.net/browse/MF-5757
https://mask.atlassian.net/browse/MF-5759
https://mask.atlassian.net/browse/MF-5669
https://mask.atlassian.net/browse/MF-5711
https://mask.atlassian.net/browse/MF-5772
https://mask.atlassian.net/browse/MF-5787
https://mask.atlassian.net/browse/MF-5799
https://mask.atlassian.net/browse/MF-5838
https://mask.atlassian.net/browse/MF-5839
https://mask.atlassian.net/browse/MF-5845
https://mask.atlassian.net/browse/MF-5847
https://mask.atlassian.net/browse/MF-5668
https://mask.atlassian.net/browse/MF-5851
=> fix: fix compose and profile

src/components/Login/LoginLens.tsx, src/modals/LoginModal.tsx, src/providers/farcaster/index.ts, src/providers/firefly/SocialMedia.ts
https://mask.atlassian.net/browse/MF-5661
https://mask.atlassian.net/browse/MF-5665
https://mask.atlassian.net/browse/MF-5731
https://mask.atlassian.net/browse/MF-5767
https://mask.atlassian.net/browse/MF-5704
https://mask.atlassian.net/browse/MF-5788
https://mask.atlassian.net/browse/MF-5770
https://mask.atlassian.net/browse/MF-5808
https://mask.atlassian.net/browse/MF-5823
=> fix: ui bugs

src/app/(normal)/post/[source]/[id]/page.tsx, src/app/api/oembed/route.ts, src/components/Actions/index.tsx, src/components/Avatar.tsx, src/components/Compose/ComposeContent.tsx, src/components/Image.tsx, src/components/Markup/MarkupLink/index.tsx, src/components/Markup/index.tsx, src/components/Oembed/Mirror.tsx, src/components/Oembed/index.tsx, src/components/Posts/Attachment.tsx, src/components/Posts/ImageAsset.tsx, src/components/Posts/PostHeader.tsx, src/components/Posts/SinglePost.tsx, src/components/Posts/ThreadBody.tsx, src/components/ProfileAvatar.tsx, src/helpers/getOpenGraphPayload.ts, src/modals/PreviewImagesModal.tsx, src/types/og.ts
=> feat: reply compose post

src/app/(normal)/search/page.tsx, src/components/NoResultsFallback.tsx, src/components/Profile/FollowButton.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/mask/setup/locale.ts, src/providers/lens/SocialMedia.ts, src/services/digestLink.ts, tsconfig.json
https://mask.atlassian.net/browse/MF-5710
https://mask.atlassian.net/browse/MF-5824
https://mask.atlassian.net/browse/MF-5831
https://mask.atlassian.net/browse/MF-5832
https://mask.atlassian.net/browse/MF-5833
https://mask.atlassian.net/browse/MF-5858
=> fix: some more ui issues

src/components/Compose/Media.tsx, src/components/Profile/Title.tsx
https://mask.atlassian.net/browse/MF-5803
https://mask.atlassian.net/browse/MF-5851
=> fix: set cursor to not allowed when images count reaches max

package.json, pnpm-lock.yaml, src/app/(normal)/layout.tsx, src/app/(settings)/components/DocumentCard.tsx, src/app/(settings)/settings/layout.tsx, src/app/(settings)/settings/more/page.tsx, src/app/layout.tsx, src/app/not-found.tsx, src/esm/Head.ts, src/helpers/createPageTitle.ts, src/i18n/index.ts
=> fix: i18n title

src/app/(normal)/following/loading.tsx, src/app/(normal)/loading.tsx, src/app/(normal)/notifications/loading.tsx, src/app/(normal)/post/[source]/[id]/layout.tsx, src/app/(normal)/post/[source]/[id]/loading.tsx, src/app/(normal)/post/[source]/[id]/page.tsx, src/app/(normal)/post/layout.tsx, src/app/(normal)/profile/[source]/[id]/loading.tsx, src/app/(normal)/profile/[source]/[id]/page.tsx, src/app/(normal)/search/loading.tsx, src/app/not-found.tsx, src/constants/index.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po
=> refactor: site metadata

src/app/(normal)/profile/[source]/[id]/page.tsx, src/app/globals.css, src/app/layout.tsx, src/components/Notification/NotificationItem.tsx, src/components/Posts/Attachment.tsx, src/components/Posts/Audio.tsx, src/components/Posts/PostHeader.tsx, src/components/Profile/Info.tsx, src/components/SideBar/index.tsx, src/components/SocialPlatformTabs.tsx, src/providers/firefly/SocialMedia.ts, tailwind.config.cjs
MF-5837 MF-5629 MF-5873 MF-5877 MF-5878 MF-5879 MF-5884
=> fix: bugfix for ui and import font

src/providers/firefly/SocialMedia.ts
=> fix: firefly provider

src/app/(normal)/page.tsx, src/hooks/useIsLogin.ts
https://mask.atlassian.net/browse/MF-5801
successor of #258
=> fix: mf-5801 login status

src/components/Markup/MarkupLink/MentionLink.tsx, src/components/Posts/Quote.tsx, src/components/Posts/SinglePost.tsx, src/components/Posts/ThreadBody.tsx, src/providers/farcaster/index.ts, src/providers/firefly/SocialMedia.ts
MF-5848 MF-5717 MF-5865 MF-5878
=> fix: bugfix for firefly api

src/components/Compose/ComposeSend/useSendFarcaster.ts, src/providers/farcaster/Session.ts, src/providers/hubble/SocialMedia.ts, src/providers/types/Warpcast.ts, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/MF-5881
=> fix: mf-5881 post to farcaster with custody wallet

src/components/Compose/ComposeImage.tsx, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/MF-5888
https://mask.atlassian.net/browse/MF-5890
=> fix: mf-5888 the remove button for image

src/components/Compose/ComposeImage.tsx
https://mask.atlassian.net/browse/MF-5890
=> fixup! fix: mf-5890 farcaster post image

src/app/(settings)/components/AccountCard.tsx, src/app/(settings)/settings/connected/page.tsx, src/components/AccountSetting.tsx, src/components/Profile/ContentTabs.tsx, src/components/ProfileName.tsx, src/components/SideBar/index.tsx, src/helpers/resolveSourceName.ts, src/modals/ProfileStatusModal.tsx
=> refactor: UI

src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts
=> fix: replace firefly api

cspell.json, src/app/(normal)/page.tsx, src/app/(settings)/settings/connected/page.tsx, src/components/Compose/ComposeAction.tsx, src/components/CustomElements.tsx, src/helpers/setupCurrentVisitingProfile.ts, src/mask/custom-elements.ts
=> refactor: payload handle

src/app/layout.tsx, src/components/MobileFallback.tsx, src/components/Notification/NotificationItem.tsx, src/components/Oembed/Mirror.tsx, src/components/Posts/ActionType.tsx, src/components/Posts/PostBody.tsx, src/components/SideBar/index.tsx, tailwind.config.cjs
=> fix: global font

src/components/CustomElements.tsx
=> fix: channel

src/components/CustomElements.tsx, src/components/MobileFallback.tsx, src/configs/wagmiClient.ts, src/mask/main/DecryptPost.tsx, src/modals/ComposeModal.tsx
=> fix: site detector

src/helpers/setupCurrentVisitingProfile.ts
=> fix: update handle

src/app/(normal)/following/page.tsx, src/app/(normal)/notifications/page.tsx, src/app/(normal)/page.tsx, src/components/AccountSetting.tsx, src/components/Actions/Comment.tsx, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/components/Compose/ComposeSend/useSendLens.ts, src/components/Compose/PostByItem.tsx, src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginLens.tsx, src/components/Profile/ContentCollected.tsx, src/components/Profile/ContentFeed.tsx, src/helpers/createPostMetadata.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/providers/hubble/SocialMedia.ts
=> chore: add ending dot

src/components/Actions/index.tsx
=> fix: stop propagation from post action row

src/components/AccountSetting.tsx, src/components/ProfileAvatarAdd.tsx, src/components/SideBar/index.tsx, tailwind.config.cjs
=> fix: responsive problem

src/components/Search/SearchBar.tsx
=> fix: hide dropdown list when click on profile

src/providers/firefly/SocialMedia.ts
=> fix: profile timeline post format

src/app/(normal)/layout.tsx, src/app/not-found.tsx
=> fix: timeline width

src/components/Search/SearchBar.tsx
=> fix(ui): add border to dropdown menu

src/components/MobileFallback.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po
=> chore: update texture

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend/index.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostByItem.tsx, src/components/shared/lexical/plugins/AtMentionsPlugin.tsx, src/modals/ComposeModal.tsx, src/store/useComposeStore.ts
=> refactor: MF-5809

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend/index.tsx, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/components/Compose/Media.tsx, src/components/Compose/PostByItem.tsx, src/components/shared/lexical/plugins/AtMentionsPlugin.tsx, src/modals/ComposeModal.tsx, src/store/useComposeStore.ts
https://mask.atlassian.net/browse/MF-5809
=> fix: mf-5809 allow to disable a platform when compose post

.github/workflows/crowdin-download.yml, .github/workflows/crowdin-upload.yml, crowdin.yml, package.json, pnpm-lock.yaml
[MF-5912](https://mask.atlassian.net/browse/MF-5912)
[MF-5912]: https://mask.atlassian.net/browse/MF-5912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: integrate crowdin

.github/workflows/crowdin-download.yml, .github/workflows/crowdin-upload.yml
=> fix: crowdin ci

src/app/api/warpcast/signin/route.ts, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/components/Login/LoginFarcaster.tsx, src/components/Oembed/Post.tsx, src/components/Search/SearchBar.tsx, src/providers/farcaster/Session.ts, src/providers/hubble/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts, src/providers/warpcast/createSessionByCustodyWallet.ts
=> refactor: farcaster provider

setups/index.ts, src/app/api/oembed/route.ts, src/app/globals.css, src/components/Markup/MarkupLink/ExternalLink.tsx, src/components/Oembed/Embed.tsx, src/components/Oembed/Mirror.tsx, src/components/Oembed/Player.tsx, src/components/Oembed/index.tsx, src/constants/regex.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/formatImageUrl.ts, src/helpers/isLinkMatchingHost.ts, src/helpers/parseURL.ts, src/providers/firefly/SocialMedia.ts, src/services/digestLink.ts, tests/helpers/isLinkMatchingHost.ts, tests/helpers/parseURL.ts
=> fix: bugfix for open graph

src/helpers/createMaskContext.ts, src/helpers/createRejectCallback.ts, src/helpers/getImageDimension.ts, src/mask/plugin-host/enable.ts, src/mask/setup/wallet.ts, src/store/useImpressionsStore.ts
=> refactor: createRejectCallback

src/components/CustomElements.tsx
=> chore: align preview env

crowdin.yml
=> fix: pattern

crowdin.yml
=> chore: osx_locale code

env.d.ts, next.config.js, src/app/layout.tsx, src/components/BuildInfo.tsx
=> chore: log build info

.github/workflows/jira-issue-key-checking.yml, src/app/api/publicationViews/route.ts, src/components/Actions/Comment.tsx, src/components/Actions/Like.tsx, src/components/Actions/index.tsx, src/components/Compose/ComposeContent.tsx, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/formatWarpcastPost.ts, src/hooks/useToggleFollow.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts, src/providers/types/Warpcast.ts, src/providers/warpcast/SocialMedia.ts
FW-250 FW-226 FW-268 FW-269 FW-270
https://mask.atlassian.net/browse/FW-250
=> fix: bugfix for warpcast provider

.github/workflows/crowdin-download.yml
=> refactor: update jira issue prefix

src/app/(normal)/post/[source]/[id]/layout.tsx, src/app/(normal)/post/[source]/[id]/page.tsx, src/app/(normal)/post/layout.tsx, src/app/(normal)/profile/[source]/[id]/layout.tsx, src/app/(normal)/profile/[source]/[id]/page.tsx, src/app/(normal)/profile/layout.tsx, src/components/Posts/Attachment.tsx, src/helpers/attachmentToOpenGraphImage.ts, src/helpers/createSiteMetadata.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/formatLensPost.ts, src/helpers/formatWarpcastPost.ts, src/helpers/isBotRequest.ts, src/middleware.ts, src/providers/lens/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/services/getPostById.ts, src/services/getProfileById.ts, src/types/index.ts
=> refactor(SEO): post & profile

next.config.js, scripts/build-logs.sh
=> chore: enhance build logs

src/app/(normal)/post/[source]/[id]/page.tsx, src/components/Posts/PostHeader.tsx, src/components/Profile/Title.tsx, src/components/Providers.tsx, src/components/Search/SearchBar.tsx, src/components/SocialPlatformTabs.tsx, src/store/useGlobalStore.ts
##
Closes FW-274 FW-277 FW-280
=> chore: adjust header bar ui

src/components/Posts/PostBody.tsx, src/mask/custom-elements/DecryptedPost.tsx, src/mask/widgets/DecryptedInspector.tsx, src/mask/widgets/components/DecryptedPost.tsx, src/services/decryptPayload.ts
=> fix: image payload

next.config.js, src/app/api/rp/route.tsx
=> chore: enable log

cspell.json, src/providers/firefly/RedPacket.ts, src/providers/types/Firefly.ts, src/providers/types/FireflyRedPacket.ts
=> chore: add red packet API

package.json, pnpm-lock.yaml, src/mask/setup/wallet.ts
=> chore: sync submodule - maskbook

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend/index.tsx, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/components/Compose/ComposeSend/useSendLens.ts, src/components/Compose/CountdownCircle.tsx, src/components/Compose/Editor.tsx, src/components/Lexical/withLexicalContext.tsx, src/constants/index.ts, src/helpers/readChars.ts, src/modals/ComposeModal.tsx, src/services/postForLens.ts, src/store/useComposeStore.ts
=> feat: add complex chars

package.json, pnpm-lock.yaml, src/app/(normal)/post/[source]/[id]/layout.tsx, src/app/(normal)/profile/[source]/[id]/layout.tsx, src/app/api/impressions/route.ts, src/app/api/metadata/route.ts, src/app/api/oembed/route.ts, src/app/api/publication-views/route.ts, src/app/api/rp/route.tsx, src/app/api/warpcast/signin/route.ts, src/components/Search/SearchBar.tsx, src/components/SideBar/index.tsx, src/helpers/createResponseJSON.ts, src/helpers/memoizeWithRedis.ts, src/services/digestLink.ts
=> fix: UI issues

src/mask/custom-elements.ts, src/modals/ComposeModal.tsx
=> refactor: update theme

src/app/(normal)/post/[source]/[id]/layout.tsx, src/app/(normal)/profile/[source]/[id]/layout.tsx, src/app/api/oembed/route.ts, src/app/api/rp/route.tsx, src/components/Oembed/index.tsx, src/components/Posts/PostBody.tsx, src/helpers/createWagmiTestWalletClient.ts, src/helpers/memoizeWithRedis.ts, tests/helpers/generateCustodyBearer.ts
=> perf: improve pages

pnpm-lock.yaml, src/components/Compose/ComposeAction.tsx, src/helpers/getEncryptedPayload.ts, src/modals/ComposeModal.tsx, src/services/decryptPayload.ts, src/services/steganography.ts
Reverts DimensionDev/mask.social#358
=> Revert "fix: lens avatar"

next.config.js, src/components/AccountSettings.tsx, src/components/Avatar.tsx, src/components/Login/LoginStatusBar.tsx, src/helpers/formatFarcasterProfileFromFirefly.ts, src/providers/firefly/SocialMedia.ts, src/providers/lens/SocialMedia.ts
=> fix: lens avatar

src/services/decryptPayload.ts, src/services/uploadToImgur.ts
https://mask.atlassian.net/browse/FW-290
=> fix: fw-290 payload could not be Uint8Array

src/app/api/rp/route.tsx, src/services/postForLens.ts, src/services/uploadToArweave.ts
=> fix: gen rp images

src/components/RedPacket/AuthorText.tsx
=> fix: from is an evm address

src/components/RedPacket/AuthorText.tsx
=> fix: from evm address

src/components/Markup/MarkupLink/ExternalLink.tsx, src/components/Posts/PostBody.tsx
=> fix: some minor bugs

src/components/Compose/ComposeAction.tsx, src/components/Search/SearchBar.tsx, src/constants/index.ts, src/helpers/fetchImageAsPNG.ts, src/helpers/readChars.ts, src/modals/ComposeModal.tsx, src/modals/LogoutModal.tsx
=> fix: secret image

cspell.json, src/app/(normal)/error.tsx, src/app/(normal)/following/page.tsx, src/components/Actions/Like.tsx, src/components/Compose/PostByItem.tsx, src/components/MobileFallback.tsx, src/helpers/getWalletClientRequired.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/modals/LoginModal.tsx, src/providers/warpcast/SocialMedia.ts
=> Release patch 0.1.6

src/components/Compose/useSetEditorContent.ts, src/helpers/setupCurrentVisitingProfile.ts, src/mask/hooks/usePostInfo.ts, src/mask/widgets/DecryptedInspector.tsx, src/modals/ComposeModal.tsx
=> fix: claim redpacket

src/components/RedPacket/AmountProgressText.tsx, src/components/RedPacket/ClaimProgressText.tsx, src/components/RedPacket/MessageText.tsx
=> fix: rp cover

src/app/(normal)/layout.tsx, src/app/layout.tsx, src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend/useSendLens.ts, src/components/RedPacket/AmountText.tsx, src/constants/regex.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, tailwind.config.cjs
Closes FW-283 FW-293 FW-295 FW-296 FW-297 MF-298 FW-304 FW-306 FW-315 FW-330
=> fix: bugfix for redpacket compose

src/components/RedPacket/AmountProgressText.tsx, src/components/RedPacket/ClaimProgressText.tsx
Closes https://mask.atlassian.net/browse/FW-342
=> fix: rp cover style

src/app/(settings)/settings/display/page.tsx
=> fix: ci error

src/app/globals.css, src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend/index.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, tailwind.config.cjs
Closes FW-283 FW-295 FW-297 FW-341 FW-296
=> fix: redpacket sender name

src/modals/ComposeModal.tsx
fw-338
fw-347
https://mask.atlassian.net/browse/FW-308
https://mask.atlassian.net/browse/FW-327
=> fix: compose editor

.github/workflows/crowdin-download.yml
=> chore: update cron

.github/workflows/sync-submodules.yml
=> chore: sync submoudle actions

src/helpers/signWithED25519.ts, src/providers/farcaster/Session.ts
=> feat: add session.sign

src/helpers/encodeMessageData.ts, src/providers/farcaster/Session.ts, src/providers/hubble/SocialMedia.ts, src/providers/types/Hubble.ts, src/types/frame.ts
=> fix: get fc signer

src/app/api/frame/route.ts, src/components/Frame/index.tsx, src/components/Oembed/Embed.tsx, src/providers/hubble/SocialMedia.ts
=> fix: frame

src/modals/LoginModal.tsx
=> fix: fw-145 login modal close icon

src/components/Compose/ComposeSend/useSendFarcaster.ts, src/providers/hubble/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> feat: add channel key when send rp post on farcaster

.github/workflows/conventional-commits.yml, .github/workflows/jira-issue-key-checking.yml, package.json, scripts/build-logs.sh, src/helpers/anySignal.ts
=> [Release] New release 0.2.0 (minor)

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend/index.tsx, src/components/CustomElements.tsx, src/components/Login/LoginStatusBar.tsx, src/constants/enum.ts, src/helpers/createMaskContext.ts, src/helpers/readChars.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/mask/hooks/usePostInfo.ts, src/modals/ComposeModal.tsx, src/providers/types/SocialMedia.ts, src/store/useComposeStore.ts, src/store/useGlobalStore.ts
Closes FW-292 FW-309 FW-317 MF-350 FW-351 FW-370 FW-390 FW-394
=> fix: compose dialog

.github/workflows/sync-submodules.yml
=> chore: sync submodule

src/helpers/formatLensPost.ts
=> fix: bugfix for lens mirror

.github/workflows/sync-submodules.yml
=> fix: sync submodule ci

src/helpers/formatLensPost.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/modals/ComposeModal.tsx, src/modals/LogoutModal.tsx
Closes FW-326 FW-309 FW-370 FW-403
=> fix: bugfix for logout

env.d.ts, src/constants/index.ts, src/helpers/encodeMessageData.ts, src/middleware.ts, src/providers/hubble/SocialMedia.ts
=> fix: hubble api

src/app/(settings)/components/AccountCard.tsx, src/app/(settings)/components/SettingsList.tsx, src/components/Profile/ContentFeed.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> fix: settings

.github/workflows/release.yml, src/components/Actions/Like.tsx, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/components/Compose/ComposeSend/useSendLens.ts, src/helpers/encodeMessageData.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/hubble/SocialMedia.ts
=> fix: fc hubble

src/providers/hubble/SocialMedia.ts
=> fix: fc post image

src/components/Compose/ComposeSend/index.tsx
=> chore: do not close compose when send error

src/helpers/encodeMessageData.ts, src/providers/hubble/SocialMedia.ts
=> fix: message coding

env.d.ts, src/providers/hubble/SocialMedia.ts
=> fix: hubble token

src/providers/hubble/SocialMedia.ts
=> fix: postid

src/components/Actions/Mirrors.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/types/SocialMedia.ts
=> fix: replace fid to author id

src/helpers/createSiteMetadata.ts
=> chore: add app-id

.github/workflows/release.yml, .github/workflows/sync-submodules.yml
=> fix: release from main branch

.github/workflows/release.yml
=> fix: version

.github/workflows/release.yml
=> refactor: version validation

src/helpers/createSiteMetadata.ts
=> chore: mobile viewport

src/components/Markup/index.tsx, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/getResourceType.ts, src/providers/types/Firefly.ts
=> fix: invalid url

.github/workflows/sync-submodules.yml
=> fix: sync submodules

src/components/Markup/MarkupLink/Hashtag.tsx
Closes https://mask.atlassian.net/browse/FW-371
=> fix: hash tag to open the publishcation search page

src/components/Markup/MarkupLink/MentionLink.tsx, src/components/Markup/MarkupLink/index.tsx, src/helpers/getLensHandleFromMentionTitle.ts
Closes https://mask.atlassian.net/browse/FW-362
=> fix: mention link

src/components/Frame/index.tsx, src/components/Markup/MarkupLink/MentionLink.tsx, src/components/Markup/MarkupLink/index.tsx
Closes https://mask.atlassian.net/browse/FW-385
=> chore(style): add frame border

.github/workflows/crowdin-download.yml, src/components/Markup/MarkupLink/Hashtag.tsx
Closes https://mask.atlassian.net/browse/FW-371
=> fix: add hash tag

src/components/Markup/MarkupLink/index.tsx, src/constants/regex.ts, src/helpers/createLensProfileFromHandle.ts, src/helpers/createLensProfileFromMentionTitle.ts, src/helpers/getLensHandleFromMentionTitle.ts
Closes https://mask.atlassian.net/browse/FW-425
Closes https://mask.atlassian.net/browse/FW-362
=> fix: mention links

src/components/Notification/NotificationItem.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
https://mask.atlassian.net/browse/fw-429
=> fix(i18n): fw-429 lingui plural for zh-hans

src/components/Notification/NotificationItem.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> chore: fixup plural, remove duplciate pharse

next.config.js, package.json, pnpm-lock.yaml, src/components/Lexical/plugins/AutoLinkPlugin.tsx, src/constants/regex.ts, src/helpers/getLensHandleFromMentionTitle.ts
=> fix: mention highlight

pnpm-lock.yaml, src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/components/Frame/index.tsx, src/components/Markup/MarkupLink/index.tsx, src/components/Markup/index.tsx, src/components/Profile/Info.tsx, src/constants/regex.ts, src/helpers/getTwitterProfileUrl.tsx, src/services/uploadToImgur.ts
Closes FW-404 FW-409 FW-417 FW-418 FW-440
=> fix: bugfix for compose

package.json, pnpm-lock.yaml
=> fix: critical package

src/components/RedPacket/AmountProgressText.tsx, src/components/RedPacket/MessageText.tsx
Closes https://mask.atlassian.net/browse/FW-439
Closes https://mask.atlassian.net/browse/FW-435
=> fix: rp images

src/configs/wagmiClient.ts
=> chore: add x1 testnet

src/hooks/useToggleFollow.tsx
https://mask.atlassian.net/browse/fw-379
=> fixup! fix: fw-379 pass specified login source from follow botton (#498)

src/components/Markup/MarkupLink/Hashtag.tsx, src/components/SocialPlatformTabs.tsx
=> fix: scroll to top when click hash tag

src/helpers/fetchArrayBufferS3.ts, src/helpers/readImageBlob.ts, src/modals/ComposeModal.tsx, src/services/steganography.ts
=> refactor: fw 413 cors

src/components/Posts/Attachment.tsx, src/helpers/fetchArrayBufferS3.ts, src/helpers/getEncryptedPayload.ts, src/helpers/readImageBlob.ts, src/modals/ComposeModal.tsx, src/services/steganography.ts
https://mask.atlassian.net/browse/fw-413
=> fix: fw-413 cached image stored on s3 could cause cors error

src/app/api/rp/route.tsx, src/components/RedPacket/CoverContainer.tsx, src/components/RedPacket/PayloadContainer.tsx, src/helpers/getTwemojiUrls.ts
Closes https://mask.atlassian.net/browse/FW-457
Closes https://mask.atlassian.net/browse/FW-456
=> chore: rp payload images

lingui.config.js, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/services/uploadToImgur.ts
=> chore: i18n of upload failed

src/components/AccountSettings.tsx, src/store/useProfileStore.ts
=> refactor: fw 419

src/components/Frame/index.tsx
=> fix: clear input text

src/locales/zh-Hans/messages.po, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/fw-465
=> fix: fw-465 search profiles via farcaster client

src/locales/zh-Hans/messages.po, src/providers/firefly/SocialMedia.ts
https://mask.atlassian.net/browse/fw-475
=> fix: fw-475 get follow status with farcaster client

scripts/setup-vercel.sh
=> chore: skip install pnpm

src/components/Compose/PostByItem.tsx
https://mask.atlassian.net/browse/fw-473
=> feat: fw-473 add source icon as badge to user avatar

src/helpers/formatFarcasterPostFromFirefly.ts
Closes https://mask.atlassian.net/browse/FW-479
=> fix: fc post embeds

pnpm-lock.yaml, src/components/Oembed/Embed.tsx, src/helpers/getSnackbarMessageFromError.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> fix: fw-484 opengraph image

src/components/Compose/ComposeContent.tsx, src/components/Compose/Editor.tsx, src/components/Frame/index.tsx, src/components/Posts/PostBody.tsx, src/constants/index.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/providers/types/SocialMedia.ts, src/store/useComposeStore.ts
Closes https://mask.atlassian.net/browse/FW-480
Closes https://mask.atlassian.net/browse/FW-483
=> feat: compose frame

cspell.json, src/helpers/canParseURL.ts, src/helpers/getResourceType.ts, src/helpers/parseURL.ts, src/helpers/resolveImgurUrl.ts, src/services/uploadToBlob.ts, tests/constants/regexp.ts
=> fix: canparse polyfill

src/components/Compose/ComposeSend/useSendFarcaster.ts, src/locales/zh-Hans/messages.po, src/providers/types/SocialMedia.ts
=> feat: send frame urls

src/components/Oembed/Embed.tsx
https://mask.atlassian.net/browse/fw-486
=> fix: fw-486 broken size of og image

src/components/Compose/ComposeContent.tsx, src/components/Compose/Editor.tsx, src/components/Oembed/index.tsx, src/components/Posts/PostBody.tsx, src/constants/index.ts, src/libs/base/Loader.ts, src/libs/frame/Loader.ts, src/libs/og/Loader.ts, src/store/useComposeStore.ts
=> refactor: fw 482

src/app/(developers)/developers/components/ToolkitList.tsx, src/app/(developers)/developers/frame/layout.tsx, src/app/(developers)/developers/frame/page.tsx, src/app/(developers)/developers/layout.tsx, src/app/(developers)/developers/og/layout.tsx, src/app/(developers)/developers/og/page.tsx, src/app/(developers)/developers/page.tsx, src/components/Compose/ComposeSend/useSendFarcaster.ts, src/constants/enum.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> feat: add dev kit

src/constants/index.ts, src/libs/base/Loader.ts, src/libs/frame/Loader.ts, src/libs/og/Loader.ts
=> chore: urls size

src/mask/widgets/DecryptedInspector.tsx
=> fix: reactive profile id

scripts/build-logs.sh
=> feat: add vercel env

scripts/build-logs.sh, src/components/Login/LoginFarcaster.tsx, src/constants/index.ts
Closes https://mask.atlassian.net/browse/FW-466
=> chore: hide custody wallet login in prod

scripts/build-logs.sh
=> chore: output submodule status to debug log

src/constants/regex.ts, tests/constants/regexp.ts
=> fix: mention regex

vite.config.ts
=> fix: unit test pathname

src/configs/wagmiClient.ts
=> feat: add okx wallet

src/locales/zh-Hans/messages.po, src/providers/warpcast/SocialMedia.ts
=> fix: farcaster discover

src/providers/warpcast/SocialMedia.ts
=> fix: bugfix for farcaster search

src/app/(normal)/layout.tsx, src/app/(normal)/post/[source]/[id]/page.tsx, src/components/AccountSettings.tsx, src/components/Login/LoginStatusBar.tsx, src/components/NavigatorBar/NavigatorBarForMobile.tsx, src/components/ProfileAvatar.tsx, src/components/ProfileAvatarAdd.tsx, src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx, src/components/SideBar/SideBarForDesktop.tsx, src/components/SideBar/SideBarForMobile.tsx, src/components/SourceIcon.tsx, src/store/useNavigatorStore.ts
=> feat: sidebar for mobile

src/components/Actions/More.tsx, src/components/Posts/PostHeader.tsx, src/components/ProfileAvatarAdd.tsx, src/components/SideBar/Menu.tsx
=> fix: responsive UI for mobile

src/locales/zh-Hans/messages.po, src/modals/ComposeModal.tsx
=> fix: ci errors

src/app/(settings)/settings/page.tsx
=> fix: path of general page

src/components/Search/ProfileInList.tsx
https://mask.atlassian.net/browse/fw-501
=> fix: fw-501 style in search profiles

src/app/(settings)/components/SettingsList.tsx, src/app/(settings)/settings/page.tsx, src/components/NavigatorBar/index.tsx, src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx, src/components/SideBar/SideBarForMobile.tsx
=> refactor: mobile ux

src/app/(developers)/components/ToolkitList.tsx, src/app/(developers)/developers/frame/page.tsx, src/app/(developers)/developers/layout.tsx, src/app/(developers)/developers/og/page.tsx, src/app/(developers)/developers/page.tsx, src/app/(settings)/components/Headline.tsx, src/app/(settings)/components/SettingsList.tsx, src/app/(settings)/components/Subtitle.tsx, src/app/(settings)/settings/communities/page.tsx, src/app/(settings)/settings/connected/page.tsx, src/app/(settings)/settings/general/page.tsx, src/app/(settings)/settings/more/page.tsx, src/locales/zh-Hans/messages.po
=> refactor: developers for mobile

src/components/AccountSettings.tsx, src/components/DraggablePopover/index.tsx, src/components/Modal.tsx, src/components/ProfileAvatarAdd.tsx, src/components/SideBar/Menu.tsx, src/components/SideBar/SideBarForDesktop.tsx, src/components/SideBar/SideBarForMobile.tsx, src/modals/DraggablePopover.tsx, src/modals/controls.ts, src/modals/index.tsx
=> feat: add DraggablePopover

src/components/NavigatorBar/NavigatorBarForMobile.tsx, src/components/Search/SearchFilter.tsx
=> feat: search filter for mobile

src/app/(normal)/post/[source]/[id]/page.tsx, src/app/(normal)/profile/[source]/[id]/page.tsx, src/app/(normal)/profile/page.tsx, src/components/ComposeButton/ComposeButtonForMobile.tsx, src/components/Markup/MarkupLink/Hashtag.tsx, src/components/SideBar/Menu.tsx, src/components/SideBar/SideBarForDesktop.tsx, src/components/SideBar/SideBarForMobile.tsx, src/constants/enum.ts, src/hooks/useCurrentVisitingPost.ts, src/hooks/useCurrentVisitingProfile.ts, src/modals/ComposeModal.tsx
=> feat: current visiting post & profile

src/assets/reply.svg, src/components/ComposeButton/ComposeButtonForMobile.tsx
=> refactor: use reply icon

src/components/Compose/ComposeAction.tsx, src/components/Providers.tsx
=> fix: add missing countdown for compose on mobile device

src/app/(normal)/helpers/discoverPosts.ts, src/app/(normal)/page.tsx, src/app/(normal)/pages/Home.tsx, src/app/(normal)/post/[source]/[id]/page.tsx, src/app/(normal)/profile/[source]/[id]/page.tsx, src/components/Oembed/Post.tsx, src/components/SocialPlatformTabs.tsx, src/helpers/replaceSearchParams.ts, src/helpers/resolveSocialPlatform.ts, src/helpers/resolveSourceInURL.ts, src/locales/zh-Hans/messages.po, src/services/getPostOGById.ts, src/services/getProfileOGById.ts, src/store/useGlobalStore.ts, src/types/index.ts
=> refactor: RSC - first page

src/components/Compose/ComposeSend/index.tsx
=> fix: handle send

src/components/Login/ProfileSettings.tsx, src/components/NavigatorBar/NavigatorBarForMobile.tsx, src/locales/zh-Hans/messages.po
=> fix: mobile UI issues

src/components/Modal.tsx, src/components/Posts/SinglePost.tsx, src/modals/PreviewImagesModal.tsx
=> fix: modal state

src/components/Login/LoginButton.tsx
Closes [FW-516](https://mask.atlassian.net/browse/FW-516)
[FW-516]: https://mask.atlassian.net/browse/FW-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: button padding

src/components/Login/ProfileSettings.tsx
=> fix: overflow

src/app/(normal)/profile/[source]/[id]/page.tsx, src/app/(normal)/profile/page.tsx, src/app/(normal)/profile/pages/Profile.tsx
=> refactor: profile page

src/app/(normal)/layout.tsx, src/app/(normal)/profile/pages/Profile.tsx, src/components/IfPathname.tsx, src/helpers/isRoutePathname.ts, src/locales/zh-Hans/messages.po
Closes [FW-517](https://mask.atlassian.net/browse/FW-517)
[FW-517]: https://mask.atlassian.net/browse/FW-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: navigation header

src/app/(normal)/search/page.tsx, src/components/Search/SearchFilter.tsx, src/constants/enum.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/store/useSearchState.ts
=> refactor: rename profiles to users

src/components/Posts/PostHeader.tsx
=> fix: header width of my posts

src/components/Profile/ContentTabs.tsx
Closes [FW-536](https://mask.atlassian.net/browse/FW-536)
[FW-536]: https://mask.atlassian.net/browse/FW-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: reset content tab when source changed

.editorconfig
=> refactor: insert_final_newline

src/components/Login/ProfileSettings.tsx, src/locales/zh-Hans/messages.po
Closes [FW-532](https://mask.atlassian.net/browse/FW-532)
[FW-532]: https://mask.atlassian.net/browse/FW-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: dev only

src/components/NavigatorBar/NavigatorBarForMobile.tsx, src/locales/zh-Hans/messages.po
Closes [FW-540](https://mask.atlassian.net/browse/FW-540)
[FW-540]: https://mask.atlassian.net/browse/FW-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: dup avatars

src/components/Compose/ComposeSend/index.tsx, src/locales/zh-Hans/messages.po
=> fix: show loading icon when sending post

src/components/Profile/ContentCollected.tsx, src/providers/lens/SocialMedia.ts
Closes [FW-538](https://mask.atlassian.net/browse/FW-538)
[FW-538]: https://mask.atlassian.net/browse/FW-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: duplicate collected post

src/components/Login/LoginFarcaster.tsx
Closes [FW-519](https://mask.atlassian.net/browse/FW-519)
[FW-519]: https://mask.atlassian.net/browse/FW-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: detect mobile device

src/app/(normal)/layout.tsx, src/components/Posts/PostHeader.tsx
Closes [FW-543](https://mask.atlassian.net/browse/FW-543)
[FW-543]: https://mask.atlassian.net/browse/FW-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: nav header

src/components/NavigatorBar/NavigatorBarForMobile.tsx, src/components/Search/SearchBar.tsx, src/components/Search/SearchInput.tsx, src/components/Search/SearchRecommendation.tsx
Closes [FW-542](https://mask.atlassian.net/browse/FW-542)
Closes [FW-535](https://mask.atlassian.net/browse/FW-535)
[FW-542]: https://mask.atlassian.net/browse/FW-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-535]: https://mask.atlassian.net/browse/FW-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: the search input

src/app/layout.tsx, src/components/Avatar.tsx, src/components/Popover.tsx, src/components/Profile/Info.tsx, src/components/Profile/Title.tsx
=> fix: popover backdrop

src/components/Providers.tsx, src/modals/index.tsx
=> fix: snackbar ui in mobile

src/providers/warpcast/login.ts
=> fix: resume session after login

src/app/(normal)/profile/[source]/[id]/page.tsx, src/app/(normal)/search/page.tsx, src/components/Profile/Info.tsx, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/fw-551
=> fix: fw-551 follow and unfollow

src/app/(normal)/search/page.tsx, src/locales/zh-Hans/messages.po
=> fix: locale

src/services/postForLens.ts
=> fix: via name

src/app/(normal)/profile/[source]/[id]/page.tsx
=> refactor: eslint

src/locales/zh-Hans/messages.po, src/providers/warpcast/SocialMedia.ts
=> fix: cors warpcast api

src/libs/base/Loader.ts, src/libs/frame/Loader.ts, src/libs/og/Loader.ts, src/locales/zh-Hans/messages.po
=> refactor: loader

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeContent.tsx, src/components/Compose/ComposeImage.tsx, src/components/Compose/ComposeSend/index.tsx, src/modals/ComposeModal.tsx, src/store/useComposeStore.ts
=> fix: thread UI

src/components/Compose/ComposeContent.tsx, src/components/Compose/ComposeThreadContent.tsx, src/modals/ComposeModal.tsx
=> refactor: animation

package.json, patches/@lexical__react@0.12.5.patch, pnpm-lock.yaml
=> fix: compose highlight url

src/app/layout.tsx, src/components/Compose/BeforeUnload.tsx, src/store/useComposeStore.ts
=> chore: before unload

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/CountdownCircle.tsx, src/constants/index.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts, src/services/crossPost.ts, src/services/crossPostThread.ts, src/services/postToFarcaster.ts, src/services/postToLens.ts
=> refactor: post servcies

src/app/(normal)/search/page.tsx, src/components/Search/SearchBar.tsx
=> fix: don't set search type to users on searching with enter

src/constants/enum.ts, src/constants/index.ts, src/helpers/getStampAvatarByProfileId.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts
=> feat: replace search user api to firefly

cspell.json, src/components/CloseButton.tsx, src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeContent.tsx, src/components/Compose/ComposeImage.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/ComposeThreadContent.tsx, src/components/Compose/ComposeVideo.tsx, src/components/Frame/Button.tsx, src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/components/RemoveButton.tsx, src/components/Search/SearchInput.tsx, src/components/Search/SearchRecommendation.tsx, src/components/SideBar/SideBarForMobile.tsx, src/helpers/getSnackbarMessageFromError.tsx, src/helpers/isEmptyPost.ts, src/helpers/isValidPost.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/modals/ComposeModal.tsx, src/modals/ConfirmModal.tsx, src/modals/LoginModal.tsx, src/modals/PreviewImagesModal.tsx, src/services/crossPost.ts, src/services/crossPostThread.ts, src/services/postToFarcaster.ts, src/services/postToLens.ts, src/store/useComposeStore.ts
=> feat: cross post thread

src/app/(normal)/post/[source]/[id]/page.tsx, src/providers/firefly/SocialMedia.ts
=> fix: bugfix for thread detail page

cspell.json, src/constants/index.ts, src/helpers/formatFarcasterProfileFromNeynar.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/types/Neynar.ts, src/providers/types/SocialMedia.ts
=> fix: add neynar social provider

src/components/Login/ProfileInList.tsx, src/components/Search/SearchInput.tsx
https://mask.atlassian.net/browse/fw-562
https://mask.atlassian.net/browse/fw-564
=> fix:  issues about icon rendering

src/components/Compose/ComposeContent.tsx, src/components/Compose/Editor.tsx, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/fw-572
https://mask.atlassian.net/browse/fw-580
https://mask.atlassian.net/browse/fw-583
=> fix: ui on mobile

src/components/Posts/SinglePost.tsx
=> fix: bugfix for show more

patches/@lexical__react@0.12.5.patch, pnpm-lock.yaml
=> chore: update lexical prod patch

src/components/Compose/PostBy.tsx, src/constants/index.ts, src/modals/LoginModal.tsx, src/store/useComposeStore.ts
=> feat: disable twitter

src/components/Compose/ReplyRestriction.tsx
=> refactor: restriction type

src/components/Actions/Collect.tsx, src/components/Actions/Comment.tsx, src/components/Actions/Like.tsx, src/components/Actions/Mirrors.tsx, src/components/Actions/Views.tsx, src/components/Actions/index.tsx, src/components/ClickableArea.tsx, src/components/Compose/Media.tsx
https://mask.atlassian.net/browse/fw-582
https://mask.atlassian.net/browse/fw-591
=> fix: adjust actions layout on mobile, uploading video

src/helpers/formatFarcasterProfileFromNeynar.ts, src/providers/firefly/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/types/Neynar.ts
=> fix: replace query follow status to neynar

src/components/Compose/ComposeSend.tsx, src/components/Login/LoginLens.tsx, src/components/Login/ProfileSettings.tsx, src/components/Oembed/Embed.tsx, src/components/Posts/PostHeader.tsx, src/components/Posts/SinglePost.tsx
https://mask.atlassian.net/browse/fw-563
https://mask.atlassian.net/browse/fw-594
=> fix: post button get disabled incorrectly

src/components/Avatar.tsx, src/components/Login/ProfileInList.tsx
=> fix: use Avatar in LoginLens

pnpm-lock.yaml, src/components/Compose/ComposeVideo.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostByItem.tsx, src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/modals/ComposeModal.tsx, src/store/useComposeStore.ts
=> fix: current compose post

src/app/layout.tsx
=> fix: revert incorrect fix

src/helpers/getAllMentionsForFarcaster.ts, src/providers/warpcast/SocialMedia.ts
=> fix: replace warpcast api to neynar

pnpm-lock.yaml, src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/ComposeThreadContent.tsx, src/components/Compose/Editor.tsx, src/components/Compose/PostByItem.tsx, src/components/Compose/ReplyRestriction.tsx, src/components/Compose/ReplyRestrictionText.tsx, src/helpers/isValidPost.ts, src/hooks/useCurrentAvailableProfile.ts, src/modals/ComposeModal.tsx, src/services/crossPostThread.ts, src/store/useComposeStore.ts
=> fix: crosspost

src/helpers/resolveRedPacketPlatformType.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/services/crossPost.ts, src/services/crossPostThread.ts, src/services/postToFarcaster.ts, src/services/postToLens.ts
=> fix: post to fc

src/components/Compose/ComposeSend.tsx, src/helpers/isPublishedPost.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/services/crossPost.ts, src/services/crossPostThread.ts, src/services/postToFarcaster.ts, src/services/uploadToImgur.ts
=> fix: cross posting error handling

src/app/api/frame/route.ts, src/components/Frame/index.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/types/frame.ts
=> chore: frame tx button

src/helpers/isPublishedPost.ts
Closes [FW-611](https://mask.atlassian.net/browse/FW-611)
[FW-611]: https://mask.atlassian.net/browse/FW-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: isPublishedPost

src/components/Markup/MarkupLink/index.tsx, src/components/Markup/index.tsx
https://mask.atlassian.net/browse/fw-595
=> fix: fw-595 highlight ens handle mention

src/components/Avatar.tsx
=> fix: passed src to Avatar could be undefined

src/providers/lens/SocialMedia.ts, src/services/getLensThreadByPostId.ts
=> fix: bugfix for hidden comment in thread query

src/services/getLensThreadByPostId.ts
=> fix: improve lens thread query

src/app/(normal)/post/[source]/[id]/page.tsx, src/providers/lens/SocialMedia.ts, src/services/getLensThreadByPostId.ts
=> fix: remove show more in detail page

src/components/Compose/ComposeContent.tsx, src/components/Frame/index.tsx, src/components/Oembed/Embed.tsx, src/components/Oembed/Player.tsx
=> fix: oembed box

src/providers/lens/SocialMedia.ts
=> chore: update error message

src/providers/lens/SocialMedia.ts
=> fix: bugfix for lens follow

src/helpers/waitUntilComplete.ts, src/providers/lens/SocialMedia.ts
=> refactor: wait until complete

src/components/Profile/FollowButton.tsx
=> fix: follow button style

src/services/crossPost.ts
https://mask.atlassian.net/browse/fw-614
=> fix(RedPacket): fw-614 update claim strategy

src/app/(normal)/following/page.tsx, src/app/(normal)/pages/Home.tsx, src/app/(normal)/post/[source]/[id]/page.tsx, src/components/Actions/Like.tsx, src/components/Profile/ContentFeed.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/types/SocialMedia.ts, src/services/crossPost.ts
=> refactor: refine like optimistic update

src/components/Posts/PostBody.tsx
=> fix: hidden post

src/helpers/getCurrentAvailableSources.ts, src/helpers/isPublishedPost.ts, src/modals/ComposeModal.tsx, src/services/crossPost.ts, src/services/crossPostThread.ts, src/store/useComposeStore.ts
Closes [FW-624](https://mask.atlassian.net/browse/FW-624)
[FW-624]: https://mask.atlassian.net/browse/FW-624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: available sources

src/app/(normal)/post/[source]/[id]/page.tsx, src/components/Actions/Like.tsx, src/components/Comments/index.tsx, src/components/Profile/ContentCollected.tsx, src/helpers/mergeThreadPostsForFarcaster.ts, src/providers/warpcast/SocialMedia.ts, src/services/postTo.ts
https://mask.atlassian.net/browse/fw-628
https://mask.atlassian.net/browse/fw-630
=> fix:  like on threads

package.json, pnpm-lock.yaml, src/hooks/useToggleFollow.tsx
MF-0000 FW-0000
https://mask.atlassian.net/browse/FW-621
=> fix(Lens): show client error message

src/services/crossPost.ts
=> fix: missing part when merge PR

src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/fw-600
https://mask.atlassian.net/browse/FW-628
@guanbinrui Please also pick to hotfix `5.1.1`
=> fix: fw-600 popular-cast-feed from warpcast doesn't provide viewer context

src/components/Frame/index.tsx, src/components/Markup/MarkupLink/Hashtag.tsx, src/helpers/getMetaContent.ts, src/helpers/q.ts, src/libs/frame/readers/metadata.ts, src/libs/og/readers/metadata.ts
https://mask.atlassian.net/browse/fw-633
https://mask.atlassian.net/browse/fw-638
=> fix(Frame): fw-633 image aspect

src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/neynar/SocialMedia.ts
=> refactor: impl social media

src/mask/widgets/DecryptedInspector.tsx, src/providers/firefly/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/services/resolveIdentity.ts
=> refactor: resolve identity

src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/fw-639
=> fix: fw-639 encode search keyword for warpcast

src/configs/farcasterClient.ts, src/helpers/encodeMessageData.ts, src/helpers/getFarcasterSessionType.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts, src/services/resolveIdentity.ts
=> refactor: withSession

src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx
https://mask.atlassian.net/browse/fw-643
=> fix: fw-643 format ens domain

src/helpers/q.ts, src/libs/frame/readers/metadata.ts
https://mask.atlassian.net/browse/fw-633
=> fix(Frame): fw-633 get frame buttons

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Posts/PostBody.tsx, src/components/Posts/PostHeader.tsx
=> fix: safari line clamp

src/components/Posts/PostBody.tsx
=> fix: post body height

cspell.json, env.d.ts, src/app/api/firefly/metrics/download/route.ts, src/app/api/firefly/metrics/upload/route.ts, src/configs/lensClient.ts, src/providers/base/SessionFactory.ts, src/providers/firefly/Session.ts, src/providers/lens/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts, src/services/uploadToIPFS.ts, src/store/useProfileStore.ts
=> feat: impl firefly session

src/constants/index.ts
Closes [FW-648](https://mask.atlassian.net/browse/FW-648)
[FW-648]: https://mask.atlassian.net/browse/FW-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update post size constants

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/CountdownCircle.tsx, src/constants/index.ts, src/helpers/getCurrentPostLimits.ts, src/helpers/isValidPost.ts
Closes [FW-648](https://mask.atlassian.net/browse/FW-648)
[FW-648]: https://mask.atlassian.net/browse/FW-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: dynamic post limits

src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx
=> fix(ui): give more space to text in nav menu

src/services/crossPost.ts
https://mask.atlassian.net/browse/fw-539
=> fix(RedPacket): fw-539 add post on

src/components/Compose/ComposeAction.tsx, src/helpers/getCurrentPostImageLimits.ts, src/modals/ComposeModal.tsx
=> refactor: getCurrentPostImageLimits

src/components/WagmiProvider.tsx, src/configs/wagmiClient.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/modals/ComposeModal.tsx, src/services/uploadToArweave.ts
=> fix: locale of rainbow kit

src/components/Login/ProfileAvatarAdd.tsx, src/components/ProfileAvatar.tsx
Closes [FW-672](https://mask.atlassian.net/browse/FW-672)
[FW-672]: https://mask.atlassian.net/browse/FW-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: hide shadow

src/app/(normal)/layout.tsx, src/app/(settings)/settings/connected/page.tsx, src/app/(settings)/settings/layout.tsx, src/app/(settings)/settings/page.tsx, src/app/layout.tsx, src/components/Frame/index.tsx, src/components/NotLoginFallback.tsx, src/components/Oembed/Embed.tsx, src/components/Providers.tsx, src/hooks/useIsDarkMode.ts, src/modals/PreviewImagesModal.tsx
https://mask.atlassian.net/browse/fw-673
https://mask.atlassian.net/browse/fw-674
https://mask.atlassian.net/browse/fw-677
https://mask.atlassian.net/browse/FW-680
https://mask.atlassian.net/browse/FW-678
=> fix: some ui issues on mobile

src/components/Notification/NotificationItem.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
Closes [FW-684](https://mask.atlassian.net/browse/FW-684)
=> refactor: update notifications api

.github/workflows/sync-submodules.yml, package.json, pnpm-lock.yaml
MF-0000 FW-0000
https://mask.atlassian.net/browse/FW-695
=> chore: sync submodule changes

src/decorators/SetQueryDataForPosts.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts, src/types/index.ts, tsconfig.json
=> refactor: batch set post detail

.github/workflows/sync-submodules.yml
=> fix: expression

src/components/Profile/ContentFeed.tsx
=> fix: deps list

src/components/Frame/index.tsx
Closes [FW-686](https://mask.atlassian.net/browse/FW-686)
=> fix: enqueueErrorMsg

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Profile/Title.tsx, src/components/Providers.tsx, src/hooks/useComeback.ts, src/store/useGlobalStore.ts
=> revert: recovery routeChanged state

src/components/VirtualList/index.tsx, src/store/useGlobalStore.ts
=> refactor: list key type

src/helpers/formatFarcasterChannelFromFirefly.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> feat: add channel apis

src/components/Compose/ComposeAction.tsx, src/components/ComposeButton/ComposeButtonForMobile.tsx, src/components/Modal.tsx, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/fw-677
https://mask.atlassian.net/browse/FW-714
=> fix: compose button when not login current source yet

src/components/Compose/ComposeAction.tsx
Closes [FW-731](https://mask.atlassian.net/browse/FW-731)
[FW-731]: https://mask.atlassian.net/browse/FW-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: share to x

src/components/Compose/Media.tsx, src/components/Posts/Attachment.tsx, src/constants/index.ts
Closes [FW-732](https://mask.atlassian.net/browse/FW-732)
[FW-732]: https://mask.atlassian.net/browse/FW-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: image size when lens alone

src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> [Release] Hotfix 5.1.1 => 5.1.1.1 (patch)

src/components/Notification/NotificationItem.tsx, src/components/Notification/ProfileLink.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> fix: dup follower msg

src/components/Posts/Attachment.tsx, src/components/Profile/ContentCollected.tsx, src/components/Profile/ContentFeed.tsx, src/helpers/getEncryptedPayload.ts
https://mask.atlassian.net/browse/fw-733
https://mask.atlassian.net/browse/fw-734
=> fix: fw-733 image with crossOrigin=anonymous make image gets blocked

src/components/Posts/Attachment.tsx
=> fixup! feat: init parallel image modal (#784)

src/decorators/SetQueryDataForCommentPost.ts, src/providers/farcaster/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/services/postToFarcaster.ts
=> refactor: decorator

src/components/Actions/Comment.tsx, src/components/Comments/index.tsx, src/components/Compose/ComposeSend.tsx, src/components/RemoveButton.tsx, src/components/SideBar/ConnectWallet.tsx, src/decorators/SetQueryDataForCommentPost.ts, src/helpers/refreshComments.ts, src/providers/farcaster/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/services/postToFarcaster.ts
https://mask.atlassian.net/browse/fw-692
https://mask.atlassian.net/browse/fw-740
https://mask.atlassian.net/browse/fw-747
=> fix: fw-740 update data right after commenting/replying

src/app/(developers)/developers/frame/page.tsx, src/app/(developers)/developers/og/page.tsx, src/components/Frame/Input.tsx, src/components/Search/SearchInput.tsx
=> chore: disable check & auto complete

src/components/Posts/PostBody.tsx, src/constants/browser.ts
=> fix: build error

package.json, pnpm-lock.yaml, src/constants/browser.ts
=> fix: browser parser

src/helpers/getAllMentionsForFarcaster.ts
=> fix: invalid mention

src/components/VirtualList/index.tsx
=> chore: replace scroll api

src/components/Compose/CountdownCircle.tsx, src/constants/index.ts, src/helpers/isValidPost.ts
Closes [FW-754](https://mask.atlassian.net/browse/FW-754)
[FW-754]: https://mask.atlassian.net/browse/FW-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: post size limits

src/components/Notification/NotificationItem.tsx, src/components/Profile/Tabs.tsx
=> fix: tab i18n

src/helpers/patchPostQueryData.ts
https://mask.atlassian.net/browse/fw-738
=> fix: fw-738 like commentOn of post

src/helpers/getResourceType.ts
https://mask.atlassian.net/browse/fw-755
=> fix: fw-755 detect image in embeds

src/app/(normal)/layout.tsx, src/app/globals.css, src/app/layout.tsx, src/components/ListInPage.tsx, src/components/NotLoginFallback.tsx
This reverts commit 2d6e2a7.MF-0000 FW-0000
=> fix: revert flex layout changes

src/app/@modal/(.)post/[id]/photos/[index]/page.tsx, src/components/Compose/Editor.tsx, src/components/Modal.tsx
=> refactor: modal warning

src/helpers/getCurrentPostLimits.ts
=> fix: not available chars

src/modals/ComposeModal.tsx
Closes [FW-718](https://mask.atlassian.net/browse/FW-718)
[FW-718]: https://mask.atlassian.net/browse/FW-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fixed compose dialog

src/components/Compose/ComposeAction.tsx
Closes [FW-764](https://mask.atlassian.net/browse/FW-764)
[FW-764]: https://mask.atlassian.net/browse/FW-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: reply mode

scripts/build-logs.sh
=> chore: add branch

package.json, pnpm-lock.yaml
=> chore: rollback pkg

src/components/Compose/ComposeAction.tsx
Closes [FW-766](https://mask.atlassian.net/browse/FW-766)
[FW-766]: https://mask.atlassian.net/browse/FW-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: share to

cspell.json, src/components/Actions/Like.tsx, src/components/Actions/index.tsx, src/components/Posts/ActionType.tsx, src/decorators/SetQueryDataForLikePost.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/getResourceType.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> fix: missing asset

src/app/@modal/(.)post/[id]/photos/[index]/page.tsx
=> fix: cancel backdrop close in mobile

src/app/(settings)/settings/connected/page.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
Closes [FW-770](https://mask.atlassian.net/browse/FW-770)
[FW-770]: https://mask.atlassian.net/browse/FW-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update copy msg

src/app/(normal)/layout.tsx, src/components/IfPathname.tsx
=> fix: timeline navbar disappear when photo modal opened

src/app/(normal)/layout.tsx, src/components/IfPathname.tsx
=> fix: warning

src/app/(normal)/layout.tsx, src/components/SocialPlatformTabs.tsx
=> fix: social platform tabs

src/components/NotLoginFallback.tsx
=> fix: padding top for NotLoginFallback

src/components/Posts/Attachment.tsx, src/components/VirtualList/VirtualList.tsx
=> chore: add stop propagation

src/app/(normal)/@modal/(.)post/[id]/photos/[index]/page.tsx
=> chore: avoid unnecessary request

src/helpers/createSiteViewport.ts
https://mask.atlassian.net/browse/fw-773
=> fix: fw-773 unsupported viewport value causes crash

.github/workflows/pick-commit.yml
=> chore: pick commit

.github/workflows/pick-commit.yml
=> fix: fetch all commits

src/components/Actions/Mirrors.tsx, src/components/VirtualList/VirtualList.tsx, src/decorators/SetQueryDataForMirrorPost.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
https://mask.atlassian.net/browse/fw-741
https://mask.atlassian.net/browse/fw-772
=> fix(Lens): fw-741 post can be mirrored many times

src/components/Frame/index.tsx
=> chore: fallback frame image

src/app/(normal)/layout.tsx
=> fix: layout issues

src/components/Comments/index.tsx, src/components/Compose/ComposeSend.tsx, src/helpers/createMockComment.ts, src/helpers/createMockPost.ts, src/helpers/refreshComments.ts, src/services/createPostTo.ts, src/services/crossPost.ts
https://mask.atlassian.net/browse/fw-769
=> fix: fw-769 insert comment optimistically

src/components/Markup/index.tsx
https://mask.atlassian.net/browse/fw-722
=> fix: fw-722 don't strip markdown from post content

scripts/build-logs.sh
=> chore: display build time in UTC time

src/constants/index.ts
=> chore: enable twitter

src/app/layout.tsx, src/constants/bowser.ts
=> fix: replace bowser

src/components/ComposeButton/ComposeButtonForMobile.tsx, src/components/Posts/ActionType.tsx, src/components/Posts/SinglePost.tsx, src/components/Posts/ThreadBody.tsx, src/helpers/isRoutePathname.ts, src/hooks/useCurrentVisitingPost.ts, tests/helpers/isRoutePathname.ts
=> fix: isPostPage state

src/app/api/auth/[...nextauth]/options.ts, src/app/api/firefly/metrics/download/route.ts, src/app/api/warpcast/signin/route.ts, src/app/layout.tsx, src/components/Compose/ComposeAction.tsx, src/components/CustomElements.tsx, src/components/Login/ProfileSettings.tsx, src/components/Posts/PostBody.tsx, src/components/Providers.tsx, src/configs/wagmiClient.ts, src/constants/env.ts, src/constants/index.ts, src/helpers/createTwitterClientV2.ts, src/helpers/createWagmiTestWalletClient.ts, src/helpers/fetchCached.ts, src/helpers/fetchSquashed.ts, src/mask/custom-elements.ts, src/providers/hubble/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/services/crossPost.ts, src/services/uploadToImgur.ts, src/store/useImpressionsStore.ts, tests/helpers/generateCustodyBearer.ts
=> fix: env crash

src/app/(settings)/settings/communities/page.tsx, src/helpers/createSiteMetadata.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
Change link `firefly.land` to `firefly.social` in settings communities page
Closes FW-526
=> feat: fw-526 adjust `firefly.land` to `firefly.social`

src/constants/regex.ts
=> chore: ff canary

pnpm-lock.yaml
https://mask.atlassian.net/browse/fw-744
=> fixup! fix: fw-744 patch react-use (#864)

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/ComposeVideo.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostByItem.tsx, src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/helpers/getCompositePost.ts, src/hooks/useCompositePost.ts, src/modals/ComposeModal.tsx, src/services/crossPost.ts, src/store/useComposeStore.ts
Closes [FW-794](https://mask.atlassian.net/browse/FW-794)
[FW-794]: https://mask.atlassian.net/browse/FW-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: composite post

src/app/api/twitter/uploadMedia/route.ts, src/components/Login/ProfileInList.tsx, src/components/Login/ProfileSettings.tsx, src/modals/ComposeModal.tsx, src/services/uploadToTwitter.ts
Closes FW-788 FW-780 FW-655 FW-688
=> fix: twitter media upload & ui 

src/app/(normal)/following/page.tsx, src/app/(normal)/pages/Home.tsx, src/components/Channel/PostList.tsx, src/components/Comments/index.tsx, src/components/ListInPage.tsx, src/components/Oembed/index.tsx, src/components/Posts/SinglePost.tsx, src/components/Profile/CollectedList.tsx, src/components/Profile/FeedList.tsx, src/components/VirtualList/getPostItemContent.tsx
Closes FW-658 FW-767 FW-796 FW-799
=> refactor: improve mobile timeline

src/app/globals.css, src/components/ListInPage.tsx
=> fix: bugfix for timeline

src/hooks/useCompositePost.ts
Closes [FW-800](https://mask.atlassian.net/browse/FW-800)
Closes [FW-800](https://mask.atlassian.net/browse/FW-801)
Closes [FW-800](https://mask.atlassian.net/browse/FW-802)
Closes [FW-800](https://mask.atlassian.net/browse/FW-803)
[FW-800]: https://mask.atlassian.net/browse/FW-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-800]: https://mask.atlassian.net/browse/FW-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-800]: https://mask.atlassian.net/browse/FW-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-800]: https://mask.atlassian.net/browse/FW-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
=> fix: use composite post

src/modals/ComposeModal.tsx, src/services/uploadToTwitter.ts
=> fix: fw-788 & img compose

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeContent.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/ComposeVideo.tsx, src/components/Compose/CountdownCircle.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostByItem.tsx, src/components/Compose/ReplyRestriction.tsx, src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/helpers/getCompositePost.ts, src/helpers/isPublishedPost.ts, src/helpers/isValidPost.ts, src/hooks/useCompositePost.ts, src/modals/ComposeModal.tsx, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts, src/services/crossPostThread.ts, src/store/useComposeStore.ts
=> refactor: compose store

src/components/Comments/index.tsx, src/components/VirtualList/getPostItemContent.tsx
=> fix: missing prop

src/services/postToTwitter.ts, src/types/index.ts
=> fix: twitter img compose

src/app/layout.tsx, src/hooks/useCompositePost.ts
=> refactor: load components

src/providers/twitter/SocialMedia.ts
https://mask.atlassian.net/browse/fw-694
=> fix: fw-694 only people you follow

src/decorators/SetQueryDataForLikePost.ts, src/providers/firefly/SocialMedia.ts
=> fix: remove farcaster fetch

env.d.ts, src/services/postToFarcaster.ts
=> feat: add channel key config

next.config.js
=> fix: missing config

src/app/api/twitter/compose/route.ts, src/app/api/twitter/me/route.ts
=> refactor: error msg

env.d.ts, next.config.js, src/services/postToFarcaster.ts
=> chore: rename env name

src/constants/env.ts, src/services/postToFarcaster.ts
=> chore: rename env

src/services/crossPostThread.ts
=> fix: get parent post by id

src/services/crossPostThread.ts
=> fix: error handling

.editorconfig, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/conventional-commits.yml, .github/workflows/crowdin-download.yml, .github/workflows/crowdin-upload.yml, .github/workflows/cspell.yml, .github/workflows/eslint.yml, .github/workflows/jira-issue-key-checking.yml, .github/workflows/lingui.yml, .github/workflows/prettier.yml, .github/workflows/release.yml, .github/workflows/sync-submodules.yml, .github/workflows/test.yaml, .prettierignore, .prettierrc, crowdin.yml
=> refactor: format *.yml

src/components/Avatar.tsx, src/components/AvatarGroup.tsx, src/components/Notification/NotificationItem.tsx
=> refactor: AvatarGroup

src/providers/firefly/SocialMedia.ts
=> fix: invalid friendship fetch

src/helpers/formatFarcasterPostFromFirefly.ts
https://mask.atlassian.net/browse/fw-814
=> fix: fw-814 frame in embeds

src/app/api/s3/route.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/services/uploadToS3.ts
=> refactor: s3

src/app/api/firefly/metrics/decrypt/route.ts, src/app/api/impressions/route.ts, src/app/api/metadata/route.ts, src/app/api/publication-views/route.ts, src/app/api/twitter/compose/route.ts, src/app/api/twitter/me/route.ts, src/app/api/twitter/uploadMedia/route.ts, src/app/api/warpcast/signin/route.ts
=> refactor: create success response json

src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> chore: add post deletion APi

src/app/globals.css, src/components/Actions/More.tsx, src/components/Login/ProfileAvatarAdd.tsx, src/components/Login/ProfileSettings.tsx, src/components/ProfileAvatar.tsx, src/providers/neynar/SocialMedia.ts
=> refactor: border line

src/components/Login/ProfileAvatarAdd.tsx, src/components/ProfileAvatar.tsx
=> refactor: remove shadow of source icon

src/components/Profile/FeedList.tsx, src/components/VirtualList/getPostItemContent.tsx, src/helpers/createDummyPost.ts, src/helpers/createMockComment.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/formatLensPost.ts, src/helpers/formatWarpcastPost.ts, src/helpers/getPostsSelector.ts, src/helpers/mergeThreadPostsForLens.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/services/postToFarcaster.ts, src/services/postToLens.ts, src/services/postToTwitter.ts
https://mask.atlassian.net/browse/fw-775
=> fix: fw-775 introduce id to Post

src/app/api/warpcast/signin/route.ts
=> fix: exipration time

src/components/Channel/Info.tsx, src/components/ChannelInList.tsx, src/components/Profile/LikedFeedList.tsx, src/components/Profile/MediaList.tsx, src/components/Profile/RepliesList.tsx, src/components/Profile/Tabs.tsx, src/components/Search/SearchRecommendation.tsx, src/constants/enum.ts, src/constants/index.ts, src/helpers/formatFarcasterChannelFromFirefly.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> feat: add new tabs in profile page

src/app/api/warpcast/signin/route.ts, src/providers/warpcast/createSessionByGrantPermission.ts
=> refactor: create private key in client

src/helpers/fetchJSON.ts, src/helpers/getNextFetchers.ts
=> refactor: no default content type

src/services/uploadToS3.ts
=> fix: upload file to s3 without default content type

src/components/Channel/Info.tsx, src/components/Search/SearchFilter.tsx, src/components/Search/SearchRecommendation.tsx, src/components/SocialPlatformTabs.tsx, src/constants/index.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/firefly/SocialMedia.ts
Closes FW-725 FW-727 FW-817 FW-819
=> fix: bugfix for channel

src/components/Profile/Tabs.tsx, src/components/Search/SearchFilter.tsx, src/constants/index.ts
=> refactor: constants

src/providers/lens/SocialMedia.ts, src/services/postToLens.ts
=> refactor: momoka request

pnpm-lock.yaml
=> fix: patch useAsyncFn

src/helpers/formatTimestamp.ts, src/providers/firefly/SocialMedia.ts
=> fix: post time formatter

package.json, pnpm-lock.yaml
=> fix: pin react-use version

src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/services/crossPostThread.ts
=> refactor: success message

public/js/browser-detector.js
https://mask.atlassian.net/browse/FW-779
=> fix: style change for different color theme

src/components/Compose/ComposeSend.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/services/crossPostThread.ts
Closes FW-841
-   [x] I have tested these changes locally.
-   [x] I have reviewed the code changes.
=> feat: add sending status progress to compose send button

src/app/api/s3/route.ts
=> fix: prettier

src/modals/ComposeModal.tsx
=> fix: scroll to bottom when add post

globals.d.ts, public/js/sentry.js, src/app/layout.tsx
=> chore: setup for sentry

pnpm-lock.yaml
=> fix: patch useAsyncFn in react-use

src/services/crossPostThread.ts
Closes [FW-850](https://mask.atlassian.net/browse/FW-850)
[FW-850]: https://mask.atlassian.net/browse/FW-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: cross post error msg

src/components/ErrorReportSnackbar.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
https://mask.atlassian.net/browse/fw-856
=> feat: copy error content

src/components/ErrorReportSnackbar.tsx
=> fix: use ClickableButton

src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/services/createPostTo.ts
=> refactor: sync msg

src/components/ErrorReportSnackbar.tsx
=> fix: ErrorReportSnackbar max width

next.config.js
=> fix: mask envs

src/helpers/getResourceType.ts
=> fix: get resource type

src/components/ErrorReportSnackbar.tsx
https://mask.atlassian.net/browse/FW-857
=> fix: adjust error reporter snackbar

src/services/createPostTo.ts
=> fix: should return post id after posting

src/components/Providers.tsx
=> fix: remove useless code

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Posts/Attachment.tsx, src/components/Posts/PostBody.tsx, src/components/Posts/Quote.tsx, src/constants/index.ts, src/helpers/getPostsSelector.ts, src/helpers/sanitizeDStorageUrl.ts, src/services/crossPost.ts
Closes FW-859 FW-860 FW-861 FW-862
=> fix: thread and lens ipfs

next.config.js
=> chore: adjust request body size limit

next.config.js, src/components/Compose/Media.tsx, src/constants/index.ts
Closes FW-0000
-   [x] I have tested these changes locally.
-   [x] I have reviewed the code changes.
-   [x] I have added unit tests if applicable.
=> chore: body size limit

src/components/Compose/ComposeSend.tsx, src/services/crossPost.ts, src/services/crossPostThread.ts
=> fix: retry message

src/app/(normal)/post/[id]/pages/DetailPage.tsx
=> fix: bugfix for thread display

src/components/Providers.tsx, src/configs/sentryClient.ts
=> chore: sentry config

src/components/Login/LoginFarcaster.tsx, src/providers/warpcast/createSessionByGrantPermission.ts
=> fix: login fc

src/components/Profile/FollowButton.tsx, src/components/Profile/Info.tsx, src/components/Profile/ProfileMoreAction.tsx, src/components/Profile/Title.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> feat: copy profile link

src/components/Compose/Media.tsx
https://mask.atlassian.net/browse/fw-843
=> fix: fw-843 do not allow to add video when already has image

src/components/ErrorReportSnackbar.tsx
https://mask.atlassian.net/browse/fw-856
=> fix: fw-856 adjust error report snackbar on mobile

src/hooks/useDeletePost.tsx, src/providers/lens/SocialMedia.ts
=> fix(Lens): fixup merge released

src/components/Markup/index.tsx, src/helpers/mergeThreadPostsForFarcaster.ts
=> fix: bugfix for markup

src/components/ListInPage.tsx, src/components/VirtualList/VirtualListFooter.tsx
=> fix: hidden footer when list initial render

src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Markup/MarkupLink/index.tsx, src/components/Markup/index.tsx, src/components/Profile/Info.tsx, src/constants/regex.ts, src/helpers/getFarcasterChannelUrlById.ts
=> feat: highlight channel in post and bio

src/app/globals.css, src/components/Channel/ChannelCard.tsx, src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Markup/MarkupLink/index.tsx, src/components/Markup/index.tsx
=> feat: channel card

cspell.json, src/app/(normal)/layout.tsx, src/app/(normal)/post/[id]/[type]/page.tsx, src/components/Actions/More.tsx, src/components/Actions/Views.tsx, src/components/Engagement/LikeList.tsx, src/components/Engagement/QuoteList.tsx, src/components/Engagement/RepostList.tsx, src/components/Engagement/type.ts, src/constants/enum.ts, src/constants/index.ts, src/constants/regex.ts, src/helpers/formatLensPostReaction.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> feat: post engagement

src/components/Channel/ChannelCard.tsx, src/components/Posts/SinglePost.tsx, src/helpers/formatFarcasterChannelFromFirefly.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts
=> feat: channel tag for farcaster

src/components/Login/ProfileAvatarInteractive.tsx, src/components/Login/ProfileSettings.tsx
=> refactor: popover for profile settings

src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Posts/ChannelAnchor.tsx, src/components/Posts/SinglePost.tsx, src/providers/firefly/SocialMedia.ts
=> fix: bugfix for channel tag

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
=> fix(Farcaster): detect deleted post

.github/workflows/cspell.yml, .github/workflows/eslint.yml, .github/workflows/lingui.yml, .github/workflows/prettier.yml, .github/workflows/release.yml, .github/workflows/test.yaml, next.config.js, package.json, scripts/setup-gh-actions.sh, scripts/setup-vercel.sh, scripts/setup.sh, src/service-workers/tsconfig.json, tsconfig.json
=> refactor: try speed ci build

src/app/(normal)/layout.tsx
MF-0000 FW-0000
https://mask.atlassian.net/browse/FW-898
=> fix: hide social tabs in engagement page

src/app/(normal)/bookmark/BookmarkList.tsx, src/decorators/SetQueryDataForBookmarkPost.ts, src/hooks/useToggleBookmark.ts, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/fw-904
=> fix: fixup fw-904 add bookmark

src/app/api/firefly/decrypt-metrics/route.ts, src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginLens.tsx, src/components/Login/ProfileSettings.tsx, src/helpers/enqueueMessage.tsx, src/helpers/isAbortedError.ts, src/helpers/restoreProfile.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/modals/ConfirmModal.tsx, src/modals/FireflySessionConfirmModal.tsx, src/modals/controls.ts, src/providers/farcaster/Session.ts, src/providers/farcaster/SessionHolder.ts, src/providers/lens/SessionHolder.ts, src/providers/lens/createSessionForProfileId.ts, src/services/syncSessionFromFirefly.ts
=> refactor: detect accounts

src/components/Compose/ComposeAction.tsx, src/components/Compose/PostBy.tsx, src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/components/Login/LoginStatusBar.tsx, src/components/NavigatorBar/NavigatorBarForMobile.tsx, src/components/Posts/FollowingPostList.tsx, src/constants/index.ts, src/hooks/useCurrentAvailableProfile.ts, src/hooks/useIsLogin.ts, src/modals/ComposeModal.tsx, src/modals/FireflySessionConfirmModal.tsx, src/modals/LoginModal.tsx, src/modals/LogoutModal.tsx, src/services/crossPost.ts, src/services/crossPostThread.ts, src/store/useComposeStore.ts
=> refactor: naming

src/app/(normal)/profile/page.tsx
=> fix: bugfix for source

public/.well-known/apple-app-site-association
=> chore: add universal link config

package.json, public/.well-known/apple-app-site-association
=> [Release] Hotfix 5.1.6 => 5.1.7 (patch)

next.config.js, src/app/api/frame/route.ts, src/components/ErrorReportSnackbar.tsx, src/constants/env.ts
=> fix: trace post redirect response, report with system info

src/constants/index.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts
=> fix: bugfix for channel detail

src/app/api/auth/[...nextauth]/options.ts, src/providers/firefly/SessionHolder.ts
=> refactor: with session

src/app/api/frame/route.ts, src/app/api/twitter/bookmark/[tweetId]/route.ts, src/app/api/twitter/bookmarks/route.ts, src/constants/enum.ts, src/decorators/SetQueryDataForBookmarkPost.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/formatTwitterPostFromFirefly.ts, src/helpers/getSearchParamsFromRequestWithZodObject.ts, src/helpers/pageableSchemas.ts, src/helpers/patchPostQueryData.ts, src/helpers/resolveSource.ts, src/hooks/useToggleBookmark.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/FW-914
https://mask.atlassian.net/browse/FW-939
=> fix: farcaster bookmark

src/app/(normal)/post/[id]/[type]/page.tsx, src/components/Actions/Bookmark.tsx, src/components/Actions/MuteChannelButton.tsx, src/components/Actions/Views.tsx, src/decorators/SetQueryDataForBlockUser.ts, src/helpers/deletePostsOfUserFromQueryData.ts, src/helpers/enqueueMessage.tsx, src/hooks/useDeletePost.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
https://mask.atlassian.net/browse/fw-868
https://mask.atlassian.net/browse/fw-881
https://mask.atlassian.net/browse/fw-909
https://mask.atlassian.net/browse/fw-913
=> fix: block user, block channel

src/app/(normal)/layout.tsx, src/components/Profile/ProfileSourceTabs.tsx, src/components/Profile/ProfileTabs.tsx, src/components/SourceTabs.tsx, src/constants/index.ts
=> refactor: sort tabs

src/app/(normal)/layout.tsx, src/app/(normal)/trending/pages/TrendingPage.tsx, src/app/globals.css, src/components/AsideTitle.tsx, src/components/Channel/ChannelList.tsx, src/components/ListInPage.tsx, src/components/Login/LoginLens.tsx, src/components/PageTitle.tsx, src/components/Search/SearchFilter.tsx, src/components/Search/SearchRecommendation.tsx, src/providers/firefly/SocialMedia.ts
=> fix: aside scrolling

src/app/(normal)/pages/Profile.tsx, src/app/(normal)/profile/page.tsx, src/app/globals.css, src/assets/article-anchor.svg, src/components/Article/ArticleHeader.tsx, src/components/Article/SingleArticle.tsx, src/components/Markup/Markup.tsx, src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Markup/MarkupLink/index.tsx, src/components/Posts/ChannelAnchor.tsx, src/components/Profile/Info.tsx, src/components/Profile/ProfileContentTabs.tsx, src/components/Profile/ProfileSourceTabs.tsx, src/components/Profile/ProfileTabs.tsx, src/components/Profile/Tabs.tsx, src/components/Profile/WalletInfo.tsx, src/components/Profile/WalletTabs.tsx, src/components/RelatedSourceIcon.tsx, src/components/RelationPlatformIcon.tsx, src/components/SourceTabs.tsx, src/constants/regexp.ts, src/helpers/formatFireflyProfilesFromWalletProfiles.ts, src/helpers/resolveSourceName.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, tests/constants/regexp.ts
Closes FW-920 FW-921 FW-924 FW-903 FW-925 FW-926  FW-935 FW-936 FW-937 FW-931
=> fix: bugfix for channel and article

src/app/globals.css, src/components/Article/SingleArticle.tsx, src/components/Profile/ProfileContentTabs.tsx, src/components/Profile/ProfileSourceTabs.tsx, src/components/Profile/ProfileTabs.tsx, src/components/Profile/WalletTabs.tsx, src/components/SourceTabs.tsx
=> fix: tabs style

cspell.json, src/components/Actions/BlockUserButton.tsx, src/components/Actions/Bookmark.tsx, src/components/Actions/UnmuteButton.tsx, src/components/Compose/ComposeSend.tsx, src/components/ErrorReportSnackbar.tsx, src/components/Profile/Info.tsx, src/components/ProfileInList.tsx, src/helpers/enqueueMessage.tsx, src/helpers/q.ts, src/hooks/useCheckPostMedias.ts, src/libs/og/readers/metadata.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/fw-842
https://mask.atlassian.net/browse/fw-919
https://mask.atlassian.net/browse/fw-922
https://mask.atlassian.net/browse/FW-942
=> fix: farcaster block/unblock and some ui issues

src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginLens.tsx, src/components/Login/ProfileSettings.tsx, src/modals/FireflySessionConfirmModal.tsx
Closes [FW-938](https://mask.atlassian.net/browse/FW-938)
[FW-938]: https://mask.atlassian.net/browse/FW-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: filter by current source

src/app/(normal)/article/[id]/pages/DetailPage.tsx, src/app/(normal)/pages/Profile.tsx, src/app/(normal)/profile/page.tsx, src/assets/mirror.xyz.svg, src/assets/paragraph.svg, src/components/Article/SingleArticle.tsx, src/components/Profile/ProfileContent.tsx, src/components/Profile/ProfileContentTabs.tsx, src/components/Profile/ProfileSourceTabs.tsx, src/components/Profile/ProfileTabs.tsx, src/components/SourceTabs.tsx, src/helpers/getProfileIdentity.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/store/useGlobalStore.ts, src/store/useProfileTabsStore.ts
=> fix: bugfix for profile tab

src/components/Login/LoginFarcaster.tsx, src/helpers/enqueueMessage.tsx, src/modals/FireflySessionConfirmModal.tsx
Closes [FW-950](https://mask.atlassian.net/browse/FW-950)
Closes [FW-951](https://mask.atlassian.net/browse/FW-951)
[FW-950]: https://mask.atlassian.net/browse/FW-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-951]: https://mask.atlassian.net/browse/FW-951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: sign in with ff

src/components/Article/SingleArticle.tsx
=> fix: bugfix for article in safari

src/app/(normal)/layout.tsx, src/components/Article/SingleArticle.tsx, src/components/Channel/ChannelList.tsx, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/formatLensPost.ts, src/providers/firefly/SocialMedia.ts
=> fix: bugfix for list

src/components/Login/LoginFarcaster.tsx, src/components/Login/ProfileSettings.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/providers/firefly/Session.ts, src/providers/lens/createSessionForProfileId.ts, src/providers/types/Firefly.ts, src/providers/warpcast/createSessionByRelayService.ts
Closes [FW-943](https://mask.atlassian.net/browse/FW-943)
[FW-943]: https://mask.atlassian.net/browse/FW-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: sync ff

src/helpers/getProfilesAll.ts, src/modals/LogoutModal.tsx
=> refactor: logout

src/components/Actions/Mirrors.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
Closes [FW-930](https://mask.atlassian.net/browse/FW-930)
[FW-930]: https://mask.atlassian.net/browse/FW-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: texture

src/app/(normal)/@modal/(.)post/[id]/photos/[index]/page.tsx, src/app/globals.css, src/components/Actions/Bookmark.tsx, src/components/Actions/Mirrors.tsx, src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Modal.tsx, src/components/Posts/ChannelAnchor.tsx, src/components/Profile/WalletInfo.tsx, src/components/Search/SearchRecommendation.tsx, src/helpers/getPostsSelector.ts, src/helpers/mergeThreadPostsForLens.ts
=> fix: bugfix for mirror

src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
=> revert: channel detail change

src/app/(normal)/bookmark/ArticleBookmarkList.tsx, src/app/(normal)/bookmark/BookmarkList.tsx, src/app/(normal)/bookmark/page.tsx, src/components/Actions/ArticleMore.tsx, src/components/Actions/BlockUserButton.tsx, src/components/Actions/Bookmark.tsx, src/components/Actions/BookmarkButton.tsx, src/components/Actions/MenuButton.tsx, src/components/Actions/More.tsx, src/components/Actions/MuteChannelButton.tsx, src/components/Actions/ReportUserButton.tsx, src/components/Article/ArticleHeader.tsx, src/components/Profile/ProfileMoreAction.tsx, src/components/SourceTabs.tsx, src/constants/index.ts, src/decorators/SetQueryDataForBookmarkPost.ts, src/helpers/formatArticleFromFirefly.ts, src/helpers/patchPostQueryData.ts, src/hooks/useToggleArticleBookmark.ts, src/hooks/useToggleBlock.ts, src/hooks/useToggleBookmark.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/modals/ConfirmModal.tsx, src/providers/firefly/Article.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/Article.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts
https://mask.atlassian.net/browse/fw-923
https://mask.atlassian.net/browse/fw-956
https://mask.atlassian.net/browse/fw-957
https://mask.atlassian.net/browse/fw-957
https://mask.atlassian.net/browse/fw-927
https://mask.atlassian.net/browse/fw-928
=> feat: fw-923 article bookmark

src/providers/firefly/Session.ts, src/providers/firefly/SessionHolder.ts, src/services/restoreFireflySession.ts, src/services/syncSessionFromFirefly.ts, src/store/useProfileStore.ts
Closes [FW-917](https://mask.atlassian.net/browse/FW-917)
[FW-917]: https://mask.atlassian.net/browse/FW-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: restoration

src/hooks/useToggleArticleBookmark.ts, src/hooks/useToggleBookmark.ts, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> fix: typing

src/app/api/twitter/userTimeline/[userId]/route.ts, src/modals/LogoutModal.tsx, src/store/useProfileTabsStore.ts
=> fix: clear tabs state when logout

src/modals/ConfirmModal.tsx, src/modals/FireflySessionConfirmModal.tsx
Closes [FW-933](https://mask.atlassian.net/browse/FW-933)
[FW-933]: https://mask.atlassian.net/browse/FW-933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: firefly modal ui

src/app/api/twitter/homeTimeline/route.ts, src/app/api/twitter/userTimeline/[userId]/liked/route.ts, src/app/api/twitter/userTimeline/[userId]/replies/route.tsx, src/app/api/twitter/userTimeline/[userId]/route.ts
=> fix: invalid page param for tweet api

src/components/Actions/ArticleMore.tsx, src/components/Actions/BlockUserButton.tsx, src/components/Actions/BookmarkButton.tsx, src/components/Actions/More.tsx, src/components/Actions/MuteChannelButton.tsx, src/components/Actions/ReportUserButton.tsx, src/components/Channel/ChannelMoreAction.tsx, src/components/Profile/ProfileMoreAction.tsx
=> fix: adjust menu button font size

src/app/(normal)/pages/Profile.tsx, src/app/(normal)/profile/pages/DetailPage.tsx, src/helpers/formatFarcasterPostFromFirefly.ts, src/providers/types/Firefly.ts
=> feat: farcaster quote

src/app/(normal)/profile/pages/DetailPage.tsx, src/components/Article/ArticleHeader.tsx, src/constants/index.ts, src/decorators/SetQueryDataForBookmarkPost.ts, src/hooks/useToggleArticleBookmark.ts
=> fix: temporarily hide bookmark for article

src/components/Profile/ProfileTabs.tsx, src/helpers/resolveSourceName.ts
=> chore: hidden single profile tab

src/components/Profile/Info.tsx, src/providers/lens/SocialMedia.ts, src/services/crossPostThread.ts
=> feat: lens following list

package.json, pnpm-lock.yaml
=> chore: upgrade next

src/components/Actions/Like.tsx, src/modals/ConfirmModal.tsx, src/providers/firefly/SocialMedia.ts
https://mask.atlassian.net/browse/fw-972
=> fix(Firefly): request with jwt token

src/app/(normal)/pages/Channel.tsx, src/components/Channel/ChannelCard.tsx, src/components/Channel/Info.tsx, src/components/Channel/Title.tsx, src/components/Profile/Info.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> chore: channel ui

src/components/Login/LoginFarcaster.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> fix: login farcaster error msg

src/components/Actions/index.tsx, src/components/Article/ArticleHeader.tsx, src/constants/index.ts
=> fix(Twitter): hide bookmark for now

src/app/(normal)/article/[id]/pages/DetailPage.tsx, src/components/Article/ArticleHeader.tsx, src/components/Markup/ArticleMarkup.tsx
=> fix: article ui

src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/modals/FireflySessionConfirmModal.tsx, src/modals/LogoutModal.tsx
Closes [FW-933](https://mask.atlassian.net/browse/FW-933)
Closes [FW-968](https://mask.atlassian.net/browse/FW-968)
[FW-933]: https://mask.atlassian.net/browse/FW-933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-968]: https://mask.atlassian.net/browse/FW-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: confirm btn texture

src/components/Channel/ChannelCard.tsx, src/components/Channel/ChannelList.tsx, src/components/Channel/Info.tsx, src/components/ListInPage.tsx, src/components/SourceTabs.tsx
=> fix: bugfix for channel ui

src/components/Actions/More.tsx, src/components/Channel/ChannelMoreAction.tsx, src/components/Login/LoginFarcaster.tsx, src/components/Profile/WalletInfo.tsx
=> fix: ens card

src/components/Profile/WalletInfo.tsx
Author by @nuanyang233 
Closes FW-0000
=> fix: ens card ui

src/components/Login/ProfileSettings.tsx, src/components/ProfileName.tsx, src/components/SideBar/Menu.tsx, src/components/SourceTabs.tsx, src/constants/enum.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> refactor: texture

src/app/(normal)/bookmarks/BookmarkList.tsx
https://mask.atlassian.net/browse/FW-914
=> fix: don't request bookmarks if no session exists

src/helpers/formatTwitterPostFromFirefly.ts, src/helpers/mergeThreadPosts.ts, src/helpers/mergeThreadPostsForTweet.ts
=> fix: filter thread tweet

src/components/Posts/SinglePost.tsx
=> fix: hidden show more in twitter timeline

src/app/(normal)/bookmarks/BookmarkList.tsx, src/modals/ConfirmModal.tsx
https://mask.atlassian.net/browse/fw-985
https://mask.atlassian.net/browse/fw-988
=> fix: fw-985 no need to check lens session

src/components/Article/SingleArticle.tsx, src/components/Posts/ImageAsset.tsx, src/components/Posts/PostBody.tsx, src/constants/bowser.ts
=> fix: article border

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Profile/Info.tsx
=> fix: fix underline broken

src/components/Article/SingleArticle.tsx
=> fix: article shadow for mobile devices

src/constants/regexp.ts
=> fix: channel regex

src/decorators/SetQueryDataForBlockUser.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/patchPostQueryData.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/SocialMedia.ts
https://mask.atlassian.net/browse/fw-990
=> fix: article shadow for mobile devices (#1099)

src/app/(normal)/profile/[id]/page.tsx, src/app/(normal)/profile/pages/DetailPage.tsx, src/components/Profile/Info.tsx, src/constants/regexp.ts, src/helpers/getLargeTwitterAvatar.ts, src/helpers/getLargetTwitterAvatar.ts
=> fix: bugfix for tabs and avatar

src/components/Compose/Media.tsx
=> refactor: disable video for fc

src/helpers/formatFarcasterPostFromFirefly.ts, src/providers/firefly/Article.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
Closes [FW-999](https://mask.atlassian.net/browse/FW-999)
[FW-999]: https://mask.atlassian.net/browse/FW-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: cast author is undefined

src/helpers/createSiteMetadata.ts
=> fix: og card type

src/constants/index.ts, src/helpers/getCurrentPostImageLimits.ts, src/helpers/getCurrentPostLimits.ts, src/services/postToFarcaster.ts
Closes [FW-983](https://mask.atlassian.net/browse/FW-983)
Closes https://github.com/DimensionDev/firefly.mask.social/issues/1088
[FW-983]: https://mask.atlassian.net/browse/FW-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: image size per post

src/components/Posts/ActionType.tsx, src/components/Posts/PostHeader.tsx, src/components/Posts/SinglePost.tsx, src/components/Posts/ThreadBody.tsx, src/components/Profile/Info.tsx, src/components/Profile/Title.tsx
=> feat: FW-1006 FW-979

src/components/Channel/ChannelCard.tsx, src/components/Channel/Info.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> feat: channel created date

src/components/ProfileName.tsx
=> feat: add truncate to profile name

src/helpers/formatTwitterPostFromFirefly.ts
=> fix: fix X attachments

src/components/Article/SingleArticle.tsx
=> chore: article ui

package.json, pnpm-lock.yaml, src/helpers/chars.ts, src/services/crossPost.ts, src/services/resolveLengthCalculator.ts
=> fix: counting chars

src/components/Actions/Bookmark.tsx, src/components/Actions/BookmarkButton.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
https://mask.atlassian.net/browse/fw-1022
=> fix: fw-1022 update bookmark text

src/providers/firefly/SocialMedia.ts
=> fix: add `sourceFid` to follow list api for fix the follow status

src/components/Actions/BlockUserButton.tsx, src/components/Actions/UnmuteButton.tsx, src/components/Posts/PostBody.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/Info.tsx, src/decorators/SetQueryDataForBlockUser.ts, src/decorators/SetQueryDataForBookmarkPost.ts, src/hooks/useIsMuted.ts, src/hooks/useToggleBlock.ts, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/fw-889
https://mask.atlassian.net/browse/fw-891
https://mask.atlassian.net/browse/fw-910
https://mask.atlassian.net/browse/fw-952
=> fix: farcaster blocking

pnpm-lock.yaml, src/components/Profile/ProfileContentTabs.tsx
https://mask.atlassian.net/browse/fw-1023
=> refactor: fw-1023 profile tab to router link

src/components/Profile/ProfileContentTabs.tsx
=> fix: faster tab switching

src/providers/firefly/SocialMedia.ts
=> chore: following timeline api

src/components/FollowInList.tsx, src/components/Profile/ProfileContentTabs.tsx, src/constants/index.ts
=> fix: /lens profile link

src/components/Profile/ProfileContentTabs.tsx
=> fix: profile content tabs

src/constants/index.ts
=> chore: channel tab

src/components/SourceTabs.tsx
=> fix: remove replace state

package.json, src/components/SourceTabs.tsx, src/constants/index.ts
=> [Release] Hotfix 5.2.0 => 5.2.1 (patch)

package.json, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/modals/ComposeModal.tsx
=> [Release] Hotfix 5.2.1 => 5.2.2 (patch)

package.json, src/constants/env.ts, src/modals/ComposeModal.tsx
=> [Release] Hotfix 5.2.2 => 5.2.3 (patch)

src/providers/types/SocialMedia.ts
=> refactor: comments

src/components/Markup/BioMarkup.tsx, src/components/Markup/Markup.tsx, src/components/Markup/NakedMarkup.tsx, src/components/Posts/PostBody.tsx, src/constants/regexp.ts
=> fix: farcaster quote and channel highlight

src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Markup/MarkupLink/index.tsx, src/components/Posts/PostBody.tsx
=> fix: duplicate og

src/components/Actions/More.tsx, src/components/Engagement/QuoteList.tsx, src/components/Notification/NotificationItem.tsx, src/components/Posts/CollapsedContent.tsx, src/components/Posts/PostBody.tsx, src/components/Profile/Info.tsx, src/components/Profile/ProfileContent.tsx, src/components/ProfileInList.tsx, src/constants/index.ts, src/decorators/SetQueryDataForBlockUser.ts, src/decorators/SetQueryDataForBookmarkPost.ts, src/decorators/SetQueryDataForFollowUser.ts, src/decorators/SetQueryDataForLikePost.ts, src/decorators/SetQueryDataForMirrorPost.ts, src/helpers/isMyProfile.ts, src/helpers/patchNotificationQueryData.ts, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/fw-1033
https://mask.atlassian.net/browse/fw-1035
=> fix: patch query data on notification and so on

src/components/Markup/MarkupLink/index.tsx, src/constants/regexp.ts
=> fix: exclude uppercase channel name

src/components/Markup/MarkupLink/index.tsx
=> fix: invalid regex test

src/components/CircleCheckboxIcon.tsx, src/components/Compose/ChannelSearchPanel.tsx, src/components/Login/ProfileInList.tsx, src/components/Search/SearchFilter.tsx
=> refactor: CircleCheckboxIcon

src/app/(normal)/@modal/(.)post/[id]/photos/[index]/page.tsx, src/app/(normal)/pages/Profile.tsx, src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/app/(normal)/profile/pages/DetailPage.tsx, src/components/Article/DiscoverArticleList.tsx, src/components/Article/FollowingArticleList.tsx, src/components/Channel/SuggestedChannels.tsx, src/components/Comments/index.tsx, src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/components/Posts/DiscoverPostList.tsx, src/components/Posts/PostBody.tsx, src/components/Profile/ArticleList.tsx, src/components/Profile/CollectedList.tsx, src/constants/index.ts, src/helpers/formatLensPost.ts, src/helpers/getPostsSelector.ts, src/helpers/q.ts, src/modals/LoginModal.tsx, src/modals/PreviewImagesModal.tsx, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/store/useComposeStore.ts, src/store/useImpressionsStore.ts, src/store/useProfileStore.ts
=> refactor: EMPTY_LIST

src/components/Article/ArticleHeader.tsx, src/components/SourceTabs.tsx, src/constants/index.ts, src/decorators/SetQueryDataForBookmarkPost.ts, src/hooks/useToggleArticleBookmark.ts
https://mask.atlassian.net/browse/FW-967
=> fix: enable article bookmark on production

src/app/(normal)/bookmarks/ArticleBookmarkList.tsx, src/decorators/SetQueryDataForBookmarkPost.ts
=> fixup! fix: enable article bookmark on production (#1158)

src/components/Channel/ChannelCard.tsx
https://mask.atlassian.net/browse/FW-1059
Closes FW-0000
=> fix: FW-1059 Channel hover card ui

public/.well-known/apple-app-site-association
=> fix: universal link

src/components/Compose/ChannelSearchPanel.tsx, src/components/Search/SearchInput.tsx
https://mask.atlassian.net/browse/FW-1061
Closes FW-0000
=> fix: FW-1061 show follower counts

src/components/Markup/MarkupLink/index.tsx, src/components/Profile/ProfileCard.tsx, src/components/Profile/ProfileTippy.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> feat: profile card

src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Posts/ChannelAnchor.tsx, src/components/Profile/ProfileCard.tsx, src/components/Profile/ProfileTippy.tsx
=> fix: tippy duration

src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/locales/zh-Hans/messages.po
=> fix: mention popup error

src/components/Actions/Collect.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> refactor: act locale

src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/FW-1078
Closes FW-0000
=> fix: FW-1078 mention popup hidden when scrolling

src/app/(normal)/bookmarks/ArticleBookmarkList.tsx, src/app/(normal)/bookmarks/BookmarkList.tsx, src/app/(normal)/notifications/page.tsx, src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/app/(normal)/search/page.tsx, src/components/Article/DiscoverArticleList.tsx, src/components/Article/FollowingArticleList.tsx, src/components/Channel/ChannelList.tsx, src/components/Channel/PostList.tsx, src/components/Comments/index.tsx, src/components/Engagement/LikeList.tsx, src/components/Engagement/QuoteList.tsx, src/components/Engagement/RepostList.tsx, src/components/Posts/DiscoverPostList.tsx, src/components/Posts/FollowingPostList.tsx, src/components/Profile/ArticleList.tsx, src/components/Profile/ChannelList.tsx, src/components/Profile/CollectedList.tsx, src/components/Profile/FeedList.tsx, src/components/Profile/LikedFeedList.tsx, src/components/Profile/MediaList.tsx, src/components/Profile/RepliesList.tsx, src/constants/enum.ts, src/helpers/getPostsSelector.ts, src/locales/zh-Hans/messages.po
=> refactor: list keys && EMPTY_LIST

src/providers/base/SessionHolder.ts, src/providers/types/Firefly.ts, src/services/bindSessionToFirefly.ts, src/services/restoreFireflySession.ts, src/services/syncSessionFromFirefly.ts
=> feat: bind sessions to firefly

src/components/Posts/ContentTranslator.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/services/translate.ts
=> refactor:  translate post

src/locales/zh-Hans/messages.po, src/providers/base/SessionHolder.ts
=> refactor: add subscription

src/components/Actions/Mirrors.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
=> fix: lens mirror

src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Posts/SinglePost.tsx, src/constants/regexp.ts, tests/constants/regexp.ts
=> fix: bugfix for channel anchor

src/components/Poll/PollButton.tsx, src/components/Poll/PollCreatorCard.tsx, src/helpers/createPoll.ts, src/store/useComposeStore.ts
=> refactor: poll namnig

src/components/Poll/PollCreatorCard.tsx, src/components/Poll/ValidInDaysSelector.tsx, src/constants/index.ts, src/helpers/createPoll.ts
=> refactor: poll helpers

src/components/Posts/ContentTranslator.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po
https://mask.atlassian.net/browse/FW-1085
Closes FW-0000
=> fix: FW-1085 replace translate loading status

src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Markup/MarkupLink/index.tsx, src/constants/regexp.ts, src/store/useChannelStore.ts, tests/constants/regexp.ts
=> fix: channel match

src/components/Posts/PostHeader.tsx, src/components/Profile/ProfileTippy.tsx, src/locales/zh-Hans/messages.po
=> feat: profile card for avatar

src/app/(settings)/components/AccountCard.tsx, src/components/Actions/UnmuteButton.tsx, src/components/ClickableButton.tsx, src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/PostByItem.tsx, src/components/Frame/Button.tsx, src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginLens.tsx, src/components/Login/ProfileSettings.tsx, src/components/Profile/FollowButton.tsx, src/modals/FireflySessionConfirmModal.tsx
=> refactor: button disabled

src/components/Markup/MarkupLink/ChannelTag.tsx, src/store/useChannelStore.ts
=> fix: channel store

cspell.json, lingui.config.js, src/helpers/resolveRainbowKitLocale.ts, src/i18n/index.ts, src/locales/zh-Hant/messages.po, src/types/index.ts
=> feat: support zh-Hant

src/components/Poll/PollCard.tsx, src/components/Posts/ContentTranslator.tsx, src/helpers/getBrowserLanguage.ts
=> refactor: replace confusing code

src/components/Channel/ChannelCard.tsx, src/components/ProfileInList.tsx, src/constants/index.ts, src/helpers/formatFarcasterChannelFromFirefly.ts, src/providers/types/Firefly.ts
Closes FW-1100 FW-1095 FW-1096
=> fix: channel card

src/app/(settings)/settings/general/page.tsx, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: locale

src/app/(settings)/components/AccountCard.tsx
=> fix: accounts ui

.github/workflows/lingui.yml, public/site.webmanifest, src/constants/index.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: subtitle

src/components/ClickableButton.tsx, src/components/Poll/PollCard.tsx, src/constants/poll.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: hide vote

src/decorators/SetQueryDataForBookmarkPost.ts
=> fix: bugfix for article bookmark

src/components/Channel/SuggestedChannels.tsx, src/components/Search/SearchBar.tsx, src/components/Search/SearchInput.tsx
=> refactor: sidebar ui

src/components/ClickableButton.tsx
=> refactor: clickable button

src/app/(normal)/layout.tsx, src/app/(settings)/settings/communities/page.tsx, src/components/LinkCloud.tsx, src/configs/sentryClient.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1019
Closes FW-0000
=> feat: link cloud

src/components/Posts/ThreadBody.tsx
=> fix: thread link

src/decorators/SetQueryDataForBookmarkPost.ts
=> fix: bugfix for following article list bookmark

src/app/(normal)/layout.tsx, src/components/LinkCloud.tsx, src/configs/sentryClient.ts, src/constants/env.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: links cloud

src/app/(normal)/post/[id]/pages/DetailPage.tsx
=> fix: filter thread post

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/app/(normal)/nft/[address]/page.tsx, src/components/CollectionDetail/NFTList.tsx, src/components/CollectionDetail/TopCollectors.tsx, src/components/NFTDetail/NFTInfo.tsx, src/components/Profile/POAPList.tsx, src/providers/simplehash/WalletProfile.ts, src/providers/types/WalletProfile.ts
=> refactor: NFT & POAPs

src/components/LinkCloud.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: links

src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/mergeThreadPostsForFarcaster.ts
=> fix: improve farcaster thread

src/components/Posts/ContentTranslator.tsx, src/helpers/getLangNameFromLocal.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/getContentLanguage.ts
https://mask.atlassian.net/browse/FW-1086
The detectedLanguage returned by the translation interface is inaccurate, so replace it
Closes FW-0000
=> fix: FW-1086 Discard inaccurate detection

src/app/(settings)/settings/more/page.tsx, src/components/LinkCloud.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1112
Closes FW-0000
=> feat: add links

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/app/(normal)/nft/[address]/page.tsx, src/components/LinkCloud.tsx, src/components/NFTDetail/CopyButton.tsx, src/components/NFTDetail/NFTInfo.tsx, src/components/NFTDetail/NFTOverflow.tsx, src/components/Posts/ContentTranslator.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, tailwind.config.cjs
=> feat: adjust nft detail ui

src/components/Compose/ChannelSearchPanel.tsx, src/components/NFTDetail/NFTOverflow.tsx, src/modals/ComposeModal.tsx, src/store/useComposeStore.ts
=> fix: update channel

src/components/Poll/PollCard.tsx, src/constants/index.ts, src/helpers/getResourceType.ts, src/providers/farcaster/Poll.ts, src/providers/lens/Poll.ts, src/providers/twitter/Poll.ts, src/providers/types/Poll.ts, src/providers/types/SocialMedia.ts, src/services/createFarcasterPoll.ts, src/services/postToFarcaster.ts, src/services/postToTwitter.ts
=> feat: create poll

src/components/Actions/ArticleBookmarkButton.tsx, src/components/Actions/ArticleMore.tsx, src/components/Actions/More.tsx, src/components/Actions/index.tsx, src/components/LinkCloud.tsx, src/components/Notification/NotificationItem.tsx, src/components/Posts/PostHeader.tsx
https://mask.atlassian.net/browse/fw-923
=> fix: fw-923 move bookmark button to the more menu

.github/workflows/eslint.yml, .github/workflows/lingui.yml, .github/workflows/prettier.yml
=> refactor: dispatch from actions page

src/components/Actions/BlockUserButton.tsx, src/components/Actions/Like.tsx, src/components/Actions/Mirrors.tsx, src/components/Actions/More.tsx, src/components/Actions/MuteChannelButton.tsx, src/components/Actions/ReportUserButton.tsx, src/components/Channel/ChannelMoreAction.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/ProfileMoreAction.tsx, src/decorators/SetQueryDataForBlockUser.ts, src/decorators/SetQueryDataForMirrorPost.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal.tsx, src/store/useBlockedUsersStore.ts
https://mask.atlassian.net/browse/FW-783
https://mask.atlassian.net/browse/FW-1076
=> fix: remove loading of pending status for optimistic update

src/components/Profile/NFTCollectionList.tsx, src/helpers/resolveSimpleHashChain.ts, src/providers/twitter/ShortLink.ts, src/providers/types/ShortLink.ts
=> feat: impl twitter short link resolver

src/components/LinkCloud.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: optimize ui

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/assets/report-spam.svg, src/components/NFTDetail/NFTInfo.tsx, src/components/NFTDetail/ReportSpamButton.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/firefly/SocialMedia.ts
=> feat: add report spam nft

src/components/LinkCloud.tsx, src/components/NFTDetail/NFTInfo.tsx, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: prettier

src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/FW-1123
closes https://github.com/DimensionDev/firefly.mask.social/issues/1258
=> fix: post_content from firefly's bookmark api could be undefined

src/components/Compose/ComposeSend.tsx
Closes [FW-1044](https://mask.atlassian.net/browse/FW-1044)
[FW-1044]: https://mask.atlassian.net/browse/FW-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: send multiple times

src/components/Compose/ReplyRestriction.tsx, src/helpers/isValidRestrictionType.ts, src/store/useComposeStore.ts
Closes [FW-1007](https://mask.atlassian.net/browse/FW-1007)
[FW-1007]: https://mask.atlassian.net/browse/FW-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: reset restriction type

src/helpers/formatTwitterPost.ts, src/providers/firefly/Article.ts, src/providers/firefly/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> fix: type errors

src/components/CollectionDetail/NFTList.tsx, src/components/CollectionDetail/NFTListByCollectionId.tsx, src/components/GridListInPage.tsx, src/components/NFTDetail/DownloadImageButton.tsx, src/components/NFTDetail/NFTInfo.tsx, src/components/Profile/POAPList.tsx, src/components/TableListInPage.tsx
Closes FW-1126 FW-1135 FW-1125 FW-1121
=> fix: fix some nft and pop issues

csp.js
=> fix: update cors policy

src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/helpers/getMentionOriginalText.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1077
Closes FW-0000
=> fix: FW-1077 fix mention tag matching rule

csp.js, src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/helpers/getMentionOriginalText.ts
=> fix: cspell erorrs

src/components/Poll/PollCard.tsx
https://mask.atlassian.net/browse/FW-1137
Closes FW-0000
=> feat: update poll ui

src/app/(normal)/pages/Home.tsx, src/assets/line-arrow-up.svg, src/components/Comments/CommentsFooter.tsx, src/components/Comments/index.tsx, src/components/LensHideComments.tsx, src/components/ListInPage.tsx, src/components/ShowMoreComments.tsx, src/components/VirtualList/VirtualListFooter.tsx, src/components/VirtualList/VirtualListFooterBottomText.tsx, src/helpers/types.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/lens/SocialMedia.ts
=> feat: lens hidden comments

src/components/CollectionDetail/NFTListByCollectionId.tsx, src/components/NFTDetail/ChainIcon.tsx, src/components/Profile/NFTCollectionList.tsx, src/components/Profile/POAPList.tsx, src/helpers/resolveSimpleHashChain.ts, src/helpers/resolveSimpleHashChainId.ts
Closes FW-1125 FW-1133 FW-1139 FW-1140
=> fix: fix nft issues

src/components/Actions/ReportUserButton.tsx, src/components/Posts/CollapsedContent.tsx, src/components/Profile/RepliesList.tsx, src/helpers/formatFarcasterPostFromFirefly.ts, src/hooks/useDeletePost.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/types/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1084
https://mask.atlassian.net/browse/fw-1146
=> fix: fw-1084 delete post in thread

src/components/Actions/ArticleBookmarkButton.tsx, src/components/Profile/ArticleList.tsx, src/decorators/SetQueryDataForBookmarkPost.ts, src/hooks/useToggleArticleBookmark.ts
https://mask.atlassian.net/browse/fw-1143
=> fix: fw-1143 bookmark article

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/PostBy.tsx, src/constants/index.ts
https://mask.atlassian.net/browse/FW-1142
https://mask.atlassian.net/browse/FW-1141
Closes FW-0000
=> feat: dynamic show share to

src/components/CollectionDetail/NFTListByCollectionId.tsx
=> fix: fix nft list query key

src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> chore: update submodule maskbook

src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/store/useComposeStore.ts
=> fix: fix unselected channels when adding posts

src/components/Compose/ComposeSend.tsx
=> fix: fix cannot add thread post when only image

src/hooks/useSearchChannel.ts
https://mask.atlassian.net/browse/FW-1138
Closes FW-0000
=> fix: adjust channel search rule

src/components/Compose/ComposeAction.tsx, src/store/useComposeStore.ts
=> refactor: poll available sources

src/app/(normal)/layout.tsx, src/components/Actions/Mirrors.tsx, src/components/Actions/MuteChannelButton.tsx, src/components/Channel/ChannelTippy.tsx, src/components/ChannelInList.tsx, src/components/Compose/ComposeAction.tsx, src/components/Posts/ChannelAnchor.tsx, src/components/Search/SearchFilter.tsx, src/helpers/formatFarcasterPostFromFirefly.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes FW-659 FW-1038  FW-1102 FW-1130 FW-1151 FW-1152 FW-1155
=> fix: bugfix for farcaster quote

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/components/ShowMoreComments.tsx, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: fix arrow direction

next-auth.d.ts, src/app/api/auth/[...nextauth]/options.ts, src/app/api/twitter/login/route.ts, src/components/Login/LoginFarcaster.tsx, src/helpers/createTwitterClientV2.ts, src/helpers/createTwitterSessionPayload.ts, src/helpers/getTwitterErrorMessage.ts, src/helpers/isSameSession.ts, src/helpers/resolveSessionHolder.ts, src/helpers/restoreProfile.ts, src/helpers/withRequestErrorHandler.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/FireflySessionConfirmModal.tsx, src/providers/base/SessionFactory.ts, src/providers/farcaster/SessionHolder.ts, src/providers/twitter/Session.ts, src/providers/twitter/SessionHolder.ts, src/providers/twitter/SocialMedia.ts, src/services/syncSessionFromFirefly.ts, src/store/useProfileStore.ts
=> feat: tw session

src/components/Actions/ReportUserButton.tsx, src/helpers/deletePostFromQueryData.ts, src/helpers/patchPostQueryData.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/farcaster/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1122
https://mask.atlassian.net/browse/FW-869
https://mask.atlassian.net/browse/FW-1146
=> fix: fw-1122 patch query data in searching posts

src/components/SideBar/Menu.tsx
https://mask.atlassian.net/browse/FW-1160
Closes FW-0000
=> fix: adjust menu order

src/app/(developers)/developers/frame/page.tsx
=> fix: section ui

src/store/useComposeStore.ts
Closes [FW-1148](https://mask.atlassian.net/browse/FW-1148)
[FW-1148]: https://mask.atlassian.net/browse/FW-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: restriction type of new added thread post

src/modals/FireflySessionConfirmModal.tsx
Closes [FW-1156](https://mask.atlassian.net/browse/FW-1156)
[FW-1156]: https://mask.atlassian.net/browse/FW-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: skip if not valid profiles found

src/modals/FireflySessionConfirmModal.tsx, src/providers/twitter/SocialMedia.ts
Closes [FW-1150](https://mask.atlassian.net/browse/FW-1150)
[FW-1150]: https://mask.atlassian.net/browse/FW-1150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: sync x profiles

src/components/ShowMoreComments.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/FireflySessionConfirmModal.tsx
=> fix: add bottom space and adjust max avatar to 5

src/components/Posts/PostHeader.tsx, src/modals/FireflySessionConfirmModal.tsx
=> fix: add profile tippy area

src/components/Channel/ChannelCard.tsx, src/components/Posts/PostHeader.tsx, src/components/Profile/ProfileCard.tsx
=> fix: profile card loading ui

src/providers/firefly/SocialMedia.ts
=> fix: pass source fid to search post api

src/components/Compose/ChannelSearchPanel.tsx, src/components/Compose/ComposeAction.tsx
https://mask.atlassian.net/browse/FW-1165
Closes FW-0000
=> fix: FW-1165 close menu after selected

src/providers/twitter/SocialMedia.ts
=> fix: handle x mute list empty error

public/js/browser-detector.js
=> fix: ipad safari detect

src/components/CollectionDetail/TopCollectors.tsx, src/helpers/formatPercentage.ts, src/helpers/getStampAvatarByProfileId.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: fix top collectors avatar and data

src/components/Profile/NFTCollectionList.tsx
=> feat: flat NFT collections less than or equal to 3

src/providers/twitter/SessionHolder.ts, src/services/uploadToTwitter.ts
Closes [FW-1174](https://mask.atlassian.net/browse/FW-1174)
Closes #1311
[FW-1174]: https://mask.atlassian.net/browse/FW-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: tw upload media

src/app/(normal)/nft/[address]/page.tsx, src/components/Tabs/index.tsx
=> feat: add secondary tab style

src/components/Profile/POAPList.tsx, src/helpers/resolveProfileUrl.ts
=> feat: click to go to the profile page of this address in owner on NFT item

src/components/CollectionDetail/TopCollectors.tsx
=> fix: top collector owned tooltip position

src/components/NFTDetail/ReportSpamButton.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: adjust confirm report spam nft dialog text

src/components/Compose/ComposeContent.tsx, src/components/Frame/Card.tsx, src/components/Frame/index.tsx
=> refactor: getNextFrame

src/app/(normal)/nft/[address]/page.tsx, src/components/CollectionDetail/CollectionTabs.tsx
=> fix: fix nft collection page loading when switch tab

src/components/CollectionDetail/TopCollectors.tsx, src/components/NFTDetail/NFTInfo.tsx, src/components/TableListInPage.tsx, src/components/VirtualList/VirtualTableFooter.tsx, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: ens or address in NFT detail page

src/services/reportCrossedPost.ts
=> fix: date-fns not found

src/services/crossPost.ts, src/services/crossPostThread.ts, src/services/reportCrossedPost.ts
Closes [FW-1189](https://mask.atlassian.net/browse/FW-1189)
[FW-1189]: https://mask.atlassian.net/browse/FW-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: report crossed post

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Comments/index.tsx, src/components/LensHideComments.tsx
=> fix: exclude thread post in lens hidden comments

src/components/Compose/ComposeAction.tsx, src/components/Compose/PostBy.tsx, src/components/Compose/PostByItem.tsx, src/components/Poll/PollButton.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/store/useComposeStore.ts
https://mask.atlassian.net/browse/FW-1182
Closes FW-0000
=> fix: FW-1182 keep poll button alive

src/components/Compose/ComposeAction.tsx, src/components/Compose/PostBy.tsx, src/components/Compose/PostByItem.tsx, src/components/Poll/PollButton.tsx, src/helpers/deletePostFromQueryData.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/fw-1191
https://mask.atlassian.net/browse/fw-1192
=> fix: fw-1191 delete lens posts

src/components/Posts/PostBody.tsx, src/components/Posts/SinglePost.tsx, src/hooks/useIsMuted.ts
=> fix: no need to check block relation from post body

src/components/NotLoginFallback.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: login fallback for bookmark article

src/services/reportCrossedPost.ts
Closes [FW-1198](https://mask.atlassian.net/browse/FW-1198)
[FW-1198]: https://mask.atlassian.net/browse/FW-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: api url

src/components/Poll/PollButton.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: modify poll unavailable prompt

src/components/Login/LoginFarcaster.tsx, src/modals/LoginModal.tsx
Closes [FW-1194](https://mask.atlassian.net/browse/FW-1194)
[FW-1194]: https://mask.atlassian.net/browse/FW-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: login fc modal

src/hooks/useToggleArticleBookmark.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-1199
=> fix: fw-1199 typo

package.json
=> [Release] New release 5.3.0 (minor)

src/components/CollectionDetail/TopCollectors.tsx, src/components/GridListInPage.tsx
=> fix: fixed top collector table layout and fix grid list height with footer

src/components/Compose/DraftList.tsx, src/helpers/createPersistStorage.ts, src/store/useComposeStore.ts
=> refactor: compose draft

src/components/Compose/DraftList.tsx, src/modals/ComposeModal.tsx, src/store/useComposeDraftStore.ts, src/store/useComposeStore.ts
=> refactor: draft store

src/components/NFTDetail/ReportSpamButton.tsx, src/components/Profile/NFTCollectionList.tsx, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts, src/services/bindSessionToFirefly.ts, src/services/getAllNFTCollections.ts, src/services/reportNFT.ts
=> refactor: services

src/components/Actions/UnmuteButton.tsx, src/components/ErrorReportSnackbar.tsx, src/components/Markup/MarkupLink/Hashtag.tsx, src/components/Markup/MarkupLink/index.tsx, src/components/Profile/Info.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-1196
https://mask.atlassian.net/browse/fw-698
https://github.com/DimensionDev/firefly.mask.social/issues/1232
=> fix: fw-1196 unmute without confirmation

src/app/globals.css, src/components/Compose/ComposeContent.tsx, src/components/Compose/ComposeImage.tsx, src/components/Posts/Attachment.tsx, src/components/Posts/PostBody.tsx, src/constants/index.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, tailwind.config.cjs
=> feat: supports multiple 4 or more images on the lens

src/components/ListInPage.tsx, src/components/Profile/MediaList.tsx, src/constants/regexp.ts, tests/constants/regexp.ts
=> fix: bugfix for lens profile tab

src/components/Compose/ComposeImage.tsx, src/components/Posts/Attachment.tsx, src/hooks/useMuteMenuList.ts, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/FW-1203
Closes FW-0000
=> feat: farcaster users mute list

src/app/(normal)/channel/pages/DetailPage.tsx, src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Actions/More.tsx, src/components/Channel/Info.tsx, src/components/Posts/ChannelAnchor.tsx, src/components/Posts/SinglePost.tsx, src/hooks/useDeletePost.ts
https://mask.atlassian.net/browse/fw-1136
https://mask.atlassian.net/browse/fw-870
=> feat: fw-1136 add channel profile in post detail page

public/js/polyfills/object.hasown.js, src/components/Compose/ComposeImage.tsx, src/components/Polyfills.tsx, src/components/Posts/Attachment.tsx, src/helpers/canParseURL.ts, src/helpers/parseURL.ts, src/helpers/resolveImgurUrl.ts, src/polyfills/AbortSignal.timeout.ts, src/polyfills/Object.hasOwn.ts, src/polyfills/URL.canParse.ts, src/polyfills/index.ts, src/services/uploadToBlob.ts
https://github.com/DimensionDev/firefly.mask.social/issues/1256
Closes FW-0000
=> fix: add AbortSignal.timeout polyfills

src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, tests/constants/regexp.ts
=> chore: update test case

package.json, src/app/api/twitter/login/route.ts, src/components/SessionProvider.tsx, src/configs/sentryClient.ts, src/constants/enum.ts, src/constants/env.ts, src/constants/index.ts, src/helpers/createTwitterSessionPayload.ts, src/providers/twitter/Session.ts, src/services/reportCrossedPost.ts, src/services/syncSessionFromFirefly.ts, src/store/useProfileStore.ts
=> [Release] Hotfix 5.3.0 => 5.3.1 (patch)

package.json, pnpm-lock.yaml, src/components/Frame/index.tsx, src/components/Posts/PostBody.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/lens/SocialMedia.ts
=> feat: lens frame

package.json, src/app/api/firefly/decrypt-metrics/route.ts, src/app/api/twitter/login/route.ts, src/components/Login/LoginLens.tsx, src/helpers/createTwitterSessionPayload.ts, src/providers/twitter/Session.ts, src/providers/twitter/SessionPayload.ts, src/providers/twitter/SocialMedia.ts, src/services/syncSessionFromFirefly.ts
=> [Release] Hotfix 5.3.1 => 5.3.2 (patch)

src/components/Compose/ComposeImage.tsx, src/components/Compose/PostBy.tsx
=> fix: lens upload image issues

src/components/Channel/MutedChannels.tsx, src/hooks/useMuteMenuList.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts
https://mask.atlassian.net/browse/FW-1204
Closes FW-0000
=> feat: farcaster channel mute list

src/components/Frame/index.tsx, src/libs/frame/readers/metadata.ts, src/types/frame.ts
=> feat: parse post_url in button

src/app/api/frame/route.ts, src/components/Frame/index.tsx, src/components/NFTs/DiscoverNFTList.tsx, src/hooks/useNFTDetail.ts, src/providers/hubble/Frame.ts, src/store/useInvalidNFTStore.ts
=> fix: frame tx

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/components/NFTDetail/Attendees.tsx, src/components/NFTDetail/NFTInfo.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: add attendees

src/providers/twitter/SocialMedia.ts
=> fix: x poll schema error

src/app/api/frame/route.ts, src/app/api/twitter/bookmarks/route.ts, src/app/api/twitter/homeTimeline/route.ts, src/app/api/twitter/mute/route.ts, src/app/api/twitter/userTimeline/[userId]/liked/route.ts, src/app/api/twitter/userTimeline/[userId]/replies/route.tsx, src/app/api/twitter/userTimeline/[userId]/route.ts, src/components/Frame/Card.tsx, src/components/Frame/index.tsx, src/libs/frame/Processor.ts, src/libs/frame/readers/metadata.ts, src/schemas/index.ts, src/types/frame.ts
=> refactor: type safe

src/app/(normal)/article/[id]/pages/DetailPage.tsx, src/components/Actions/MuteArticleButton.tsx, src/components/Actions/WatchArticleButton.tsx, src/decorators/SetQueryDataForBlockWallet.ts, src/decorators/SetQueryDataForBookmarkPost.ts, src/decorators/SetQueryDataForWatchWallet.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-1229
https://mask.atlassian.net/browse/fw-1233
https://mask.atlassian.net/browse/fw-1234
https://mask.atlassian.net/browse/fw-1235
https://mask.atlassian.net/browse/fw-1236
=> fix: some article ui issues

src/components/Posts/Attachment.tsx
=> fix: attachment in quote style

src/components/NFTs/NFTFeedBody.tsx, src/components/NFTs/SingleNFTFeed.tsx
=> fix: fix collection link cannot click

src/components/NFTs/DiscoverNFTList.tsx, src/helpers/getFrameClientProtocol.ts, src/helpers/getMetaContent.ts, src/libs/frame/readers/metadata.ts, src/libs/og/readers/metadata.ts
=> refactor: getMetaContent

src/app/globals.css, src/components/Actions/ToggleMutedChannelButton.tsx, src/components/Actions/ToggleMutedProfileButton.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/ComposeThreadContent.tsx, src/components/Compose/DraftList.tsx, src/modals/ComposeModal.tsx, src/services/crossPostThread.ts
Closes FW-1250 FW-1241 FW-1220 FW-1215
=> fix: bugfix for draft state store

src/modals/ComposeModal.tsx, src/modals/LogoutModal.tsx
=> refactor: remove shadow in light mode

src/components/ComposeButton/ComposeButtonForMobile.tsx, src/decorators/SetQueryDataForBlockWallet.ts, src/decorators/SetQueryDataForWatchWallet.ts
https://mask.atlassian.net/browse/fw-1229
https://mask.atlassian.net/browse/fw-1233
https://mask.atlassian.net/browse/fw-1235
https://mask.atlassian.net/browse/fw-1263
=> fix(Article): update status
