src/app/(normal)/@modal/(.)post/[id]/photos/[index]/page.tsx, src/components/Posts/Attachment.tsx
=> fix: lens image issues

src/components/Compose/ComposeContent.tsx, src/components/Compose/Editor.tsx, src/components/Posts/PostBody.tsx, src/components/Posts/Reply.tsx, src/components/ProfileAvatar.tsx
https://mask.atlassian.net/browse/FW-1224
Closes FW-0000
=> feat: update reply compose ui

src/components/Actions/ToggleMutedProfileButton.tsx
https://mask.atlassian.net/browse/FW-1237
Closes FW-0000
=> fix: user mute status error

src/helpers/pollWithRetry.ts, src/modals/LogoutModal.tsx, src/providers/base/SessionFactory.ts, src/providers/firefly/Session.ts, src/providers/firefly/createSessionByGrantPermission.ts, src/providers/lens/SocialMedia.ts, src/providers/types/Firefly.ts
=> feat: scan the qrcode

src/app/(developers)/components/ToolkitList.tsx, src/app/(developers)/developers/settings/layout.tsx, src/app/(developers)/developers/settings/page.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/firefly/Article.ts, src/providers/firefly/SocialMedia.ts, src/services/bindSessionToFirefly.ts, src/services/commitPoll.ts, src/services/createRedPacketImage.tsx, src/services/getAllNFTCollections.ts, src/services/getContentLanguage.ts, src/services/reportCrossedPost.ts, src/services/reportNFT.ts, src/services/restoreFireflySession.ts, src/services/syncSessionFromFirefly.ts, src/services/translate.ts, src/services/uploadToArweave.ts, src/settings/index.ts, src/store/useDeveloperSettings.ts
=> feat: settings for developers

src/components/Login/LoginFirefly.tsx, src/components/Login/ProfileSettings.tsx, src/components/RelationPlatformIcon.tsx, src/constants/error.ts, src/helpers/resolveSocialMediaProvider.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/FireflySessionConfirmModal.tsx, src/providers/base/SessionFactory.ts, src/providers/base/SessionHolder.ts, src/providers/farcaster/Session.ts, src/providers/firefly/Session.ts, src/providers/firefly/createSessionByGrantPermission.ts, src/providers/lens/Session.ts, src/providers/twitter/Session.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/Firefly.ts, src/services/bindSessionToFirefly.ts, src/services/createPostTo.ts, src/services/decryptPayload.ts, src/services/restoreFireflySession.ts
=> refactor: errors

src/helpers/getPollFrameUrl.ts
=> feat: force refresh poll frame

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Actions/PostStatistics.tsx, src/components/Actions/index.tsx, src/components/Posts/ChannelAnchor.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes FW-1278 FW-1270 FW-1280 FW-1277
=> fix: issues FW-1278 FW-1270 FW-1280 FW-1277

src/components/NFTs/NFTFeedBody.tsx, src/components/NFTs/NFTFeedHeader.tsx, src/components/NFTs/VirtualListHelper.tsx, src/components/VirtualList/VirtualList.tsx
Closes FW-1232 FW-1264 FW-1268 FW-1267
=> fix: fix issues FW-1232 FW-1264 FW-1268 FW-1267

src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginFirefly.tsx, src/constants/error.ts, src/constants/index.ts, src/helpers/pollWithRetry.ts, src/providers/firefly/createSessionByGrantPermission.ts, src/providers/lens/SocialMedia.ts, src/providers/warpcast/createSessionByRelayService.ts, src/services/restoreFireflySession.ts
=> refactor: error handling

src/components/Actions/PostStatistics.tsx, src/helpers/resolveEngagementLink.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes FW-1271 FW-1272 FW-1278
=> fix: post action issues

src/components/Compose/DraftList.tsx, src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/getPollFrameUrl.ts, src/helpers/getStampAvatarByProfileId.ts
=> fix: bugfix for cross at

src/helpers/resolveMintUrl.ts
=> fix: resolve zora url

src/hooks/useStateWithSearchParams.ts
=> feat: optimistic updates `useStateWithSearchParams`

src/app/api/frame/route.ts
=> fix: http redirect

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/components/CollectionDetail/TopCollectors.tsx, src/components/NFTDetail/Attendees.tsx, src/components/NFTDetail/NFTInfo.tsx, src/components/NFTs/NFTFeedHeader.tsx, src/components/SourceTabs.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx, src/providers/simplehash/WalletProfile.ts
Closes FW-1274 FW-1275 FW-1273
=> feat: poap issues

src/components/NFTs/NFTFeedHeader.tsx
=> fix: fix FW-1267

src/components/NFTs/NFTFeedBody.tsx, src/components/Profile/NFTCollectionList.tsx
=> refactor: use small preview image for nft

src/helpers/chars.ts
=> chore: add FRAME_TAG

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/components/NFTDetail/NFTInfo.tsx, src/modals/LoginModal.tsx, src/services/muteNFT.ts
https://mask.atlassian.net/browse/fw-1283
https://mask.atlassian.net/browse/fw-1299
=> fix: fw-1299 decrease height of login modal

cspell.json, src/components/Actions/More.tsx, src/components/LinkCloud.tsx, src/components/Posts/Audio.tsx, src/constants/index.ts, src/helpers/sanitizeDStorageUrl.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes FW-702 FW-745 FW-1306 FW-1307
=> fix: bugfix for lens media

src/components/Actions/PostStatistics.tsx
=> fix: fix FW-1287

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/CountdownCircle.tsx, src/helpers/chars.ts, src/helpers/formatLensPost.ts, src/helpers/isValidPost.ts, src/hooks/useSetEditorContent.ts, src/modals/ComposeModal.tsx, src/services/postToLens.ts, src/store/useComposeStore.ts
=> feat: support hey frames

src/components/Login/LoginFarcaster.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: update locales

src/components/Login/LoginFirefly.tsx, src/providers/lens/Frame.ts
Closes [FW-1314](https://mask.atlassian.net/browse/FW-1314)
[FW-1314]: https://mask.atlassian.net/browse/FW-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: timeout error

public/.well-known/apple-app-site-association
=> chore: association

src/components/Actions/WatchWalletButton.tsx, src/components/NFTDetail/Attendees.tsx, src/components/Profile/WatchButton.tsx, src/hooks/useToggleWatchWallet.ts, src/providers/lens/Frame.ts
https://mask.atlassian.net/browse/fw-1308
https://mask.atlassian.net/browse/fw-1309
=> fix: watch button

package.json, public/.well-known/apple-app-site-association
=> [Release] Hotfix 5.3.2 => 5.3.3 (patch)

src/app/(normal)/post/[id]/[type]/page.tsx, src/app/globals.css, src/components/Channel/SuggestedChannels.tsx, src/components/ComposeButton/ComposeButtonForMobile.tsx, src/components/NotLoginFallback.tsx, src/components/Profile/ProfileContentTabs.tsx, src/components/Profile/ProfileSourceTabs.tsx, src/components/Profile/WalletTabs.tsx, src/components/SideBar/ActiveApp.tsx, src/components/SideBar/Menu.tsx, src/components/SourceTabs.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, tailwind.config.cjs
https://mask.atlassian.net/browse/FW-757
Closes FW-0000
=> feat: support active app

src/app/not-found.tsx
https://mask.atlassian.net/browse/FW-1337
Closes FW-0000
=> fix: mobile 404 page ui

src/components/Compose/ComposeSend.tsx, src/components/Login/LoginFarcaster.tsx, src/components/Oembed/index.tsx, src/components/Profile/WalletInfo.tsx, src/components/Search/SearchBar.tsx, src/components/Search/SearchRecommendation.tsx, src/helpers/formatTwitterPost.ts, src/helpers/resolveTCOLink.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx
Closes FW-608 FW-616 FW-699 FW-994 FW-1149 FW-1340
=> fix: bugfix for mobile login

src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1328
Closes FW-0000
=> fix: increase click area for side menu in mobile

src/components/Posts/PostBody.tsx, src/components/Posts/Reply.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: update reply compose ui

src/components/Actions/MuteWalletButton.tsx, src/components/Article/SingleArticle.tsx, src/components/NFTs/DiscoverNFTList.tsx, src/components/NFTs/FollowingNFTList.tsx, src/decorators/SetQueryDataForBlockWallet.ts, src/hooks/useNFTDetail.ts, src/hooks/useReportSpamNFT.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/types/NFTs.ts
https://mask.atlassian.net/browse/fw-1305
https://mask.atlassian.net/browse/fw-1312
https://mask.atlassian.net/browse/fw-1315
https://mask.atlassian.net/browse/fw-1321
https://mask.atlassian.net/browse/fw-1322
https://mask.atlassian.net/browse/FW-1317
=> fix: mute, watch, bookmark statuses of post/article 

src/helpers/getSnackbarMessageFromError.tsx, src/providers/lens/Frame.ts
https://mask.atlassian.net/browse/FW-978
Closes FW-0000
=> fix: optimize fetch failed prompt

public/js/browser-detector.js, src/app/globals.css, src/app/layout.tsx, src/components/SideBar/SideBarForMobile.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1000
Closes FW-0000
=> fix: optimize tips ui when browser unavailable

src/components/Compose/ComposeAction.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1134
Closes FW-0000
=> feat: remove mention and hashtag button

src/app/(normal)/pages/Home.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx, src/components/Tabs/index.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes FW-1325 FW-1330 FW-1338 FW-1339
=> fix: discover issues

src/app/globals.css, src/components/Posts/PostBody.tsx, src/components/Posts/Reply.tsx, src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx
=> fix: fix css global pollution

src/components/Posts/PostBody.tsx, src/components/Posts/Reply.tsx, src/components/Profile/WalletInfo.tsx, src/components/Profile/WalletMoreAction.tsx, src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx, src/decorators/SetQueryDataForBlockWallet.ts, src/helpers/formatArticleFromFirefly.ts, src/hooks/useIsWalletMuted.ts, src/hooks/useToggleWatchWallet.ts, src/providers/types/Article.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/fw-1342
https://mask.atlassian.net/browse/fw-1323
=> fix: fw-1342 watch/unwatch api is case sensitive

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/ChannelInList.tsx, src/components/Profile/WalletInfo.tsx
https://mask.atlassian.net/browse/fw-1347
https://mask.atlassian.net/browse/fw-1348
=> fix: fw-1348 highlight link in channel bio

src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/components/Markup/ArticleMarkup.tsx, src/components/Posts/ImageAsset.tsx
=> chore: ui style for at mention

src/assets/poll.svg, src/components/Compose/ComposeAction.tsx, src/helpers/chars.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/formatLensPost.ts, src/helpers/getPollFrameUrl.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/crossPost.ts, src/services/postToFarcaster.ts, src/services/postToLens.ts, src/store/useComposeStore.ts
https://mask.atlassian.net/browse/FW-1351
https://mask.atlassian.net/browse/FW-1349
https://mask.atlassian.net/browse/FW-1346
Closes FW-0000
=> feat: append author info for poll frame link

src/components/Channel/ChannelTippy.tsx, src/components/ChannelInList.tsx, src/components/ProfileInList.tsx
https://mask.atlassian.net/browse/fw-1348
https://mask.atlassian.net/browse/fw-1373
=> fix: fw-1348 adjust channel item style

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/components/Actions/Bookmark.tsx, src/components/Actions/Comment.tsx, src/components/Actions/PostStatistics.tsx, src/components/Actions/Share.tsx, src/components/Actions/index.tsx, src/components/NFTDetail/NFTInfo.tsx, src/components/NFTDetail/NFTOverflow.tsx, src/components/Notification/NotificationItem.tsx, src/components/Posts/ChannelAnchor.tsx, src/components/Posts/SinglePost.tsx, src/components/ProfileInList.tsx
Closes FW-1352 FW-1353 FW-1359 FW-1360 FW-1362 FW-1363 FW-1364 FW-1371 FW-1372 FW-1376
=> feat: post issues

src/components/Poll/PollCard.tsx, src/constants/index.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1183
Closes FW-0000
=> feat: twitter poll time left

src/components/Actions/More.tsx
https://mask.atlassian.net/browse/fw-1210
=> fix: fw-1210 false report on farcaster

src/components/Compose/ComposeContent.tsx, src/components/Frame/Card.tsx, src/components/Frame/index.tsx
https://mask.atlassian.net/browse/FW-1385
Closes FW-0000
=> fix: frame login status

src/app/(developers)/developers/settings/page.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: settings locale

src/app/(settings)/components/AccountCard.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: switching state

src/app/(normal)/search/page.tsx, src/components/ClickableArea.tsx, src/components/NoResultsFallback.tsx, src/components/Posts/Attachment.tsx, src/components/Profile/POAPList.tsx, src/components/Profile/ProfileTabs.tsx, src/helpers/formatFarcasterPostFromFirefly.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts
=> feat: add unknown source preview

src/components/Poll/PollCard.tsx, src/components/Posts/PostBody.tsx, src/components/Profile/Info.tsx, src/components/Profile/ProfileCard.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/twitter/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1219
=> fix(Twitter): fw-1219 update follow status

src/app/(whiteboard)/login/desktop/page.tsx, src/app/layout.tsx, src/assets/fullLogo.svg, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: login transition page

src/app/(whiteboard)/login/desktop/page.tsx, src/app/layout.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/ProfileMoreAction.tsx, src/hooks/useIsProfileMuted.ts
=> fix(Farcaster): add profile report button

src/components/Poll/PollCard.tsx
=> fix: update poll status text

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/components/NFTs/NFTFeedBody.tsx, src/hooks/usePoapAttendeesCount.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: poap issues

src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal.tsx
Closes [FW-1366](https://mask.atlassian.net/browse/FW-1366)
Closes [FW-1386](https://mask.atlassian.net/browse/FW-1386)
[FW-1366]: https://mask.atlassian.net/browse/FW-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-1386]: https://mask.atlassian.net/browse/FW-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ff modal title

src/helpers/createSessionStorage.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes [FW-1382](https://mask.atlassian.net/browse/FW-1382)
Closes [FW-1386](https://mask.atlassian.net/browse/FW-1386)
[FW-1382]: https://mask.atlassian.net/browse/FW-1382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-1386]: https://mask.atlassian.net/browse/FW-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: session storage

src/components/Login/ProfileSettings.tsx, src/components/NFTs/NFTFeedBody.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: revert texture

src/helpers/fetch.ts, src/services/restoreFireflySession.ts
=> fix: fc timeout

src/providers/firefly/createSessionByGrantPermission.ts
=> refactor: api url

src/app/api/frame/route.ts
Closes [FW-716](https://mask.atlassian.net/browse/FW-716)
[FW-716]: https://mask.atlassian.net/browse/FW-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: schema

src/store/useInvalidNFTStore.ts
=> feat: cache invalid nft

package.json, pnpm-lock.yaml, src/app/(whiteboard)/login/desktop/page.tsx, src/app/layout.tsx, src/assets/fullLogo.svg, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> [Release] Hotfix 5.3.3 => 5.3.4 (patch)

package.json, pnpm-lock.yaml
=> chore: upgrade next version

src/components/Profile/ProfileTabs.tsx, src/helpers/formatFarcasterPostFromFirefly.ts
=> fix: bugfix for profile tabs

src/components/Actions/More.tsx, src/components/Actions/ReportPostButton.tsx, src/components/Profile/ProfileMoreAction.tsx, src/hooks/useReportPost.ts, src/hooks/useReportProfile.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1406
=> feat: fw-1406 report post

src/components/Poll/PollCard.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: fix x poll duration error

src/app/(whiteboard)/login/desktop/page.tsx, src/components/OpenFireflyAppButton.tsx, src/components/SideBar/Menu.tsx, src/helpers/openAppIfInstalled.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1397
Closes FW-0000
=> refactor: open app with url scheme

src/components/Actions/ToggleMutedChannelButton.tsx, src/components/Actions/ToggleMutedProfileButton.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1408
Closes FW-0000
=> fix: remove ask confirm when unmute

src/app/(whiteboard)/login/desktop/page.tsx, src/components/Actions/More.tsx, src/components/Actions/ToggleMutedChannelButton.tsx, src/components/Actions/ToggleMutedProfileButton.tsx
https://mask.atlassian.net/browse/fw-1406
=> fix: fw-1406 remove report user on post

src/components/Actions/PostStatistics.tsx
=> fix: fw-1396 hidden farcaster post send from

src/components/Actions/More.tsx, src/components/Actions/ReportArticleButton.tsx, src/components/Channel/ChannelMoreAction.tsx, src/components/Profile/ProfileMoreAction.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-1413
=> fix: fw-1413 adjust text in the more menu

src/components/Actions/NFTReportSpamButton.tsx, src/hooks/useReportSpamNFT.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/lens/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1406
https://mask.atlassian.net/browse/fw-1413
=> fix: fw-1406 dont mute after report

src/app/(whiteboard)/login/desktop/page.tsx, src/components/OpenFireflyAppButton.tsx, src/components/Posts/ImageAsset.tsx, src/constants/env.ts, src/helpers/formatLensPost.ts, src/helpers/getPollFrameUrl.ts
1. add env config for app url scheme
2. append author information for lens poll
Closes FW-0000
=> feat: add env for app url scheme

src/app/(normal)/nft/[address]/[tokenId]/page.tsx, src/components/NFTDetail/NFTOverflow.tsx, src/components/NFTDetail/NFTProperties.tsx, src/helpers/getNFTPropertyDateString.ts, src/helpers/getNFTPropertyValue.ts, src/helpers/isTimestamp.ts, src/helpers/isUnixTimestamp.ts, src/helpers/openAppIfInstalled.ts
=> feat: format date in nft detail page

src/app/api/frame/route.ts, src/components/Compose/DraftList.tsx, src/modals/ComposeModal.tsx
=> fix: bugfix for draft icon

src/components/Compose/ComposeAction.tsx
=> fix: disable action when post error

src/components/Login/LoginFirefly.tsx
Closes [FW-1432](https://mask.atlassian.net/browse/FW-1432)
[FW-1432]: https://mask.atlassian.net/browse/FW-1432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: confirmation message

src/components/Modal.tsx, src/modals/ComposeModal.tsx, src/modals/ConfirmModal.tsx
=> fix: disable backdrop close

src/app/(normal)/pages/Profile.tsx, src/components/NFTs/NFTMoreAction.tsx, src/components/Profile/Info.tsx, src/components/Profile/Title.tsx, src/components/Profile/WalletInfo.tsx, src/components/Profile/WalletMoreAction.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-1429
https://mask.atlassian.net/browse/fw-1431
https://mask.atlassian.net/browse/FW-1436
=> fix: some UI updates

src/components/Login/LoginFirefly.tsx, src/components/OpenFireflyAppButton.tsx, src/components/Profile/Title.tsx, src/helpers/openAppSchemes.ts
Closes [FW-1427](https://mask.atlassian.net/browse/FW-1427)
Closes [FW-1432](https://mask.atlassian.net/browse/FW-1432)
[FW-1427]: https://mask.atlassian.net/browse/FW-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-1432]: https://mask.atlassian.net/browse/FW-1432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: login ff with mobile devices

src/decorators/SetQueryDataForBlockProfile.ts
=> fix: profile mute status error

src/components/NFTs/FollowingNFTList.tsx, src/components/Profile/WalletTabs.tsx
=> fix: do not remove feed in walet's feed page

src/components/Compose/DraftList.tsx, src/components/Compose/Placeholder.tsx, src/helpers/chars.ts, src/helpers/isEmptyPost.ts, src/services/postToFarcaster.ts, src/services/postToLens.ts, src/services/postToTwitter.ts, src/store/useComposeStore.ts
Closes [FW-1438](https://mask.atlassian.net/browse/FW-1438)
[FW-1438]: https://mask.atlassian.net/browse/FW-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: meansure length

src/helpers/chars.ts
=> fix: strategy

src/services/crossPostThread.ts
=> refactor: wait for 3s

src/helpers/createSessionStorage.ts
=> fix: data upgrade

package.json, src/app/(whiteboard)/login/desktop/page.tsx, src/components/OpenFireflyAppButton.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal.tsx
=> [Release] Hotfix 5.4.0 => 5.4.1 (patch)

src/components/Frame/index.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: connect profile

src/components/Poll/PollCreatorCard.tsx, src/helpers/chars.ts, src/modals/ComposeModal.tsx
=> fix: length Infinity error and tooltip

src/helpers/openAppSchemes.ts
=> fix: app open strategy

src/providers/firefly/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1434
=> fix: fw-1434 missing parameter fid for bookmark api

src/app/(normal)/pages/Home.tsx, src/components/LinkCloud.tsx
=> fix: fix locale message cannot refresh when switching language

src/components/Compose/ComposeAction.tsx
=> fix: request to connect wallet

src/components/Search/SearchInput.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: search input locale

src/app/(normal)/article/[id]/pages/DetailPage.tsx, src/components/Actions/Share.tsx
=> chore: replace link icon

src/components/ComposeButton/ComposeButtonForMobile.tsx
=> chore: hidden compose button in some page

src/components/Profile/FollowButton.tsx
=> fix: pass rest props to mute button inside follow button

package.json, src/app/(normal)/article/[id]/pages/DetailPage.tsx, src/app/(normal)/pages/Home.tsx, src/app/(settings)/components/AccountCard.tsx, src/app/(whiteboard)/login/desktop/page.tsx, src/components/Actions/Share.tsx, src/components/Actions/ToggleMutedButton.tsx, src/components/Actions/Views.tsx, src/components/Compose/ComposeAction.tsx, src/components/Compose/PostByItem.tsx, src/components/ComposeButton/ComposeButtonForMobile.tsx, src/components/Frame/index.tsx, src/components/LinkCloud.tsx, src/components/NotLoginFallback.tsx, src/components/OpenFireflyAppButton.tsx, src/components/Poll/PollCreatorCard.tsx, src/components/Profile/FollowButton.tsx, src/components/Search/SearchInput.tsx, src/components/SideBar/Menu.tsx, src/helpers/chars.ts, src/helpers/openAppSchemes.ts, src/hooks/useToggleBookmark.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx, src/modals/LoginModal.tsx, src/providers/firefly/SocialMedia.ts
=> [Release] Hotfix 5.4.1 => 5.4.2 (patch)

src/components/Compose/ComposeAction.tsx, src/components/Poll/PollButton.tsx
https://mask.atlassian.net/browse/FW-1454
Closes FW-0000
=> fix: disable redpacket when poll created

src/app/(normal)/pages/Profile.tsx, src/components/Profile/ProfileContent.tsx, src/components/SuspendedAccountFallback.tsx, src/components/SuspendedAccountInfo.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: new suspended account fallback

src/components/Compose/GifEntryButton.tsx, src/components/Compose/Media.tsx, src/helpers/confirmMediasFile.ts, src/helpers/formatTwitterPost.ts, src/services/postToLens.ts, src/types/giphy.ts
=> fix: support twitter gif

src/components/Markup/MarkupLink/ChannelTag.tsx, src/components/Profile/ProfileTippy.tsx, src/components/TippyContext/index.tsx
https://mask.atlassian.net/browse/fw-1459
=> fix: fixup fw-1459 avoid nested tippy

src/constants/index.ts
=> feat: adjust farcaster post char size

src/components/Actions/BookmarkArticleButton.tsx, src/components/Actions/MuteWalletButton.tsx, src/components/Actions/NFTReportSpamButton.tsx, src/components/Actions/ReportArticleButton.tsx, src/components/Actions/WatchWalletButton.tsx
https://mask.atlassian.net/browse/FW-1473
Closes FW-0000
=> fix: update nft and articles list icon

next.config.js, src/hooks/useSetEditorContent.ts, src/modals/ComposeModal.tsx
=> chore: hidden rp tag

src/components/Frame/index.tsx, src/helpers/formatLensPost.ts, src/services/postToLens.ts, src/services/validateMessage.ts, src/store/useComposeStore.ts
=> feat: support lens sharinglink

src/components/Frame/index.tsx
=> chore: frame error

src/app/api/warpcast/signin/route.ts, src/helpers/encodeMessageData.ts, src/helpers/waitForSignedKeyRequest.ts, src/providers/types/Warpcast.ts, src/providers/warpcast/createSessionByGrantPermission.ts
=> fix: signer key not found

src/components/ScannableQRCode.tsx
https://mask.atlassian.net/browse/FW-1514
Closes FW-0000
=> feat: update QR code background

src/components/Compose/GifEntryButton.tsx
https://mask.atlassian.net/browse/FW-1509
Closes FW-0000
=> fix: disable gif when cant use

src/modals/ConfirmModal.tsx
Closes [FW-1512](https://mask.atlassian.net/browse/FW-1512)
[FW-1512]: https://mask.atlassian.net/browse/FW-1512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: align title

src/components/Posts/Attachment.tsx
=> fix: support mixed image and video

.github/workflows/test.yaml, pnpm-lock.yaml, src/components/TokenProfile/ContractList.tsx, src/constants/regexp.ts, src/helpers/formatMarketCap.ts, src/hooks/useLineChart.ts, tests/constants/regexp.ts
=> fix: discard hash tag like #123

package.json, src/app/api/warpcast/signin/route.ts, src/assets/small-link.svg, src/components/Actions/ReportProfileButton.tsx, src/components/Channel/ChannelMoreAction.tsx, src/components/Profile/MuteWalletButton.tsx, src/components/Profile/ProfileMoreAction.tsx, src/components/Profile/WatchButton.tsx, src/components/ScannableQRCode.tsx, src/helpers/encodeMessageData.ts, src/helpers/resolveEmbedMediaType.ts, src/helpers/waitForSignedKeyRequest.ts, src/modals/ConfirmModal.tsx, src/providers/types/Warpcast.ts, src/providers/warpcast/createSessionByGrantPermission.ts
=> [Release] Hotfix 5.4.3 => 5.4.4 (patch)

src/app/(normal)/token/[symbol]/layout.tsx, src/app/(normal)/token/[symbol]/not-found.tsx, src/app/(normal)/token/[symbol]/page.tsx, src/app/not-found.tsx, src/components/BaseNotFound.tsx, src/components/ClickableArea.tsx, src/components/Markup/MarkupLink/SymbolTag.tsx, src/components/TokenProfile/TokenDetail.tsx, src/components/TokenProfile/TokenProfile.tsx, src/hooks/useCoinPriceStats.ts, src/hooks/useTokenInfo.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: click on symbol tag on mobile

src/components/TokenProfile/TokenProfile.tsx, src/hooks/useLineChart.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-1527
=> fix: fw-1527 format date

src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/FW-1538
Closes FW-0000
=> fix: delay clear compose content

src/helpers/resolveMediaObjectUrl.ts, src/services/postToLens.ts
=> fix: resolve media

src/app/(normal)/profile/pages/DetailPage.tsx, src/components/SourceTabs.tsx, src/helpers/resolveSource.ts, src/store/useGlobalStore.ts, src/store/useProfileTabsStore.ts
=> refactor: UI issues

package.json, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/getResourceType.ts, src/helpers/resolveEmbedMediaType.ts, src/providers/types/Firefly.ts
=> [Release] New release 5.4.5

pnpm-lock.yaml, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/postToFarcaster.ts, src/services/postToLens.ts, src/services/postToTwitter.ts
=> fix: posted post status

pnpm-lock.yaml, src/app/(normal)/@modal/(.)post/[id]/photos/[index]/page.tsx, src/app/globals.css, src/components/Markup/ArticleMarkup.tsx, src/modals/PreviewImagesModal.tsx
=> fix: article multi images preview

pnpm-lock.yaml, src/components/Blink/ActionContainer.tsx, src/constants/env.ts, src/helpers/parseBlinksFromContent.ts, src/helpers/resolveActionJson.ts, src/providers/blink/Loader.ts, src/providers/types/Blink.ts
=> feat: blink match

src/helpers/getResourceType.ts
=> fix: duplicate helper

src/components/Actions/Comment.tsx, src/components/Actions/Like.tsx, src/components/TokenProfile/TokenDetail.tsx, src/components/TokenProfile/TokenProfile.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: align market cap

src/components/Posts/PostBody.tsx, src/components/Posts/PostLinks.tsx, src/helpers/parseBlinksFromContent.ts
=> feat: blink match oembed url

package.json, scripts/build-logs.sh, src/components/Posts/PostBody.tsx, src/constants/env.ts, src/helpers/formatFarcasterPostFromFirefly.ts
=> [Release] Hotfix 5.4.5 => 5.4.6 (patch)

src/app/(normal)/@modal/(.)post/[id]/photos/[index]/page.tsx, src/modals/PreviewImagesModal.tsx
=> fix: swiper slide bugfix

.github/workflows/cspell.yml, .github/workflows/eslint.yml, .github/workflows/lingui.yml, .github/workflows/prettier.yml, .github/workflows/test.yaml
=> ci: upgrade pnpm/action-setup to v4

src/components/Compose/GifEntryButton.tsx, src/components/Compose/GifSelector.tsx
https://mask.atlassian.net/browse/FW-1570
https://mask.atlassian.net/browse/FW-1572
Closes FW-0000
=> fix: fix gif selector ui

next.config.js
=> chore: add ipfs pattern

public/.well-known/apple-app-site-association, public/.well-known/assetlinks.json, vercel.json
=> chore: update apple association

package.json, public/.well-known/apple-app-site-association, public/.well-known/assetlinks.json, vercel.json
=> [Release] Hotfix 5.4.6 => 5.4.7 (patch)

src/modals/FireflySessionConfirmModal.tsx
Closes [FW-1523](https://mask.atlassian.net/browse/FW-1523)
[FW-1523]: https://mask.atlassian.net/browse/FW-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: set current account

pnpm-lock.yaml, src/helpers/account.ts, src/modals/FireflySessionConfirmModal.tsx, src/modals/LogoutModal.tsx
=> fix: logout all accounts

src/components/Posts/Attachment.tsx, src/components/Posts/PostBody.tsx
=> fix: pick asset from available attachments

src/app/api/solana/action/route.ts, src/components/Blink/ActionButton.tsx, src/components/Posts/PostLinks.tsx, src/components/SolanaWalletAdapterProvider.tsx, src/helpers/getWalletClientRequired.ts, src/modals/RainbowKitConnectModal.tsx, src/modals/controls.ts, src/modals/index.tsx
Closes FW-1582 FW-1590 FW-1564 FW-1565 FW-1576 FW-1577 FW-1587 FW-1592
=> fix: blink issues

src/components/Login/LoginLens.tsx, src/helpers/createLensSDK.ts, src/providers/lens/SessionHolder.ts, src/providers/lens/createAccountForProfileId.ts, src/store/useProfileStore.ts
Closes [FW-1524](https://mask.atlassian.net/browse/FW-1524)
[FW-1524]: https://mask.atlassian.net/browse/FW-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: login lens

package.json, pnpm-lock.yaml, src/helpers/getAllMentionsForFarcaster.ts
=> feat: long cast

src/constants/poll.ts
=> fix: lens poll max options

src/components/Login/LoginFarcaster.tsx, src/helpers/account.tsx, src/services/bindFireflySession.ts, src/services/bindOrRestoreFireflySession.ts, src/services/restoreFireflySession.ts
Closes [FW-1540](https://mask.atlassian.net/browse/FW-1540)
[FW-1540]: https://mask.atlassian.net/browse/FW-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: createAccountByRelayService

src/components/Login/LoginLens.tsx
Closes [FW-1573](https://mask.atlassian.net/browse/FW-1573)
[FW-1573]: https://mask.atlassian.net/browse/FW-1573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fix sroll error when select lens profiles

src/components/Compose/ComposeImage.tsx, src/helpers/getResourceType.ts
=> fix: supercast video type

src/app/(developers)/developers/layout.tsx, src/app/(normal)/layout.tsx, src/app/(settings)/settings/layout.tsx, src/components/Login/ProfileAvatarAdd.tsx, src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx, src/components/SideBar/SideBarForDesktop.tsx
=> feat: side menu

src/components/Markup/MarkupLink/SymbolTag.tsx, src/components/TokenProfile/TokenDetail.tsx, src/components/TokenProfile/TokenProfile.tsx, src/components/TokenProfile/TokenSecurity.tsx, src/hooks/useCoinPriceStats.ts, src/hooks/useLineChart.ts, src/hooks/usePriceLineChart.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/coingecko/index.ts, src/providers/types/Coingecko.ts, src/providers/types/Trending.ts
https://mask.atlassian.net/browse/fw-1602
https://mask.atlassian.net/browse/fw-1603
https://mask.atlassian.net/browse/fw-1605
https://mask.atlassian.net/browse/fw-1607
https://mask.atlassian.net/browse/fw-1608
https://mask.atlassian.net/browse/fw-1609
https://mask.atlassian.net/browse/fw-1610
https://mask.atlassian.net/browse/fw-1611
https://mask.atlassian.net/browse/fw-1612
=> fix: some ui issues of token profile

src/components/Profile/ProfileTabs.tsx
Closes [FW-1601](https://mask.atlassian.net/browse/FW-1601)
[FW-1601]: https://mask.atlassian.net/browse/FW-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: refresh profile page after login changed

.github/workflows/cspell.yml, .github/workflows/eslint.yml, .github/workflows/lingui.yml, .github/workflows/prettier.yml, .github/workflows/test.yaml, package.json, public/.well-known/apple-app-site-association
=> [Release] Hotfix 5.4.7 => 5.4.8 (patch)

src/helpers/formatLensPost.ts, src/services/postToLens.ts, src/store/useComposeStore.ts
=> fix: append frame link for lens

src/components/Blink/index.tsx, src/components/Frame/index.tsx
=> fix: resolve tco in blink

src/components/TokenProfile/TokenDetail.tsx, src/helpers/formatPrice.tsx, src/hooks/useLineChart.ts, tests/helpers/formatPrice.tsx
https://mask.atlassian.net/browse/fw-1651
https://mask.atlassian.net/browse/fw-1653
=> fix: fw-1651 price chart on dark mode

src/services/restoreFireflySession.ts
Closes [FW-1598](https://mask.atlassian.net/browse/FW-1598)
Closes [FW-1631](https://mask.atlassian.net/browse/FW-1631)
[FW-1598]: https://mask.atlassian.net/browse/FW-1598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-1631]: https://mask.atlassian.net/browse/FW-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fake signer request token

src/components/Posts/Attachment.tsx, src/helpers/resolveMediaObjectUrl.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/postToTwitter.ts, src/types/compose.ts
https://mask.atlassian.net/browse/FW-1649
Closes FW-0000
=> fix: add uploadIds for twitter media

src/components/TokenProfile/TokenDetail.tsx, src/components/TokenProfile/TokenProfile.tsx, src/hooks/usePriceLineChart.ts
=> fix: chart color

src/app/api/twitter/login/route.ts, src/components/Login/ProfileSettings.tsx, src/helpers/account.tsx, src/helpers/createTwitterSessionPayload.ts, src/store/useProfileStore.ts
Closes [FW-1600](https://mask.atlassian.net/browse/FW-1600)
[FW-1600]: https://mask.atlassian.net/browse/FW-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: switch tw account

src/app/(normal)/@modal/(.)post/[id]/photos/[index]/page.tsx, src/components/Posts/Attachment.tsx
https://mask.atlassian.net/browse/FW-1663
Closes FW-0000
=> fix: twitter animated gif viewer

src/app/globals.css, src/components/SideBar/ConnectWallet.tsx, src/helpers/getAllMentionsForFarcaster.ts, src/polyfills/index.ts, src/polyfills/requestIdleCallback.ts, src/store/useComposeStore.ts, src/store/useGlobalStore.ts
Closes FW-1637 FW-1627 FW-1621 FW-1654 FW-1507
=> fix: blink solana issues

src/components/Profile/ProfileTabs.tsx
https://mask.atlassian.net/browse/FW-1601
Closes FW-0000
=> fix: refresh profile when login changed

src/components/Login/LoginLens.tsx, src/helpers/account.tsx, src/helpers/createLensSDK.ts, src/helpers/resolveSessionHolder.ts, src/providers/lens/SessionHolder.ts, src/providers/lens/createAccountForProfileId.ts, src/services/syncAccountsFromFirefly.ts
Closes [FW-1598](https://mask.atlassian.net/browse/FW-1598)
Closes [FW-1665](https://mask.atlassian.net/browse/FW-1665)
[FW-1598]: https://mask.atlassian.net/browse/FW-1598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-1665]: https://mask.atlassian.net/browse/FW-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: switch account

src/components/SolanaWalletAdapterProvider.tsx
=> feat: hidden some solana wallets

src/components/Compose/ComposeAction.tsx, src/constants/env.ts
**We need to apply a production apiKey for giphy after release, so we need a transition time**
Closes FW-0000
=> feat: add env control for compose gif

src/components/Blink/ActionContainer.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: blink translation

src/modals/ConfirmModal.tsx
=> fix: adjust gap

src/components/Actions/PostStatistics.tsx, src/helpers/assertLensAccountOwner.ts, src/providers/lens/SocialMedia.ts
=> fix: bugfix for lens

src/polyfills/AbortSignal.timeout.ts, src/polyfills/URL.canParse.ts, src/polyfills/requestIdleCallback.ts
=> fix: polyfill

package.json, src/app/api/twitter/login/route.ts, src/helpers/createTwitterSessionPayload.ts
Closes [FW-1671](https://mask.atlassian.net/browse/FW-1671)
[FW-1671]: https://mask.atlassian.net/browse/FW-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: x login

package.json, public/.well-known/apple-app-site-association
=> [Release] Hotfix 5.4.8 => 5.4.9 (patch)

src/app/(settings)/components/SettingsList.tsx, src/app/(settings)/settings/mutes/page.tsx, src/hooks/useMuteMenuList.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> chore: mute i18n

src/components/Posts/Attachment.tsx, src/constants/index.ts, src/services/crossPost.ts
=> refactor: disable x preview

src/app/(normal)/@modal/(.)post/[id]/photos/[index]/page.tsx, src/components/Posts/Attachment.tsx, src/components/Posts/VideoAsset.tsx, src/components/Posts/WithPreviewLink.tsx, src/constants/index.ts, src/services/crossPost.ts
https://mask.atlassian.net/browse/FW-1663
Closes FW-0000
=> fix: disable twitter media preview

src/store/useProfileStore.ts
=> fix: tw session

src/components/Login/LoginLens.tsx, src/helpers/account.tsx, src/modals/ConfirmModal.tsx, src/providers/lens/SessionHolder.ts, src/services/syncAccountsFromFirefly.ts
=> fix: switching session

src/helpers/chars.ts
=> fix: add char limit for poll

src/constants/index.ts
https://mask.atlassian.net/browse/FW-1675
Closes FW-0000
=> fix: adjust farcaster media limit

package.json, src/components/CircleCheckboxIcon.tsx, src/components/Login/ProfileSettings.tsx
https://mask.atlassian.net/browse/fw-1658
=> fix: fw-1658 avoid icon shrinking in profile settings

src/components/Login/LoginLens.tsx, src/locales/zh-Hans/messages.po
=> fix: modal UI

src/components/Login/LoginLens.tsx, src/helpers/account.ts, src/modals/ConfirmFireflyModal.tsx, src/modals/controls.ts, src/modals/index.tsx
=> refactor: confirm firefly modal

src/components/Compose/ComposeAction.tsx, src/components/Compose/GifSelector.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostBy.tsx, src/constants/index.ts, src/helpers/getCurrentPostImageLimits.ts, src/hooks/useCheckPostMedias.ts
https://mask.atlassian.net/browse/FW-1678
Closes FW-0000
=> fix: adjust farcaster image limit when quote

src/components/Compose/ComposeAction.tsx, src/components/Compose/GifSelector.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostBy.tsx, src/constants/index.ts, src/helpers/getCurrentPostImageLimits.ts, src/hooks/useCheckPostMedias.ts
Reverts DimensionDev/firefly.mask.social#1761
=> Revert "fix: adjust farcaster image limit when quote"

src/components/Compose/ComposeAction.tsx, src/components/Compose/GifSelector.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostBy.tsx, src/constants/index.ts, src/helpers/getCurrentPostImageLimits.ts, src/hooks/useCheckPostMedias.ts
Reverts DimensionDev/firefly.mask.social#1764
=> Revert "Revert "fix: adjust farcaster image limit when quote""

src/components/NFTs/NFTMoreAction.tsx, src/helpers/formatTwitterPost.ts, src/providers/twitter/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1672
https://mask.atlassian.net/browse/fw-1680
https://mask.atlassian.net/browse/FW-1501
=> fix: some profile related issues

src/app/(normal)/bookmarks/BookmarkList.tsx, src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Blink/ActionContainer.tsx, src/constants/error.ts, src/decorators/SetQueryDataForBlockWallet.ts, src/decorators/SetQueryDataForLikePost.ts, src/helpers/getAllMentionsForFarcaster.ts, src/hooks/useDeletePost.ts, src/hooks/useToggleMutedChannel.ts, src/providers/firefly/SocialMedia.ts
=> refactor: re-throw errors

src/decorators/SetQueryDataForMirrorPost.ts
=> fix: bugfix for deploy

src/app/(normal)/layout.tsx, src/app/(normal)/profile/[id]/page.tsx, src/app/(normal)/profile/pages/DetailPage.tsx, src/components/Markup/MarkupLink/SymbolTag.tsx
https://mask.atlassian.net/browse/fw-1675
https://mask.atlassian.net/browse/fw-1679
=> fix: fw-1675 image gallery affects profile page

src/constants/index.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/farcaster/SessionHolder.ts, src/providers/hubble/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/types/Hubble.ts
Closes FW-0000
[FW-1647]: https://mask.atlassian.net/browse/FW-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: hubble provider

src/helpers/formatBalance.ts, src/helpers/number.ts
=> refactor: numbers

src/components/Actions/ArticleMore.tsx, src/components/Actions/More.tsx, src/components/Channel/ChannelMoreAction.tsx, src/components/MoreActionMenu.tsx, src/components/NFTs/NFTMoreAction.tsx, src/components/Profile/ProfileMoreAction.tsx, src/components/Profile/WalletMoreAction.tsx, src/components/TokenProfile/ContractList.tsx
=> refactor: more action menu

src/assets/circle-share.svg, src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes [FW-1687](https://mask.atlassian.net/browse/FW-1687)
[FW-1687]: https://mask.atlassian.net/browse/FW-1687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: replace open app icon

src/components/Compose/ComposeAction.tsx, src/components/Compose/ComposeUI.tsx, src/components/Compose/DraftList.tsx, src/components/Compose/SchedulePostEntryButton.tsx, src/components/Compose/SchedulePostSettings.tsx, src/components/Compose/ScheduleTaskList.tsx, src/components/TimePicker.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx, src/modals/DraggablePopover.tsx, src/modals/SchedulePostModal.tsx
=> refactor: mobile schedule modal

src/app/(normal)/pages/Profile.tsx, src/assets/more-circle.svg, src/components/Actions/ToggleMutedButton.tsx, src/components/MoreActionMenu.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/Info.tsx, src/components/Profile/MuteWalletButton.tsx, src/components/Profile/ProfileMoreAction.tsx, src/components/Profile/Title.tsx, src/components/Profile/WatchButton.tsx, src/hooks/useIsMyProfile.ts
https://mask.atlassian.net/browse/fw-1689
https://mask.atlassian.net/browse/fw-974
=> feat: fw-974 stick nav bar for my profiles

package.json, src/components/Compose/ComposeAction.tsx, src/components/Compose/GifSelector.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostBy.tsx, src/constants/index.ts, src/helpers/getCurrentPostImageLimits.ts, src/hooks/useCheckPostMedias.ts
=> [Release] Hotfix 5.5.0 => 5.5.1 (patch)

src/app/(developers)/developers/settings/page.tsx, src/settings/index.ts, src/store/useDeveloperSettingsStore.ts
=> refactor: developer settings store

src/components/Profile/ProfileAction.tsx, src/components/Profile/ProfileLoginStatus.tsx, src/components/Profile/ProfileMoreAction.tsx, src/components/Profile/Title.tsx
https://mask.atlassian.net/browse/FW-1729
Closes FW-0000
=> feat: update profile action ui

src/components/Profile/WatchButton.tsx, src/constants/error.ts, src/helpers/getSnackbarMessageFromError.tsx, src/helpers/getWalletClientRequired.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal.tsx
https://mask.atlassian.net/browse/FW-1726
https://mask.atlassian.net/browse/FW-1728
Closes FW-0000
=> fix: profile action

src/components/Compose/GifSelector.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1717
Closes FW-0000
=> fix: add size limit for gif

src/configs/wagmiClient.ts, src/constants/index.ts, src/helpers/isSupportedChainId.ts
=> feat: isSupportedChainid

src/app/(normal)/layout.tsx, src/components/Compose/ComposeWatcher.tsx, src/components/Login/LoginLens.tsx, src/providers/lens/updateSignless.ts
=> feat: compose route watcher

src/components/Avatar.tsx, src/configs/wagmiClient.ts, src/constants/index.ts, src/helpers/domain-test.ts, src/helpers/resolveFirstAvailableUrl.ts
=> fix: ignore warpcast avatar validator

src/components/Actions/More.tsx, src/components/Actions/MuteWalletButton.tsx, src/components/Channel/ChannelMoreAction.tsx, src/components/MoreActionMenu.tsx, src/components/Profile/ProfileMoreAction.tsx
https://mask.atlassian.net/browse/FW-1726
Closes FW-0000
=> fix: login required before action

src/components/Tips/TipsUI.tsx, src/components/Tips/TokenSelector.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1757
https://mask.atlassian.net/browse/FW-1759
Closes FW-0000
=> fix: tips ui

src/store/useProfileStore.ts
=> fix: remove test code

src/hooks/useCheckPostMedias.ts, src/hooks/useCheckSessions.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: check sessions

src/components/Compose/ComposeAction.tsx, src/components/Compose/SchedulePostSettings.tsx, src/components/Compose/ScheduleTaskList.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/SchedulePostModal.tsx, src/services/crossSchedulePost.tsx, src/services/crossSchedulePostThread.ts
Closes FW-1706  FW-1708 FW-1713 FW-1718 FW-1737
=> fix: bugfix for schedule post

src/components/Tips/TipSuccess.tsx, src/components/Tips/TipsUI.tsx, src/components/Tips/TokenSelector.tsx, src/components/Tips/WalletSelector.tsx, src/components/Tips/index.tsx, src/components/Tips/tipsModalRouter.tsx, src/hooks/useCurrentFireflyProfiles.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/TipsModal.tsx
https://mask.atlassian.net/browse/FW-1764
https://mask.atlassian.net/browse/FW-1767
https://mask.atlassian.net/browse/FW-1768
https://mask.atlassian.net/browse/FW-1769
https://mask.atlassian.net/browse/FW-1770
https://mask.atlassian.net/browse/FW-1766
https://mask.atlassian.net/browse/FW-1772
Closes FW-0000
=> feat: lookup all related wallets

src/components/Tips/TipSuccess.tsx, src/components/Tips/TokenSelector.tsx
=> chore: prettier

src/components/Actions/ArticleMore.tsx, src/components/Actions/More.tsx, src/components/NFTs/NFTMoreAction.tsx, src/components/Profile/WalletInfo.tsx, src/hooks/useIsMyRelatedProfile.ts
https://mask.atlassian.net/browse/FW-1784
Closes FW-0000
=> fix: hideen unused action for related profile

src/app/(normal)/layout.tsx
=> fix: duplicate header in preview image

src/helpers/account.ts, src/helpers/getProfileState.ts, src/services/bindOrRestoreFireflySession.ts
=> chore: upload metrics

src/app/globals.css, src/components/Compose/ComposeAction.tsx, src/components/Compose/DraftPage.tsx, src/components/Compose/ScheduleTaskList.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts, src/services/crossSchedulePost.tsx, src/services/crossSchedulePostThread.ts
Closes FW-1711 FW-1712 FW-1730 FW-1731 FW-1737 FW-1756
=> fix: bugfix for schedule post ui

src/components/Tips/TokenIcon.tsx
https://mask.atlassian.net/browse/FW-1791
Closes FW-0000
=> feat: update token icon size

src/app/(developers)/components/ToolkitList.tsx, src/app/(developers)/developers/blink/layout.tsx, src/app/(developers)/developers/blink/page.tsx, src/app/api/solana/action/route.ts, src/constants/enum.ts, src/helpers/withRequestRedisCache.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: blink cache

src/components/Login/ProfileSettings.tsx
https://mask.atlassian.net/browse/FW-1785
Closes FW-0000
=> fix: show all lens profiles

src/constants/error.ts, src/helpers/account.ts, src/services/restoreFireflySession.ts
=> fix: restore ff session from synced accounts

src/services/bindFireflySession.ts
=> fix: bugfix for bind farcaster

src/services/bindFireflySession.ts, src/services/restoreFireflySession.ts
Closes [FW-1789](https://mask.atlassian.net/browse/FW-1789)
[FW-1789]: https://mask.atlassian.net/browse/FW-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: reconnect failed

src/components/Tips/TipSuccess.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1795
Closes FW-0000
=> fix: tips share ui

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Actions/PostStatistics.tsx, src/components/Actions/index.tsx, src/components/Posts/PostBody.tsx
=> fix: bugfix for detail style

src/components/Blink/index.tsx, src/components/Posts/PostLinks.tsx
=> fix: oembed

src/providers/ethereum/getDefaultGas.ts
https://mask.atlassian.net/browse/FW-1796
Closes FW-0000
=> fix: estimate more gas

src/helpers/chars.ts, src/store/useComposeStore.ts
=> feat: sort post content

src/components/Login/ProfileSettings.tsx
=> fix: disable fetch when wallet hast connect

src/services/metrics.ts
=> refactor: no need to sync sessions

src/components/Frame/index.tsx, src/helpers/isSameOriginUrl.ts
=> feat: whitelist for frame jump link

src/components/Frame/index.tsx
=> fix: whitelist for production url

src/providers/ethereum/getDefaultGas.ts
=> fix: fallback gas limit

src/components/Posts/Attachment.tsx
=> fix: image re-render after post state changed

src/helpers/resolveMediaObjectUrl.ts, src/services/createLensSchedulePostPayload.ts, src/services/postToLens.ts, src/services/uploadToS3.ts
https://mask.atlassian.net/browse/fw-1799
=> fix: fw-1799 upload image to S3 for lens

src/app/api/firefly/metrics/route.ts, src/helpers/isSameSession.ts, src/helpers/ts.ts, src/polyfills/AbortSignal.timeout.ts, src/services/metrics.ts
=> fix: sync lens sessions

src/services/bindFireflySession.ts, src/services/restoreFireflySession.ts
=> refactor: only granted

tests/helpers/ts.ts
=> chore: add test cases for ts

src/components/Tips/TokenIcon.tsx, src/components/Tips/TokenSelector.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-1805
Closes FW-0000
=> fix: tips token icon ui

src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/ethereum/Transfer.ts
=> fix: estimate more gas for tips

src/helpers/account.ts
=> refactor: add account later

src/components/Tips/AddressLink.tsx, src/components/Tips/TokenSelector.tsx, src/components/Tips/WalletSelector.tsx, src/components/Tips/index.tsx, src/components/Tips/tipsModalRouter.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/TipsModal.tsx, src/providers/ethereum/Transfer.ts, src/providers/ethereum/getDefaultGas.ts
=> feat: optimize tips ui

src/components/Tips/index.tsx, src/providers/ethereum/getDefaultGas.ts
=> fix: available wallet profiles for tips

src/helpers/resolveLensQuery.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: lens schedule post payload

cspell.json, src/app/api/frame/route.ts, src/components/Frame/index.tsx, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: temporarily workaround for polymaket frame

src/app/(normal)/pages/Profile.tsx, src/app/(normal)/profile/[id]/not-found.tsx, src/components/Profile/ProfileNotFound.tsx
=> fix: keep profile source tab even profile is not found

src/components/Login/ProfileAvatarInteractive.tsx, src/components/Login/ProfileSettings.tsx
=> fix: hidden popover before login

src/app/(normal)/pages/Profile.tsx
https://mask.atlassian.net/browse/fw-1825
=> fix: fw-1825 twitter profile not found

src/app/(normal)/profile/pages/DetailPage.tsx, src/hooks/useCurrentFireflyProfiles.ts
=> fix: independent process twitter profiles

src/services/metrics.ts
=> fix: filter out invalid fc token

src/modals/LogoutModal.tsx
https://mask.atlassian.net/browse/fw-1825
=> fix: fw-1825 do not reset profile tab when logout

src/components/Compose/SchedulePostSettings.tsx, src/components/DatePicker.tsx, src/components/Profile/ProfileContentTabs.tsx, src/components/TimePicker.tsx, src/helpers/resolveLensQuery.ts, src/services/createTwitterSchedulePostPayload.ts, src/services/crossSchedulePost.tsx, src/services/crossSchedulePostThread.ts
=> fix: bugfix for schedule thread

src/app/api/frame/route.ts, src/components/Frame/index.tsx, src/helpers/resolveMintUrl.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/hubble/Frame.ts, src/providers/types/Frame.ts, src/types/frame.ts
=> feat: eth sign typed data

src/app/api/frame/route.ts, src/app/api/solana/action/route.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/base/Loader.ts
=> refactor: handle action error

package.json, src/app/api/frame/route.ts, src/components/Frame/index.tsx, src/helpers/resolveMintUrl.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/hubble/Frame.ts, src/providers/types/Frame.ts, src/types/frame.ts
=> [Release] Hotfix 5.5.3 => 5.5.4 (patch)

src/helpers/isTopLevelDomain.ts
=> chore: add social in TLD

src/helpers/isTopLevelDomain.ts
=> chore: add land to TLD

src/components/ProfileInList.tsx
=> fix: text truncate in top profile

src/components/Tips/TokenItem.tsx, src/helpers/switchEthereumChain.ts, src/providers/ethereum/Network.ts, src/providers/ethereum/Transfer.ts, src/providers/solana/Network.ts, src/providers/types/Network.ts
https://mask.atlassian.net/browse/FW-1824
Closes FW-0000
=> fix: switch chain with parameter

src/helpers/waitForEthereumTransaction.ts, src/providers/ethereum/Transfer.ts, src/providers/solana/Transfer.ts, src/providers/types/Transfer.ts
https://mask.atlassian.net/browse/FW-1830
Closes FW-0000
=> fix: transaction confirm

src/app/(developers)/developers/frame/page.tsx, src/components/Frame/index.tsx, src/components/Posts/PostLinks.tsx, src/helpers/createDummyPost.ts, src/helpers/generateSiteUrl.ts, src/helpers/isSameOriginUrl.ts, src/modals/ConfirmBeforeLeavingModal.tsx, src/modals/controls.ts, src/modals/index.tsx
=> refactor: generateSiteUrl

src/app/not-found.tsx
https://mask.atlassian.net/browse/fw-1834
https://mask.atlassian.net/browse/fw-1836
=> fix: adjust 404 page style

src/providers/ethereum/Transfer.ts
https://mask.atlassian.net/browse/FW-1831
Closes FW-0000
=> fix: add more gaslimit for transaction

src/app/(normal)/pages/Profile.tsx
https://mask.atlassian.net/browse/fw-1825
=> fix: fw-1825 twitter login is required

src/app/(settings)/settings/more/page.tsx, src/components/LinkCloud.tsx, src/components/Profile/ProfileMoreAction.tsx, src/components/SideBar/Menu.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: replace text

src/components/ErrorReportSnackbar.tsx, src/decorators/SetQueryDataForBlockProfile.ts, src/helpers/enqueueMessage.tsx
=> fix: line wrap in error report toast

src/app/(normal)/layout.tsx
=> fix: fw-1835

src/providers/ethereum/isNativeToken.ts
https://mask.atlassian.net/browse/FW-1848
Closes FW-0000
=> fix: judge native token

src/components/Profile/NFTCollectionList.tsx, src/services/getWalletsNFTCollections.ts
=> fix: FW-1208 replace new nft collections api

src/app/(settings)/settings/more/page.tsx, src/components/LinkCloud.tsx, src/components/SideBar/SideBarForDesktop.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: fw-1853

src/components/MaskProviders.tsx, src/components/SideBar/Menu.tsx
=> fix: sync calendar locale

src/components/Compose/SchedulePostSettings.tsx, src/components/Frame/index.tsx, src/components/Lexical/plugins/AutoLinkPlugin.tsx, src/components/Profile/ProfileContentTabs.tsx, src/helpers/fixUrlProtocol.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/helpers/generateComposeProps.ts, src/helpers/isTopLevelDomain.ts, src/hooks/useCheckPostMedias.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx, src/services/crossSchedulePost.tsx, src/services/crossSchedulePostThread.ts
=> fix: add tld rule for oembed urls

src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/components/Lexical/plugins/AutoLinkPlugin.tsx, src/components/Posts/ContentTranslator.tsx, src/helpers/generateComposeProps.ts, src/hooks/useIsLogin.ts, src/modals/controls.ts
https://mask.atlassian.net/browse/FW-1838
Closes FW-0000
=> fix: avoid detecting language without login

src/app/(normal)/search/layout.tsx, src/app/(normal)/search/page.tsx
=> fix: invalid search page scroll

src/helpers/getWalletClientRequired.ts
Closes [FW-1843](https://mask.atlassian.net/browse/FW-1843)
[FW-1843]: https://mask.atlassian.net/browse/FW-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: swich chain

src/app/api/frame/route.ts, src/helpers/getErrorMessageFromFetchError.ts, src/helpers/getFrameErrorMessage.ts, src/helpers/getSnackbarMessageFromError.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes [FW-1842](https://mask.atlassian.net/browse/FW-1842)
[FW-1842]: https://mask.atlassian.net/browse/FW-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: superrare frame

.github/workflows/sync-submodules.yml, scripts/setup-gh-actions.sh
=> fix: actions

src/app/(normal)/profile/page.tsx, src/components/Login/LoginTwitter.tsx
https://mask.atlassian.net/browse/FW-1852
Closes FW-0000
=> fix: twitter login redirect url

src/app/(normal)/pages/Profile.tsx, src/hooks/useCurrentFireflyProfiles.ts, src/providers/firefly/SocialMedia.ts
=> fix: compose twitter profiles in need

src/components/Actions/Bookmark.tsx, src/components/Profile/ProfileSourceTabs.tsx, src/components/Profile/ProfileTabs.tsx
https://mask.atlassian.net/browse/fw-1677
=> fix: fw-1677 avoid page jittering

src/mask/widgets/CalendarWidget.tsx
=> fix: remove calendar provider icon

src/components/Posts/VideoAsset.tsx
https://mask.atlassian.net/browse/FW-1867
Closes FW-0000
=> fix: gif autoplay

src/components/SideBar/SideBarForDesktop.tsx, src/components/SuggestedFollows/SuggestedFollowUsersList.tsx
=> fix: FW-1866

src/app/api/twitter/user/[userId]/route.ts, src/store/useProfileStore.ts
Closes [FW-1849](https://mask.atlassian.net/browse/FW-1849)
[FW-1849]: https://mask.atlassian.net/browse/FW-1849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: twitter state

src/components/Tips/TipsUI.tsx, src/components/Tips/TokenItem.tsx, src/helpers/waitForEthereumTransaction.ts, src/providers/ethereum/Transfer.ts, src/providers/ethereum/getAvailableBalance.ts, src/providers/ethereum/getTokenBalance.ts, src/services/getTokensByAddress.ts
https://mask.atlassian.net/browse/FW-1855
https://mask.atlassian.net/browse/FW-1868
Closes FW-0000
=> feat: tips ux

src/components/Profile/ProfileSourceTabs.tsx
https://mask.atlassian.net/browse/FW-1876
Closes FW-0000
=> fix: fixed profile after source changed

src/app/(normal)/pages/Profile.tsx, src/app/(normal)/profile/page.tsx
=> fix: show login fallback without profile

src/app/(normal)/profile/pages/DetailPage.tsx
=> fix: merge profiles for twitter

src/components/Compose/DraftList.tsx, src/components/Compose/ScheduleTaskList.tsx, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> chore: schedule i18n

src/app/(normal)/pages/Profile.tsx, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: profile fallback without login

src/app/(settings)/components/AccountCard.tsx, src/app/(settings)/settings/connected/page.tsx, src/components/Login/ProfileSettings.tsx, src/hooks/useConnectedAccounts.ts, src/locales/en/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: settings connected accounts

src/abis/USDT.ts, src/helpers/getTokenAbiForWagmi.ts, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/ethereum/Transfer.ts, src/providers/ethereum/getTokenBalance.ts
https://mask.atlassian.net/browse/FW-1863
Closes FW-0000
=> fix: usdt abi for wagmi

src/helpers/account.ts
Closes [FW-1747](https://mask.atlassian.net/browse/FW-1747)
[FW-1747]: https://mask.atlassian.net/browse/FW-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: overwrite ff session

src/app/(developers)/developers/blink/page.tsx
=> feat: blink refresh on x url

src/configs/wagmiClient.ts, src/helpers/createWagmiPublicClient.ts, src/helpers/resolveRPCUrl.ts
https://mask.atlassian.net/browse/FW-1863
Closes FW-0000
=> fix: customize rpc URL

src/app/(normal)/pages/Profile.tsx
=> fix: no fallback for wallet profile

src/components/Frame/index.tsx, src/helpers/openIntentUrl.ts
=> refactor: open intent url

lingui.config.js, src/components/Compose/SchedulePostSettings.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/crossSchedulePost.tsx, src/services/crossSchedulePostThread.ts
=> refactor: error msg locale

src/modals/ConfirmBeforeLeavingModal.tsx
https://mask.atlassian.net/browse/FW-1884
Closes FW-0000
=> fix: fix link jump confirm

src/app/(developers)/developers/blink/page.tsx, src/components/Blink/index.tsx, src/helpers/resolveBlinkTCO.ts, src/providers/blink/Parser.ts
=> feat: x interstitial

src/components/Compose/SchedulePostSettings.tsx, src/components/Compose/ScheduleTaskList.tsx, src/helpers/checkScheduleTime.ts, src/helpers/getScheduleTaskContent.ts, src/modals/ComposeModal.tsx, src/services/crossSchedulePost.tsx, src/services/crossSchedulePostThread.ts
Closes FW-1885 FW-1888 FW-1890 FW-1891
=> fix: bugfix for schedule time

src/components/NFTs/NFTMoreAction.tsx, src/constants/enum.ts
=> fix: nft more action

src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/ethereum/getTokenBalance.ts
=> fix: tips token balance

src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx
=> fix: draft tooltip text

src/components/CollectionDetail/TopCollectors.tsx
=> fix: fw-1899

src/app/api/solana/action/route.ts, src/components/Blink/ActionContainer.tsx, src/components/Blink/ActionForm.tsx, src/components/Blink/ActionInput.tsx, src/components/Blink/ActionLayout.tsx, src/constants/error.ts, src/helpers/fetch.ts, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/types/blink.ts
=> feat: blink form layout

src/components/CollectionDetail/NFTList.tsx
=> fix: hide nft owner address tag

src/components/Notification/NotificationItem.tsx
https://mask.atlassian.net/browse/fw-1898
=> fix: fw-1898 duplicate profiles occur in mirror notification

src/components/NFTs/NFTMoreAction.tsx
=> fixup! fix: nft more action (#1960)

src/app/globals.css
=> fix: time picker

src/components/Oembed/Mirror.tsx, src/components/Oembed/index.tsx
https://mask.atlassian.net/browse/fw-1907
=> fix: fw-1907 failed-load url gets hidden

src/components/Notification/NotificationFilter.tsx
https://mask.atlassian.net/browse/FW-1911
Closes FW-0000
=> fix: notification filter bar ui

src/helpers/resolveNftUrl.ts
=> fix: bugfix for nft page router

src/app/(normal)/profile/pages/DetailPage.tsx
https://mask.atlassian.net/browse/fw-1909
=> fix: fw-1909 twitter tab glicth

src/components/DatePicker.tsx, src/components/TimePicker.tsx
=> fix: replace popover to tippy

src/components/LinkCloud.tsx, src/components/Oembed/Embed.tsx, src/components/Oembed/index.tsx, src/components/Posts/PostLinks.tsx
https://mask.atlassian.net/browse/fw-1907
=> fix: fixup fw-1907 

src/components/Actions/ToggleMutedButton.tsx
https://mask.atlassian.net/browse/FW-1908
Closes FW-0000
=> fix: mute button ui

src/components/PreviewMedia/index.tsx
https://mask.atlassian.net/browse/FW-1910
Closes FW-0000
=> fix: media preview modal ui

src/helpers/createErrorResponseJSON.ts, src/helpers/createResponseJSON.ts
=> fix: no dynamic headers

src/app/api/solana/action/route.ts, src/app/api/twitter/homeTimeline/route.ts, src/app/api/twitter/me/route.ts, src/app/api/twitter/mute/route.ts, src/app/api/twitter/userTimeline/[userId]/liked/route.ts, src/app/api/twitter/userTimeline/[userId]/replies/route.tsx, src/app/api/twitter/userTimeline/[userId]/route.ts, src/schemas/index.ts
=> refactor: page limit

src/app/globals.css
=> fix: date picker color

package.json
=> [Release] New release 5.6.0 (minor)

src/components/Compose/SchedulePostSettings.tsx
=> chore: close modal after clear time

src/components/Frame/index.tsx, src/modals/ConfirmLeavingModal.tsx, src/modals/ConfirmModal.tsx, src/modals/controls.ts, src/modals/index.tsx
Closes [FW-709](https://mask.atlassian.net/browse/FW-709)
[FW-709]: https://mask.atlassian.net/browse/FW-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: close the modal

src/app/api/twitter/compose/route.ts, src/services/createTwitterSchedulePostPayload.ts
=> fix: twitter schedule poll

src/helpers/resolveFireflyProfiles.ts
=> fix: same wallet address

src/middleware.ts, vercel.json
=> refactor: redirect with vercel.json

pnpm-lock.yaml, src/components/MaskProviders.tsx, src/components/Providers.tsx, src/mask/widgets/PageInspector.tsx
=> refactor: maskbook is slimmer

src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/farcaster/Session.ts, src/services/metrics.ts
=> fix: merge sessions

src/components/Markup/MarkupLink/index.tsx
=> fix: twitter profile tippy

src/helpers/formatTimestamp.ts
=> fix: fix time format

src/components/Posts/PostHeader.tsx, src/components/Posts/SinglePost.tsx
=> feat: FW-1901

src/app/globals.css, src/components/Tips/TipsUI.tsx, src/components/Tips/index.tsx, tailwind.config.cjs
https://mask.atlassian.net/browse/FW-1923
Closes FW-0000
=> feat: tips ui and text

src/app/api/twitter/auth/route.ts, src/services/bindFireflySession.ts, src/services/restoreFireflySession.ts, src/store/useProfileStore.ts
Closes [FW-1914](https://mask.atlassian.net/browse/FW-1914)
[FW-1914]: https://mask.atlassian.net/browse/FW-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: restore ff session

src/components/Actions/More.tsx, src/components/Actions/MuteAllProfile.tsx, src/components/Profile/ProfileMoreAction.tsx, src/components/Profile/WalletMoreAction.tsx, src/decorators/SetQueryDataForBlockProfile.ts, src/decorators/SetQueryDataForBlockWallet.ts, src/helpers/getPlatformQueryKey.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/FW-1644
Closes FW-0000
=> fix: mute all account

src/components/Tips/TipsUI.tsx
https://mask.atlassian.net/browse/FW-1930
Closes FW-0000
=> fix: support chinese input mode for tips amount

src/app/globals.css, src/decorators/SetQueryDataForBlockWallet.ts, src/providers/types/Firefly.ts, tailwind.config.cjs
=> fix: support alpha for rgb color

src/components/Profile/FollowButton.tsx, src/components/ProfileInList.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: follow back

src/components/Profile/NFTCollectionList.tsx
=> fix: nft list name

src/components/Oembed/index.tsx, src/providers/og/Processor.ts
=> chore: keep show url when og no data

src/components/Actions/index.tsx, src/components/Posts/PostHeader.tsx, src/components/Posts/SinglePost.tsx, src/components/Profile/Title.tsx, src/constants/index.ts, src/helpers/formatLensPost.ts, src/helpers/formatTwitterPost.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes FW-1948 FW-1951 FW-1952 FW-1955 FW-1956 FW-1957
=> fix: twitter issues

src/app/(normal)/profile/[id]/[category]/layout.tsx, src/components/AvatarGroup.tsx, src/components/Profile/Info.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/lens/SocialMedia.ts, src/store/useProfileStore.ts
Closes FW-1927 FW-1939 FW-1940 FW-1941
=> feat: mutuals in profile page

src/components/Actions/More.tsx
https://mask.atlassian.net/browse/FW-1954
Closes FW-0000
=> feat: remove mute all in post timeline

src/components/Actions/ToggleMutedProfileButton.tsx, src/components/Posts/PostBody.tsx, src/components/Profile/FollowButton.tsx, src/hooks/useIsProfileMuted.ts
https://mask.atlassian.net/browse/FW-1949
Closes FW-0000
=> fix: update mute status for profile

src/components/NFTs/NFTFeedAction.tsx, src/components/Profile/WalletInfo.tsx, src/components/RedPacket/AuthorText.tsx, src/helpers/resolveMintUrl.ts
=> refactor: remove isAddress front detection

src/app/api/avatar/route.ts, src/app/api/frame/route.ts, src/app/api/oembed/route.ts, src/app/api/rp/route.tsx, src/app/api/s3/route.ts, src/app/api/thread/route.ts, src/app/api/twitter/[tweetId]/route.ts, src/app/api/twitter/compose/route.ts, src/app/api/warpcast/signed-key/route.ts, src/helpers/getGatewayErrorMessage.ts, src/providers/frame/Processor.ts, src/providers/og/Processor.ts, src/providers/warpcast/SocialMedia.ts, src/services/createRedPacketImage.tsx
Closes [FW-1937](https://mask.atlassian.net/browse/FW-1937)
[FW-1937]: https://mask.atlassian.net/browse/FW-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: respond digest errors

src/helpers/account.ts, src/services/crossSchedulePost.tsx, src/services/crossSchedulePostThread.ts, src/services/metrics.ts
=> refactor: uploadSessions

src/providers/firefly/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1922
https://mask.atlassian.net/browse/fw-1929
=> fix: fw-1929 like status in thread

src/app/api/frame/route.ts, src/app/api/oembed/route.ts
=> refactor: log message

src/components/Profile/ProfileCard.tsx
=> feat: FW-1505

src/components/Posts/PostBody.tsx, src/components/Posts/PostHeader.tsx, src/components/Posts/ThreadBody.tsx
=> feat: FW-1948

src/components/SuggestedFollows/SuggestedFollowUsersList.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx, src/helpers/formatFarcasterProfileFromSuggestedFollow.ts, src/helpers/formatLensProfile.ts, src/providers/farcaster/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/Firefly.ts, src/providers/types/SocialMedia.ts, src/services/getFarcasterSuggestFollows.ts, src/services/getLensSuggestFollows.ts
=> feat: new suggest follow api

src/constants/error.ts, src/helpers/fetch.ts, src/providers/frame/Processor.ts
=> refactor: opt frame processor - error handling

src/providers/frame/Processor.ts
Closes [FW-1971](https://mask.atlassian.net/browse/FW-1971)
[FW-1971]: https://mask.atlassian.net/browse/FW-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove bot header

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/app/globals.css, src/components/Actions/Like.tsx, src/components/Actions/index.tsx, src/components/Posts/PostBody.tsx, src/helpers/getProfileBySession.ts, src/services/metrics.ts
=> refactor: mv to helper

src/store/useProfileStore.ts
=> fix: skip everything

src/services/bindFireflySession.ts, src/store/useProfileStore.ts
=> chore: update bind url

src/components/Search/SearchFilter.tsx, src/components/Search/SearchRecommendation.tsx
https://mask.atlassian.net/browse/fw-1980
=> fix(Search): fw-1980 encode keyword

src/components/Actions/Mirrors.tsx, src/components/Actions/PostStatistics.tsx, src/components/Actions/index.tsx
https://mask.atlassian.net/browse/FW-1975
https://mask.atlassian.net/browse/FW-1977
Closes FW-0000
=> fix: timeline actions ui

src/app/api/twitter/compose/route.ts, src/app/api/twitter/uploadMedia/route.ts, src/app/api/twitter/users/route.ts, src/helpers/getPlatformQueryKey.ts, src/helpers/getTwitterErrorMessage.ts, src/helpers/runInSafe.ts, src/helpers/withTwitterRequestErrorHandler.ts, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/services/getProfilesByIds.ts
https://mask.atlassian.net/browse/FW-1967
Closes FW-0000
=> fix: replace firefly mute system

src/app/(normal)/channel/pages/DetailPage.tsx, src/components/Channel/ChannelTabs.tsx, src/components/Channel/ChannelTrending.tsx, src/constants/enum.ts, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/lens/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/SocialMedia.ts
https://mask.atlassian.net/browse/FW-1643
Closes FW-0000
=> feat: channel trending posts

src/app/api/twitter/compose/route.ts, src/app/api/twitter/uploadMedia/route.ts, src/app/api/twitter/user/[userId]/route.ts
=> refactor: twitter api handing

src/helpers/account.ts
Closes [FW-1895](https://mask.atlassian.net/browse/FW-1895)
[FW-1895]: https://mask.atlassian.net/browse/FW-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove session from metrics

src/app/api/twitter/[tweetId]/comments/route.ts, src/app/api/twitter/[tweetId]/route.ts, src/app/api/twitter/bookmark/[tweetId]/route.ts, src/app/api/twitter/bookmarks/route.ts, src/app/api/twitter/compose/route.ts, src/app/api/twitter/follow/[targetId]/route.ts, src/app/api/twitter/homeTimeline/route.ts, src/app/api/twitter/like/[postId]/route.ts, src/app/api/twitter/me/route.ts, src/app/api/twitter/mute/[targetId]/route.ts, src/app/api/twitter/mute/route.ts, src/app/api/twitter/retweet/[postId]/route.ts, src/app/api/twitter/threadTweets/[tweetId]/route.ts, src/app/api/twitter/unfollow/[targetId]/route.ts, src/app/api/twitter/unlike/[postId]/route.ts, src/app/api/twitter/unretweet/[postId]/route.ts, src/app/api/twitter/uploadMedia/route.ts, src/app/api/twitter/user/[userId]/route.ts, src/app/api/twitter/userTimeline/[userId]/liked/route.ts, src/app/api/twitter/userTimeline/[userId]/replies/route.tsx, src/app/api/twitter/userTimeline/[userId]/route.ts, src/app/api/twitter/username/[username]/route.ts, src/app/api/twitter/users/route.ts, src/components/Frame/index.tsx, src/helpers/createTwitterErrorResponse.ts, src/helpers/getTwitterErrorMessage.ts
=> refactor: handling tw errors

src/components/Notification/ProfileLink.tsx, src/components/Profile/ProfileCard.tsx, src/components/Profile/ProfileTippy.tsx
=> refactor: ProfileCard

src/hooks/useTipsTokens.ts
https://mask.atlassian.net/browse/FW-1993
Closes FW-0000
=> fix: sort tips token by usd value

package.json, pnpm-lock.yaml, src/components/Compose/SchedulePostEntryButton.tsx, src/components/ScannableQRCode.tsx, src/modals/LoginModal/LensView.tsx
=> fix: use the original qrcode

src/components/Posts/PostLinks.tsx
=> refactor: reduce memo

src/components/Tips/SendTipsButton.tsx, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts, src/services/getAllPlatformProfileFromFirefly.ts, src/services/reportTokenTips.ts, src/services/uploadTokenTips.ts
=> feat: add upload tips records to server

src/components/Login/LoginFarcaster.tsx, src/components/Search/SearchRecommendation.tsx, src/components/TokenProfile/TokenDetail.tsx, src/modals/LoginModal/FarcasterView.tsx
https://mask.atlassian.net/browse/fw-1969
https://mask.atlassian.net/browse/fw-1998
https://mask.atlassian.net/browse/fw-1999
=> fix: login farcaster

src/app/api/twitter/userTimeline/[userId]/route.ts, src/components/Actions/index.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/ProfileAction.tsx, src/components/ProfileInList.tsx, src/components/Tips/SendTipsButton.tsx, src/constants/index.ts, src/providers/farcaster/SocialMedia.ts
Closes FW-1997 FW-1962 FW-1961
=> fix: some issues

src/constants/index.ts, src/helpers/getPollFrameUrl.ts, src/helpers/resolveEmbedMediaType.ts, src/settings/index.ts
https://mask.atlassian.net/browse/FW-1905
Closes FW-0000
=> feat: poll supports test env

src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginFirefly.tsx, src/hooks/useAbortController.ts
https://mask.atlassian.net/browse/fw-1996
https://mask.atlassian.net/browse/fw-2007
=> fix: login issues

src/components/Lexical/plugins/AtMentionsPlugin.tsx, src/hooks/useAbortController.ts, src/hooks/useDetectOverflow.ts
=> refactor: types

src/app/globals.css, src/components/Compose/DraftList.tsx, src/components/Compose/ScheduleTaskList.tsx, src/components/Markup/Markup.tsx, src/components/Markup/MarkupLink/index.tsx, src/constants/regexp.ts, src/helpers/isValidDomain.ts
Closes FW-1803 FW-1887 FW-1918
=> feat: lens handle link

src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal/LensView.tsx, src/modals/LoginModal/routes.tsx
=> fix: handle user discarding wallet connection

src/app/globals.css, src/components/Compose/ComposeAction.tsx, src/modals/ComposeModal.tsx
=> fix: rp bugfix

src/store/useProfileStore.ts
=> fix: persist tw session

src/services/bindFireflySession.ts, src/services/bindOrRestoreFireflySession.ts
=> fix: bind tw

src/services/restoreFireflySession.ts
=> fix: tw api 400

src/app/(normal)/pages/Profile.tsx
=> fix: FW-2008

src/components/Tips/SendTipsButton.tsx
=> fix: FW-2012

src/services/restoreFireflySession.ts
=> fix: api data

src/app/(normal)/pages/Home.tsx, src/constants/env.ts
=> feat: add openrank api switch

src/app/globals.css, src/components/Channel/SuggestedChannels.tsx, src/components/Posts/ContentTranslator.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx
https://mask.atlassian.net/browse/FW-1981
Closes FW-0000
=> fix: highlight color dark mode

src/app/api/twitter/[tweetId]/comments/route.ts
=> fix: FW-2003

src/app/(normal)/channel/pages/DetailPage.tsx, src/components/Channel/Info.tsx, src/constants/env.ts
=> fix: channel trending env control

src/components/Tips/SendTipsButton.tsx, src/hooks/useTipsContext.tsx, src/modals/TipsModal.tsx
=> fix: FW-2013

src/helpers/account.ts, src/services/bindFireflySession.ts, src/services/restoreFireflySession.ts
=> fix: remove ff metrics

src/store/useProfileStore.ts
=> fix: wrong condition

src/store/useProfileStore.ts
=> fix: restore ff session from tw server session

src/services/bindFireflySession.ts
=> fix: bind tw api

src/components/Channel/ChannelTrending.tsx
https://mask.atlassian.net/browse/FW-2015
Closes FW-0000
=> fix: channel trending pagination

src/app/(normal)/pages/Profile.tsx
https://mask.atlassian.net/browse/FW-1727
Closes FW-0000
=> fix: fixed wallet profile header

src/components/Actions/ArticleMore.tsx, src/components/NFTs/NFTMoreAction.tsx, src/components/Profile/WalletMoreAction.tsx, src/components/Tips/index.tsx
=> fix: update tips entry button ui

src/providers/firefly/SocialMedia.ts
=> fix: channel trending casts cursor fixed

src/components/Compose/ComposeAction.tsx, src/components/Login/LoginLens.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/fw-1813
https://mask.atlassian.net/browse/fw-1893
=> fix: fw-1893 set profile url as promote link

pnpm-lock.yaml
=> chore: remove web3-telemery

src/components/Login/LoginFarcaster.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-2016
=> fix: fw-2016 redirect to new connect if token doesn't exists

src/components/Posts/ThreadBody.tsx
https://mask.atlassian.net/browse/FW-2022
Closes FW-0000
=> fix: timeline cell ui

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Posts/PostBody.tsx
=> fix: hide post action when deleted the post

src/assets/radio-off.svg, src/assets/radio-on.svg, src/components/RadioButton.tsx, src/components/Search/SearchFilter.tsx, src/components/Search/SearchInput.tsx
https://mask.atlassian.net/browse/fw-2024
=> fix: fw-2024 adjust search ui

src/store/useDeveloperSettingsStore.ts
=> fix: sync red packet api root

src/components/Frame/index.tsx, src/components/Oembed/index.tsx, src/providers/blink/Loader.ts, src/types/blink.ts
=> fix: post links types error

src/components/Login/ProfileAvatarAdd.tsx, src/constants/enum.ts, src/helpers/createSessionStorage.ts, src/store/useProfileStore.ts
Closes [FW-2018](https://mask.atlassian.net/browse/FW-2018)
Closes [FW-2021](https://mask.atlassian.net/browse/FW-2021)
Closes [FW-2023](https://mask.atlassian.net/browse/FW-2023)
[FW-2021]: https://mask.atlassian.net/browse/FW-2021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2023]: https://mask.atlassian.net/browse/FW-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2018]: https://mask.atlassian.net/browse/FW-2018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: profile store

src/app/globals.css
=> chore: global css

src/components/RadioButton.tsx, src/components/TokenProfile/ContractList.tsx, src/components/TokenProfile/TokenDetail.tsx, src/components/TokenProfile/useChainInfo.ts, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/coingecko/chain-infos.ts, src/providers/types/Trending.ts
https://mask.atlassian.net/browse/fw-2024
https://mask.atlassian.net/browse/fw-2026
https://mask.atlassian.net/browse/fw-2029
=> fix: fw-2026 add kava, handle unknown chains

src/components/Posts/PostBody.tsx
https://mask.atlassian.net/browse/fw-2025
=> fix: fw-2025 render attachments that contain encrypted payload

src/components/NFTDetail/NFTOverflow.tsx, src/components/NFTDetail/NFTProperties.tsx, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2028
Closes FW-0000
=> fix: nft details ui

src/store/useDeveloperSettingsStore.ts
=> refactor: revert rp api

src/app/(normal)/pages/Profile.tsx, src/components/Login/LoginLens.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal/LensView.tsx
https://mask.atlassian.net/browse/FW-2032
=> fix: empty profiles list in LoginLens

src/app/(settings)/components/DisconnectButton.tsx, src/app/(settings)/settings/wallets/page.tsx, src/decorators/SetQueryDataForAddWallet.ts, src/decorators/SetQueryDataForDeleteWallet.ts, src/providers/firefly/SocialMedia.ts, src/services/disconnectFirefly.ts
https://mask.atlassian.net/browse/FW-2030
Closes FW-0000
=> fix: update query after wallet added

src/components/Blink/ActionContainer.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/blink/Loader.ts
=> fix: add message for successful transaction and fix the blink constructor

src/components/NotLoginFallback.tsx, src/components/SideBar/Menu.tsx, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> refactor: loading indicator

src/assets/radio-on.svg, src/modals/LoginModal/MainView.tsx
=> fix: hide login firefly qrcode on mobile

src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ConfirmFireflyModal.tsx
=> refactor: update texture

src/helpers/account.ts, src/store/useProfileStore.ts
=> refactor: filter out current adding account

src/components/LinkCloud.tsx, src/constants/env.ts, src/helpers/formatFarcasterPostFromFirefly.ts, src/modals/ConfirmFireflyModal.tsx
Closes FW-2036 FW-2031 FW-2027 
=> chore: hidden feedback entry

src/helpers/account.ts
=> fix: logout tw by override

src/components/Channel/ChannelTabs.tsx, src/components/Posts/ThreadBody.tsx
https://mask.atlassian.net/browse/FW-2037
Closes FW-0000
=> fix: channel trending ui

src/helpers/loadTwemojiUrls.ts
Closes [FW-1953](https://mask.atlassian.net/browse/FW-1953)
Learn more: https://github.com/twitter/twemoji/issues/580
=> fix: max cdn is down

src/components/Frame/index.tsx, src/helpers/resolveMintUrl.ts
Closes [FW-1936](https://mask.atlassian.net/browse/FW-1936)
=> fix: moshi frame

src/helpers/account.ts
=> chore: add logs

src/components/MoreActionMenu.tsx, src/components/TokenProfile/ContractList.tsx
=> refactor: not all more action menu requires user login

src/components/SideBar/ConnectWallet.tsx, src/helpers/resolve.ts, src/helpers/resolveValue.ts
=> refactor: resolve value

src/components/CustomElements.tsx, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/fw-2038
https://mask.atlassian.net/browse/fw-2039
=> fix: fw-2038 fw-2039 reopening modal breaks state fatally

src/components/Posts/VideoAsset.tsx
=> fix: append text mark for animated gif

src/components/Notification/NotificationItem.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: embed select

src/components/RadioButton.tsx
https://mask.atlassian.net/browse/fw-2040
=> fix: fw-2040 use button in RadioButton directly

src/components/Profile/Title.tsx
=> fix: optimize profile head ui

src/components/Blink/ActionContainer.tsx
=> fix: blink error message

src/assets/radio-off.svg, src/components/RadioButton.tsx
https://mask.atlassian.net/browse/fw-2024
=> fix: fw-2024 color of radio off button on dark mode

src/helpers/formatLensPost.ts, src/providers/lens/SocialMedia.ts
https://mask.atlassian.net/browse/fw-1050
=> fix: fw-1050 filter posts

src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginFirefly.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ConfirmFireflyModal.tsx
https://mask.atlassian.net/browse/fw-2042
https://mask.atlassian.net/browse/fw-2043
https://mask.atlassian.net/browse/fw-2044
=> fix: fw-2042 fw-2043 fw-2044 login issues

src/helpers/formatLensPost.ts
https://mask.atlassian.net/browse/fw-2048
=> fix: fw-2048 checking mute status of post author

src/app/(normal)/post/[id]/page.tsx, src/app/(normal)/profile/[id]/page.tsx, src/hooks/useCopyText.ts
=> fix: fix post and profile og metadata

src/helpers/account.ts
Closes [FW-2045](https://mask.atlassian.net/browse/FW-2045)
[FW-2045]: https://mask.atlassian.net/browse/FW-2045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: logout next-auth

src/helpers/account.ts, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes [FW-1895](https://mask.atlassian.net/browse/FW-1895)
[FW-1895]: https://mask.atlassian.net/browse/FW-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: no need to remove metrics when logout all

src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/twitter/SessionHolder.ts, src/services/getPostOGById.ts, src/services/getProfileById.ts, src/services/getProfileOGById.ts
=> fix: fix x provider in server side and handle og error

src/helpers/chars.ts, src/hooks/useSetEditorContent.ts, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/fw-2047
=> fix: fw-2047 cross post redpacket

src/app/api/s3/route.ts, src/components/Compose/Media.tsx, src/constants/index.ts, src/helpers/isValidFileType.ts
=> fix: extend allowed media types

src/components/Actions/PostStatistics.tsx, src/components/Frame/index.tsx, src/components/Posts/PostHeader.tsx, src/helpers/isSendFromFirefly.ts
https://mask.atlassian.net/browse/FW-2055
Closes FW-0000
=> fix: fw-2055

src/helpers/account.ts, src/store/useProfileStore.ts
=> refactor: add logs

src/components/Compose/DraftList.tsx, src/helpers/account.ts, src/modals/ConfirmFireflyModal.tsx, src/store/useProfileStore.ts
=> fix: confirm modal on-cancel

src/components/Compose/ComposeRouteRoot.tsx, src/components/Compose/ComposeRouter.tsx, src/components/Compose/ComposeUI.tsx, src/components/Gif/EmojiList.tsx, src/components/Gif/GifEntryButton.tsx, src/components/Gif/GifList.tsx, src/components/Gif/GifSelector.tsx, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/FW-2053
Closes FW-0000
=> fix: child route for gif selector

src/services/getPostLinks.ts
=> refactor: file ext in post links

src/components/Actions/PostStatistics.tsx, src/components/Posts/WithPreviewLink.tsx
=> chore: disable prefetch

src/components/Actions/PostStatistics.tsx, src/components/Actions/index.tsx, src/components/Posts/PostHeader.tsx, src/components/Posts/ThreadBody.tsx
=> chore: exact match detail page

src/components/Posts/PostLinks.tsx, src/hooks/useIsProfileMuted.ts
=> fix: set staleTime for a query with post request

src/components/Markup/MarkupLink/SymbolTag.tsx
=> refactor: skip token/ prefetch

src/components/Compose/ComposeContent.tsx
=> fix: twitter quote in compose content

src/modals/ComposeModal.tsx
=> refactor: close modal

src/components/Login/LoginFarcaster.tsx, src/components/SideBar/Menu.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal/FarcasterView.tsx, src/modals/LoginModal/MainView.tsx, src/modals/LoginModal/index.tsx
=> chore: restore login fc

src/components/Login/LoginLens.tsx, src/components/Popover.tsx, src/modals/LoginModal/RootView.tsx, src/modals/LoginModal/index.tsx
=> fix: adjust lens login ui on mobile

src/components/ErrorReportSnackbar.tsx, src/constants/error.ts, src/helpers/account.ts, src/helpers/fetch.ts, src/providers/frame/Processor.ts
=> fix: debug promise error

src/modals/LoginModal/FarcasterView.tsx
=> fix: the default sign type

src/helpers/enqueueMessage.tsx, src/helpers/getDetailedErrorMessage.ts, src/services/crossPost.ts
=> refactor: report crossPost error

src/components/Actions/PostStatistics.tsx, src/components/Actions/index.tsx, src/components/Posts/PostBody.tsx, src/components/Posts/PostHeader.tsx, src/components/Posts/SinglePost.tsx
https://mask.atlassian.net/browse/FW-2076
https://mask.atlassian.net/browse/FW-2077
Closes FW-0000
=> fix: ui for comment list

src/components/Profile/FollowButton.tsx, src/providers/firefly/SocialMedia.ts
https://mask.atlassian.net/browse/fw-2082
=> fix: fw-2082 followed by

src/components/Login/LoginFarcaster.tsx, src/components/Login/LoginLens.tsx, src/components/Popover.tsx, src/modals/LoginModal/index.tsx
https://mask.atlassian.net/browse/fw-2080
https://mask.atlassian.net/browse/FW-2086
=> fix: fw-2080 farcaster login on PC

src/app/(normal)/profile/[id]/[category]/layout.tsx, src/helpers/isSameProfile.ts
=> fix: fix `Mutuals` tab when loading profile

src/app/api/twitter/userTimeline/[userId]/replies/route.tsx
=> fix: twitter reply timeline api

src/decorators/SetQueryDataForDeleteWallet.ts, src/helpers/formatWalletConnection.ts, src/helpers/isSameConnectionAddress.ts
=> refactor: isSameConnectionAddress

src/components/Compose/ComposeSend.tsx, src/components/Compose/PostBy.tsx, src/components/Compose/PostByItem.tsx
=> fix: optimize compose ui

src/services/createLensSchedulePostPayload.ts
=> fix: query user setting before schedule post

src/app/(settings)/components/WalletGroup.tsx
=> fix: hidden disconnect for related wallet [6.0]

src/components/IfPathname.tsx
=> fix: ignore photo preview path change

src/app/(normal)/layout.tsx, src/components/IfPathname.tsx
=> fix: code style

src/services/createLensSchedulePostPayload.ts
=> fix: incorrect signless condition

src/components/IfPathname.tsx
=> fix: bugfix for pathname

src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/fw-2082
=> fix: fw-2082 follow back

package.json, pnpm-lock.yaml, src/components/Compose/Media.tsx, src/components/Gif/GifSelector.tsx, src/constants/index.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/firefly/SocialMedia.ts, src/providers/types/Firefly.ts, src/services/uploadToS3.ts
https://mask.atlassian.net/browse/fw-2089
=> fix: fw-2089 upload file to s3 directly

src/app/globals.css, src/components/Posts/Attachment.tsx, src/components/Posts/VideoAsset.tsx
=> fix: video attachment display

package.json
=> [Release] New release 6.0.0 (minor)

src/components/Compose/Media.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/postToTwitter.ts
=> feat: support x video

src/components/Providers.tsx
=> refactor: merge hooks

src/components/Compose/ComposeRouter.tsx
=> fix: open compose modal faster at the first time

package.json, pnpm-lock.yaml, src/configs/wagmiClient.ts, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> chore: upgrade viem & wagmi

package.json, src/components/Posts/Attachment.tsx
=> fix: bugfix for react-use

src/app/api/twitter/[tweetId]/comments/route.ts, src/app/api/twitter/[tweetId]/route.ts, src/app/api/twitter/bookmark/[tweetId]/route.ts, src/app/api/twitter/bookmarks/route.ts, src/app/api/twitter/compose/route.ts, src/app/api/twitter/follow/[targetId]/route.ts, src/app/api/twitter/home/route.ts, src/app/api/twitter/like/[postId]/route.ts, src/app/api/twitter/me/route.ts, src/app/api/twitter/mute/[targetId]/route.ts, src/app/api/twitter/mute/route.ts, src/app/api/twitter/retweet/[postId]/route.ts, src/app/api/twitter/threadTweets/[tweetId]/route.ts, src/app/api/twitter/unfollow/[targetId]/route.ts, src/app/api/twitter/unlike/[postId]/route.ts, src/app/api/twitter/unretweet/[postId]/route.ts, src/app/api/twitter/user/[userId]/route.ts, src/app/api/twitter/userTimeline/[userId]/liked/route.ts, src/app/api/twitter/userTimeline/[userId]/replies/route.tsx, src/app/api/twitter/userTimeline/[userId]/route.ts, src/app/api/twitter/username/[username]/route.ts, src/app/api/twitter/users/route.ts, src/components/Compose/Media.tsx, src/providers/twitter/SocialMedia.ts
=> refactor: x api

src/app/api/twitter/[tweetId]/comments/route.ts, src/app/api/twitter/[tweetId]/route.ts, src/app/api/twitter/bookmark/[tweetId]/route.ts, src/app/api/twitter/bookmarks/route.ts, src/app/api/twitter/compose/route.ts, src/app/api/twitter/follow/[targetId]/route.ts, src/app/api/twitter/home/route.ts, src/app/api/twitter/homeTimeline/route.ts, src/app/api/twitter/like/[postId]/route.ts, src/app/api/twitter/me/route.ts, src/app/api/twitter/mute/[targetId]/route.ts, src/app/api/twitter/mute/route.ts, src/app/api/twitter/retweet/[postId]/route.ts, src/app/api/twitter/threadTweets/[tweetId]/route.ts, src/app/api/twitter/unfollow/[targetId]/route.ts, src/app/api/twitter/unlike/[postId]/route.ts, src/app/api/twitter/unretweet/[postId]/route.ts, src/app/api/twitter/user/[userId]/route.ts, src/app/api/twitter/userTimeline/[userId]/liked/route.ts, src/app/api/twitter/userTimeline/[userId]/replies/route.tsx, src/app/api/twitter/userTimeline/[userId]/route.ts, src/app/api/twitter/username/[username]/route.ts, src/app/api/twitter/users/route.ts, src/components/Compose/Media.tsx, src/constants/index.ts, src/providers/twitter/SocialMedia.ts
=> fix: x api errors

public/.well-known/apple-app-site-association
=> chore: update association json

src/components/RadioButton.tsx
https://mask.atlassian.net/browse/FW-2073
Closes FW-0000
=> fix: radio button ui

src/components/Posts/VideoAsset.tsx
=> fix: add debug for video

pnpm-lock.yaml
Learn more https://github.com/DimensionDev/firefly.mask.social/security/dependabot/6
Closes FW-0000
=> chore: upgrade anchormore

pnpm-lock.yaml
https://github.com/DimensionDev/firefly.mask.social/security/dependabot/6
Closes FW-0000
=> chore: anchormore

package.json, pnpm-lock.yaml
https://github.com/DimensionDev/firefly.mask.social/security/dependabot/38
https://github.com/DimensionDev/firefly.mask.social/security/dependabot/18
Closes FW-0000
=> chore: up solana/web3.js

src/components/Posts/VideoAsset.tsx
=> fix: forward x video url only for gif

package.json, pnpm-lock.yaml
=> chore: up @crowdin/cli

package.json, pnpm-lock.yaml
=> chore: update override

package.json, public/.well-known/apple-app-site-association, src/app/api/twitter/[tweetId]/comments/route.ts, src/app/api/twitter/[tweetId]/route.ts, src/app/api/twitter/bookmark/[tweetId]/route.ts, src/app/api/twitter/bookmarks/route.ts, src/app/api/twitter/compose/route.ts, src/app/api/twitter/follow/[targetId]/route.ts, src/app/api/twitter/home/route.ts, src/app/api/twitter/like/[postId]/route.ts, src/app/api/twitter/me/route.ts, src/app/api/twitter/mute/[targetId]/route.ts, src/app/api/twitter/mute/route.ts, src/app/api/twitter/retweet/[postId]/route.ts, src/app/api/twitter/threadTweets/[tweetId]/route.ts, src/app/api/twitter/unfollow/[targetId]/route.ts, src/app/api/twitter/unlike/[postId]/route.ts, src/app/api/twitter/unretweet/[postId]/route.ts, src/app/api/twitter/user/[userId]/route.ts, src/app/api/twitter/userTimeline/[userId]/liked/route.ts, src/app/api/twitter/userTimeline/[userId]/replies/route.tsx, src/app/api/twitter/userTimeline/[userId]/route.ts, src/app/api/twitter/username/[username]/route.ts, src/app/api/twitter/users/route.ts, src/components/Compose/ComposeRouter.tsx, src/components/Compose/Media.tsx, src/constants/index.ts, src/providers/twitter/SocialMedia.ts
=> [Release] Hotfix 6.0.0 => 6.0.1 (patch)

public/.well-known/apple-app-site-association
=> chore: fix association

src/services/createTwitterSchedulePostPayload.ts
=> fix: schedule twitter image

vercel.json
https://mask.atlassian.net/browse/FW-2097
=> fix: redirects for legacy profile urls

src/components/Compose/Media.tsx, src/constants/index.ts, src/hooks/useCheckPostMedias.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/postToFarcaster.ts
https://mask.atlassian.net/browse/FW-1329
Closes FW-0000
=> feat: support upload video on farcaster

src/app/api/twitter/threadTweets/[tweetId]/route.ts
=> fix: x thread api

package.json, pnpm-lock.yaml, tests/helpers/formatPrice.tsx, vite.config.ts
=> fix: vitest type

src/services/createTwitterSchedulePostPayload.ts
=> fix: incorrect media key

src/services/getAllPlatformProfileFromFirefly.ts
=> fix: identity query

src/components/Actions/MuteAllProfile.tsx
=> chore: remove duplicate at

src/components/Actions/MuteAllProfile.tsx
=> fix: rename mute all confirmation text

src/constants/bowser.ts, src/constants/env.ts, src/helpers/bom.ts, src/helpers/createLensSDK.ts, src/helpers/getBrowserLanguage.ts, src/helpers/getCurrentSourceFromUrl.ts, src/helpers/getLocaleFromCookies.ts, src/helpers/getMeaningfulThemeMode.ts, src/helpers/getMobileDevice.ts, src/helpers/getUserLocale.ts, src/helpers/isLinkMatchingHost.ts, src/providers/twitter/SessionHolder.ts, src/services/addPostViews.ts, src/store/useProfileStore.ts
=> feat: add bom helpers

tests/helpers/getTimeLeft.ts
=> fix: unit test for helpers

src/services/addPostViews.ts, src/store/useLeafwatchPersistStore.ts
=> refactor: viewer id

src/components/Posts/ChannelAnchor.tsx, src/components/Posts/PostHeader.tsx
https://mask.atlassian.net/browse/FW-2102
Closes FW-0000
=> feat: post header ui

src/hooks/useIsProfileMuted.ts
https://mask.atlassian.net/browse/FW-2103
Closes FW-0000
=> fix: sync mute status for farcaster

src/providers/safary/Telemetry.ts
=> chore: add event id

src/decorators/SetQueryDataForBlockProfile.ts, src/hooks/useIsProfileMuted.ts
=> fix: update query for mute

src/helpers/getTimeLeft.ts, tests/helpers/getTimeLeft.ts
=> fix: unit test ci

src/app/globals.css, src/components/Actions/PostStatistics.tsx, src/components/Compose/ComposeUI.tsx, src/components/Gif/GifSelector.tsx, src/components/Posts/PostBody.tsx, src/components/Posts/PostHeader.tsx, src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/FW-2104
https://mask.atlassian.net/browse/FW-2106
https://mask.atlassian.net/browse/FW-2119
https://mask.atlassian.net/browse/FW-2118
Closes FW-0000
=> fix: post ui

src/components/Posts/VideoAsset.tsx
=> fix: forward url only for x gif

src/components/Compose/ChannelSearchPanel.tsx, src/components/Compose/ComposeUI.tsx, src/components/Compose/ReplyRestriction.tsx, src/components/Posts/ChannelAnchor.tsx, src/components/Posts/PostHeader.tsx
=> feat: optimize compose ui

src/app/(normal)/profile/[id]/[category]/layout.tsx, src/components/Profile/Title.tsx, src/components/ProfileInList.tsx
https://mask.atlassian.net/browse/fw-2109
https://mask.atlassian.net/browse/fw-2110
=> fix: fw-2109 sticky nav bar

src/decorators/SetQueryDataForAddWallet.ts
https://mask.atlassian.net/browse/FW-2078
Closes FW-0000
=> fix: avoid add wallet which already exists

src/components/Frame/index.tsx
=> refactor: clean up logs

src/constants/error.ts, src/helpers/fetch.ts, src/providers/frame/Processor.ts
=> refactor: track request method

src/helpers/formatTwitterMedia.ts, src/helpers/formatTwitterPost.ts
=> refactor: support m3u8 for x video

src/components/Posts/PostHeader.tsx, src/decorators/SetQueryDataForBlockProfile.ts
=> fix: post header ui

src/app/(developers)/components/ToolkitList.tsx, src/app/(developers)/developers/general/layout.tsx, src/app/(developers)/developers/general/page.tsx, src/app/(developers)/developers/page.tsx, src/components/LinkCloud.tsx, src/decorators/SetQueryDataForBlockProfile.ts, src/helpers/resolveSource.ts
=> refactor: settings => general

src/helpers/formatTwitterMedia.ts, src/helpers/resolveSource.ts
**The m3u8 link is not stable enugh. So we deprecate this**
Closes FW-0000
=> fix: deprecate m3u8 on x

src/components/Oembed/index.tsx, src/helpers/createSiteMetadata.ts, src/helpers/formatTwitterPost.ts, src/helpers/resolveSource.ts
=> fix: x issues and og issues

src/services/getPostOGById.ts
=> feat: post og default image

src/app/api/twitter/[tweetId]/route.ts
=> fix: retweet post lost some data

src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: translation for wallets

src/components/Profile/Info.tsx
=> fix: profile name overflow

src/components/LinkCloud.tsx
=> fix: community link

src/components/Posts/VideoAsset.tsx, src/components/Posts/VideoPoster.tsx
https://mask.atlassian.net/browse/FW-2132
Closes FW-0000
=> fix: farcaster video poster

src/app/(settings)/components/AddWalletButton.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2139
Closes FW-0000
=> feat: optimize tooltip when adding wallet

src/components/CollectionDetail/NFTList.tsx, src/components/Profile/POAPList.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
FW-1985
[https://github.com/DimensionDev/Maskbook/pull/11750](https://github.com/DimensionDev/Maskbook/pull/11750)
=> feat: add nft token count

src/components/Tips/TipsModalRouter.tsx
=> fix: remove delay

src/components/SuggestedFollows/SuggestedFollowsCard.tsx
=> fix: default top profile show more button

src/components/ChannelInList.tsx, src/components/Posts/PostHeader.tsx, src/components/Profile/ProfileCard.tsx, src/components/Profile/ProfileCell.tsx
=> fix: fix text overflow

src/components/Tips/TipsUI.tsx, src/constants/regexp.ts
https://mask.atlassian.net/browse/FW-2140
Closes FW-0000
=> fix: optimize token amount input

src/app/api/twitter/user/[userId]/route.ts
=> fix: fix twitter get user api error handle

src/components/Profile/Info.tsx
=> feat: adjust profile info to grid layout

src/assets/edit-profile.svg, src/components/Actions/ToggleMutedButton.tsx, src/components/Actions/ToggleMutedProfileButton.tsx, src/components/EditProfile/EditProfileButton.tsx, src/components/Profile/FollowButton.tsx, src/components/Profile/Info.tsx, src/components/Profile/ProfileAction.tsx
=> feat: profile button layout

src/services/uploadToTwitter.ts
https://mask.atlassian.net/browse/FW-2128
Closes FW-0000
=> fix: form data boundary on uploading

src/components/Compose/DraftList.tsx, src/components/Compose/ScheduleTaskList.tsx, src/components/Markup/BioMarkup.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> chore: failed draft post title

src/components/Compose/DraftList.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> chore: typo

next.config.js, src/app/(developers)/developers/upload/layout.tsx, src/app/(developers)/developers/upload/page.tsx, src/app/(normal)/layout.tsx, src/app/globals.css, src/components/Advertisement.tsx, src/constants/enum.ts, src/constants/index.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/uploadToS3.ts, src/types/advertisement.ts
=> feat: advertisement swiper

src/providers/lens/SocialMedia.ts
=> fix: add missing cursor

src/constants/enum.ts, src/helpers/memoizeWithRedis.ts
=> refactor: redis ttl

src/components/CollectionDetail/NFTList.tsx, src/providers/simplehash/WalletProfile.ts
=> chore: add skip score check option

src/components/Login/ProfileInList.tsx, src/components/ProfileName.tsx
https://mask.atlassian.net/browse/fw-2160
=> fix: fw-2160 name overflow in lens

src/components/Posts/ActionType.tsx, src/components/Profile/Info.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: text overflow

cspell.json, src/components/AsideTitle.tsx, src/components/Channel/SuggestedChannels.tsx, src/components/SuggestedFollows/ProfileSlide.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx, src/decorators/SetQueryDataForBlockProfile.ts, src/decorators/SetQueryDataForFollowProfile.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> feat: suggest profiles

next.config.js, src/components/Compose/Media.tsx, src/constants/index.ts, src/helpers/getCurrentPostVideoLimits.ts
https://mask.atlassian.net/browse/FW-2128
Closes FW-0000
=> fix: video max size limits

src/components/Profile/MutedProfileItem.tsx, src/providers/firefly/SocialMedia.ts
https://mask.atlassian.net/browse/FW-2093
Closes FW-0000
=> feat: replace mute list interface

src/components/Tips/TokenSelector.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2154
Closes FW-0000
=> feat: toggle button for token list

src/constants/error.ts, src/helpers/fetch.ts, src/providers/frame/Processor.ts
=> refactor: avoid truncation

src/app/api/avatar/route.ts, src/app/api/frame/route.ts, src/app/api/oembed/route.ts, src/app/api/thread/route.ts
=> refactor: response with error

src/app/api/firefly/metrics/route.ts
=> fix: metric schema

src/components/Profile/FollowersLink.tsx, src/components/Profile/ProfileCard.tsx, src/components/SuggestedFollows/ProfileSlide.tsx
=> refactor: followers link

src/app/(settings)/components/AccountCard.tsx, src/app/(settings)/components/DocumentCard.tsx, src/app/(settings)/components/LinkCard.tsx, src/app/(settings)/components/WalletItem.tsx, src/app/(settings)/components/waitForDisconnectConfirmation.tsx, src/app/(settings)/components/waitForSelectReportReason.tsx, src/components/Frame/Card.tsx, src/components/Login/LoginLens.tsx, src/components/SuggestedFollows/ProfileSlide.tsx, tailwind.config.cjs
=> refactor: box shadow

package.json, pnpm-lock.yaml, scripts/setup-vercel.sh, src/app/api/firefly/metrics/route.ts, src/components/CollectionDetail/NFTList.tsx, src/components/Compose/DraftList.tsx, src/components/Compose/ScheduleTaskList.tsx, src/components/LinkCloud.tsx, src/components/Markup/BioMarkup.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx, src/components/Tips/TipsUI.tsx, src/constants/regexp.ts, src/hooks/useNFTDetail.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/providers/lens/SocialMedia.ts, src/providers/simplehash/WalletProfile.ts
=> [Release] Hotfix 6.0.2 => 6.0.3 (patch)

src/components/ActionButton.tsx, src/components/ChainBoundary.tsx, src/components/ChainGuardButton.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/CollectArticleModal.tsx
=> refactor: <ChainGuardButton />

src/app/globals.css, src/components/Profile/Info.tsx
=> fix: word break in profile page

src/components/Tips/TipsModalHeader.tsx
https://mask.atlassian.net/browse/FW-2171
Closes FW-0000
=> fix: tips title overflow

src/app/api/auth/[...nextauth]/options.ts
=> feat: twitter auth scope

src/app/api/auth/[...nextauth]/options.ts
=> fix: remove twitter auth scope

src/constants/index.ts
=> feat: og title

src/constants/index.ts, src/modals/CollectArticleModal.tsx
=> fix: incorrect fee in polygon when mint article

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Actions/PostStatistics.tsx, src/components/Actions/index.tsx, src/components/Posts/ActionType.tsx, src/components/Posts/PostHeader.tsx, src/components/Posts/SinglePost.tsx, src/components/Posts/ThreadBody.tsx
https://mask.atlassian.net/browse/FW-2108
Closes FW-0000
=> fix: post thread ui

src/components/Login/ProfileAvatarAdd.tsx, src/components/RelatedSourceIcon.tsx
https://mask.atlassian.net/browse/FW-2145
Closes FW-0000
=> fix: replace x icon in wallet profile

src/components/Article/ArticleActions.tsx, src/components/Article/ArticleCollect.tsx, src/modals/CollectArticleModal.tsx, src/providers/paragraph/Processor.ts
=> fix: article collect in mobile mode

src/app/globals.css, src/components/Posts/Attachment.tsx, src/components/Posts/PostBody.tsx
=> feat: post attachment layout

src/providers/paragraph/Processor.ts
=> fix: missing owner address for article

src/components/Advertisement.tsx, src/components/AsideTitle.tsx, src/components/Channel/SuggestedChannels.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx
https://mask.atlassian.net/browse/FW-2181
https://mask.atlassian.net/browse/FW-2183
https://mask.atlassian.net/browse/FW-2184
Closes FW-0000
=> feat: optimize ad swiper ux

src/helpers/createDummyProfile.ts, src/providers/base/SessionFactory.ts, src/providers/firefly/Session.ts, src/providers/firefly/createAccountByGrantPermission.ts, src/providers/firefly/createAccountBySignMessage.ts, src/providers/types/Firefly.ts
Closes [FW-2153](https://mask.atlassian.net/browse/FW-2153)
[FW-2153]: https://mask.atlassian.net/browse/FW-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: impl createAccountBySignMessage

src/providers/firefly/Article.ts, src/providers/mirror/index.ts
=> refactor: article providers

src/components/Login/LoginFarcaster.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> chore: update reconnect description

src/components/Article/ArticleCollect.tsx, src/providers/firefly/Article.ts, src/providers/mirror/index.ts, src/providers/paragraph/index.tsx, src/providers/types/Article.ts
=> refactor: article naming

src/helpers/filterNotificationsByProfileId.ts, src/providers/firefly/SocialMedia.ts, src/providers/lens/SocialMedia.ts
=> feat: filter lens muted/blocked notifications

src/components/Article/ArticleActions.tsx, src/constants/regexp.ts, src/modals/EnableSignlessModal.tsx, src/providers/paragraph/index.tsx
Closes FW-2177 FW-2196 FW-2197 FW-2198
=> chore: email regexp

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/Actions/PostStatistics.tsx, src/components/Actions/index.tsx, src/components/Posts/ThreadBody.tsx
https://mask.atlassian.net/browse/FW-2185
Closes FW-0000
=> fix: optimize post thread ui

src/app/(normal)/post/[id]/page.tsx, src/app/(normal)/profile/pages/DetailPage.tsx, src/components/LoginRequiredGuard.tsx
=> refactor: twitter login

src/components/Channel/SuggestedChannels.tsx, src/components/SuggestedFollows/SuggestedFollowUsersList.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx, src/services/getSuggestedFollows.ts
https://mask.atlassian.net/browse/FW-2189
https://mask.atlassian.net/browse/FW-2193
Closes FW-0000
=> fix: suggest followers cursor

src/app/(normal)/pages/Profile.tsx, src/app/(normal)/post/[id]/page.tsx, src/app/(normal)/profile/page.tsx, src/app/(normal)/profile/pages/DetailPage.tsx, src/components/LoginRequiredGuard.tsx, src/components/NotLoginFallback.tsx, src/components/RequireLogin.tsx
=> fix: twitter profile page or post page must login

src/app/(normal)/post/[id]/page.tsx, src/app/(normal)/profile/page.tsx, src/app/(normal)/profile/pages/DetailPage.tsx, src/components/Article/SingleArticle.tsx, src/components/LoginRequiredGuard.tsx, src/components/NFTs/NFTFeedBody.tsx
=> fix: adjust ui

src/providers/og/readers/iframe.ts
https://mask.atlassian.net/browse/FW-2188
Closes FW-0000
=> fix: tiktok video link regexp

package.json, src/app/not-found.tsx, src/components/LinkCloud.tsx
=> [Release] Hotfix 6.0.4 => 6.0.5 (patch)

src/constants/regexp.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/createLensSchedulePostPayload.ts
=> chore: enable momoka tips

src/components/Article/ArticleActions.tsx, src/components/Comments/CommentsFooter.tsx, src/components/Comments/index.tsx, src/components/HideComments.tsx, src/providers/farcaster/SocialMedia.ts, src/providers/firefly/SocialMedia.ts, src/providers/hubble/SocialMedia.ts, src/providers/neynar/SocialMedia.ts, src/providers/twitter/SocialMedia.ts, src/providers/types/SocialMedia.ts, src/providers/warpcast/SocialMedia.ts
=> feat: farcaster hidden comments

src/components/Posts/PostBody.tsx, src/services/createFarcasterSchedulePostPayload.ts
=> fix: schedule video post on farcaster

src/app/(normal)/bookmarks/ArticleBookmarkList.tsx, src/app/(normal)/bookmarks/BookmarkList.tsx, src/app/(normal)/notifications/page.tsx, src/components/Article/FollowingArticleList.tsx, src/components/NFTs/FollowingNFTList.tsx
=> fix: refresh list when switch account

src/components/Tips/TipSuccess.tsx, src/modals/TipsModal.tsx
https://mask.atlassian.net/browse/FW-2205
https://mask.atlassian.net/browse/FW-2206
Closes FW-0000
=> fix: share post after tips

src/components/Posts/ImageAsset.tsx
https://mask.atlassian.net/browse/FW-2203
Closes FW-0000
=> fix: image max height

src/components/SuggestedFollows/SuggestedFollowUsersList.tsx, src/components/SuggestedFollows/SuggestedFollowsCard.tsx, src/services/getSuggestedFollows.ts
https://mask.atlassian.net/browse/FW-2193
Closes FW-0000
=> fix: recall suggest profiles on need

src/components/Compose/Media.tsx, src/components/Gif/GifSelector.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
=> fix: indicate file size in error message

src/components/SuggestedFollows/SuggestedFollowsCard.tsx
https://mask.atlassian.net/browse/FW-2182
Closes FW-0000
=> fix: rerender swiper when parent toggle show

src/app/(developers)/developers/general/page.tsx, src/components/Login/LoginButton.tsx, src/helpers/account.ts, src/modals/LoginModal/MainView.tsx
Closes [FW-2129](https://mask.atlassian.net/browse/FW-2129)
[FW-2129]: https://mask.atlassian.net/browse/FW-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: confirm to restore accounts in the middle of the login process

src/components/DatePicker.tsx
https://mask.atlassian.net/browse/FW-2211
Closes FW-0000
=> fix: close date picker

src/components/Compose/Media.tsx, src/components/Gif/GifSelector.tsx, src/constants/index.ts, src/helpers/getPostFileSizeLimit.ts
https://mask.atlassian.net/browse/FW-2212
Closes FW-0000
=> feat: post file size limit

src/components/Posts/Attachment.tsx
=> fix: quote attachment width

src/components/Image.tsx
=> feat: loading status for image

src/app/(normal)/post/[id]/pages/DetailPage.tsx, src/components/HideComments.tsx
=> fix: comments loading status

src/app/api/firefly/metrics/route.ts, src/components/Login/LoginFarcaster.tsx, src/helpers/ed25519.ts, src/helpers/encodeMessageData.ts, src/services/reportFarcasterSigner.ts, src/services/validateFarcasterSignerKey.ts
Closes [FW-2232](https://mask.atlassian.net/browse/FW-2232)
[FW-2232]: https://mask.atlassian.net/browse/FW-2232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add reportFarcasterSigner

src/components/Compose/Media.tsx, src/constants/index.ts
https://mask.atlassian.net/browse/FW-2227
https://mask.atlassian.net/browse/FW-2228
Closes FW-0000
=> fix: file size limit for x

src/app/(settings)/settings/layout.tsx
=> fix: setting layout

src/components/Posts/ThreadBody.tsx
https://mask.atlassian.net/browse/fw-2225
=> fix: fw-2225 checking if is the same post

package.json, pnpm-lock.yaml
=> chore: upgrade lens sdk

src/components/Article/ArticleCollect.tsx, src/components/Article/ArticleShare.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
Closes FW-2194 FW-2244 FW-2245 FW-2246
=> feat: collect not found status

src/app/api/twitter/uploadMedia/chunk/append/route.ts, src/app/api/twitter/uploadMedia/chunk/init/route.ts, src/app/api/twitter/uploadMedia/chunk/route.ts, src/components/Compose/Media.tsx, src/components/Gif/GifSelector.tsx, src/constants/enum.ts, src/constants/index.ts, src/helpers/getPostFileSizeLimit.ts, src/services/uploadToTwitter.ts, src/services/uploadToTwitterWithChunks.ts, src/types/twitter.ts
=> fix: fragment upload on x

src/components/Profile/POAPList.tsx
=> fix: nft list count tag bg

src/components/Tips/TipSuccess.tsx, src/components/Tips/TipsUI.tsx, src/modals/TipsModal.tsx
https://mask.atlassian.net/browse/FW-2254
https://mask.atlassian.net/browse/FW-2255
Closes FW-0000
=> fix: share tips content

src/app/api/twitter/uploadMedia/chunk/append/route.ts, src/constants/enum.ts, src/constants/index.ts, src/services/uploadToTwitterWithChunks.ts
=> fix: file mime type enum

src/helpers/isSameSession.ts, src/providers/firefly/createAccountByGrantPermission.ts, src/providers/types/Firefly.ts
Closes [FW-2167](https://mask.atlassian.net/browse/FW-2167)
[FW-2167]: https://mask.atlassian.net/browse/FW-2167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: comparing ff sessions

src/components/Login/LoginFarcaster.tsx, src/services/reportFarcasterSigner.ts
=> fix: report fc session

src/app/globals.css, src/components/Actions/Collect.tsx, src/components/Notification/NotificationItem.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2224
Closes FW-0000
=> fix: replace lens acted

src/components/Actions/MuteWalletButton.tsx, src/components/Profile/MuteWalletButton.tsx, src/components/Profile/WatchButton.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2252
Closes FW-0000
=> fix: confirm wallet mute status

src/components/Actions/PostStatistics.tsx, src/components/Poll/FramePoll.tsx, src/components/Poll/PollCard.tsx, src/components/Poll/VoteResult.tsx, src/components/Tips/TipSuccess.tsx, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2247
https://mask.atlassian.net/browse/FW-2248
https://mask.atlassian.net/browse/FW-2206
Closes FW-0000
=> fix: show poll votes in post action

src/components/ClickableArea.tsx, src/components/Markup/MarkupLink/Hashtag.tsx
https://mask.atlassian.net/browse/FW-2239
Closes FW-0000
=> fix: disable hashtag in twitter

src/modals/ComposeModal.tsx, src/store/useComposeStore.ts
=> feat: adjust red-packet image order in compose

src/app/(settings)/components/ReportButton.tsx, src/providers/firefly/SocialMedia.ts, src/services/disconnectFirefly.ts
https://mask.atlassian.net/browse/FW-2241
https://mask.atlassian.net/browse/FW-2243
Closes FW-0000
=> fix: disconnect wallet only when no related social profile

src/app/api/twitter/uploadMedia/chunk/init/route.ts
https://mask.atlassian.net/browse/FW-2128
Closes FW-0000
=> fix: use string id for x media id

src/components/Compose/Media.tsx, src/components/EditProfile/EditProfileAvatarEditor.tsx, src/helpers/createSiteMetadata.ts, src/helpers/fetchImageAsPNG.ts, src/helpers/formatTwitterMedia.ts, src/helpers/resolveMediaObjectUrl.ts, src/hooks/useCheckPostMedias.ts, src/modals/ComposeModal.tsx, src/services/steganography.ts, src/services/uploadToIPFS.ts
https://mask.atlassian.net/browse/FW-2242
Closes FW-0000
=> fix: size limit for gif

src/components/ErrorReportSnackbar.tsx
https://mask.atlassian.net/browse/fw-2262
=> fix: fw-2262 eror toast text overflow

src/components/Login/LoginStatusBar.tsx, src/components/Login/ProfileAvatarAdd.tsx, src/helpers/account.ts, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal/MainView.tsx
Closes [FW-2213](https://mask.atlassian.net/browse/FW-2213)
Closes [FW-2214](https://mask.atlassian.net/browse/FW-2214)
[FW-2213]: https://mask.atlassian.net/browse/FW-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2214]: https://mask.atlassian.net/browse/FW-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: restore accounts

src/components/Posts/PostBody.tsx, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2264
Closes FW-0000
=> fix: increase frame poll rendering priority

src/assets/radio.yes.svg, src/components/Compose/ChannelSearchPanel.tsx, src/components/Compose/ComposeActions/ChannelAction.tsx, src/components/Compose/ComposeActions/MediaAction.tsx, src/components/Compose/ComposeActions/PlatformAction.tsx, src/components/Compose/ComposeActions/ReplyRestrictionAction.tsx, src/components/Compose/ComposeActions/index.tsx, src/components/Compose/ComposeActions/types.ts, src/components/Compose/ComposeUI.tsx, src/components/Compose/Media.tsx, src/components/Compose/PostBy.tsx, src/components/Compose/PostByItem.tsx, src/components/Compose/ReplyRestriction.tsx, src/components/Compose/UploadDropArea.tsx, src/components/Compose/useAddImages.ts, src/components/Compose/useAddVideo.ts, src/components/ComposeButton/ComposeButtonForMobile.tsx, src/components/Modal.tsx, src/components/Search/SearchFilter.tsx, src/components/Search/SearchInput.tsx, src/constants/index.ts, src/helpers/isImageFileType.ts, src/helpers/isVideoFileType.ts, src/modals/ConfirmModal.tsx, src/modals/LoginModal/MainView.tsx
https://mask.atlassian.net/browse/fw-1646
=> feat: fw-1646 refine compose ui/ux

src/components/Posts/PostBody.tsx, src/components/Posts/SinglePost.tsx
=> fix: don't show post from muted user

src/components/Posts/SinglePost.tsx
=> feat: show post action in profile page when muted

src/helpers/generateVideoCover.ts, src/helpers/uploadVideoCover.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/createLensSchedulePostPayload.ts, src/services/postToLens.ts
=> feat: generate video cover

src/providers/lens/updateSignless.ts
=> fix: wait until update signless complete

src/services/metrics.ts
=> chore: replace time compare func

src/providers/lens/updateSignless.ts
=> fix: add delay time for signless status change

src/constants/index.ts, src/helpers/chars.ts, src/helpers/formatTwitterProfile.ts
=> feat: twitter premium max post content length

src/components/Search/SearchInput.tsx
=> fix: do not autofoucs search input

package.json, pnpm-lock.yaml, src/app/api/firefly/metrics/route.ts, src/components/Compose/Media.tsx, src/components/DatePicker.tsx, src/components/Gif/GifSelector.tsx, src/components/Login/LoginFarcaster.tsx, src/constants/index.ts, src/helpers/account.ts, src/helpers/ed25519.ts, src/helpers/encodeMessageData.ts, src/helpers/getPostFileSizeLimit.ts, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/ComposeModal.tsx, src/providers/lens/SocialMedia.ts, src/providers/lens/createAccountForProfileId.ts, src/services/crossSchedulePost.tsx, src/services/crossSchedulePostThread.ts, src/services/metrics.ts, src/services/reportFarcasterSigner.ts, src/services/validateFarcasterSignerKey.ts, src/store/useComposeStore.ts, src/store/useProfileStore.ts
=> [Release] Hotfix 6.0.5 => 6.0.6 (patch)

src/providers/lens/SocialMedia.ts
=> fix: switch chain before follow

src/app/api/twitter/uploadMedia/chunk/append/route.ts, src/constants/index.ts, src/services/uploadToTwitterWithChunks.ts
=> fix: use buffer to upload

src/components/Channel/SuggestedChannels.tsx, src/decorators/SetQueryDataForBlockChannel.ts
https://mask.atlassian.net/browse/FW-1094
Closes FW-0000
=> fix: filter suggest channels

src/components/Posts/SinglePost.tsx
=> fix: show post action in detail page

src/components/Tips/TipSuccess.tsx, src/helpers/chars.ts
https://mask.atlassian.net/browse/FW-2260
Closes FW-0000
=> fix: use default content when mention mismatch

globals.d.ts, next.config.js, pnpm-lock.yaml, src/app/api/og/post/[source]/[postId]/image/route.tsx, src/helpers/withRequestErrorHandler.ts, src/services/getPostOGById.ts
=> feat: post og image

src/components/ShowMoreComments.tsx, src/modals/ComposeModal.tsx
=> fix: duplicate avatar

src/components/Posts/Video.tsx
=> fix: video clickable area in post timeline

src/decorators/SetQueryDataForBlockProfile.ts
=> fix: reload notifications api after mute user in notifications page

src/configs/wagmiClient.ts
=> refactor: disable feats

src/app/api/blink/proxy/route.tsx, src/app/api/og/post/[source]/[postId]/image/route.tsx, src/components/Blink/ActionContainer.tsx, src/components/Blink/index.tsx, src/components/Posts/PostLinks.tsx, src/constants/index.ts, src/services/getPostOGById.ts
=> fix: post og image path and twitter premium chars count

src/services/getProfileOGById.ts
=> feat: profile og description

src/services/uploadToTwitterWithChunks.ts
https://mask.atlassian.net/browse/FW-2273
Closes FW-0000
=> fix: wait upload only for big file on x

src/app/api/og/post/[source]/[postId]/image/route.tsx, src/components/Compose/ChannelSearchPanel.tsx, src/components/Compose/ComposeThreadContent.tsx
=> refactor: post og image

src/helpers/withRequestErrorHandler.ts
=> fix: request type error

src/components/Login/ProfileAvatarAdd.tsx, src/components/SideBar/ConnectWallet.tsx, src/components/SideBar/Menu.tsx, src/constants/enum.ts, src/helpers/createSessionStorage.ts, src/hooks/useAsyncStatus.ts, src/hooks/useProfileStore.ts, src/store/useGlobalStore.ts, src/store/useProfileStore.ts
=> refactor: global store

src/components/Actions/Comment.tsx, src/components/Actions/Like.tsx, src/components/Actions/Mirrors.tsx, src/components/Login/LoginStatusBar.tsx, src/components/NotLoginFallback.tsx
=> refactor: remove wallet connection for lens

src/components/Actions/MuteWalletButton.tsx, src/components/Login/LoginStatusBar.tsx, src/components/Login/ProfileSettings.tsx, src/components/MoreActionMenu.tsx, src/components/Poll/VoteButton.tsx, src/components/Profile/WatchButton.tsx, src/helpers/resolveSource.ts, src/modals/LoginModal/MainView.tsx, src/modals/LoginModal/index.tsx
Closes [FW-2129](https://mask.atlassian.net/browse/FW-2129)
[FW-2129]: https://mask.atlassian.net/browse/FW-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: remove restore confirmation

src/components/Profile/ProfileAction.tsx
=> fix: missing return

src/constants/enum.ts, src/helpers/getFrameClientProtocol.ts, src/providers/frame/Processor.ts, src/services/getPostLinks.ts, src/types/frame.ts
=> fix: display frame with platform

src/providers/firefly/SocialMedia.ts
https://mask.atlassian.net/browse/FW-2297
Closes FW-0000
=> fix: fetch trending channels with token

src/constants/index.ts, src/services/uploadToS3.ts
=> feat: part upload to s3

src/components/Login/LoginFarcaster.tsx, src/locales/en/messages.po, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/pseudo/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/services/getPostLinks.ts
=> refactor: login modal ux

src/services/uploadToTwitterWithChunks.ts
https://mask.atlassian.net/browse/FW-2289
Closes FW-0000
=> fix: parallel upload on x

src/app/globals.css, src/components/EditProfile/EditProfileForm.tsx, src/components/Form/FormTextarea.tsx, src/components/Notification/NotificationItem.tsx, src/components/Notification/ProfileLink.tsx, src/helpers/inputClassName.ts, src/hooks/usePriceLineChart.ts, tailwind.config.cjs
Closes FW-2296 FW-2295 FW-2294
=> fix: fix ui

src/components/EditProfile/EditProfileForm.tsx
=> feat: remove scrollbar in edit profile textarea

src/hooks/useAsyncStatus.ts, src/locales/ja/messages.po, src/locales/ko/messages.po, src/locales/zh-Hans/messages.po, src/locales/zh-Hant/messages.po, src/modals/LoginModal/index.tsx
=> refactor: revert changes

src/helpers/chars.ts
=> feat: adjust max chars size

src/components/Compose/ComposeImages.tsx, src/components/Compose/ComposeSend.tsx, src/components/Compose/Media.tsx, src/components/Lexical/nodes/MentionsNode.tsx, src/components/Posts/Attachment.tsx
https://mask.atlassian.net/browse/fw-2290
https://mask.atlassian.net/browse/fw-2292
=> fix: fw-2290 adjust accept types for image

src/components/Compose/Editor.tsx, src/constants/regexp.ts
=> fix: twitter handle containing pure numbers
