DimensionDev/firefly.mask.social

- src/components/ErrorReportSnackbar.tsx
> fix: encode error report url params

- src/app/api/blink/proxy/route.tsx
- src/providers/types/Blink.ts
- src/services/getPostLinks.ts
> fix: blink single button href

- src/components/Login/LoginStatusBar.tsx
> fix: remove laoding of ProfileAvatarAdd

- src/app/(normal)/profile/[id]/[category]/layout.tsx
> fix: mutuals title layout

- src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/fw-2315
> fix: fw-2315 hide close button for mobile only

- package.json
- pnpm-lock.yaml
- src/app/api/blink/proxy/route.tsx
- src/hooks/useActionAdapter.ts
- src/services/getPostLinks.ts
> feat: evm blink

- src/modals/ComposeModal.tsx
https://mask.atlassian.net/browse/fw-2315
> fix: fw-2315 checking max instead

- src/modals/ConfirmModal.tsx
> fix: close on close button

- src/app/(developers)/developers/blink/page.tsx
- src/app/(developers)/developers/frame/page.tsx
- src/app/(developers)/developers/og/page.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> refactor: remove dot

- src/components/Compose/ComposeUI.tsx
- src/components/Compose/UploadDropArea.tsx
https://mask.atlassian.net/browse/fw-2319
> fix: fw-2319 drag-n-drop video to compose

- src/app/api/blink/proxy/image/route.ts
- src/app/api/og/post/[source]/[postId]/image/route.tsx
- src/app/api/twitter/article/[id]/image/route.ts
- src/components/Article/ArticleBody.tsx
- src/components/Article/SingleArticle.tsx
- src/components/Posts/PostBody.tsx
- src/helpers/createProxyImageResponse.ts
- src/helpers/formatTwitterPost.ts
- src/helpers/resolvePostArticleUrl.ts
- src/providers/types/SocialMedia.ts
- src/providers/warpcast/SocialMedia.ts
> feat: twitter post article

- src/components/Compose/ComposeSend.tsx
- src/services/crossPostThread.ts
- src/services/uploadAndConvertToM3u8.ts
> refactor: m3u8

- src/components/SideBar/Menu.tsx
- src/constants/env.ts
> feat: open android app

- src/modals/controls.ts
> fix: import path

- src/components/Article/ArticleLayout.tsx
- src/providers/mirror/index.ts
- src/providers/paragraph/index.tsx
> fix: bugfix for limo article

- src/app/(normal)/pages/Home.tsx
- src/components/Channel/ChannelTabs.tsx
- src/components/Profile/ProfileContentTabs.tsx
- src/components/Profile/WalletTabs.tsx
- src/hooks/useStateWithSearchParams.ts
> refactor: improve type

- src/components/Posts/PostBody.tsx
> fix: thread body show button in timeline

- csp.js
> fix: image csp

- src/helpers/formatFarcasterPostFromFirefly.ts
> feat: farcaster video poster

- src/app/(developers)/developers/layout.tsx
- src/app/(developers)/developers/page.tsx
- src/app/(normal)/bookmarks/layout.tsx
- src/app/(normal)/bookmarks/page.tsx
- src/components/NFTs/NFTFeedAction.tsx
- src/components/Tips/TokenSelector.tsx
- src/components/Tips/WalletSelector.tsx
> refactor: bookmarkets title

- src/app/(developers)/components/ToolkitList.tsx
- src/app/(developers)/developers/blink/layout.tsx
- src/app/(developers)/developers/blink/page.tsx
- src/app/(developers)/developers/frame/layout.tsx
- src/app/(developers)/developers/frame/page.tsx
- src/app/(developers)/developers/general/page.tsx
- src/app/(developers)/developers/og/page.tsx
- src/app/(developers)/developers/session/layout.tsx
- src/app/(developers)/developers/session/page.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> chore: add session validator

- src/components/LinkCloud.tsx
- src/constants/env.ts
> feat: developers entry switch

- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/LoginModal/LensView.tsx
Closes [FW-2344](https://mask.atlassian.net/browse/FW-2344)
Closes [FW-2204](https://mask.atlassian.net/browse/FW-2204)
[FW-2344]: https://mask.atlassian.net/browse/FW-2344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2204]: https://mask.atlassian.net/browse/FW-2204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: login lens view

- src/helpers/formatFarcasterPostFromFirefly.ts
https://mask.atlassian.net/browse/FW-2343
https://mask.atlassian.net/browse/FW-2345
Closes FW-0000
> fix: replace video poster

- src/constants/index.ts
- src/helpers/resolveEmbedMediaType.ts
https://mask.atlassian.net/browse/FW-2342
Closes FW-0000
> fix: replace poll frame domain

- src/components/SuggestedFollows/ProfileSlide.tsx
- src/components/SuggestedFollows/SuggestedFollowsCard.tsx
> feat: suggest profiles card ui

- src/components/Compose/ComposeSend.tsx
- src/helpers/resolveCreateSchedulePostPayload.ts
- src/services/createFarcasterSchedulePostPayload.ts
- src/services/createLensSchedulePostPayload.ts
- src/services/createTwitterSchedulePostPayload.ts
- src/services/crossSchedulePost.tsx
- src/services/crossSchedulePostThread.ts
https://mask.atlassian.net/browse/FW-2350
Closes FW-0000
> fix: support m3u8 on schdule post

- src/assets/css/limo.css
- src/components/Article/ArticleBody.tsx
- src/components/Article/ArticleLayout.tsx
- src/components/Article/SingleArticle.tsx
> fix: article style

- src/components/Posts/PostHeader.tsx
- src/components/SuggestedFollows/ProfileSlide.tsx
> fix: use handle for lens identity

- src/services/uploadAndConvertToM3u8.ts
> feat: no need to wait for convert

- pnpm-lock.yaml
- src/helpers/getProfileBySession.ts
- src/helpers/refreshLensSession.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: refresh token

- src/components/Actions/Mirrors.tsx
- src/decorators/SetQueryDataForDeletePost.ts
- src/decorators/SetQueryDataForMirrorPost.ts
- src/helpers/updateQueryForLensPosts.ts
- src/hooks/useMirror.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/lens/SocialMedia.ts
https://mask.atlassian.net/browse/FW-2216
Closes FW-0000
> feat: unmirror post on lens

- src/components/Posts/SinglePost.tsx
> fix: don't show muted post in timeline

- src/services/uploadAndConvertToM3u8.ts
> fix: wait for first chunk on converting

- src/services/uploadAndConvertToM3u8.ts
> fix: fixed video size on converting m3u8

- src/app/(normal)/notifications/page.tsx
- src/app/(normal)/profile/[id]/[category]/pages/FollowersList.tsx
- src/app/(normal)/profile/[id]/[category]/pages/FollowingList.tsx
- src/app/(normal)/profile/[id]/[category]/pages/MutualFollowersList.tsx
- src/app/globals.css
- src/components/Article/DiscoverArticleList.tsx
- src/components/Article/FollowingArticleList.tsx
- src/components/CollectionDetail/TopCollectors.tsx
- src/components/Markup/PostMarkup.tsx
- src/components/NFTs/DiscoverNFTList.tsx
- src/components/NFTs/FollowingNFTList.tsx
- src/components/NavigatorBar/NavigatorBarForMobile.tsx
- src/components/Posts/DiscoverPostList.tsx
- src/components/Posts/FollowingPostList.tsx
- src/components/Posts/ForYouPostList.tsx
- src/components/Posts/RecentPostList.tsx
- src/components/Profile/ArticleList.tsx
- src/components/Profile/POAPList.tsx
- src/components/SuggestedFollows/SuggestedFollowUsersList.tsx
> fix: bugfix for post display on safari

- src/helpers/getLensHandleFromMentionTitle.ts
- tests/helpers/getLensHandleFromMentionTitle.ts
> fix: bugfix for lens handle support

- src/services/uploadAndConvertToM3u8.ts
> fix: change args in converting m3u8

- .github/workflows/issue.yml
- src/services/createLensSchedulePostPayload.ts
- src/services/resolveIdentity.ts
- src/services/uploadToIPFS.ts
> chore: add action to decode issues

- src/providers/lens/SessionHolder.ts
- src/services/createLensSchedulePostPayload.ts
- src/services/resolveIdentity.ts
- src/services/uploadToIPFS.ts
> fix: remove assert session

- src/configs/wagmiClient.ts
> fix: add missing connectors

- src/configs/wagmiClient.ts
> fix: enable injected

- src/providers/twitter/SocialMedia.ts
> fix: fix twitter user timeline repeat post

- src/store/useProfileStore.ts
> fix: refresh current token session

- src/components/Article/ArticleBody.tsx
- src/components/Article/ArticleCollect.tsx
- src/components/ChainGuardButton.tsx
- src/components/Posts/PostLinks.tsx
- src/modals/CollectArticleModal.tsx
- src/providers/lens/SocialMedia.ts
- src/services/getPostLinks.ts
Closes FW-2374 FW-2375 FW-2376 FW-2380
> fix: bugfix for article action

- src/components/Notification/ProfileLink.tsx
> fix: remove default profile

- src/components/SideBar/Menu.tsx
> fix: sidebar menu match

- src/app/(normal)/@modal/(.)post/[source]/[id]/photos/[index]/page.tsx
- src/components/Posts/SinglePost.tsx
- src/helpers/getPostImageUrl.tsx
- src/helpers/isSocialSource.ts
- src/helpers/parsePostUrl.ts
- src/helpers/parseProfileUrl.ts
- src/middleware.ts
- vercel.json
> fix: post url and post photo preview

- src/helpers/parseProfileUrl.ts
- src/middleware.ts
> fix: parse profile url

- src/components/NFTs/NFTFeedBody.tsx
> fix: fix NFT feed body layout when switching

- src/helpers/getPollFrameUrl.ts
https://mask.atlassian.net/browse/FW-2267
Closes FW-0000
> fix: append profile handle on poll og

- src/app/(normal)/page.ts
- src/middleware.ts
> fix: root pathname

- src/components/Advertisement.tsx
> fix: add loading for advertisement

- src/components/Actions/Collect.tsx
- src/components/Posts/PostCollect.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/CollectPostModal.tsx
Closes FW-2386 FW-2387 FW-2388 FW-2390 FW-2391
> fix: bugfix for lens collect modal

- src/components/Actions/PostStatistics.tsx
- src/components/Actions/index.tsx
- src/components/ComposeButton/ComposeButtonForMobile.tsx
- src/components/Posts/ActionType.tsx
- src/components/Posts/PostHeader.tsx
- src/components/Posts/ThreadBody.tsx
- src/components/Posts/WithPreviewLink.tsx
- src/constants/enum.ts
- src/helpers/getPostUrl.ts
- src/helpers/resolvePostUrl.ts
- src/hooks/useCurrentVisitingPost.ts
> fix: replace url for post detail page

- src/components/Calendar/DatePicker.tsx
- src/components/Calendar/DatePickerTab.tsx
> refactor: adjust calendar font size

- src/components/Compose/ComposeThreadContent.tsx
- src/components/Compose/Placeholder.tsx
> fix: compose thread overflow

- package.json
- src/components/Compose/ComposeThreadContent.tsx
- src/components/Compose/Placeholder.tsx
- src/components/Notification/ProfileLink.tsx
> [Release] Hotfix 6.1.2 => 6.1.3 (patch)

- src/components/Advertisement.tsx
- src/components/SuggestedFollows/SuggestedFollowsCard.tsx
> fix: add skeleton for sidebar

- cspell.json
- src/app/(normal)/article/[id]/pages/DetailPage.tsx
- src/helpers/formatArticleFromFirefly.ts
- src/helpers/parseParagraphHtml.ts
- src/providers/paragraph/type.ts
- src/providers/types/Article.ts
- src/providers/types/Firefly.ts
> fix: bugfix for paragraph article

- src/components/Article/SingleArticle.tsx
- src/components/Article/SingleArticleHeader.tsx
- src/components/ChainGuardButton.tsx
- src/components/Posts/PostCollect.tsx
- src/hooks/useSuperFollow.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/CollectPostModal.tsx
Closes FW-2392 FW-2393 FW-2394 FW-2402 FW-2403 FW-2404 FW-2405 FW-2406 FW-2407 FW-2408
> fix: bugfix for lens collect

- src/helpers/createSiteMetadata.ts
> feat: add canonical tag

- src/components/Oembed/index.tsx
- src/helpers/getArticleDigest.ts
> fix: type errors (safeUnreachable)

- src/components/Compose/ChannelSearchPanel.tsx
- src/components/SuggestedFollows/SuggestedFollowsCard.tsx
> fix: ui for channel selector

- src/app/(normal)/profile/pages/ProfilePageLayout.tsx
- src/components/Profile/WalletInfo.tsx
- src/components/Profile/WalletProfileContentList.tsx
- src/components/RelatedSourceIcon.tsx
- src/helpers/formatFireflyProfilesFromWalletProfiles.ts
- src/helpers/getAddressType.ts
- src/providers/types/Firefly.ts
- src/services/getAllPlatformProfileFromFirefly.ts
> feat: solana address profile

- src/app/(settings)/settings/layout.tsx
> feat: sticky setting more mobile header

- src/app/(normal)/post/[source]/[id]/page.tsx
- src/app/(normal)/post/[source]/[id]/pages/DetailPage.tsx
- src/components/MoreActionMenu.tsx
> fix: twitter post detail page

- src/app/(normal)/profile/(profile)/[source]/[id]/page.ts
> fix: profile page redirect

- src/app/(normal)/article/[id]/pages/DetailPage.tsx
- src/components/Article/SingleArticleHeader.tsx
- src/components/Markup/PostMarkup.tsx
- src/components/Posts/Attachment.tsx
- src/components/Posts/PostBody.tsx
- src/components/Posts/PostCollect.tsx
- src/helpers/formatArticleFromFirefly.ts
- src/hooks/useNavigatorTitle.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes FW-2412 FW-2413 FW-2416 FW-2424 FW-2431 FW-2404
> fix: bugfix for article type

- src/components/Profile/FollowersLink.tsx
- src/components/Profile/ProfileCard.tsx
- src/components/TokenProfile/CommunityLink.tsx
- src/helpers/getChannelUrl.ts
- src/helpers/isEngagementType.ts
- src/helpers/parseEngagementUrl.ts
- src/middleware.ts
Closes FW-2435 FW-2436 FW-2437
> fix: seo issues

- src/app/(normal)/token/[symbol]/page.tsx
- src/constants/enum.ts
- src/helpers/getTokenPageOG.ts
> feat: token page og

- src/app/layout.tsx
> chore: update ga

- src/components/Posts/PostCollect.tsx
- src/components/Profile/ArticleList.tsx
- src/helpers/formatLensPost.ts
- src/hooks/useNavigatorTitle.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes FW-2337 FW-2412 FW-2439 FW-2440 FW-2441
> fix: post collect

- src/app/(developers)/components/NativeMethodButton.tsx
- src/app/(developers)/components/ToolkitList.tsx
- src/app/(developers)/components/WebMethodButton.tsx
- src/app/(developers)/developers/bridge/layout.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/app/(developers)/developers/layout.tsx
- src/components/ClickableArea.tsx
- src/components/ClickableButton.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/types/bridge.ts
> chore: impl bridge ui

- src/app/(settings)/components/MutedWallets.tsx
- src/components/WalletItem.tsx
- src/decorators/SetQueryDataForBlockWallet.ts
- src/helpers/createMetadataWalletProfile.ts
- src/helpers/formatAddress.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/firefly/SocialMedia.ts
- src/providers/types/Firefly.ts
- src/providers/types/SocialMedia.ts
- src/services/getWalletProfileByAddressOrEns.ts
https://mask.atlassian.net/browse/FW-2447
https://mask.atlassian.net/browse/FW-2448
https://mask.atlassian.net/browse/FW-2449
https://mask.atlassian.net/browse/FW-2450
Closes FW-0000
> fix: fetch wallet profile

- src/app/(developers)/components/MethodButton.tsx
- src/helpers/formatAddress.ts
- src/providers/firefly/Bridge.ts
- src/types/bridge.ts
> refactor: align with spec

- src/app/(developers)/developers/bridge/page.tsx
- src/app/(developers)/developers/general/page.tsx
- src/app/(settings)/components/Section.tsx
- src/providers/firefly/Bridge.ts
> fix: firefly bridge

- src/polyfills/localStorage.ts
> fix: polyfill ls

- src/polyfills/index.ts
> fix: ls polyfill

- src/helpers/createMetadataPostById.ts
> chore: post metadata title

- src/app/layout-body.tsx
- src/app/layout.tsx
> fix: delay layout body

- src/hooks/useMuteMenuList.ts
> fix: hide muted contents when no profile login

- src/polyfills/localStorage.ts
> fix: set ls

- src/configs/wagmiClient.ts
> feat: support scroll sdk

- src/constants/index.ts
https://mask.atlassian.net/browse/FW-2458
Closes FW-0000
> fix: filter solana on tips

- src/app/(developers)/developers/bridge/page.tsx
- src/types/bridge.ts
> chore: add back method

- src/providers/firefly/Bridge.ts
> fix: global variable

- src/app/(developers)/components/MethodButton.tsx
- src/providers/firefly/Bridge.ts
> fix: bridge messages

- src/app/(developers)/components/MethodButton.tsx
- src/app/(settings)/settings/more/layout.tsx
- src/app/(settings)/settings/mutes/[source]/[type]/layout.tsx
- src/app/(settings)/settings/mutes/layout.tsx
- src/helpers/createMetadataPostById.ts
- src/helpers/parseDiscoverUrl.ts
- src/helpers/parseOldSettingsUrl.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/middleware.ts
> chore: page title i18n

- src/app/(developers)/components/MethodButton.tsx
- src/providers/firefly/Bridge.ts
> refactor: remove no return

- src/app/(developers)/components/MethodButton.tsx
- src/providers/firefly/Bridge.ts
- src/types/bridge.ts
> fix: call params

- src/providers/firefly/Bridge.ts
> refactor: compatible with ios

- src/app/(developers)/components/MethodButton.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/types/bridge.ts
> refactor: align spec

- src/providers/firefly/Bridge.ts
> fix: call native method

- src/helpers/parseOldNotification.ts
- src/middleware.ts
> fix: notifications redirect

- src/components/Compose/Media.tsx
- src/helpers/parseOldSettingsUrl.ts
> chore: settings mutes

- src/constants/limitation.ts
- src/services/uploadToTwitter.ts
- src/services/uploadToTwitterWithChunks.ts
> feat: support amplify video for twitter

- src/components/Tips/SendTipsButton.tsx
https://mask.atlassian.net/browse/FW-2459
Closes FW-0000
> fix: replace wallet connect modal for tips

- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/firefly/Bridge.ts
> chore: is support native

- src/modals/AddWalletModal.tsx
https://mask.atlassian.net/browse/fw-2460
> fix: fw-2460 binding solana wallets

- src/app/(normal)/search/[type]/layout.tsx
- src/app/(normal)/search/[type]/page.tsx
- src/app/(normal)/search/page.tsx
- src/components/Search/SearchBar.tsx
- src/components/Search/SearchFilter.tsx
- src/components/Search/SearchRecommendation.tsx
- src/helpers/resolveSearchUrl.ts
- src/providers/twitter/SocialMedia.ts
https://mask.atlassian.net/browse/fw-2464
> fix: fw-2464 source tabs in search page

- src/components/Article/SingleArticle.tsx
- src/components/Article/SingleArticleHeader.tsx
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: bugfix for bookmark article

- src/app/(normal)/bookmarks/BookmarkList.tsx
https://mask.atlassian.net/browse/fw-2471
> fix: fw-2471 current source in bookmark list

- src/app/(activity)/activity/cz/page.tsx
- src/components/CZ/ActivityClaimButton.tsx
> fix: cz event issues

- src/components/NFTs/FollowingNFTList.tsx
https://mask.atlassian.net/browse/fw-2476
> fix: fw-2476 following nfts login requirement

- src/constants/limitation.ts
> fix: update video limitation for x

- vercel.json
> chore: redirect

- next.config.js
- vercel.json
> chore: rewrite

- src/middleware.ts
- src/providers/firefly/Bridge.ts
> fix: bridge

- src/app/layout-body.tsx
- src/components/IfHostname.tsx
> fix: cz layout

- src/app/layout-body.tsx
- src/app/layout.tsx
- src/constants/index.ts
> fix: hide browser detection tips

- src/components/CZ/ActivityClaimSuccessDialog.tsx
- src/components/CZ/ActivityHomePage.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: ens name query and share post content

- src/components/CZ/ActivityClaimButton.tsx
- src/components/CZ/ActivityHomePage.tsx
> fix: claim button loading style in cz event

- src/app/(activity)/activity/cz/layout.tsx
- src/components/CZ/ActivityModal.tsx
> feat: cz host redirect

- src/components/CZ/ActivityClaimButton.tsx
- src/components/CZ/ActivityClaimSuccessDialog.tsx
- src/components/CZ/ActivityDialog.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> feat: cz event share text

- src/constants/limitation.ts
> fix: add max file size for x video

- src/components/Advertisement.tsx
- src/constants/index.ts
- src/settings/index.ts
> fix: add env control for advertisement config

- src/components/Advertisement.tsx
- src/constants/enum.ts
> fix: directly open dialog for cz activity

- src/components/Profile/MutedProfileItem.tsx
https://mask.atlassian.net/browse/FW-2466
Closes FW-0000
> fix: FW-2466

- src/constants/limitation.ts
Reverts DimensionDev/firefly.mask.social#2706
> Revert "fix: add max file size for x video"

- src/app/(normal)/profile/pages/ProfilePageLayout.tsx
- src/providers/firefly/SessionHolder.ts
- src/providers/firefly/SocialMedia.ts
- src/services/getAllPlatformProfileFromFirefly.ts
> fix: bugfix for sol profile

- src/components/CZ/ActivityClaimSuccessDialog.tsx
> fix: hidden explorer url in ios

- src/assets/chains/ethereum.svg
- src/components/Profile/WalletInfo.tsx
https://mask.atlassian.net/browse/fw-2457
> fix: fw-2457 add network icon in wallet profile

- src/components/CZ/ActivityClaimSuccessDialog.tsx
> feat: update cz event post text

- src/components/Gif/GifSelector.tsx
- src/helpers/formatFileSize.ts
- src/helpers/validatePostFile.ts
https://mask.atlassian.net/browse/fw-2507
> fix: fw-2507 represent file size in regular units

- src/components/CZ/ActivityClaimSuccessDialog.tsx
> fix: cz share text

- src/configs/wagmiClient.ts
Closes [FW-2509](https://mask.atlassian.net/browse/FW-2509)
[FW-2509]: https://mask.atlassian.net/browse/FW-2509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: hide social auth

- src/components/Advertisement.tsx
- src/components/Calendar/NFTList.tsx
> fix: support open activity on native

- src/helpers/isSameSession.ts
- src/store/useProfileStore.ts
> fix: sync x account

- src/components/CZ/ActivityClaimSuccessDialog.tsx
> feat: cz event share text in mobile

- src/providers/base/SessionHolder.ts
- src/providers/farcaster/SessionHolder.ts
- src/providers/firefly/Article.ts
- src/providers/firefly/SessionHolder.ts
- src/providers/firefly/SocialMedia.ts
- src/providers/twitter/SessionHolder.ts
- src/providers/twitter/SocialMedia.ts
- src/services/metrics.ts
- src/store/useProfileStore.ts
> fix: tw login

- src/components/Markup/MarkupLink/TcoLink.tsx
- src/components/Posts/ThreadBody.tsx
> fix: tco link

- src/app/(normal)/article/[id]/pages/DetailPage.tsx
- src/app/(normal)/token/[symbol]/not-found.tsx
- src/components/Article/ArticleBody.tsx
- src/components/Article/ArticleLayout.tsx
- src/components/Markup/MarkupLink/Hashtag.tsx
- src/helpers/resolveSearchUrl.ts
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: block searching articles

- src/components/Login/ProfileAvatarInteractive.tsx
- src/components/ProfileAvatar.tsx
> fix: loading status

- src/components/Login/ProfileAvatarInteractive.tsx
> fix: is loading

- src/helpers/account.ts
> fix: logout x

- src/app/(normal)/bookmarks/[source]/page.tsx
> chore: bookmarks title

- src/app/(normal)/error.tsx
> chore: remove duplicate error

- src/components/Tips/index.tsx
> fix: fetch profiles with session for tips

- package.json
- src/providers/firefly/Bridge.ts
> [Release] Hotfix 6.2.1 => 6.2.2 (patch)

- package.json
- src/components/CZ/ActivityShortRules.tsx
- src/components/Posts/PostBody.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> [Release] Hotfix 6.2.2 => 6.2.3 (patch) 

- pnpm-lock.yaml
- src/mask/setup/wallet.ts
> chore: remove unused components

- scripts/build-logs.sh
> fix: git branch name

- pnpm-lock.yaml
- src/components/CollectionDetail/TopCollectors.tsx
- src/components/NFTDetail/Attendees.tsx
- src/components/NFTDetail/NFTOverflow.tsx
- src/providers/ethereum/ExplorerResolver.ts
- src/providers/ethereum/Network.ts
https://mask.atlassian.net/browse/FW-2523
Closes FW-0000
> feat: use BlockScan as block browser

- package.json
- src/components/CZ/ActivityShortRules.tsx
- src/components/Posts/PostBody.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> chore: bump version to 6.3.0

- src/providers/safary/getPublicParameters.ts
> chore: add social parameters

- src/app/(normal)/layout.tsx
- src/app/not-found.tsx
- src/components/IfPathname.tsx
- src/components/NavigatorBar/NavigatorBarForMobile.tsx
- src/components/Search/SearchBar.tsx
- src/helpers/parseOldBookmarkUrl.ts
- src/helpers/parseOldFollowingUrl.ts
- src/helpers/parseOldNotification.ts
- src/helpers/parseProfileUrl.ts
> refactor: keep PageRoute

- src/modals/AddWalletModal.tsx
https://mask.atlassian.net/browse/FW-2532
Closes FW-0000
> fix: hide success prompt when wallet has already connected before

- src/providers/goplus/rules.ts
https://mask.atlassian.net/browse/FW-2534
Closes FW-0000
> fix: transfer percent to number on GoPlus res

- src/components/Calendar/CalendarContent.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> feat: remove events from calendar

- src/providers/frame/Processor.ts
> refactor: discard non-text content-type when digesting document

- package.json
- patches/@livepeer__core@3.2.7.patch
- pnpm-lock.yaml
- src/components/Posts/Video.tsx
- src/components/Posts/VideoAsset.tsx
- src/components/Providers.tsx
- src/configs/livepeerClient.ts
> refactor: video

- src/app/(normal)/article/[id]/page.tsx
- src/app/(normal)/article/[id]/pages/DetailPage.tsx
- src/helpers/createMetadataArticleById.ts
- src/helpers/createMetadataToken.ts
- src/services/getArticleCover.ts
> fix: article page og image

- src/app/(settings)/components/WalletItem.tsx
- src/components/NFTDetail/Attendees.tsx
- src/components/NFTDetail/NFTOverflow.tsx
- src/components/Profile/WalletInfo.tsx
https://mask.atlassian.net/browse/FW-2535
https://mask.atlassian.net/browse/FW-2539
Closes FW-0000
> feat: add link for wallet address

- src/components/Actions/More.tsx
- src/components/Profile/WalletMoreAction.tsx
- src/components/ProfileVerifyBadge/index.tsx
- src/providers/twitter/SocialMedia.ts
- src/providers/types/Firefly.ts
> fix: fix styles and twitter profile badge

- src/app/globals.css
- src/components/Markup/Markup.tsx
- src/components/Markup/NakedMarkup.tsx
> chore: keep list style in post

- src/store/useProfileStore.ts
> fix: bugfix for refresh account

- src/components/ProfileVerifyBadge/index.tsx
- src/providers/twitter/SocialMedia.ts
- src/providers/types/SocialMedia.ts
> fix: fix twitter badge color

- src/app/api/twitter/search/all/route.ts
- src/constants/index.ts
- src/providers/twitter/SocialMedia.ts
https://mask.atlassian.net/browse/FW-2550
https://mask.atlassian.net/browse/FW-2546
Closes FW-0000
> fix: remove unknow operator for x query keyword

- src/components/Posts/SuperFollow.tsx
- src/helpers/formatLensPost.ts
> fix: follow moudle

- package.json
- pnpm-lock.yaml
- src/helpers/promise.ts
- src/libs/SingletonModal.ts
- src/libs/ValueRef.ts
- src/mask/background-worker/ready.ts
- src/mask/setup/message.ts
> fixup! chore: minor update [6.3] (#2682)

- src/components/Actions/More.tsx
- src/components/Compose/SchedulePostSettings.tsx
- src/components/DatePicker.tsx
- src/components/TimePicker.tsx
> fix: timer picker ux

- src/app/api/twitter/search/all/route.ts
- src/helpers/createTwitterClientV2.ts
> feat: support OAuth2 for x api

- src/components/Login/LoginFarcaster.tsx
- src/components/Providers.tsx
- tailwind.config.cjs
https://mask.atlassian.net/browse/fw-2564
> fix: fw-2564 update info toast style

- src/components/Article/ArticleCollect.tsx
- src/components/Posts/Reply.tsx
- src/providers/paragraph/Processor.ts
- src/providers/paragraph/index.tsx
> fix: paragraph position

- src/app/(settings)/settings/general/page.tsx
https://mask.atlassian.net/browse/fw-2559
> fix: fw-2559 change locale

- src/components/Login/LoginFarcaster.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
update text
https://mask.atlassian.net/browse/fw-2564
> fixup! fix: fw-2564 update info toast style (#2786)

- src/components/Providers.tsx
- src/locales/zh-Hant/messages.po
> chore: update locale

- package.json
- patches/dayjs-twitter@0.5.0.patch
- pnpm-lock.yaml
- src/components/Notification/NotificationItem.tsx
- src/components/Notification/NotificationPostBody.tsx
- src/providers/paragraph/index.tsx
> fix: notification post

- src/components/Calendar/CalendarContent.tsx
- src/components/LinkCloud.tsx
- src/components/SuggestedFollows/SuggestedFollowsCard.tsx
> fix: layout UI

- src/components/Compose/SchedulePostSettings.tsx
- src/components/Posts/Video.tsx
- src/components/Tips/index.tsx
- src/helpers/checkScheduleTime.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/EnableSignlessModal.tsx
- src/services/crossSchedulePost.tsx
- src/services/crossSchedulePostThread.ts
> fix: warning message

- src/components/Calendar/NFTList.tsx
- src/helpers/fixUrlProtocol.ts
https://mask.atlassian.net/browse/fw-2566
> fix: fw-2566 fix url in nft

- src/components/Article/ArticleBody.tsx
- src/providers/paragraph/Processor.ts
> fix: paragraph article default chain

- src/app/(developers)/components/MethodButton.tsx
- src/types/bridge.ts
Closes [FW-2515](https://mask.atlassian.net/browse/FW-2515)
[FW-2515]: https://mask.atlassian.net/browse/FW-2515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: impl openUrl

- src/components/Posts/PostBody.tsx
https://mask.atlassian.net/browse/fw-2565
> fix: fw-2565 don't show og/attachments during decoding image

- src/components/NFTs/NFTMoreAction.tsx
> fix: nft feed color

- src/constants/chain.ts
https://mask.atlassian.net/browse/FW-2572
Closes FW-0000
> fix: Matic to Polygon

- src/app/(settings)/components/ConnectMPCWalletButton.tsx
- src/app/(settings)/components/WalletItem.tsx
- src/app/(settings)/settings/wallets/page.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2526
Closes FW-0000
> feat: support MPC wallets in settings

- src/components/TransactionSimulator/config.tsx
- src/components/TransactionSimulator/simulateAndCheckSecurity.ts
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2574
Closes FW-0000
> fix: token amount in simulation

- src/components/Posts/TweetSpace.tsx
> refactor: space

- src/components/Compose/SchedulePostSettings.tsx
> chore: missing notification

- src/components/TransactionSimulator/ContinueButton.tsx
- src/components/TransactionSimulator/DataPanel.tsx
- src/components/TransactionSimulator/SimulatorContent.tsx
- src/components/TransactionSimulator/config.tsx
- src/components/TransactionSimulator/simulateAndCheckSecurity.ts
- src/providers/types/Tenderly.ts
https://mask.atlassian.net/browse/FW-2573
https://mask.atlassian.net/browse/FW-2575
Closes FW-0000
> fix: remove simulation loading and display default data

- src/components/Profile/ProfileTabs.tsx
- src/components/Profile/WalletInfo.tsx
- src/helpers/isMPCWallet.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2527
Closes FW-0000
> feat: highlight MPC wallet in profile page

- src/helpers/isMPCWallet.ts
> fix: judging condition for MPC wallet

- src/app/api/frame/route.ts
- src/helpers/memoizeWithRedis.ts
> fix: ingore frame cache when got empty cache

- src/components/Compose/DraftList.tsx
- src/components/Compose/DraftPage.tsx
- src/components/Compose/ScheduleTaskList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/store/useFireflyIdentityStore.ts
- src/store/usePreferenceStore.ts
https://mask.atlassian.net/browse/fw-2570
> feat: fw-2570 add schedule tip

- src/app/(normal)/profile/(profile)/[source]/page.tsx
- src/store/useFireflyIdentityStore.ts
> refactor: firefly profile store

- src/components/TransactionSimulator/ContinueButton.tsx
- src/components/TransactionSimulator/MessagesTippy.tsx
> fix: simulation dark mode

- src/app/(developers)/components/MethodButton.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/providers/firefly/Bridge.ts
- src/types/bridge.ts
> feat: add bridge methods for events

- src/configs/wagmiClient.ts
- src/providers/mirror/index.ts
> refactor: renaming

- package.json
- src/app/api/time/route.ts
- src/components/CZ/ActivityContext.tsx
- src/components/CZ/ActivityHomePage.tsx
- src/components/SideBar/Menu.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/types/Firefly.ts
> [Release] Hotfix 6.2.5 => 6.2.6 (patch)

- src/components/TransactionSimulator/config.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/mirror/index.ts
> refactor: format pay and receive in simulation

- next.config.js
- src/app/(normal)/article/[id]/pages/DetailPage.tsx
- src/helpers/parseParagraphHtml.ts
> fix: build errors

- src/components/Posts/Attachment.tsx
- src/components/Posts/PostBody.tsx
- src/components/Posts/VideoAsset.tsx
https://mask.atlassian.net/browse/FW-2549
Closes FW-0000
> feat: optimize attachment display in quote

- src/components/Calendar/CalendarContent.tsx
- src/components/Calendar/NFTList.tsx
- src/components/Calendar/NewsList.tsx
https://mask.atlassian.net/browse/mf-6454
> fix: mf-6454 nft list empty status

- src/components/CZ/ActivityContext.tsx
> fix: activity context deps

- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/LoginModal/RootView.tsx
- src/modals/LoginModal/index.tsx
https://mask.atlassian.net/browse/fw-2587
https://mask.atlassian.net/browse/FW-2588
> fix: fw-2587 router pending status

- src/app/(whiteboard)/telegram/login/page.tsx
> feat: mobile login by tg

- src/components/Compose/Editor.tsx
- src/components/Lexical/plugins/AtMentionsPlugin.tsx
> refactor: import types from Lexical

- src/app/(settings)/components/WalletItem.tsx
- src/components/CollectionDetail/CollectionInfo.tsx
- src/components/CopyTextButton.tsx
- src/components/NFTDetail/NFTOverflow.tsx
- src/components/SolanaAccountModal.tsx
- src/components/TokenProfile/ContractList.tsx
- src/components/TokenProfile/TokenDetail.tsx
- src/components/WalletItem.tsx
> refactor: CopyTextButton

- src/providers/telemetry/index.ts
- src/store/useDeveloperSettingsStore.ts
> chore: enable telemetry by default

- src/components/Posts/PostBody.tsx
https://mask.atlassian.net/browse/FW-2601
Closes FW-0000
> fix: display frame and red packet in quote

- src/constants/limitation.ts
> fix: remove video size limitation for x

- src/components/Calendar/NFTList.tsx
https://mask.atlassian.net/browse/fw-2593
> fixup! fix: fw-2593 website icon in nft event list (#2859)

- src/components/Profile/ProfileMoreAction.tsx
https://mask.atlassian.net/browse/fw-2603
> fix: fw-2603 copy profile url

- src/components/Snapshot/SingleSnapshot.tsx
- src/components/Snapshot/SingleSnapshotHeader.tsx
> fix: bugfix for snapshot ui

- src/components/Profile/ProfileMoreAction.tsx
- src/components/Snapshot/SingleSnapshot.tsx
- src/components/Snapshot/SnapshotResults.tsx
- src/components/Snapshot/SnapshotVotesList.tsx
> fix: missing tooltip

- src/components/WagmiProvider.tsx
> refactor: WagmiConfig is deprecated

- patches/@particle-network__auth-core@2.0.4.patch
- pnpm-lock.yaml
- src/app/(developers)/components/BridgeMethodButton.tsx
- src/app/(developers)/components/EthereumMethodButton.tsx
- src/app/(developers)/components/ToolkitList.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/app/(developers)/developers/ethereum/layout.tsx
- src/app/(developers)/developers/ethereum/page.tsx
- src/app/(settings)/components/ConnectMPCWalletButton.tsx
- src/app/connectors/ParticleConnector.ts
- src/components/Providers.tsx
- src/components/SideBar/ConnectWallet.tsx
- src/configs/wagmiClient.ts
- src/constants/env.ts
- src/constants/error.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/types/ethereum.ts
> feat: add particle connector

- src/components/Calendar/NFTList.tsx
- src/components/TokenProfile/CommunityLink.tsx
- src/constants/regexp.ts
https://mask.atlassian.net/browse/FW-2592
Closes FW-0000
> feat: intercept x links in calendar

- src/components/Calendar/NFTList.tsx
- src/components/NFTs/NFTFeedAction.tsx
https://mask.atlassian.net/browse/fw-2593
> fix(UI): do not uppercase nft operation

- src/components/Actions/ArticleMore.tsx
- src/components/Actions/More.tsx
- src/components/Actions/ShareAction.tsx
- src/components/Actions/SnapshotMore.tsx
- src/components/CZ/ActivityConnectWalletButton.tsx
- src/components/Channel/ChannelMoreAction.tsx
- src/components/CopyTextButton.tsx
- src/components/MenuGroup.tsx
- src/components/NFTs/NFTMoreAction.tsx
- src/components/Profile/ProfileMoreAction.tsx
- src/components/Profile/WalletMoreAction.tsx
- src/components/Tips/index.tsx
- src/components/TokenProfile/ContractList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> refactor: upgrade Menu

- src/components/Profile/WalletMoreAction.tsx
> fix: import

- src/app/(normal)/profile/(profile)/[source]/page.tsx
- src/services/account.ts
- src/store/usePreferenceStore.ts
https://mask.atlassian.net/browse/fw-2600
> fix: fw-2600 schedule tip

- src/app/(normal)/bookmarks/[source]/layout.tsx
- src/app/(normal)/discover/[source]/layout.tsx
- src/app/(normal)/following/[source]/layout.tsx
- src/app/(normal)/notifications/[source]/layout.tsx
- src/app/(normal)/profile/pages/ProfilePageLayout.tsx
- src/app/(normal)/search/[source]/[type]/page.tsx
- src/components/SourceTabs/SourceTab.tsx
- src/components/SourceTabs/index.tsx
https://mask.atlassian.net/browse/fw-2604
> fix: fw-2604 scroll active tab into view

- src/components/Oembed/Embed.tsx
- src/components/Posts/Attachment.tsx
https://mask.atlassian.net/browse/FW-2609
Closes FW-0000
> fix: ui bugs about radius

- src/components/Article/ArticleBody.tsx
- src/components/Snapshot/SnapshotBody.tsx
- src/components/SourceTabs/index.tsx
> fix: invalid article author

- src/services/getProfileById.ts
> feat: support handle on x profile page

- src/components/ProfileVerifyBadge/index.tsx
https://mask.atlassian.net/browse/FW-2610
Closes FW-0000
> fix: ui bugs for x company logo

- src/modals/AddWalletModal.tsx
https://mask.atlassian.net/browse/FW-2616
Closes FW-0000
> fix: expose error from api on binding wallet

- src/app/(activity)/activity/cz/layout.tsx
- src/app/(developers)/developers/page.tsx
- src/middleware.ts
> fix: redirect

- src/constants/env.ts
> refactor: remove unused envs

- src/providers/telemetry/index.ts
- src/providers/types/Telemetry.ts
> chore: add log filters

- src/providers/telemetry/captureAccountEvent.ts
- src/providers/telemetry/captureComposeEvent.ts
- src/providers/telemetry/capturePostActionEvent.ts
- src/providers/telemetry/captureProfileActionEvent.ts
- src/providers/telemetry/captureSyncModalEvent.ts
- src/providers/telemetry/index.ts
- src/providers/types/Telemetry.ts
> feat: log filters

- src/components/Compose/DraftList.tsx
- src/components/Compose/ScheduleTaskList.tsx
https://mask.atlassian.net/browse/fw-2622
> fix: fw-2622 remove scrollbar in draft modal

- src/app/(developers)/components/MethodButton.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/providers/firefly/Bridge.ts
- src/types/bridge.ts
> feat: bridge method is following

- src/app/(developers)/components/BridgeMethodButton.tsx
- src/types/bridge.ts
> feat: (bridge) add isFollowing

- src/app/(developers)/components/BridgeMethodButton.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/types/bridge.ts
> fix: bridge demo page

- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/AddWalletModal.tsx
- src/services/createLensSchedulePostPayload.ts
> fix: remove wallet require when schedule lens

- src/components/SourceTabs/SourceTab.tsx
> fix: tab hover style in mobile

- .github/workflows/issue.yml
- package.json
- patches/@reown__appkit-scaffold-ui@1.1.3.patch
- pnpm-lock.yaml
- src/configs/wagmiClient.ts
> feat: promote Firefly Wallet

- src/components/Frame/index.tsx
- src/helpers/formatTwitterPost.ts
> fix: tweet content

- package.json
- patches/@solana__wallet-adapter-react-ui@0.9.35.patch
- pnpm-lock.yaml
> fix: ensure Firefly Wallet display first in solana wallets

- src/app/(developers)/components/BridgeMethodButton.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/types/bridge.ts
> chore: follow up

- public/js/browser-detector.js
- src/app/layout.tsx
> fix: ignore bowser detector on firefly app

- src/providers/types/Telemetry.ts
> refactor: rename log

- src/providers/telemetry/getPublicParameters.ts
> fix: public parameters

- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/AddWalletModal.tsx
https://mask.atlassian.net/browse/FW-2652
https://mask.atlassian.net/browse/FW-2616
Closes FW-0000
> fix: rewrite error message in adding wallet

- src/providers/telemetry/getPublicParameters.ts
- src/providers/telemetry/index.ts
> fix: ga event

- src/providers/telemetry/capturePostActionEvent.ts
> chore: enable post action for testing

- public/js/browser-detector.js
- src/app/(activity)/(event)/event/[name]/page.tsx
- src/components/Activity/ActivityConnectButton.tsx
- src/components/Activity/ActivityConnectCard.tsx
- src/components/Activity/ActivityFollowTargetCard.tsx
- src/components/Activity/ActivityListItem.tsx
- src/components/Activity/ActivityMintSuccessDialog.tsx
- src/components/Activity/ActivityTaskFollowCard.tsx
- src/components/Activity/ActivityTwitterLoginButton.tsx
- src/components/Activity/NavigationBar.tsx
- src/components/Activity/hooks/useActivityCompose.tsx
- src/components/Activity/hooks/useActivityPremiumList.tsx
- src/components/Activity/hooks/useIsLoginTwitterInActivity.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes FW-2649 FW-2650 FW-2662 FW-2663 FW-2665 FW-2666
> fix: activity issues

- src/providers/telemetry/captureAccountEvent.ts
- src/providers/telemetry/captureComposeEvent.ts
- src/providers/telemetry/captureProfileActionEvent.ts
- src/providers/telemetry/captureSyncModalEvent.ts
> refactor: remove version filter

- src/app/layout.tsx
> chore: update gtm

- src/assets/calendar.svg
- src/components/Posts/TweetSpace.tsx
https://mask.atlassian.net/browse/FW-2585
Closes FW-0000
> fix: time error in x space

- src/components/Posts/PostBody.tsx
- src/helpers/getEncryptedPayload.ts
https://mask.atlassian.net/browse/fw-2671
> fix: fw-2671 liking post flickers UI

- src/providers/telemetry/getPublicParameters.ts
> fix: evm address

- src/components/ParticleProvider.tsx
- src/components/SolanaWalletAdapterProvider.tsx
- src/configs/wagmiClient.ts
- src/connectors/ParticleConnector.ts
> refactor: adhere particle env

- src/modals/AddWalletModal.tsx
> fix: rewrite error message

- src/app/api/twitter/user/search/route.ts
- src/constants/index.ts
- src/helpers/formatTwitterProfile.ts
- src/providers/twitter/SocialMedia.ts
> feat: support search users on x

- src/providers/telemetry/captureAccountEvent.ts
- src/providers/telemetry/captureComposeEvent.ts
> feat: enabled compose capture and login capture

- src/app/(developers)/components/TelemetryMethodButton.tsx
- src/app/(developers)/components/ToolkitList.tsx
- src/app/(developers)/developers/telemetry/layout.tsx
- src/app/(developers)/developers/telemetry/page.tsx
- src/constants/env.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/telemetry/index.ts
- src/providers/types/Telemetry.ts
- src/types/telemetry.ts
> chore: add debug telemetry switch

- src/app/(developers)/developers/general/page.tsx
- src/constants/env.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/telemetry/getPublicParameters.ts
- src/providers/telemetry/index.ts
- src/settings/index.ts
- src/store/useDeveloperSettingsStore.ts
> chore: telemetry debug

- src/providers/telemetry/getPublicParameters.ts
- src/providers/telemetry/index.ts
> fix: hex value

- src/providers/telemetry/captureComposeEvent.ts
> feat: send post capture

- src/locales/zh-Hans/messages.po
> chore: zh trans

- src/components/Compose/SchedulePostSettings.tsx
- src/components/Posts/PostCollect.tsx
- src/components/Posts/PostLinks.tsx
- src/components/Profile/NFTCollectionList.tsx
- src/components/Profile/Title.tsx
- src/components/TokenProfile/TokenDetail.tsx
- src/helpers/account.ts
- src/helpers/formatArticleFromFirefly.ts
- src/helpers/formatLensPost.ts
- src/helpers/resolveMediaObjectUrl.ts
- src/providers/twitter/SocialMedia.ts
- src/services/reportFarcasterSigner.ts
- src/store/useProfileStore.ts
Closes [FW-2680](https://mask.atlassian.net/browse/FW-2680)
[FW-2680]: https://mask.atlassian.net/browse/FW-2680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: upload signer config

- src/components/Actions/More.tsx
https://mask.atlassian.net/browse/FW-2582
Closes FW-0000
> fix: link error

- src/configs/wagmiClient.ts
> refactor: debug mode

- src/app/(developers)/components/BridgeMethodButton.tsx
> fix: update bridge compose params

- src/components/Activity/hooks/useLoginInActivity.ts
- src/types/bridge.ts
> feat: bridge login params

- package.json
- src/components/Activity/hooks/useActivityCompose.tsx
> [Release] Hotfix 6.2.9 => 6.2.10 (patch) 

- src/app/layout.tsx
- src/components/ErrorBoundary/Crash.tsx
- src/components/ErrorBoundary/index.tsx
- src/components/Providers.tsx
Closes [FW-2683](https://mask.atlassian.net/browse/FW-2683)
[FW-2683]: https://mask.atlassian.net/browse/FW-2683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: migrate error boundary from mask

- src/components/Compose/ComposeActions/index.tsx
https://mask.atlassian.net/browse/fw-2684
> fix: fw-2684 missing dep in opening redpacket dialog

- src/components/Providers.tsx
> fix: crash

- src/app/(activity)/(event)/event/[name]/page.tsx
- src/app/(activity)/(event)/event/cz_welcome_back_airdrop/page.tsx
- src/app/(activity)/(event)/events/page.tsx
- src/components/Activity/ActivityDesktopNavigationBar.tsx
- src/components/Activity/ActivityNavigationBar.tsx
- src/middleware.ts
> feat: activity ssr

- src/app/globals.css
- src/components/Snapshot/SnapshotBody.tsx
- src/components/Snapshot/SnapshotVotesList.tsx
> fix: snapshot markup style

- src/components/Snapshot/SnapshotBody.tsx
- src/components/Snapshot/SnapshotChoice.tsx
> fix: disable status

- patches/@reown__appkit-scaffold-ui@1.1.3.patch
- pnpm-lock.yaml
- src/configs/wagmiClient.ts
- src/constants/reown.ts
https://mask.atlassian.net/browse/fw-2624
> fix: fw-2624 update feature wallets

- src/app/(event)/event/[name]/page.tsx
- src/components/Posts/TweetSpace.tsx
- src/helpers/isToday.ts
- src/helpers/isTomorrow.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: space issues

- src/app/(settings)/components/ConnectMPCWalletButton.tsx
- src/app/(settings)/settings/wallets/page.tsx
https://mask.atlassian.net/browse/FW-2692
Closes FW-0000
> fix: add env control for mpc wallets in settings

- src/app/globals.css
- src/components/Advertisement/Swiper.tsx
- src/components/SuggestedFollows/SuggestedFollowsCard.tsx
> fix: optimize GLS for sidebar

- src/helpers/formatTwitterPost.ts
- src/helpers/formatTwitterProfile.ts
https://mask.atlassian.net/browse/FW-2706
Closes FW-0000
> fix: wrong data structure in x

- src/app/(normal)/post/[source]/[id]/page.tsx
- src/app/(normal)/post/[source]/[id]/pages/TwitterDetailPage.tsx
- src/app/(normal)/profile/pages/ProfilePageLayout.tsx
- src/components/Profile/TwitterProfileInfo.tsx
- src/helpers/formatTwitterPost.ts
> fix: skip the ssr page of twitter

- src/components/ErrorBoundary/Crash.tsx
- src/components/ErrorBoundary/index.tsx
> refactor: error boundary

- src/providers/paragraph/index.tsx
> fix: paragraph estimate

- package.json
> fix: fix deploy oom errors

- src/app/(developers)/developers/telemetry/page.tsx
> fix: pick errors

- src/components/Activity/ActivityElex24/ActivityElex24Vote.tsx
> fix: vote status

- src/components/Activity/VotingResultBanner.tsx
- src/components/CollectionDetail/CollectionInfo.tsx
> feat: replace bg for voting nft collection

- src/components/Activity/ActivityContext.tsx
- src/components/Activity/ActivityMobileNavigationBar.tsx
- src/components/Activity/ActivityTasks/ActivityElex24Tasks.tsx
- src/components/Activity/hooks/useIsLoginTwitterInActivity.ts
- src/helpers/resolveActivityUrl.ts
> feat: activity share

- src/app/api/twitter/user/search/route.ts
Closes [FW-2714](https://mask.atlassian.net/browse/FW-2714)
[FW-2714]: https://mask.atlassian.net/browse/FW-2714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: format search query on x

- src/components/Posts/Attachment.tsx
- src/components/Posts/ImageAsset.tsx
> feat: optimize single image ui in post

- src/app/(event)/event/[name]/page.tsx
> fix: activity 404 page

- src/components/CollectionDetail/CollectionTabs.tsx
- src/components/CollectionDetail/NFTList.tsx
- src/components/GridListInPage.tsx
> fix: nft collection placeholder ui

- src/components/Activity/ActivityMobileNavigationBar.tsx
- src/components/Activity/ActivityTasks/ActivityElex24Tasks.tsx
- src/helpers/resolveActivityUrl.ts
- src/providers/telemetry/captureActivityEvent.ts
Closes FW-2713 FW-2715 FW-2716
> feat: activity captrue and share content

- src/components/Activity/ActivityHeader.tsx
> fix: activity time style

- src/helpers/createMetadataEventDetailPage.ts
> fix: handle activity api not found

- src/components/Activity/VotingResultBanner.tsx
> fix: rounding for voting result

- src/components/Activity/ActivityConnectButton.tsx
- src/components/Activity/ActivityMobileNavigationBar.tsx
> feat: refetch bound address list when click change button

- src/components/Posts/SinglePost.tsx
https://mask.atlassian.net/browse/fw-2721
> feat: fw-2721 hide posts from muted channel immediately

- src/components/Activity/VotingResultBanner.tsx
https://mask.atlassian.net/browse/FW-2719
Closes FW-0000
> fix: wait for font loaded

- src/providers/firefly/Activity.ts
> feat: activity address list no cache

- src/helpers/getEncryptedPayload.ts
> refactor: cache decode image

- src/helpers/getEncryptedPayload.ts
> perf: cache decoding steganography decoding image

- src/helpers/createMetadataPostById.ts
- src/i18n/index.ts
> refactor: get current i18n

- src/helpers/createMetadataPostById.ts
- src/i18n/index.ts
> fix: post detail metadata title

- src/providers/firefly/Endpoint.ts
> fix: account disconnect

- src/app/(event)/event/[name]/page.tsx
- src/components/Activity/ActivityEndedDialog.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> feat: activity ended dialog

- src/app/(event)/layout.tsx
- src/components/Activity/ActivityElex24/ActivityElex24Vote.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> feat: update activity i18n and navbar

- src/components/Activity/VotingResultBanner.tsx
> fix: voting results mobile ui

- public/.well-known/apple-app-site-association
> chore: update apple site components

- src/app/(normal)/bookmarks/[source]/layout.tsx
- src/app/(normal)/channel/[id]/[type]/layout.tsx
- src/app/(normal)/discover/[source]/[discover]/layout.tsx
- src/app/(normal)/discover/[source]/layout.tsx
- src/app/(normal)/following/[source]/layout.tsx
- src/app/(normal)/nft/[chainId]/[address]/[tokenId]/page.tsx
- src/app/(normal)/nft/pages/NFTDetailPage.tsx
- src/app/(normal)/notifications/[source]/layout.tsx
- src/app/(normal)/post/[source]/[id]/[type]/layout.tsx
- src/app/(normal)/post/[source]/[id]/page.tsx
- src/app/(normal)/post/[source]/page.tsx
- src/app/(normal)/profile/(profile)/[source]/[id]/[category]/layout.tsx
- src/app/(normal)/profile/(profile)/[source]/page.tsx
- src/app/(normal)/profile/(relation)/[source]/[id]/relation/[category]/layout.tsx
- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/components/Compose/SchedulePostSettings.tsx
- src/components/Posts/PostCollect.tsx
- src/components/Posts/PostLinks.tsx
- src/components/Profile/NFTCollectionList.tsx
- src/components/Profile/Title.tsx
- src/components/Profile/WalletProfileContentList.tsx
- src/components/TokenProfile/TokenDetail.tsx
- src/helpers/createMetadataNFT.ts
- src/helpers/formatArticleFromFirefly.ts
- src/helpers/formatLensPost.ts
- src/helpers/resolveMediaObjectUrl.ts
- src/providers/twitter/SocialMedia.ts
- src/store/useProfileStore.ts
> refactor: popa list

- src/app/(normal)/nft/[chainId]/[address]/[tokenId]/page.tsx
- src/app/(normal)/nft/[chainId]/[address]/page.tsx
- src/app/(normal)/post/[source]/[id]/page.tsx
- src/app/(normal)/post/[source]/[id]/photos/[index]/page.tsx
- src/app/(normal)/post/[source]/page.tsx
- src/app/(normal)/profile/pages/ProfilePageLayout.tsx
- src/middleware.ts
> refactor: middleware seq

- src/app/(normal)/bookmarks/[source]/layout.tsx
- src/app/(normal)/channel/[id]/[type]/layout.tsx
- src/app/(normal)/discover/[source]/[discover]/layout.tsx
- src/app/(normal)/discover/[source]/layout.tsx
- src/app/(normal)/following/[source]/layout.tsx
- src/app/(normal)/nft/[chainId]/[address]/[tokenId]/page.tsx
- src/app/(normal)/nft/pages/NFTDetailPage.tsx
- src/app/(normal)/notifications/[source]/layout.tsx
- src/app/(normal)/post/[source]/[id]/[type]/layout.tsx
- src/app/(normal)/post/[source]/[id]/page.tsx
- src/app/(normal)/post/[source]/page.tsx
- src/app/(normal)/profile/(profile)/[source]/[id]/[category]/layout.tsx
- src/app/(normal)/profile/(relation)/[source]/[id]/relation/[category]/layout.tsx
- src/components/TokenProfile/TokenDetail.tsx
> refactor: not found

- src/actions/changeLocale.ts
- src/app/(normal)/bookmarks/page.ts
- src/app/(normal)/channel/[id]/page.tsx
- src/app/(normal)/discover/[source]/layout.tsx
- src/app/(normal)/following/page.tsx
- src/app/(normal)/nft/[chainId]/[address]/[tokenId]/page.tsx
- src/app/(normal)/nft/[chainId]/[address]/page.tsx
- src/app/(normal)/notifications/page.tsx
- src/app/(normal)/page.ts
- src/app/(normal)/post/[source]/[id]/page.tsx
- src/app/(normal)/post/[source]/page.tsx
- src/app/(normal)/profile/(profile)/[source]/page.tsx
- src/app/(normal)/profile/page.tsx
- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/app/(normal)/search/page.tsx
- src/components/Profile/WalletProfileContentList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> refactor: redirect

- src/app/(normal)/nft/pages/NFTCollectionPage.tsx
- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/components/Profile/WalletProfileContentList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: remove dao tab

- src/app/(normal)/intent/compose/layout.tsx
- src/app/(normal)/intent/compose/loading.tsx
- src/app/(normal)/intent/compose/page.tsx
- src/app/(normal)/intent/compose/pages/ShareLinkPage.tsx
- src/components/Lexical/plugins/AtMentionsPlugin.tsx
- src/helpers/formatSearchIdentities.ts
https://mask.atlassian.net/browse/FW-2685
Closes FW-0000
> feat: internal share link

- src/providers/twitter/SocialMedia.ts
https://mask.atlassian.net/browse/FW-2724
Closes FW-0000
> fix: data structure error in x api

- src/actions/changeLocale.ts
- src/app/(normal)/bookmarks/[source]/layout.tsx
- src/app/(normal)/bookmarks/page.ts
- src/app/(normal)/channel/[id]/[type]/layout.tsx
- src/app/(normal)/channel/[id]/page.tsx
- src/app/(normal)/discover/[source]/[discover]/layout.tsx
- src/app/(normal)/discover/[source]/layout.tsx
- src/app/(normal)/following/[source]/layout.tsx
- src/app/(normal)/following/page.tsx
- src/app/(normal)/intent/compose/page.tsx
- src/app/(normal)/nft/[chainId]/[address]/[tokenId]/page.tsx
- src/app/(normal)/nft/pages/NFTDetailPage.tsx
- src/app/(normal)/notifications/[source]/layout.tsx
- src/app/(normal)/notifications/page.tsx
- src/app/(normal)/page.ts
- src/app/(normal)/post/[source]/[id]/[type]/layout.tsx
- src/app/(normal)/post/[source]/[id]/page.tsx
- src/app/(normal)/post/[source]/[id]/pages/DetailPage.tsx
- src/app/(normal)/post/[source]/page.tsx
- src/app/(normal)/profile/(profile)/[source]/[id]/[category]/layout.tsx
- src/app/(normal)/profile/(profile)/[source]/page.tsx
- src/app/(normal)/profile/(relation)/[source]/[id]/relation/[category]/layout.tsx
- src/app/(normal)/profile/page.tsx
- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/app/(normal)/search/page.tsx
- src/components/TokenProfile/TokenDetail.tsx
> refactor: remove return

- src/components/Activity/ActivityElex24/ActivityElex24ResultsBanner.tsx
- src/components/CollectionDetail/CollectionInfo.tsx
- src/constants/env.ts
> refactor: Elex24 activity result

- src/components/Profile/ProfileAction.tsx
> fix: update profile follow state when client render

- src/components/Compose/PostByItem.tsx
- src/modals/ComposeModal.tsx
> feat: add draft confirm to compose login

- src/helpers/getEncryptedPayload.ts
> fix: typo error

- src/components/Activity/hooks/useLoginInActivity.ts
- src/components/CollectionDetail/TopCollectors.tsx
- src/components/NFTDetail/Attendees.tsx
> fix: attendees avatar shrink-0 and handle activity login error handler

- src/providers/telemetry/captureAccountEvent.ts
- src/providers/telemetry/captureComposeEvent.ts
- src/providers/telemetry/capturePostActionEvent.ts
- src/providers/telemetry/captureProfileActionEvent.ts
- src/providers/telemetry/captureSyncModalEvent.ts
> chore: turn on telemetry

- src/app/(normal)/pages/Discover.tsx
- src/components/Notification/NotificationFilter.tsx
https://mask.atlassian.net/browse/fw-2747
> fix: fw-2747 adjust label tab color

- package.json
- src/components/Activity/hooks/useIsLoginTwitterInActivity.ts
- src/hooks/useFireflyBridgeAuthorization.ts
> [Release] Hotfix 6.2.13 => 6.2.14 (patch) 

- src/abis/Paragraph.ts
- src/components/Article/ArticleCollect.tsx
- src/modals/CollectArticleModal.tsx
- src/modals/DraggablePopover.tsx
- src/providers/mirror/index.ts
- src/providers/paragraph/index.tsx
https://mask.atlassian.net/browse/FW-2744
https://mask.atlassian.net/browse/FW-2745
https://mask.atlassian.net/browse/FW-2746
> fix: fw-2745 fw-2744 collect article

- src/components/Frame/index.tsx
- src/components/TransactionSimulator/simulate.tsx
- src/constants/error.ts
- src/hooks/useActionAdapter.ts
- src/providers/mirror/index.ts
https://mask.atlassian.net/browse/FW-2755
Closes FW-0000
> fix: no alert when user canceled simulation

- src/providers/telemetry/captureAccountEvent.ts
- src/providers/telemetry/captureActivityEvent.ts
- src/providers/telemetry/captureComposeEvent.ts
- src/providers/telemetry/capturePostActionEvent.ts
- src/providers/telemetry/captureProfileActionEvent.ts
- src/providers/telemetry/captureSyncModalEvent.ts
> refactor: capture async

- src/modals/LogoutModal.tsx
> feat: farcaster logout without route progress bar

- .github/workflows/pull-request-linker.yml
> chore: pr linker action

- src/helpers/formatTwitterPost.ts
Closes [FW-2742](https://mask.atlassian.net/browse/FW-2742)
> fix: format twitter post

- src/components/Article/ArticleCollect.tsx
https://mask.atlassian.net/browse/fw-2767
> fix: fw-2767 open tx in explorer afater collecting

- src/app/globals.css
> fix: sidebar icon display

- .github/workflows/pull-request-linker.yml
- src/providers/warpcast/createAccountByRelayService.ts
Closes [FW-2771](https://mask.atlassian.net/browse/FW-2771)
[FW-2771]: https://mask.atlassian.net/browse/FW-2771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: login fc success

- src/components/Tips/SendTipsButton.tsx
- src/helpers/resolveFireflyProfileId.ts
- src/services/reportTokenTips.ts
> fix: account id

- src/providers/telemetry/captureComposeEvent.ts
- src/providers/telemetry/getComposeEventParameters.ts
Closes [FW-2733](https://mask.atlassian.net/browse/FW-2733)
[FW-2733]: https://mask.atlassian.net/browse/FW-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: compose event parameters

- src/providers/lens/SocialMedia.ts
- src/services/getThreads.ts
Closes [FW-2795](https://mask.atlassian.net/browse/FW-2795)
[FW-2795]: https://mask.atlassian.net/browse/FW-2795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: invalid thread api url

- src/providers/telemetry/capturePollEvent.ts
- src/providers/types/Telemetry.ts
- src/services/crossPost.ts
Closes [FW-2758](https://mask.atlassian.net/browse/FW-2758)
Closes [FW-2776](https://mask.atlassian.net/browse/FW-2776)
Closes [FW-2736](https://mask.atlassian.net/browse/FW-2736)
Closes [FW-2804](https://mask.atlassian.net/browse/FW-2804)
Closes [FW-2789](https://mask.atlassian.net/browse/FW-2789)
[FW-2758]: https://mask.atlassian.net/browse/FW-2758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2776]: https://mask.atlassian.net/browse/FW-2776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2804]: https://mask.atlassian.net/browse/FW-2804?atlOrigin=eyJpIjoiNWR …
> refactor: poll id

- src/helpers/fetchJSON.ts
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/lens/SocialMedia.ts
- src/services/getThreads.ts
> refactor: fetchJSON

- src/services/crossPost.ts
> refactor: sync poll in current stack

- src/services/post.ts
Closes [FW-2749](https://mask.atlassian.net/browse/FW-2749)
Closes [FW-2774](https://mask.atlassian.net/browse/FW-2774)
Closes [FW-2787](https://mask.atlassian.net/browse/FW-2787)
[FW-2749]: https://mask.atlassian.net/browse/FW-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2774]: https://mask.atlassian.net/browse/FW-2774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2787]: https://mask.atlassian.net/browse/FW-2787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: upgrade schedule api

- src/providers/types/Telemetry.ts
Closes [FW-2806](https://mask.atlassian.net/browse/FW-2806)
[FW-2806]: https://mask.atlassian.net/browse/FW-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: logs name

- src/providers/telemetry/captureSyncModalEvent.ts
- src/services/account.ts
Closes [FW-2763](https://mask.atlassian.net/browse/FW-2763)
Closes [FW-2764](https://mask.atlassian.net/browse/FW-2764)
[FW-2763]: https://mask.atlassian.net/browse/FW-2763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2764]: https://mask.atlassian.net/browse/FW-2764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: sync modal parameters

- src/components/Actions/MuteWalletButton.tsx
- src/hooks/useToggleMutedChannel.ts
- src/hooks/useToggleMutedProfile.ts
- src/providers/telemetry/captureMuteEvent.ts
Closes [FW-2765](https://mask.atlassian.net/browse/FW-2765)
Closes [FW-2766](https://mask.atlassian.net/browse/FW-2766)
Closes [FW-2769](https://mask.atlassian.net/browse/FW-2769)
[FW-2765]: https://mask.atlassian.net/browse/FW-2765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2766]: https://mask.atlassian.net/browse/FW-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2769]: https://mask.atlassian.net/browse/FW-2769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add captureMuteEvent

- src/modals/ComposeModal.tsx
- src/providers/telemetry/captureComposeEvent.ts
Closes [FW-2752](https://mask.atlassian.net/browse/FW-2752)
[FW-2752]: https://mask.atlassian.net/browse/FW-2752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: capture draft event

- src/components/Article/ArticleBody.tsx
- src/components/Article/TwitterArticleBody.tsx
- src/components/Snapshot/SnapshotBody.tsx
- src/components/Snapshot/SnapshotFallbackContent.tsx
Closes [FW-2811](https://mask.atlassian.net/browse/FW-2811)
[FW-2811]: https://mask.atlassian.net/browse/FW-2811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: article body style in compose

- src/components/Actions/MuteAllProfile.tsx
- src/providers/telemetry/captureMuteEvent.ts
Closes [FW-2765](https://mask.atlassian.net/browse/FW-2765)
> chore: mute all

- src/components/Actions/MuteAllProfile.tsx
- src/components/Actions/MuteWalletButton.tsx
- src/components/Compose/SchedulePostSettings.tsx
- src/components/Compose/ScheduleTaskList.tsx
- src/hooks/useToggleMutedChannel.ts
- src/hooks/useToggleMutedProfile.ts
- src/modals/ComposeModal.tsx
- src/providers/telemetry/captureComposeEvent.ts
- src/providers/telemetry/captureMuteEvent.ts
- src/providers/types/Telemetry.ts
- src/services/crossSchedulePost.tsx
- src/services/crossSchedulePostThread.ts
Closes [FW-2739](https://mask.atlassian.net/browse/FW-2739)
Closes [FW-2751](https://mask.atlassian.net/browse/FW-2751)
[FW-2751]: https://mask.atlassian.net/browse/FW-2751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2739]: https://mask.atlassian.net/browse/FW-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: schedule post

- src/modals/ComposeModal.tsx
- src/providers/telemetry/captureComposeEvent.ts
Closes [FW-2813](https://mask.atlassian.net/browse/FW-2813)
[FW-2813]: https://mask.atlassian.net/browse/FW-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: thread

- src/modals/ComposeModal.tsx
- src/services/metrics.ts
Closes [FW-2784](https://mask.atlassian.net/browse/FW-2784)
Closes [FW-2800](https://mask.atlassian.net/browse/FW-2800)
[FW-2784]: https://mask.atlassian.net/browse/FW-2784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2800]: https://mask.atlassian.net/browse/FW-2800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: account synced

- src/modals/ComposeModal.tsx
- src/settings/index.ts
> refactor: dev api

- src/components/CustomElements.tsx
- src/helpers/rpPayload.ts
- src/modals/ComposeModal.tsx
- src/providers/telemetry/captureLuckyDropEvent.ts
- src/providers/telemetry/captureProfileActionEvent.ts
- src/providers/telemetry/getComposeEventParameters.ts
- src/providers/telemetry/getPostEventParameters.ts
- src/providers/telemetry/getProfileEventParameters.ts
- src/providers/types/Telemetry.ts
- src/types/rp.ts
Closes [FW-2737](https://mask.atlassian.net/browse/FW-2737)
Closes [FW-2757](https://mask.atlassian.net/browse/FW-2757)
Closes [FW-2775](https://mask.atlassian.net/browse/FW-2775)
Closes [FW-2788](https://mask.atlassian.net/browse/FW-2788)
Closes [FW-2802](https://mask.atlassian.net/browse/FW-2802)
[FW-2737]: https://mask.atlassian.net/browse/FW-2737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2757]: https://mask.atlassian.net/browse/FW-2757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2775]: https://mask.atlassian.net/browse/FW-2775?atlOrigin=eyJpIjoiNWR …
> fix: rp ids

- src/components/Article/ArticleBody.tsx
- src/components/Article/ArticleHeader.tsx
https://mask.atlassian.net/browse/fw-2810
> fixup! fix: fw-2810 failed to compose author url (#3084)

- src/providers/telemetry/capturePostActionEvent.ts
- src/providers/telemetry/getPostEventParameters.ts
- src/providers/telemetry/getProfileEventParameters.ts
Closes [FW-2777](https://mask.atlassian.net/browse/FW-2777)
Closes [FW-2793](https://mask.atlassian.net/browse/FW-2793)
Closes [FW-2805](https://mask.atlassian.net/browse/FW-2805)
> refactor: self post events

- src/providers/telemetry/captureAccountEvent.ts
- src/providers/telemetry/captureComposeEvent.ts
- src/providers/telemetry/getPostEventParameters.ts
- src/services/account.ts
Closes [FW-2762](https://mask.atlassian.net/browse/FW-2762)
Closes [FW-2734](https://mask.atlassian.net/browse/FW-2734)
[FW-2762]: https://mask.atlassian.net/browse/FW-2762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: log out all accounts

- src/providers/telemetry/captureComposeEvent.ts
Closes [FW-2750](https://mask.atlassian.net/browse/FW-2750)
[FW-2750]: https://mask.atlassian.net/browse/FW-2750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: time format

- src/app/(normal)/pages/Discover.tsx
- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/components/Notification/NotificationFilter.tsx
- src/components/SourceTabs/SourceTab.tsx
- src/components/SourceTabs/index.tsx
https://mask.atlassian.net/browse/fw-2812
> fix: fw-2812 adjust color of label tab

- src/components/Compose/ComposeSend.tsx
- src/components/Compose/DraftList.tsx
- src/modals/ComposeModal.tsx
- src/store/useComposeDraftStore.ts
- src/store/useComposeStore.ts
> refactor: rename draft id state

- src/providers/telemetry/getComposeEventParameters.ts
Closes [FW-2814](https://mask.atlassian.net/browse/FW-2814)
[FW-2814]: https://mask.atlassian.net/browse/FW-2814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: is schedule

- src/helpers/polls.ts
- src/providers/farcaster/Poll.ts
- src/providers/lens/Poll.ts
- src/providers/telemetry/getComposeEventParameters.ts
- src/providers/types/Poll.ts
- src/providers/types/Telemetry.ts
- src/services/createPostTo.ts
- src/services/crossPost.ts
- src/services/crossSchedulePost.tsx
- src/store/useComposeStore.ts
> refactor: poll id map

- src/helpers/polls.ts
- src/providers/farcaster/Poll.ts
- src/providers/lens/Poll.ts
- src/providers/telemetry/getComposeEventParameters.ts
- src/providers/types/Poll.ts
- src/providers/types/Telemetry.ts
- src/services/createPostTo.ts
- src/services/crossPost.ts
- src/services/crossSchedulePost.tsx
- src/store/useComposeStore.ts
https://mask.atlassian.net/browse/FW-2804
Closes FW-0000
> fix: report x post with pollId

- src/helpers/getErrorMessageFromFetchError.ts
Closes [FW-2760](https://mask.atlassian.net/browse/FW-2760)
[FW-2760]: https://mask.atlassian.net/browse/FW-2760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: fetch error msg

- src/assets/css/limo.css
- src/assets/css/paragraph.css
Closes [FW-2818](https://mask.atlassian.net/browse/FW-2818)
[FW-2818]: https://mask.atlassian.net/browse/FW-2818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: article link color

- src/helpers/getErrorMessageFromFetchError.ts
> fix: lint error

- src/helpers/getErrorMessageFromFetchError.ts
- src/helpers/getSnackbarMessageFromError.tsx
- src/providers/telemetry/index.ts
Closes [FW-2809
](https://mask.atlassian.net/browse/FW-2809)
> fix: get safary

- src/helpers/getFrameClientProtocol.ts
- src/providers/frame/Processor.ts
> fix: compatible open frame protocol

- src/assets/notification.svg
- src/components/Article/ArticleCollect.tsx
- src/components/Notification/NotificationFilter.tsx
- src/components/SourceTabs/index.tsx
https://mask.atlassian.net/browse/fw-2817
> fix: fw-2817 collect article

- src/components/SideBar/ExclusiveEvents.tsx
> fix: event icon

- src/components/ListInPage.tsx
- src/components/NotLoginFallback.tsx
- src/components/Snapshot/SnapshotBody.tsx
- src/components/Snapshot/SnapshotChoice.tsx
- src/decorators/SetQueryDataForBookmarkPost.ts
- src/helpers/resolveFallbackImageUrl.ts
Closes [FW-2819](https://mask.atlassian.net/browse/FW-2819) FW-2820 FW-2821
[FW-2819]: https://mask.atlassian.net/browse/FW-2819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bugfix for daos

- src/app/globals.css
> fix: calendar tabs style with ssr

- src/components/SolanaWalletAdapterProvider.tsx
- src/components/WagmiProvider.tsx
- src/providers/telemetry/captureConnectWalletEvent.ts
- src/providers/types/Telemetry.ts
Closes [FW-2823](https://mask.atlassian.net/browse/FW-2823)
[FW-2824]: https://mask.atlassian.net/browse/FW-2824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2823]: https://mask.atlassian.net/browse/FW-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: connect wallet event

- src/components/SolanaWalletAdapterProvider.tsx
- src/components/WagmiProvider.tsx
Closes [FW-2827](https://mask.atlassian.net/browse/FW-2827)
[FW-2827]: https://mask.atlassian.net/browse/FW-2827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: sol addr

- src/app/(normal)/bookmarks/ArticleBookmarkList.tsx
- src/components/Snapshot/SnapshotBookmarkList.tsx
- src/components/WagmiProvider.tsx
Closes [FW-2826](https://mask.atlassian.net/browse/FW-2826)
[FW-2826]: https://mask.atlassian.net/browse/FW-2826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: snapshot bookmark

- src/app/layout-body.tsx
- src/components/Providers.tsx
- src/components/SolanaWalletAdapterProvider.tsx
- src/components/WagmiProvider.tsx
Closes [FW-2823](https://mask.atlassian.net/browse/FW-2823)
[FW-2823]: https://mask.atlassian.net/browse/FW-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: provider

- src/store/useComposeStore.ts
> fix: update pollId in post chars

- src/services/crossPost.ts
> fix: parent post

- src/app/(settings)/components/DocumentCard.tsx
- src/app/(settings)/components/LinkCard.tsx
- src/app/(settings)/settings/more/page.tsx
> fix: more page ssr

- src/helpers/getLocaleFromCookies.ts
> refactor: get from cookies

- src/app/(developers)/developers/blink/page.tsx
- src/app/(developers)/developers/frame/page.tsx
- src/app/(developers)/developers/general/page.tsx
- src/app/(developers)/developers/og/page.tsx
- src/app/(developers)/developers/session/page.tsx
- src/app/(developers)/developers/upload/page.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> refactor: developer pages

- src/app/(settings)/settings/general/page.tsx
- src/app/layout.tsx
- src/hooks/useIsDarkMode.ts
> fix: incorrect import path

- src/app/(developers)/developers/layout.tsx
- src/app/(event)/layout.tsx
- src/app/(normal)/layout.tsx
- src/app/(settings)/settings/layout.tsx
- src/app/not-found.tsx
- src/components/Advertisement/index.tsx
- src/components/SideBar/SideBarForDesktop.tsx
- src/hooks/useMediaQuery.ts
- src/modals/LoginModal/MainView.tsx
- src/modals/LoginModal/index.tsx
- tailwind.config.cjs
> refactor: breakpoints

- package.json
- src/app/(developers)/developers/layout.tsx
- src/app/(event)/layout.tsx
- src/app/(normal)/layout.tsx
- src/app/(settings)/settings/layout.tsx
- src/app/not-found.tsx
- src/components/SideBar/SideBarForDesktop.tsx
- src/hooks/useMediaQuery.ts
- src/modals/LoginModal/index.tsx
- tailwind.config.cjs
> [Release] Hotfix 6.2.14 => 6.2.15 (patch)

- src/services/crossPost.ts
> fix: use latest chars after poll updated

- src/app/(normal)/layout.tsx
- src/components/WithinDiscover.tsx
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-2828
> fix: fw-2828 sidebar content within discover

- src/app/(normal)/profile/(profile)/[source]/[id]/[category]/page.tsx
Closes [FW-2830](https://mask.atlassian.net/browse/FW-2830)
[FW-2830]: https://mask.atlassian.net/browse/FW-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: twitter user timeline require login

- src/app/(normal)/layout.tsx
- src/components/WithinDiscover.tsx
https://mask.atlassian.net/browse/fw-2828
> fixup! fix: fw-2828 sidebar content within discover (#3130)

- src/components/Channel/ChannelProvider.tsx
- src/components/SideBar/Post.tsx
- src/hooks/useCurrentVisitingChannel.ts
https://mask.atlassian.net/browse/FW-2841
Closes FW-0000
> fix: compose with current channel

- src/components/NotLoginFallback.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-2829](https://mask.atlassian.net/browse/FW-2829)
[FW-2829]: https://mask.atlassian.net/browse/FW-2829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: TW loading

- src/app/(normal)/bookmarks/[source]/page.tsx
- src/app/api/twitter/login/route.ts
- src/app/api/twitter/logout/route.ts
- src/components/ActionButton.tsx
- src/components/Actions/ShareAction.tsx
- src/components/Snapshot/SingleSnapshot.tsx
- src/components/Snapshot/SnapshotBody.tsx
- src/components/Snapshot/SnapshotResults.tsx
- src/components/Snapshot/SnapshotVotesList.tsx
- src/helpers/getSnapshotChoiceShareText.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/twitter/SessionHolder.ts
- src/providers/twitter/SocialMedia.ts
- src/services/account.ts
Closes [FW-2831](https://mask.atlassian.net/browse/FW-2831)  [FW-2834](https://mask.atlassian.net/browse/FW-2834) FW-2835 FW-2836 FW-2837 FW-2839 FW-2840 FW-2843
[FW-2831]: https://mask.atlassian.net/browse/FW-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2834]: https://mask.atlassian.net/browse/FW-2834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: snapshot bugfix

- src/components/Snapshot/SnapshotVotesList.tsx
> fix: reply review

- src/app/(settings)/settings/general/page.tsx
https://mask.atlassian.net/browse/fw-2842
> fix: fw-2842 lingui activiate locale

- src/helpers/getSnapshotChoiceShareText.ts
> fix: bugfix for snapshot share text

- src/components/Actions/ShareAction.tsx
https://mask.atlassian.net/browse/fw-2836
> fix: fw-2836 change link icon

- src/components/Snapshot/SingleSnapshot.tsx
- src/components/TextOverflowTooltip.tsx
https://mask.atlassian.net/browse/fw-2843
> fix: fw-2843 disable tooltip if not overflow

- src/components/Snapshot/SnapshotBody.tsx
- src/components/Snapshot/SnapshotResults.tsx
- src/components/Snapshot/SnapshotVotesList.tsx
- src/helpers/setupTwitterSession.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/snapshot/index.ts
Closes [FW-2834](https://mask.atlassian.net/browse/FW-2834) FW-2847 FW-2848
[FW-2834]: https://mask.atlassian.net/browse/FW-2834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: clear twitter session

- src/components/LinguiClientProvider.tsx
- src/components/Providers.tsx
- src/i18n/index.ts
> refactor: i18n provider

- src/app/(settings)/settings/general/page.tsx
- src/components/Actions/Mirrors.tsx
- src/components/InitialProviders.tsx
- src/components/LinguiClientProvider.tsx
- src/components/Providers.tsx
- src/components/Snapshot/SingleSnapshot.tsx
- src/hooks/useDetectOverflow.ts
- src/i18n/index.ts
https://mask.atlassian.net/browse/fw-2842
> fix: fw-2842 align i18n instance

- src/app/(normal)/intent/compose/pages/ShareLinkPage.tsx
- src/app/(normal)/search/[...slug]/page.tsx
- src/app/(normal)/search/[...slug]/pages/SearchChannelContent.tsx
- src/app/(normal)/search/[...slug]/pages/SearchNFTContent.tsx
- src/app/(normal)/search/[...slug]/pages/SearchPostContent.tsx
- src/app/(normal)/search/[...slug]/pages/SearchProfileContent.tsx
- src/app/(normal)/search/[...slug]/pages/SearchTokenContent.tsx
- src/components/Lexical/plugins/AtMentionsPlugin.tsx
- src/components/Search/CrossProfileItem.tsx
- src/components/Search/Empty.tsx
- src/components/Search/SearchableProfileItem.tsx
- src/helpers/formatSearchIdentities.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/types/Firefly.ts
> fix: compose x profiles in searching profiles

- src/app/(normal)/search/[...slug]/layout.tsx
- src/app/(normal)/search/[...slug]/page.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: search page title

- src/components/Snapshot/SnapshotResults.tsx
- src/components/Snapshot/SnapshotVotesList.tsx
Closes [FW-2848](https://mask.atlassian.net/browse/FW-2848) FW-2849
[FW-2848]: https://mask.atlassian.net/browse/FW-2848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: snapshot result height

- src/components/Snapshot/SnapshotBody.tsx
Closes [FW-2851](https://mask.atlassian.net/browse/FW-2851)
[FW-2851]: https://mask.atlassian.net/browse/FW-2851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: snapshot UI

- src/app/(normal)/profile/(profile)/[source]/[id]/layout.tsx
- src/app/(normal)/profile/pages/ProfilePageLayout.tsx
- src/components/Actions/ArticleMore.tsx
- src/components/Actions/SnapshotMore.tsx
Closes [FW-2852](https://mask.atlassian.net/browse/FW-2852)
[FW-2852]: https://mask.atlassian.net/browse/FW-2852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: profile ssr

- src/components/Profile/ProfileTabs.tsx
- src/components/Profile/WalletActions.tsx
- src/components/SourceTabs/index.tsx
> fix: profile tab scrollable

- src/components/Markup/Markup.tsx
https://mask.atlassian.net/browse/fw-2853
> fix: fw-2853 parsing link after url

- src/components/Snapshot/SnapshotBody.tsx
- src/providers/firefly/Bridge.ts
> fix: bridge ssr error

- src/app/(normal)/search/[...slug]/pages/SearchTokenContent.tsx
- src/components/TokenProfile/TokenMarketData.tsx
- src/components/TokenProfile/useTradeInfo.ts
- src/helpers/createMetadataToken.ts
- src/hooks/useCoinPriceStats.ts
- src/hooks/useCoinTrending.ts
- src/hooks/useTokenInfo.ts
- src/hooks/useTokenPrice.ts
- src/providers/coingecko/index.ts
- src/providers/types/CoinGecko.ts
- src/providers/types/Trending.ts
- src/services/searchTokens.ts
> refactor: rename CoinGecko Provider

- src/app/api/firefly/sponsorship/route.ts
- src/libs/JWTGenerator.ts
- src/providers/base/SessionFactory.ts
- src/providers/farcaster/Session.ts
- src/providers/warpcast/createAccountByFireflySponsorship.ts
> refactor: sponsorship

- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/components/Profile/WalletProfileContentList.tsx
- src/constants/enum.ts
- src/constants/index.ts
- src/helpers/isWalletProfileCategory.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/fw-2856
> ui: fw-2856 adjust gap in category tab

- src/components/Snapshot/SnapshotResults.tsx
- src/components/Snapshot/SnapshotVotesList.tsx
> fix: snapshot vote list

- src/providers/coingecko/index.ts
> chore: rename

- src/components/SolanaWalletAdapterProvider.tsx
> fix: remove Phantom which has been builtin

- src/components/Search/SearchableTokenItem.tsx
> fix: usd symbol

- src/components/Notification/NotificationSettings.tsx
> refactor: notification settings

- src/components/Login/LoginFarcaster.tsx
- src/components/Login/LoginFirefly.tsx
- src/providers/firefly/Session.ts
- src/providers/types/Firefly.ts
- src/services/account.ts
- src/services/bindOrRestoreFireflySession.ts
Closes [FW-2858](https://mask.atlassian.net/browse/FW-2858)
[FW-2858]: https://mask.atlassian.net/browse/FW-2858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: add is new

- src/app/(normal)/explore/[explore]/layout.tsx
- src/components/Search/SearchBar.tsx
> fix: explore ui

- src/app/not-found.tsx
- src/components/NavigatorBar/NavigatorBarForMobile.tsx
> fix: remove search filter

- src/components/Snapshot/SnapshotVotesList.tsx
> fix: vote choice overflow

- src/app/(normal)/post/[source]/[id]/pages/DetailPage.tsx
> fix: lost comment

- src/components/Login/LoginFarcaster.tsx
- src/providers/warpcast/createAccountByFireflySponsorship.ts
Closes [FW-2859](https://mask.atlassian.net/browse/FW-2859)
[FW-2859]: https://mask.atlassian.net/browse/FW-2859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: farcaster sponsorship session

- src/services/getPostLinks.ts
Closes [FW-2854](https://mask.atlassian.net/browse/FW-2854)
[FW-2854]: https://mask.atlassian.net/browse/FW-2854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: valid post link

- src/app/(settings)/settings/more/page.tsx
Closes [FW-2855](https://mask.atlassian.net/browse/FW-2855)
[FW-2855]: https://mask.atlassian.net/browse/FW-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: new firefly telegram url

- src/components/Search/SearchTabs.tsx
https://mask.atlassian.net/browse/FW-2864
Closes FW-0000
> fix: adjust tab position on search page

- src/services/bindFireflySession.ts
- src/services/restoreFireflySession.ts
> fix: bind accounts from relay service

- lingui.config.js
- src/app/(settings)/settings/wallets/page.tsx
- src/connectors/ParticleConnector.ts
- src/connectors/ParticleSolanaWallet.ts
- src/constants/error.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/firefly/Endpoint.ts
- src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/fw-2658
> fix: fw-2658 notify missing of MPC wallets

- .github/workflows/draft-released-pull-request.yml
- .github/workflows/eslint.yml
- .github/workflows/lingui.yml
- .github/workflows/prettier.yml
> fix: draft pr

- src/components/SourceTabs/index.tsx
https://mask.atlassian.net/browse/fw-2869
> fix: fw-2869 hide arrow buttons when disabled

- src/constants/regexp.ts
https://mask.atlassian.net/browse/fw-2869
> fix: do not match empty lens handle

- .github/workflows/draft-released-pull-request.yml
> refactor: draft release pr

- .github/workflows/decode-issue.yml
> fix: action name

- src/app/(normal)/explore/[explore]/layout.tsx
- src/app/(normal)/post/[source]/[id]/page.tsx
- src/components/NavigatorBar/NavigatorBarForMobile.tsx
Closes [FW-2852](https://mask.atlassian.net/browse/FW-2852) 
Closes [FW-2867](https://mask.atlassian.net/browse/FW-2867)
Closes [FW-2875](https://mask.atlassian.net/browse/FW-2875)
[FW-2852]: https://mask.atlassian.net/browse/FW-2852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: mobile mode bugfix

- crowdin.yml
- src/app/(normal)/explore/[explore]/layout.tsx
- src/app/(normal)/explore/[explore]/page.tsx
- src/app/(normal)/explore/pages/Explore.tsx
- src/components/ChannelInList.tsx
- src/components/ProfileInList.tsx
- src/components/Search/SearchableTokenItem.tsx
- src/constants/index.ts
- src/helpers/resolveExploreUrl.ts
- src/providers/coingecko/index.ts
Closes [FW-2871](https://mask.atlassian.net/browse/FW-2871) FW-2872 FW-2874
> fix: explore mobile ui

- src/components/Snapshot/FollowingSnapshotList.tsx
Closes [FW-2882](https://mask.atlassian.net/browse/FW-2882)
[FW-2882]: https://mask.atlassian.net/browse/FW-2882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: login require in following list

- .github/workflows/eslint.yml
> fix: ci actions

- src/app/(normal)/nft/[chainIdOrCollectionId]/[addressOrTokenId]/page.tsx
- src/app/(normal)/nft/pages/NFTCollectionPage.tsx
- src/app/(normal)/nft/pages/NFTDetailPage.tsx
- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/components/CollectionDetail/CollectionInfo.tsx
- src/components/CollectionDetail/CollectionTabs.tsx
- src/components/CollectionDetail/NFTCollection.tsx
- src/components/CollectionDetail/NFTList.tsx
- src/components/CollectionDetail/NFTListByCollectionId.tsx
- src/components/CollectionDetail/TopCollectors.tsx
- src/components/NFTDetail/Attendees.tsx
- src/components/NFTDetail/ChainIcon.tsx
- src/components/NFTDetail/NFTInfo.tsx
- src/components/NFTDetail/NFTOverflow.tsx
- src/components/Profile/POAPList.tsx
- src/components/Profile/WalletProfileContentList.tsx
- src/constants/index.ts
- src/helpers/createMetadataNFT.ts
- src/helpers/parseChainId.ts
- src/helpers/resolveExplorer.ts
- src/helpers/resolveNftUrl.ts
- src/helpers/resolveProfileUrl.ts
- src/helpers/resolveWalletProfileProvider.ts
- src/hooks/useNFTCollection.tsx
- src/hooks/useNFTDetail.ts
- src/hooks/usePoapAttendeesCount.ts
- src/providers/simplehash/EVMWalletProfile.ts
- src/providers/simplehash/SolanaWalletProfile.ts
- src/providers/types/WalletProfile.ts
https://mask.atlassian.net/browse/FW-2861
Closes FW-0000
> feat: support Solana NFT

- src/components/NotLoginFallback.tsx
- src/components/Polymarket/PolymarketActivityItem.tsx
- src/components/Polymarket/PolymarketActivityResult.tsx
- src/components/Polymarket/PolymarketTimeLine.tsx
- src/constants/enum.ts
- src/helpers/formatCommentCounts.ts
- src/helpers/resolveFallbackImageUrl.ts
https://mask.atlassian.net/browse/FW-2885
https://mask.atlassian.net/browse/FW-2887
https://mask.atlassian.net/browse/FW-2888
Closes FW-0000
> fix: polymarket ui bugs

- src/components/BackButton.tsx
- src/components/Search/SearchRecommendation.tsx
https://mask.atlassian.net/browse/FW-2876
https://mask.atlassian.net/browse/FW-2873
Closes FW-0000
> fix: search ui bugs

- src/components/CollectionDetail/NFTList.tsx
- src/providers/simplehash/EVMWalletProfile.ts
- src/providers/types/WalletProfile.ts
> fix: skip score check in nft list

- src/connectors/ParticleConnector.ts
- src/connectors/ParticleSolanaWallet.ts
> fix: disable alert message when auto connect

- src/constants/env.ts
> chore: add envs

- src/components/NFTDetail/NFTOverflow.tsx
> fix: solana nft standard

- src/components/Polymarket/PolymarketActivityItem.tsx
- src/components/Polymarket/PolymarketTimeLine.tsx
- src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/FW-2899
https://mask.atlassian.net/browse/FW-2901
https://mask.atlassian.net/browse/FW-2902
Closes FW-0000
> fix: add following source for polymarket list

- src/decorators/SetQueryDataForBlockWallet.ts
- src/decorators/SetQueryDataForWatchWallet.ts
https://mask.atlassian.net/browse/FW-2900
Closes FW-0000
> fix: update query data for polymarket

- src/app/(normal)/search/[...slug]/pages/SearchProfileContent.tsx
- src/components/Search/SearchableProfileItem.tsx
- src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/FW-2903
Closes FW-0000
> fix: special handle for x avatar on searching users

- src/components/Polymarket/PolymarketActivityItem.tsx
- src/components/Polymarket/PolymarketActivityRate.tsx
- src/components/Polymarket/PolymarketActivityResult.tsx
https://mask.atlassian.net/browse/FW-2909
Closes FW-0000
> fix: support more choice on polymarket

- src/providers/simplehash/SolanaWalletProfile.ts
> fix: skip score check in solana nft

- .github/workflows/maintenance.yml
> fix: commit all

- src/connectors/ParticleConnector.ts
> refactor: FW-29212

- src/app/(settings)/components/AccountCard.tsx
- src/services/getPostLinks.ts
Closes [FW-2916](https://mask.atlassian.net/browse/FW-2916)
[FW-2916]: https://mask.atlassian.net/browse/FW-2916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: blink sdk type and disconnect account button

- src/components/Posts/PostBody.tsx
> fix: optimize compose on quoting and replying

- src/providers/types/Firefly.ts
- src/services/bindFireflySession.ts
> fix: create account from relay service

- src/app/(normal)/article/[id]/not-found.tsx
- src/app/(normal)/channel/[id]/not-found.tsx
- src/app/(normal)/nft/[chainIdOrCollectionId]/not-found.tsx
- src/app/(normal)/post/[source]/not-found.tsx
- src/app/(normal)/profile/not-found.tsx
- src/app/(normal)/token/[symbol]/not-found.tsx
- src/components/NotFound.tsx
> refactor: Trans

- src/app/(normal)/article/[id]/not-found.tsx
- src/app/(normal)/channel/[id]/not-found.tsx
- src/app/(normal)/nft/[chainIdOrCollectionId]/not-found.tsx
- src/app/(normal)/post/[source]/[id]/pages/DetailPage.tsx
- src/app/(normal)/post/[source]/not-found.tsx
- src/app/(normal)/profile/(profile)/[source]/[id]/layout.tsx
- src/app/(normal)/profile/not-found.tsx
- src/app/(normal)/token/[symbol]/not-found.tsx
- src/components/NotFound.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2911
Closes FW-0000
> feat: 404 page

- src/components/Channel/SuggestedChannels.tsx
- src/constants/enum.ts
- src/constants/index.ts
https://mask.atlassian.net/browse/FW-2925
Closes FW-0000
> fix: link for channel trending more button

- src/modals/DisconnectFireflyAccountModal.tsx
- src/services/account.ts
Closes [FW-2920](https://mask.atlassian.net/browse/FW-2920) 
Closes [FW-2919](https://mask.atlassian.net/browse/FW-2919)
[FW-2920]: https://mask.atlassian.net/browse/FW-2920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-2919]: https://mask.atlassian.net/browse/FW-2919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: disconnect account without x logout

- src/helpers/enqueueMessage.tsx
> refactor: detect rejection error

- src/helpers/enqueueMessage.tsx
https://mask.atlassian.net/browse/FW-2922
Closes FW-0000
> fix: show warning when user rejected

- src/services/account.ts
Closes [FW-2883](https://mask.atlassian.net/browse/FW-2883)
[FW-2883]: https://mask.atlassian.net/browse/FW-2883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: login with overwrite cannot sync the twitter token

- src/providers/base/SessionFactory.ts
- src/providers/firefly/Session.ts
- src/providers/firefly/createAccountByGrantPermission.ts
- src/providers/firefly/createAccountBySignMessage.ts
- src/providers/telemetry/captureAccountEvent.ts
- src/providers/types/Firefly.ts
- src/services/account.ts
- src/services/restoreFireflySession.ts
> chore: add captureAccountCreateSuccessEvent

- src/providers/firefly/Endpoint.ts
> fix: search identities

- src/app/(settings)/components/ConnectMPCWalletButton.tsx
- src/app/(settings)/components/WalletItem.tsx
- src/components/Calendar/EventList.tsx
- src/components/Calendar/hooks/useEventList.tsx
- src/components/Compose/ScheduleTaskList.tsx
- src/components/NFTDetail/ChainIcon.tsx
- src/components/SideBar/ConnectWallet.tsx
- src/components/SolanaAccountModal.tsx
- src/components/Tips/TokenItem.tsx
- src/components/TokenProfile/ContractList.tsx
- src/components/TokenProfile/TokenDetail.tsx
- src/helpers/getChainInfo.ts
- src/helpers/getNetworkDescriptor.ts
- src/helpers/resolveCreateSchedulePostPayload.ts
- src/helpers/resolveLensQuery.ts
- src/helpers/resolveTokenTransfer.ts
- src/hooks/useTipsTokens.ts
- src/hooks/useTipsValidation.ts
- src/modals/ConnectWalletModal.tsx
- src/modals/SchedulePostModal.tsx
- src/modals/TipsModal.tsx
- src/providers/ethereum/Transfer.ts
- src/providers/firefly/Activity.ts
- src/providers/solana/Transfer.ts
- src/providers/solana/resolveSolanaWalletAdapter.ts
- src/providers/telemetry/captureActivityEvent.ts
- src/providers/types/Activity.ts
- tsconfig.json
Closes [FW-2930](https://mask.atlassian.net/browse/FW-2930)
[FW-2930]: https://mask.atlassian.net/browse/FW-2930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: use local helpers

- src/helpers/getChainInfo.ts
> fix: chain icon import url

- src/app/(normal)/token/[symbol]/not-found.tsx
- src/components/NotFound.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2943
Closes FW-0000
> fix: token detail ui

- src/app/globals.css
- src/hooks/usePriceLineChart.ts
pick from main branch
https://mask.atlassian.net/browse/fw-2832
> fix: fw-2832 color of price chart

- src/app/(whiteboard)/telegram/login/page.tsx
- src/providers/telemetry/captureAccountEvent.ts
- src/providers/types/SocialMedia.ts
- src/providers/types/Telemetry.ts
- src/services/account.ts
- src/store/useProfileStore.ts
> refactor: rename authSource => profileSource

- src/app/(whiteboard)/telegram/login/page.tsx
> chore: remove useless options

- src/components/Search/SearchableProfileItem.tsx
- src/providers/snapshot/index.ts
Closes [FW-2948](https://mask.atlassian.net/browse/FW-2948) FW-2949
[FW-2948]: https://mask.atlassian.net/browse/FW-2948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bugfix for snapshot link

- src/components/Profile/ProfileTabs.tsx
- src/components/SourceTabs/index.tsx
https://mask.atlassian.net/browse/fw-2947
> fix: fw-2947 scroll active tab into view

- src/components/Profile/FollowButton.tsx
Closes [FW-2954](https://mask.atlassian.net/browse/FW-2954)
[FW-2954]: https://mask.atlassian.net/browse/FW-2954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bugfix for follow button

- src/components/ChannelInList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-2955](https://mask.atlassian.net/browse/FW-2955)
[FW-2955]: https://mask.atlassian.net/browse/FW-2955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: suggest channel cell ui

- src/constants/error.ts
https://mask.atlassian.net/browse/FW-2927
Closes FW-0000
> fix: parse error message from html

- src/configs/sentryClient.ts
> refactor: import from sentry

- src/app/(normal)/layout.tsx
- src/app/(normal)/search/[...slug]/pages/SearchPostContent.tsx
https://mask.atlassian.net/browse/FW-2952
https://mask.atlassian.net/browse/FW-2953
Closes FW-0000
> fix: search ui for mobile mode

- src/app/(normal)/layout.tsx
- src/components/SourceTabs/index.tsx
https://mask.atlassian.net/browse/FW-2966
Closes FW-0000
> fix: Modal z-index

- src/helpers/createTwitterSessionPayload.ts
> fix: reading x auth token from undefined

- src/helpers/getSnackbarMessageFromError.tsx
> fix: lowercase for solana error message

- src/components/Calendar/EventList.tsx
- src/components/Calendar/NewsList.tsx
- src/components/Calendar/hooks/useEventList.ts
- src/components/Calendar/hooks/useLumaEvents.ts
- src/providers/calendar/index.ts
> fix: fetch all events within the time range

- src/app/(settings)/components/AccountCard.tsx
https://mask.atlassian.net/browse/fw-2942
> fix: fw-2942 login idle accounts

- src/app/(normal)/notifications/[source]/page.tsx
- src/app/(settings)/settings/page.tsx
- src/components/Notification/NotificationSettings.tsx
- src/hooks/useNotificationSettings.ts
- src/providers/lens/SocialMedia.ts
- src/providers/types/SocialMedia.ts
Closes [FW-2968](https://mask.atlassian.net/browse/FW-2968) FW-2946
[FW-2968]: https://mask.atlassian.net/browse/FW-2968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: support high signal filter for lens notifications

- src/app/(normal)/search/[...slug]/pages/SearchProfileContent.tsx
- src/app/(settings)/components/AccountCard.tsx
- src/components/Notification/NotificationItem.tsx
- src/components/Search/SearchRecommendation.tsx
- src/helpers/isSameProfile.ts
- src/hooks/useCurrentFireflyProfiles.ts
- src/services/account.ts
https://mask.atlassian.net/browse/fw-2942
https://mask.atlassian.net/browse/FW-2973
> fixup! fix: fw-2942 login idle accounts

- src/connectors/ParticleSolanaWallet.ts
- src/constants/error.ts
> refactor: fw 2972

- src/app/(settings)/components/ConnectMPCWalletButton.tsx
- src/components/SideBar/ConnectWallet.tsx
- src/connectors/ParticleSolanaWallet.ts
- src/constants/error.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-2972
Closes FW-0000
> fix: display loading when wallet is connecting

- src/components/SideBar/ConnectWallet.tsx
- src/hooks/useNotificationSettings.ts
- src/mask/setup/custom-event-provider.ts
> fix: connection

- src/app/(settings)/settings/page.tsx
Closes [FW-2946](https://mask.atlassian.net/browse/FW-2946)
[FW-2946]: https://mask.atlassian.net/browse/FW-2946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: settings for mobile

- src/app/(normal)/search/[...slug]/pages/SearchTokenContent.tsx
- src/app/(normal)/token/[symbol]/layout.tsx
- src/components/Search/SearchableTokenItem.tsx
- src/components/TokenProfile/TokenMarketData.tsx
- src/helpers/createMetadataToken.ts
- src/hooks/useNotificationSettings.ts
- src/hooks/useTokenInfo.ts
- src/providers/types/CoinGecko.ts
- src/services/getTokenFromCoinGecko.ts
https://mask.atlassian.net/browse/FW-2971
Closes FW-0000
> feat: support more token profile

- src/helpers/getSnackbarMessageFromError.tsx
> fix: capture solana wallet error message

- src/components/SourceTabs/index.tsx
> fix: remove tabs arrows

- src/app/api/auth/[...nextauth]/options.ts
- src/components/ProfileAvatar.tsx
- src/helpers/resolveSource.ts
- src/modals/LoginModal/MainView.tsx
- src/services/account.ts
- src/store/useProfileStore.ts
> fix: third party login

- src/services/bindFireflySession.ts
> refactor: auth error

- src/components/Login/LoginFarcaster.tsx
- src/constants/error.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/services/bindFireflySession.ts
Closes [FW-2939](https://mask.atlassian.net/browse/FW-2939)
[FW-2939]: https://mask.atlassian.net/browse/FW-2939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FarcasterAlreadyBoundError

- src/components/Compose/ComposeActions/index.tsx
- src/components/SideBar/ConnectWallet.tsx
- src/hooks/useConnections.ts
- src/mask/setup/wallet.ts
- src/modals/ComposeModal.tsx
- src/store/useGlobalStore.ts
> refactor: web3 state async status

- src/app/(normal)/post/[source]/[id]/pages/DetailPage.tsx
> fix: invalid exclude comments

- src/hooks/useConnections.ts
> fix: disable loading when wallet auto connect

- src/components/Login/ProfileInList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/ConfirmFireflyModal.tsx
- src/modals/DisconnectFireflyAccountModal.tsx
- src/modals/LogoutModal.tsx
> fix: alert message on disconnecting account

- src/components/Login/LoginFarcaster.tsx
- src/helpers/fetch.ts
- src/helpers/fetchArrayBuffer.ts
- src/helpers/fetchBlob.ts
- src/helpers/fetchGlobal.ts
- src/helpers/fetchJSON.ts
- src/helpers/fetchText.ts
- src/helpers/getNextFetchers.ts
- src/providers/base/SessionHolder.ts
- src/providers/farcaster/SessionHolder.ts
- src/providers/firefly/Endpoint.ts
- src/providers/firefly/SessionHolder.ts
- src/providers/firefly/SocialMedia.ts
- src/providers/third-party/SessionHolder.ts
- src/providers/twitter/SessionHolder.ts
- src/providers/twitter/SocialMedia.ts
- src/providers/warpcast/SocialMedia.ts
- src/services/bindFireflySession.ts
- src/services/metrics.ts
- src/services/post.ts
- src/services/reportCrossedPost.ts
Closes [FW-2939](https://mask.atlassian.net/browse/FW-2939)
[FW-2939]: https://mask.atlassian.net/browse/FW-2939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: fetch

- src/components/Activity/ActivityMobileNavigationBar.tsx
- src/components/Activity/ActivityTasks/ActivityFrensgivingTasks.tsx
- src/components/Activity/hooks/useActivityCurrentAccountHandle.ts
- src/components/Activity/hooks/useActivityShareUrl.ts
- src/helpers/resolveActivityUrl.ts
Closes [FW-2996](https://mask.atlassian.net/browse/FW-2996)
[FW-2996]: https://mask.atlassian.net/browse/FW-2996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: activity share url

- src/helpers/formatSearchIdentities.ts
- src/providers/types/Firefly.ts
https://mask.atlassian.net/browse/FW-2998
Closes FW-0000
> fix: wallet profile link in search page

- src/components/Profile/WalletInfo.tsx
https://mask.atlassian.net/browse/FW-2997
Closes FW-0000
> fix: disable watch for solana profile

- src/components/Activity/ActivityConnectCard.tsx
- src/components/Activity/ActivityFollowTargetCard.tsx
- src/components/Activity/ActivityLoginButton.tsx
- src/components/Activity/ActivityPremiumConditionList.tsx
- src/components/Activity/ActivityTaskFollowCard.tsx
- src/components/Activity/ActivityTasks/ActivityFrensgivingTasks.tsx
- src/components/Activity/hooks/useActivityShareUrl.ts
> feat: connecting status and text weight on event page

- src/components/Article/ArticleDetailContent.tsx
Closes [FW-2999](https://mask.atlassian.net/browse/FW-2999)
[FW-2999]: https://mask.atlassian.net/browse/FW-2999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: come back for article detail page

- src/components/Compose/ComposeActions/index.tsx
- src/modals/ConnectWalletModal.tsx
Closes [FW-3003](https://mask.atlassian.net/browse/FW-3003)
[FW-3003]: https://mask.atlassian.net/browse/FW-3003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: rp open wallet connect modal

- src/components/Comments/index.tsx
- src/components/Posts/PostBody.tsx
> fix: wait twitter async status

- src/components/Article/ArticleBody.tsx
> fix: cover url

- src/components/Activity/ActivityConnectButton.tsx
- src/components/Activity/hooks/useActivityConnections.ts
> feat: activity login status on mobile

- src/app/(whiteboard)/login/desktop/page.tsx
> fix: login desktop ssr

- src/providers/types/ThirdParty.ts
- src/store/useImpressionsStore.ts
- src/store/useProfileStore.ts
Closes [FW-3006](https://mask.atlassian.net/browse/FW-3006)
> fix: twitter state

- src/app/api/firefly/sponsorship/route.ts
- src/app/api/warpcast/signin/route.ts
- src/providers/warpcast/createAccountByFireflySponsorship.ts
- src/providers/warpcast/createAccountByGrantPermission.ts
- src/providers/warpcast/signedKeyRequests.ts
> refactor: sign key request

- src/components/Activity/hooks/useActivityPremiumList.tsx
> feat: event frensgiving premium condition

- src/app/(settings)/components/AccountCard.tsx
Closes [FW-3001](https://mask.atlassian.net/browse/FW-3001)
> fix: auto open connect modal on account settings page

- package.json
- pnpm-lock.yaml
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: pin mui/material to fix align mui dialog sub components

- src/app/(normal)/channel/[source]/[id]/[type]/layout.tsx
- src/app/globals.css
- src/components/Compose/ComposeActions/index.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/mask/components/MaskProviders.tsx
- src/mask/plugins/red-packet/components/FireflyRedpacketConfirmDialog.tsx
- src/mask/plugins/red-packet/components/RedPacket/index.tsx
- src/mask/plugins/red-packet/components/Requirements/index.tsx
> fix: disable shadowroot for mask components

- src/components/Channel/ChannelMoreAction.tsx
- src/helpers/formatOrbClubToChannel.ts
- src/providers/types/Orb.ts
- src/providers/types/SocialMedia.ts
> feat: disable joining private orb club

- src/providers/lens/SocialMedia.ts
https://mask.atlassian.net/browse/FW-3016
Closes FW-0000
> fix: edit lens profile

- src/components/Posts/ChannelAnchor.tsx
- src/components/SideBar/Post.tsx
- src/hooks/useCurrentVisitingChannel.ts
https://mask.atlassian.net/browse/FW-3017
https://mask.atlassian.net/browse/FW-3018
https://mask.atlassian.net/browse/FW-3020
Closes FW-0000
> fix: remove suspense query in channel anchor

- src/helpers/enqueueMessage.tsx
- src/mask/plugins/red-packet/components/FireflyRedPacketDetailsItem.tsx
- src/mask/plugins/red-packet/components/RedPacket/index.tsx
- src/mask/plugins/red-packet/components/Requirements/index.tsx
- src/mask/plugins/red-packet/hooks/useClaimStrategyStatus.ts
- src/mask/plugins/red-packet/hooks/useParseRedPacket.ts
> refactor: remove web3-*

- src/app/api/warpcast/signin/route.ts
- src/components/Frame/index.tsx
- src/components/NFTDetail/NFTInfo.tsx
- src/components/Oembed/Mirror.tsx
- src/components/Posts/PostCollect.tsx
- src/components/Profile/POAPList.tsx
- src/components/Snapshot/SnapshotBody.tsx
- src/components/Snapshot/SnapshotVotesList.tsx
- src/helpers/createWagmiTestWalletClient.ts
- src/helpers/ed25519.ts
- src/providers/og/readers/payload.ts
- src/providers/types/Hubble.ts
- src/providers/warpcast/createAccountByGrantPermission.ts
- src/types/og.ts
> refactor: hex

- src/hooks/useCurrentVisitingPost.ts
- src/hooks/useValueRef.ts
> fix: value ref on server

- src/mask/setup/wallet.ts
> fix: send rp tx

- src/components/Search/SearchContentPanel.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/TokenSelectorModal.tsx
> fix: fallback/error ui in search modal

- src/components/ActivityCell/NFTs/NFTsActivityCellCard.tsx
- src/components/ActivityCell/NFTs/NFTsBookmarkButton.tsx
- src/components/NFTs/BookmarkButton.tsx
- src/components/NFTs/SingleNFTFeed.tsx
- src/helpers/resolveNFTIdFromAsset.ts
> feat: add bookmark button

- src/components/NFTDetail/NFTInfo.tsx
- src/components/NFTs/NFTPreview.tsx
https://mask.atlassian.net/browse/FW-3026
https://mask.atlassian.net/browse/FW-3027
Closes FW-0000
> fix: nft ui

- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/components/Notification/NotificationSettings.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-3025](https://mask.atlassian.net/browse/FW-3025)
[FW-3025]: https://mask.atlassian.net/browse/FW-3025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: locales

- src/components/NFTs/BookmarkButton.tsx
- src/components/Profile/NFTCollectionList.tsx
- src/components/Profile/POAPList.tsx
https://mask.atlassian.net/browse/FW-3028
Closes FW-0000
> fix: add bookmark button in wallet profile

- src/components/Posts/EncryptedPost.tsx
- src/components/Posts/PostBody.tsx
- src/constants/index.ts
- src/helpers/createLensSDK.ts
- src/helpers/formatLensPost.ts
- src/hooks/useDecryptPost.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/farcaster/SocialMedia.ts
- src/providers/firefly/SocialMedia.ts
- src/providers/hubble/SocialMedia.ts
- src/providers/lens/SessionHolder.ts
- src/providers/lens/SocialMedia.ts
- src/providers/neynar/SocialMedia.ts
- src/providers/twitter/SocialMedia.ts
- src/providers/types/SocialMedia.ts
- src/providers/warpcast/SocialMedia.ts
> feat: support decrypt lens post

- src/mask/plugins/red-packet/components/RedPacketDialog.tsx
- src/mask/plugins/red-packet/components/RedPacketERC20Form.tsx
> refactor: sync sub modules

- cspell.json
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/mask/bindings/components.ts
- src/mask/plugins/red-packet/components/RedPacket/OperationFooter.tsx
- src/mask/plugins/red-packet/components/RedPacket/index.tsx
- src/mask/plugins/red-packet/components/WalletConnectedBoundary.tsx
- src/mask/plugins/red-packet/hooks/useCheckSponsorableGasFee.ts
- src/mask/plugins/red-packet/hooks/useClaimCallback.ts
- src/providers/red-packet/index.ts
Closes [FW-2988](https://mask.atlassian.net/browse/FW-2988)
[FW-2988]: https://mask.atlassian.net/browse/FW-2988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: gasless to claim of red packet

- src/helpers/resolveSourceName.ts
Closes [FW-3029](https://mask.atlassian.net/browse/FW-3029)
[FW-3029]: https://mask.atlassian.net/browse/FW-3029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: resolveSourceName

- src/providers/firefly/Endpoint.ts
- src/providers/telemetry/captureActivityEvent.ts
- src/providers/types/Firefly.ts
> feat: support x handle in profile route

- cspell.json
- src/hooks/useCreateFTRedpacketCallback.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/mask/plugins/red-packet/constants.ts
- src/modals/ComposeModal.tsx
- src/modals/RedpacketModal/ConfirmView.tsx
- src/modals/RedpacketModal/RedpacketContext.tsx
- src/modals/RedpacketModal/ShareAccountsPopover.tsx
> feat: create rp

- src/components/Posts/EncryptedPost.tsx
- src/components/Posts/PostBody.tsx
- src/components/Posts/PostBodyContent.tsx
- src/hooks/useDecryptPost.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> refactor: avoid loops in PostBody

- src/hooks/useCreateFTRedpacketCallback.ts
- src/modals/controls.ts
> fix: rp import

- src/app/(normal)/search/[...slug]/pages/SearchProfileContent.tsx
- src/components/Search/SearchableProfileItem.tsx
- src/providers/firefly/Endpoint.ts
> fix: add missed cursor in search profiles

- src/components/Tabs/SolidTabs.tsx
- src/constants/index.ts
https://mask.atlassian.net/browse/FW-3030
Closes FW-0000
> fix: adjust tab sort in bookmark page

- src/app/(normal)/bookmarks/NFTBookmarkList.tsx
- src/components/NFTs/NFTPreview.tsx
- src/helpers/resolveNFTImageUrl.ts
https://mask.atlassian.net/browse/FW-3036
Closes FW-0000
> feat: resolve nft image url

- src/app/layout.tsx
- src/components/Actions/Mirrors.tsx
- src/components/Actions/More.tsx
- src/components/Actions/ReportPostButton.tsx
- src/components/Actions/ReportProfileButton.tsx
- src/components/Login/ProfileSettings.tsx
- src/components/MoreActionMenu.tsx
> refactor: react scan

- src/components/Advertisement/Swiper.tsx
- src/constants/enum.ts
- src/modals/controls.ts
> feat: clean cz event code

- src/components/CollectionDetail/NFTList.tsx
- src/components/Profile/POAPList.tsx
- src/components/WalletBaseMoreAction.tsx
- src/services/fillBookmarkStatusForNFT.ts
https://mask.atlassian.net/browse/FW-3035
Closes FW-0000
> fix: remove bookmark button in WalletBaseMoreAction & batch query

- src/components/Profile/Info.tsx
Closes [FW-3023](https://mask.atlassian.net/browse/FW-3023)
[FW-3023]: https://mask.atlassian.net/browse/FW-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fixed the issue of not refreshing the profile after edit profile

- package.json
- pnpm-lock.yaml
- src/mask/plugins/red-packet/components/RedPacketConfirmDialog.tsx
> refactor: launch icon

- pnpm-lock.yaml
> chore: lock file

- src/components/Advertisement/index.tsx
> fix: fixed advertisement env

- src/components/Posts/PostBody.tsx
- src/helpers/createLensSDK.ts
- src/providers/lens/SessionHolder.ts
- src/providers/lens/SocialMedia.ts
> fix: rm lens gate

- src/components/RedPacket/AmountProgressText.tsx
- src/components/RedPacket/Cover.tsx
- src/components/RedPacket/CoverContainer.tsx
- src/components/RedPacket/PayloadContainer.tsx
- src/helpers/formatCommentCounts.ts
- src/services/createRedPacketImage.tsx
Closes [FW-3504](https://mask.atlassian.net/browse/FW-3504) FW-3503 FW-3501
> fix: cover generate

- src/app/api/rp/route.tsx
Closes [FW-3055](https://mask.atlassian.net/browse/FW-3055)
> fix: emoji message length

- src/components/Compose/ComposeImages.tsx
- src/components/RedPacket/AmountProgressText.tsx
- src/components/RedPacket/CoverContainer.tsx
- src/components/RedPacket/PayloadContainer.tsx
- src/helpers/formatCommentCounts.ts
- src/helpers/resolveMediaObjectUrl.ts
- src/modals/ComposeModal.tsx
- src/types/compose.ts
> fix: rp cover bugfix

- src/components/RedPacket/AmountProgressText.tsx
- src/helpers/formatPrice.tsx
> chore: shrank display

- src/components/Markup/MarkupLink/index.tsx
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: lens handle color

- src/app/api/rp/route.tsx
- src/assets/arrow-circle.svg
- src/components/RedPacket/AmountProgressText.tsx
- src/components/RedPacket/AuthorText.tsx
- src/components/RedPacket/ClaimProgressText.tsx
- src/components/RedPacket/Cover.tsx
- src/components/RedPacket/CoverContainer.tsx
- src/components/RedPacket/MessageText.tsx
- src/components/RedPacket/Payload.tsx
- src/components/RedPacket/PayloadContainer.tsx
- src/components/Tabs/index.tsx
- src/helpers/hexToRGBA.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/RedPacketModal/ConfirmView.tsx
- src/modals/RedPacketModal/MainView.tsx
- src/modals/RedPacketModal/RedPacketContext.tsx
- src/providers/red-packet/index.ts
- src/services/createRedPacketImage.tsx
> feat: default rp cover

- src/hooks/useDecryptPost.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: error message on decrypting post

- src/hooks/useCreateFTRedPacketCallback.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/RedPacketModal/ConfirmView.tsx
- src/modals/RedPacketModal/RedPacketContext.tsx
> fix: upload redpacket payload

- next.config.js
> chore: next image conf

- src/app/api/og/post/[source]/[postId]/image/route.tsx
- src/components/RedPacket/AmountProgressText.tsx
- src/components/RedPacket/RedPacketCard.tsx
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/RedPacketModal/ConfirmView.tsx
- src/services/createRedPacketImage.tsx
> fix: bugfix for rp

- src/components/Posts/PostBodyContent.tsx
> fix: skip waiting for decrypting rp payload

- src/app/api/rp/route.tsx
- src/providers/frame/Processor.ts
> fix: log failed reason

- src/app/api/og/post/[source]/[postId]/image/route.tsx
- src/app/globals.css
- src/assets/disable-no.svg
- src/assets/radio-off.svg
> refactor: change light bg color

- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/services/createRedPacketImage.tsx
> fix: log getting theme result

- src/store/useDeveloperSettingsStore.ts
> fix: dev api

- src/app/api/og/post/[source]/[postId]/image/route.tsx
- src/components/RedPacket/AuthorText.tsx
- src/components/RedPacket/PayloadContainer.tsx
> fix: bugfix for rp cover

- src/store/useDeveloperSettingsStore.ts
> fix: invalid state

- src/components/Frame/Layout.tsx
- src/components/Frame/V2/Card.tsx
- src/components/Frame/V2/Layout.tsx
- src/constants/env.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/RedPacketModal/ConfirmView.tsx
- src/services/getPostLinks.ts
http://localhost:3000/post/farcaster/0x5ad7183c00feb142b703d0c473a86d1a41b3f053
Closes FW-0000
> feat: impl frame v2 in timeline

- src/components/Search/SearchTokenPanel.tsx
https://mask.atlassian.net/browse/FW-3093
Closes FW-0000
> fix: support search token by contract

- src/helpers/patchNotificationQueryData.ts
https://mask.atlassian.net/browse/FW-3100
Closes FW-0000
> fix: sync like status

- src/components/ActivityCell/ActivityCellActionTag.tsx
Closes [FW-3076](https://mask.atlassian.net/browse/FW-3076)
[FW-3076]: https://mask.atlassian.net/browse/FW-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FW-3076 tag line break

- src/components/Activity/ActivityTasks/index.tsx
- src/components/Search/SearchSources.tsx
Closes [FW-3075](https://mask.atlassian.net/browse/FW-3075)
[FW-3075]: https://mask.atlassian.net/browse/FW-3075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: disable lens and x when searching for profile posts

- src/components/HideComments.tsx
> fix: rename queryKey in comment list

- src/components/EditProfile/EditProfileForm.tsx
- src/constants/limitation.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-3023](https://mask.atlassian.net/browse/FW-3023)
[FW-3023]: https://mask.atlassian.net/browse/FW-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: edit profile bio min size

- cspell.json
- src/components/Activity/ActivityClaimButton.tsx
- src/components/Activity/ActivityContext.tsx
- src/components/Activity/ActivityFollowTargetCard.tsx
- src/components/Activity/ActivityMobileOnly.tsx
- src/components/Activity/ActivityPremiumAddressVerifyButton.tsx
- src/components/Activity/ActivityPremiumAddressVerifyCard.tsx
- src/components/Activity/ActivityPremiumConditionList.tsx
- src/components/Activity/ActivityTasks/ActivityElex24Tasks.tsx
- src/components/Activity/ActivityTasks/ActivityFrensgivingTasks.tsx
- src/components/Activity/ActivityTasks/ActivityHlblTasks.tsx
- src/components/Activity/ActivityTasks/ActivityPenguTasks.tsx
- src/components/Activity/ActivityTasks/index.tsx
- src/components/Activity/hooks/useActivityBindAddress.ts
- src/components/Activity/hooks/useActivityClaimCondition.ts
- src/components/Activity/hooks/useActivityPremiumList.tsx
- src/constants/index.ts
- src/constants/mentions.ts
- src/helpers/chars.ts
- src/helpers/replaceObjectInStringArray.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/firefly/Activity.ts
- src/providers/types/Activity.ts
- tests/helpers/replaceObjectInStringArray.ts
> feat: pick event pengu

- src/components/Activity/ActivityClaimButton.tsx
- src/components/Activity/ActivityMintSuccessDialog.tsx
- src/components/Activity/ActivityTasks/ActivityPenguTasks.tsx
- src/providers/types/Activity.ts
> feat: solana explorer and claim params

- src/components/Activity/ActivityHeader.tsx
- src/components/Activity/ActivityTasks/ActivityPenguTasks.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-3114](https://mask.atlassian.net/browse/FW-3114)
[FW-3114]: https://mask.atlassian.net/browse/FW-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: event pengu text

- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/DisconnectFireflyAccountModal.tsx
- src/services/account.ts
> fix: disconnect thirdparty account

- src/components/RedPacket/RedPacketCard.tsx
- src/components/RedPacket/RedPacketCardFooter.tsx
- src/components/RedPacket/RedPacketInspector.tsx
- src/components/RedPacket/RequirementsModal.tsx
- src/components/RedPacket/useVerifyAndClaim.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/mask/plugins/red-packet/hooks/useClaimStrategyStatus.ts
- src/services/createRedPacketImage.tsx
https://mask.atlassian.net/browse/fw-3096
> fix: fw-3096 verify and claim

- src/app/(settings)/components/ThirdPartAccounts.tsx
- src/app/(settings)/components/ThirdPartDisconnectButton.tsx
- src/providers/types/Firefly.ts
> fix: only show connected third account in settings

- src/helpers/getEncryptedPayload.ts
- src/locales/ja/messages.po
- src/services/decryptPayload.ts
https://mask.atlassian.net/browse/MF-6526
> fix: mf-6526 decode encoded image

- src/locales/ja/messages.po
- src/providers/red-packet/types.ts
> refactor: claim type

- src/constants/index.ts
- src/modals/RedPacketModal/ConfirmView.tsx
https://mask.atlassian.net/browse/fw-3090
https://mask.atlassian.net/browse/fw-3121
> fix: fw-3090 fw-3121 custom cover file type

- src/assets/wallet2.svg
- src/components/RedPacket/AmountProgressText.tsx
- src/components/RedPacket/RedPacketCard.tsx
- src/components/RedPacket/RedPacketCardFooter.tsx
- src/components/RedPacket/useVerifyAndClaim.tsx
- src/hooks/useCreateFTRedPacketCallback.ts
- src/hooks/useERC20Allowance.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/mask/plugins/red-packet/hooks/useAvailabilityComputed.ts
- src/modals/RedPacketModal/ConfirmView.tsx
- src/modals/RedPacketModal/MainView.tsx
- src/modals/RedPacketModal/RedPacketActionButton.tsx
- src/modals/RedPacketModal/RedPacketContext.tsx
- src/modals/RedPacketModal/RequirementsView.tsx
- src/modals/RedPacketModal/ShareAccountsPopover.tsx
- src/modals/RedPacketModal/routes.tsx
Closes [FW-3033](https://mask.atlassian.net/browse/FW-3033) FW-3034 FW-3073 FW-3078 FW-3079 FW-3080 FW-3083 FW-3087 FW-3089 FW-3091 FW-3092 FW-3094 FW-3095 FW-3101 FW-3102 FW-3117
[FW-3033]: https://mask.atlassian.net/browse/FW-3033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bugfix for redpacket

- src/components/RedPacket/RequirementsModal.tsx
- src/mask/plugins/red-packet/components/Requirements/index.tsx
> fixup! refactor: claim type (#3537)

- src/app/(settings)/components/ThirdPartConnectButton.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/LoginModal/MainView.tsx
Closes [FW-3048](https://mask.atlassian.net/browse/FW-3048) FW-3064
[FW-3048]: https://mask.atlassian.net/browse/FW-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bugfix for third party

- src/components/RedPacket/RedPacketCard.tsx
- src/components/RedPacket/useVerifyAndClaim.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: no need to open requirements modal if no requiremnts

- src/components/Activity/ActivityClaimButton.tsx
- src/components/Activity/ActivityNormalSuccessDialog.tsx
- src/components/Activity/ActivityTasks/ActivityPenguTasks.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> feat: pengu text

- src/app/(normal)/profile/pages/FollowersList.tsx
- src/app/(normal)/profile/pages/FollowingList.tsx
- src/components/FollowInList.tsx
- src/components/ProfileInList.tsx
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-3120
Closes FW-0000
> fix: hide follwers count for farcaster profile

- src/components/Activity/ActivityMobileOnly.tsx
- src/components/Activity/ActivityTasks/ActivityPenguTasks.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> feat: activity mobile only ssr

- src/components/TokenProfile/TokenDetail.tsx
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-3135
Closes FW-0000
> feat: ui for infinite value in token profile

- src/app/(normal)/profile/pages/FollowersList.tsx
- src/app/(normal)/profile/pages/FollowingList.tsx
- src/components/FollowInList.tsx
- src/components/ProfileInList.tsx
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/firefly/SocialMedia.ts
> feat: batch fetch profiles in following list

- src/app/(settings)/components/ThirdPartAccounts.tsx
- src/components/ProfileAvatar.tsx
- src/helpers/formatAccountFromConnections.ts
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/DisconnectFireflyAccountModal.tsx
https://mask.atlassian.net/browse/FW-3132
Closes FW-0000
> fix: sync third party account from connections

- src/components/NFTDetail/NFTInfoPreview.tsx
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-3116](https://mask.atlassian.net/browse/FW-3116)
[FW-3116]: https://mask.atlassian.net/browse/FW-3116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: nft video autoplay icon

- src/app/api/rp/route.tsx
> refactor: IS_PREVIEW

- src/app/api/rp/route.tsx
- src/helpers/fetchImageAsPNG.ts
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/ComposeModal.tsx
so that we can create redpacket beyond staging and production
> chore: allow to fetch rp cover cors

- src/app/(whiteboard)/telegram/login/page.tsx
- src/components/Actions/MuteWalletButton.tsx
- src/components/RedPacket/RedPacketCard.tsx
- src/components/SideBar/Menu.tsx
- src/hooks/useRefundCallback.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/mask/plugins/red-packet/hooks/useRefundCallback.ts
> fix: bugfix for rp claim

- src/app/(settings)/components/AccountCard.tsx
https://mask.atlassian.net/browse/fw-2976
> fix: fw-2976 don't show managed lens account in settings

- src/components/Activity/ActivityConnectCard.tsx
- src/components/Activity/ActivityPremiumAddressVerifyCard.tsx
- src/components/Activity/ActivityTaskFollowCard.tsx
- src/components/Activity/ActivityTasks/ActivityPenguTasks.tsx
Closes [FW-3137](https://mask.atlassian.net/browse/FW-3137) FW-3142
[FW-3137]: https://mask.atlassian.net/browse/FW-3137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fw-3137 fw-3142 activity sytles

- src/components/SideBar/Menu.tsx
Closes [FW-3128](https://mask.atlassian.net/browse/FW-3128)
[FW-3128]: https://mask.atlassian.net/browse/FW-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bugfix for sidebar menu

- src/components/RedPacket/useVerifyAndClaim.tsx
- src/helpers/createEIP1193Provider.ts
- src/modals/LoginModal/MainView.tsx
> fix: eslint

- src/components/Profile/ProfileMoreAction.tsx
Closes [FW-3136](https://mask.atlassian.net/browse/FW-3136)
[FW-3136]: https://mask.atlassian.net/browse/FW-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: hide the search in profile function on your own profile page

- src/components/RedPacket/RedPacketCard.tsx
- src/helpers/formatToken.ts
- src/hooks/useCreateFTRedPacketCallback.ts
- src/mask/plugins/red-packet/hooks/useDefaultCreateGas.ts
Closes [FW-3144](https://mask.atlassian.net/browse/FW-3144) FW-3080
[FW-3144]: https://mask.atlassian.net/browse/FW-3144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bugfix for invalid token type

- src/app/(settings)/settings/connected/page.tsx
- src/services/account.ts
Closes [FW-3145](https://mask.atlassian.net/browse/FW-3145)
[FW-3145]: https://mask.atlassian.net/browse/FW-3145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bugfix for logout all

- src/components/Activity/ActivityTasks/ActivityPenguTasks.tsx
> fix: padding bottom on event page android

- src/providers/lens/SocialMedia.ts
https://mask.atlassian.net/browse/FW-3146
Closes FW-0000
> fix: profileId in fetching orb club

- src/app/(normal)/channel/[source]/[id]/not-found.tsx
- src/components/NotFound.tsx
- src/components/Tabs/SolidTabs.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: source in channel 404 page

- src/providers/ethereum/isNativeToken.ts
Closes [FW-3143](https://mask.atlassian.net/browse/FW-3143)
[FW-3143]: https://mask.atlassian.net/browse/FW-3143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: hack for aurora native token

- src/app/(settings)/components/AccountCard.tsx
- src/hooks/useCreateFTRedPacketCallback.ts
- src/providers/ethereum/isNativeToken.ts
> fix: detect debank native token

- src/providers/ethereum/isNativeToken.ts
> fixup! fix: detect debank native token (#3582)

- src/hooks/useAvailableBalance.ts
- src/modals/RedPacketModal/MainView.tsx
> fix: checking if gas is insufficient

- package.json
- src/components/Activity/ActivityClaimButton.tsx
- src/components/Activity/ActivityConnectCard.tsx
- src/components/Activity/ActivityMobileOnly.tsx
- src/components/Activity/ActivityNormalSuccessDialog.tsx
- src/components/Activity/ActivityPremiumAddressVerifyCard.tsx
- src/components/Activity/ActivityTaskFollowCard.tsx
- src/components/Activity/ActivityTasks/ActivityPenguTasks.tsx
- src/components/Activity/hooks/useActivityShareUrl.ts
- src/constants/env.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> [Release] Hotfix 6.5.0 => 6.5.1 (patch)

- src/components/Activity/ActivityConnectButton.tsx
- src/components/Activity/ActivityPremiumAddressVerifyButton.tsx
> fix: activity connect button menu layout

- package.json
- src/components/Activity/ActivityConnectButton.tsx
- src/components/Activity/ActivityPremiumAddressVerifyButton.tsx
> [Release] Hotfix 6.5.1 => 6.5.2 (patch)

- src/components/Activity/hooks/useActivityBindAddress.ts
> fix: event bind address error handle on mobile

- src/components/Actions/ArticleMore.tsx
- src/components/ActivityCell/ActivityCellHeader.tsx
- src/components/ActivityCell/Polymarket/ActivityCellPolymarketAction.tsx
- src/components/Article/SingleArticleHeader.tsx
- src/components/NFTs/NFTFeedHeader.tsx
- src/components/NFTs/SingleNFTFeed.tsx
- src/components/Snapshot/SingleSnapshotHeader.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-3157](https://mask.atlassian.net/browse/FW-3157)
[FW-3157]: https://mask.atlassian.net/browse/FW-3157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: activity cell header

- src/components/NFTs/BookmarkButton.tsx
- src/components/NFTs/NFTPreview.tsx
- src/decorators/SetQueryDataForBookmarkNFT.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/services/getCollectionFromUrl.ts
https://mask.atlassian.net/browse/FW-3147
https://mask.atlassian.net/browse/FW-3148
https://mask.atlassian.net/browse/FW-3149
https://mask.atlassian.net/browse/FW-3150
Closes FW-0000
> fix: review errors in digesting nft link

- src/constants/env.ts
> chore: turn on frame v2

- src/providers/frame/Host.ts
> fix: profile not found

- src/app/(developers)/components/BridgeMethodButton.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/app/(whiteboard)/frame/page.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/FrameViewerModal/index.tsx
- src/providers/firefly/Bridge.ts
- src/types/bridge.ts
- src/types/frame.ts
> feat: frame v2 for mobile

- src/components/RedPacket/RedPacketCard.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-3188](https://mask.atlassian.net/browse/FW-3188)
> chore: remove from handle

- src/components/Actions/index.tsx
- src/decorators/AddLikeStatusToTwitterPosts.ts
- src/helpers/addLikeStatusToTwitterPost.ts
- src/providers/twitter/SocialMedia.ts
- src/store/useTwitterLikeStore.ts
> feat: twitter like status

- src/app/(whiteboard)/frame/page.tsx
- src/components/Frame/V2/Card.tsx
- src/helpers/createEIP1193Provider.ts
- src/modals/FrameViewerModal/index.tsx
- src/providers/frame/Host.ts
- src/types/bridge.ts
> feat: fetching frame from mobile devices

- src/components/SuggestedFollows/SuggestedFollowUsersList.tsx
- src/providers/lens/SocialMedia.ts
https://mask.atlassian.net/browse/FW-3119
Closes FW-0000
> feat: replace explore profiles api for lens

- src/components/Tips/TipSuccess.tsx
https://mask.atlassian.net/browse/FW-3159
Closes FW-0000
> fix: ensure only one mention tag for each source

- src/services/account.ts
- src/store/useProfileStore.ts
> fix: bugfix for login notification

- src/components/Actions/ToggleJoinChannel.tsx
- src/hooks/useToggleJoinChannel.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/DisconnectFireflyAccountModal.tsx
https://mask.atlassian.net/browse/FW-3165
https://mask.atlassian.net/browse/FW-3173
Closes FW-0000
> fix: remove confirm modal when leaving lens club

- src/components/Article/SingleArticleHeader.tsx
- src/components/Snapshot/SingleSnapshotHeader.tsx
Closes [FW-3157](https://mask.atlassian.net/browse/FW-3157)
[FW-3157]: https://mask.atlassian.net/browse/FW-3157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: activity cell header icon size

- src/app/(whiteboard)/components/FramePage.tsx
- src/app/(whiteboard)/frame/page.tsx
- src/types/bridge.ts
> chore: update frame context

- src/app/(whiteboard)/components/FramePage.tsx
- src/app/(whiteboard)/frame/page.tsx
- src/components/Frame/V2/Card.tsx
- src/modals/FrameViewerModal/index.tsx
> chore: adjust frame card style

- src/app/(whiteboard)/telegram/login/page.tsx
- src/components/FungibleTokenInput.tsx
- src/components/RedPacket/RedPacketCard.tsx
- src/components/Tabs/index.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/NonFungibleCollectionSelectModal/CollectionItem.tsx
- src/modals/RedPacketModal/MainView.tsx
- src/modals/RedPacketModal/RequirementsView.tsx
- src/providers/third-party/SessionHolder.ts
- src/services/account.ts
- src/services/bindFireflySession.ts
- src/store/useProfileStore.ts
Closes [FW-3166](https://mask.atlassian.net/browse/FW-3166)
Closes [FW-3167](https://mask.atlassian.net/browse/FW-3167)
Closes [FW-3169](https://mask.atlassian.net/browse/FW-3169)
Closes [FW-3170](https://mask.atlassian.net/browse/FW-3170)
Closes [FW-3171](https://mask.atlassian.net/browse/FW-3171)
Closes [FW-3172](https://mask.atlassian.net/browse/FW-3172)
[FW-3166]: https://mask.atlassian.net/browse/FW-3166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-3167]: https://mask.atlassian.net/browse/FW-3167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FW-3169]: …
> fix: rp ui

- src/app/(normal)/post/[source]/[id]/pages/EngagementLayout.tsx
- src/app/(normal)/profile/pages/FollowPageLayout.tsx
- src/components/Profile/Title.tsx
- src/components/SideBar/ConnectWallet.tsx
- src/components/SideBar/ExclusiveEvents.tsx
- src/components/SideBar/Menu.tsx
- src/components/SideBar/Profile.tsx
- src/components/Tabs/SecondTabs.tsx
- src/components/Tabs/index.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/RedPacketModal/MainView.tsx
https://mask.atlassian.net/browse/FW-3110
Closes FW-0000
> feat: optimize ui for tabs

- src/app/(whiteboard)/components/FramePage.tsx
- src/app/(whiteboard)/frame/page.tsx
- src/hooks/useFireflyBridgeSupported.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/RedPacketModal/MainView.tsx
> refactor: loading status

- src/modals/DisconnectFireflyAccountModal.tsx
> fix: error message on disconnecting account

- cspell.json
- src/components/ProfileSourceIcon.tsx
- src/components/ProjectItem.tsx
- src/providers/firefly/Endpoint.ts
- src/providers/types/Firefly.ts
Closes [FW-3104](https://mask.atlassian.net/browse/FW-3104) FW-3174
[FW-3104]: https://mask.atlassian.net/browse/FW-3104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: open rootdata detail by api

- src/app/(whiteboard)/components/GhostError.tsx
- src/app/(whiteboard)/frame/page.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: iframe style

- src/components/Search/SearchContentPanel.tsx
- src/modals/NonFungibleCollectionSelectModal/NoFungibleTokenSelectPanel.tsx
https://mask.atlassian.net/browse/fw-3168
> fix: fw-3168 chains in nft collection picker

- src/modals/NonFungibleCollectionSelectModal/CollectionItem.tsx
- src/modals/NonFungibleCollectionSelectModal/NoFungibleTokenSelectPanel.tsx
https://mask.atlassian.net/browse/fw-3168
> fixup! fix: fw-3168 chains in nft collection picker (#3621)

- src/components/ProjectItem.tsx
- src/modals/NonFungibleCollectionSelectModal/CollectionItem.tsx
- src/providers/firefly/Endpoint.ts
- src/providers/types/Firefly.ts
- src/store/useProfileStore.ts
Closes [FW-3104](https://mask.atlassian.net/browse/FW-3104) FW-3163 FW-3170
[FW-3104]: https://mask.atlassian.net/browse/FW-3104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: root data url

- src/components/InitialProviders.tsx
- src/locales/zh-Hans/messages.po
> fix: bugfix for dark mode record

- src/app/(normal)/profile/pages/ProfileCategoryTabs.tsx
- src/components/Profile/WalletProfileContentList.tsx
- src/constants/enum.ts
- src/constants/index.ts
- src/helpers/isWalletProfileCategory.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
> fix: daos label

- cspell.json
- src/components/Article/ArticleCollect.tsx
- src/components/NFTDetail/NFTInfo.tsx
- src/components/NFTs/FreeMintButton.tsx
- src/components/ProjectItem.tsx
- src/components/ProjectTrendingList.tsx
- src/hooks/useSponsorMintNFT.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/telemetry/captureMintEvent.ts
- src/providers/telemetry/index.ts
- src/providers/types/Firefly.ts
- src/providers/types/Telemetry.ts
> feat: capture mint/collect event

- src/components/ActivityCell/NFTs/NFTsActivityCellCard.tsx
- src/components/NFTDetail/NFTInfoPreview.tsx
- src/components/ProjectItem.tsx
- src/components/ProjectTrendingList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-3105](https://mask.atlassian.net/browse/FW-3105)
[FW-3105]: https://mask.atlassian.net/browse/FW-3105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: nft timeline video player

- src/components/ProfileInList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/farcaster/SocialMedia.ts
- src/providers/firefly/SocialMedia.ts
> feat: ensure followers count is not empty

- src/components/Actions/CopyLinkButton.tsx
- src/components/CollectionDetail/CollectionInfo.tsx
https://mask.atlassian.net/browse/FW-3180
https://mask.atlassian.net/browse/FW-3181
Closes FW-0000
> fix: remove unused mint button in collection details

- src/components/NFTDetail/NFTInfo.tsx
- src/components/NFTDetail/PoapTrait.tsx
- src/components/NFTs/NFTPreview.tsx
- src/hooks/usePoapTraits.ts
- src/providers/simplehash/type.ts
- src/services/getNFTFromUrl.ts
https://mask.atlassian.net/browse/FW-3179
Closes FW-0000
> fix: display country in poap details

- src/components/Article/ArticleCollect.tsx
- src/components/ProjectTrendingList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
Closes [FW-3134](https://mask.atlassian.net/browse/FW-3134)
[FW-3134]: https://mask.atlassian.net/browse/FW-3134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: article collected status

- src/app/(normal)/nft/pages/NFTDetailPage.tsx
- src/components/NFTDetail/NFTInfo.tsx
- src/components/NFTs/FreeMintButton.tsx
- src/modals/FreeMintModal/MintButton.tsx
- src/providers/simplehash/formatSimpleHashNFT.ts
- src/providers/simplehash/type.ts
- src/providers/types/Firefly.ts
> fix: append simplehash contract

- src/modals/FreeMintModal/MintParamsPanel.tsx
> refactor: remove confusing code

- src/app/(normal)/profile/(profile)/[source]/[id]/layout.tsx
- src/app/(normal)/profile/pages/ProfilePageLayout.tsx
- src/components/Profile/ProfileSourceTabs.tsx
- src/helpers/createMetadataProfileById.ts
https://mask.atlassian.net/browse/FW-3178
Closes FW-0000
> fix: ensure display profile when no relation found in firefly

- src/hooks/useSponsorMintNFT.ts
> fix: simplehash contract on minting nft

- src/components/Article/ArticleCollect.tsx
https://mask.atlassian.net/browse/FW-3183
Closes FW-0000
> fix: collect button text

- cspell.json
- src/app/api/twitter/[tweetId]/comments/route.ts
- src/app/api/twitter/compose/route.ts
- src/app/api/twitter/threadTweets/[tweetId]/route.ts
- src/components/Posts/ExcludeReplyUserList.tsx
- src/components/Posts/Reply.tsx
- src/components/ProjectItem.tsx
- src/components/ProjectTrendingList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/providers/twitter/SocialMedia.ts
- src/services/getThreads.ts
- src/services/postToTwitter.ts
- src/store/useComposeStore.ts
Closes [FW-3071](https://mask.atlassian.net/browse/FW-3071)
[FW-3071]: https://mask.atlassian.net/browse/FW-3071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: reply multiple users exclude

- cspell.json
- src/app/api/twitter/[tweetId]/comments/route.ts
- src/app/api/twitter/threadTweets/[tweetId]/route.ts
- src/components/ProjectItem.tsx
- src/components/ProjectTrendingList.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/services/getThreads.ts
Closes [FW-3162](https://mask.atlassian.net/browse/FW-3162)
[FW-3162]: https://mask.atlassian.net/browse/FW-3162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: twitter thread in post detail

- src/components/Posts/Video.tsx
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
https://mask.atlassian.net/browse/FW-3185
Closes FW-0000
> fix: play lens video with fallback src

- src/app/(whiteboard)/components/FramePage.tsx
- src/app/(whiteboard)/frame/page.tsx
> fix: frame rendering

- src/components/Posts/Reply.tsx
Closes [FW-3071](https://mask.atlassian.net/browse/FW-3071)
[FW-3071]: https://mask.atlassian.net/browse/FW-3071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: reply memo deps

- src/app/(developers)/components/BridgeMethodButton.tsx
- src/app/(developers)/developers/bridge/page.tsx
- src/app/(whiteboard)/frame/page.tsx
- src/providers/firefly/Bridge.ts
- src/types/bridge.ts
> chore: add setFrameReadyOptions

- src/components/Posts/ExcludeReplyUserList.tsx
- src/components/Posts/Reply.tsx
Closes [FW-3188](https://mask.atlassian.net/browse/FW-3188) FW-3189 FW-3190
[FW-3188]: https://mask.atlassian.net/browse/FW-3188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: twitter reply users issues

- src/components/Frame/V2/Card.tsx
- src/constants/enum.ts
- src/helpers/assertLensAccountOwner.ts
- src/helpers/createEIP1193Provider.ts
- src/helpers/frame.ts
- src/helpers/switchEthereumChain.ts
- src/locales/en/messages.po
- src/locales/ja/messages.po
- src/locales/ko/messages.po
- src/locales/pseudo/messages.po
- src/locales/zh-Hans/messages.po
- src/locales/zh-Hant/messages.po
- src/modals/FrameViewerModal/MoreActionMenu.tsx
- src/modals/FrameViewerModal/index.tsx
- src/providers/frame/Processor.ts
- src/types/frame.ts
Closes [FW-3191](https://mask.atlassian.net/browse/FW-3191)
[FW-3191]: https://mask.atlassian.net/browse/FW-3191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: frame v2

- src/app/(whiteboard)/components/FramePage.tsx
- src/app/(whiteboard)/frame/page.tsx
- src/components/Frame/V2/Card.tsx
- src/modals/FrameViewerModal/MoreActionMenu.tsx
- src/providers/frame/Host.ts
> fix: fid type

- src/components/Posts/ContentTranslator.tsx
> fix: translate button color

- src/components/Frame/V1/Card.tsx
- src/helpers/formatExternalLink.ts
> feat: capture x post url

- src/app/(normal)/profile/(relation)/[source]/[id]/relation/[category]/layout.tsx
- src/app/(normal)/profile/pages/ProfilePageLayout.tsx
- src/components/Profile/Title.tsx
https://mask.atlassian.net/browse/FW-3193
Closes FW-0000
> fix: fallback profile identity in profile page

- src/providers/firefly/Endpoint.ts
- src/providers/types/NFTs.ts
> feat: upgrade discover nft api

- src/app/(normal)/profile/pages/FollowPageLayout.tsx
https://mask.atlassian.net/browse/FW-3195
Closes FW-0000
> fix: tabs ui

- src/components/Profile/ProfileCard.tsx
https://mask.atlassian.net/browse/FW-3196
Closes FW-0000
> feat: sort following tags in profile hover card

- src/components/ErrorBoundary/Crash.tsx
- src/components/Modal.tsx
- src/components/Popover.tsx
- src/components/PreviewMedia/index.tsx
- src/components/SideBar/SideBarForMobile.tsx
- src/modals/DraggablePopover.tsx
> refactor: modals

- src/components/Activity/ActivityMintSuccessDialog.tsx
- src/components/Activity/ActivityNormalSuccessDialog.tsx
- src/components/EditProfile/EditProfileDialog.tsx
- src/components/Modal.tsx
- src/components/Popover.tsx
- src/modals/ComposeModal.tsx
- src/modals/LoginModal/index.tsx
- src/modals/NonFungibleCollectionSelectModal/index.tsx
- src/modals/TipsModal.tsx
- src/modals/TokenSelectorModal.tsx
> refactor: modal props
